### ISSUE TITLE
error installing: CMake Error: Problem with archive_write_finish_entry(): Can't restore time

### ISSUE THREAD

**Issue by sjackman** [COMBINE-lab/salmon#10]
I get the following error when installing `salmon`:
```
cd /var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/external && /gsc/btl/linuxbrew/Cellar/cmake/3.3.0/bin/cmake -P /var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/libcereal-prefix/src/libcereal-stamp/extract-libcereal.cmake
-- extracting...
     src='/var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/external/cereal-v1.0.0.tgz'
     dst='/var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/external/cereal-1.0.0'
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/external/cereal-v1.0.0.tgz
-- extracting... [error clean up]
CMake Error at /var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/libcereal-prefix/src/libcereal-stamp/extract-libcereal.cmake:33 (message):
  error: extract of
  '/var/tmp/sjackman/salmon20150803-27338-1qoka2g/salmon-0.4.2/external/cereal-v1.0.0.tgz'
  failed
```

Is it possible to compile `salmon` with its external dependencies provided externally rather than vendored into `salmon`? What is `cereal`?

**Comment by sjackman** [comment]
This `cmake` issue appears to be a bug in Linuxbrew. See https://github.com/Homebrew/linuxbrew/issues/391

**Comment by rob-p** [comment]
Interesting! `cereal` is a C++ serialization library.  Is the problem related to a specific version of `cmake` within Linuxbrew?

**Comment by sjackman** [comment]
My guess, and this is a long shot, is that it's a bug in the `tar` library of `cmake`, that's made evident because my system at work has up-to-date Linux headers and glibc but is running an eight-year-old Linux kernel (CentOS 5.10). I can upgrade everything with Linuxbrew except the running kernel. I've seen this situation show bugs before when the software uses compile time kernel feature checks like `HAVE_PIPE2` when it should be using a run time check, namely checking whether the call to `pipe2` fails with `ENOSYS`.

**Comment by sjackman** [comment]
Note that I do (now) have `cereal` installed, so there is no need for `salmon` to download and build it. It would be nice if this were an option to use the system-provided `cereal` library.

**Comment by rob-p** [comment]
Noted --- I'll add an option to look for it locally first.

**Comment by sjackman** [comment]
Thanks, Rob!

No smart dashes in GFM? Shame. If you're on a Mac, Option-hyphen and Option-Shift-option produce en- and em- dashes respectively. Option-semicolon produces an ellipses. I use these three shortcuts all the time.

**Comment by sjackman** [comment]
I'm still experiencing this `cmake` error:
```
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /var/tmp/sjackman/salmon20160307-4399-1vksuoo/salmon-0.6.0/external/libdivsufsort.zip
-- extracting... [error clean up]
CMake Error at /var/tmp/sjackman/salmon20160307-4399-1vksuoo/salmon-0.6.0/libdivsufsort-prefix/src/libdivsufsort-stamp/extract-libdivsufsort.cmake:33 (message):
  error: extract of
  '/var/tmp/sjackman/salmon20160307-4399-1vksuoo/salmon-0.6.0/external/libdivsufsort.zip'
  failed
```
Here's a gist of the logs:
https://gist.github.com/sjackman/2bbfcf212c555fb20505#file-02-make-L397-L404

**Comment by sjackman** [comment]
Where does `extract-libdivsufsort.cmake` live? I don't find it in the `salmon` repository. Is it generated automatically by `cmake`? The following patch/hack works around the `cmake -E tar xfz` bug for me. It seems to only affect extracting the `libdivsufsort.zip`, perhaps because it's a `zip`. If that is the case, and there's a `.tar.gz` distribution of `libdivsufsort`, then there may be a simple fix.

```diff
--- libdivsufsort-prefix/src/libdivsufsort-stamp/extract-libdivsufsort.cmake.orig	2016-03-07 22:02:35.000000000 -0800
+++ libdivsufsort-prefix/src/libdivsufsort-stamp/extract-libdivsufsort.cmake	2016-03-07 22:06:49.000000000 -0800
@@ -23,7 +23,7 @@
 # Extract it:
 #
 message(STATUS "extracting... [tar xfz]")
-execute_process(COMMAND ${CMAKE_COMMAND} -E tar xfz ${filename}
+execute_process(COMMAND unzip ${filename}
   WORKING_DIRECTORY ${ut_dir}
   RESULT_VARIABLE rv)
 
```

**Comment by rob-p** [comment]
`extract-libdivsufsort.cmake` is auto-generated during configuration.  However, the zip itself is grabbed as part of RapMap.  I can take a look at what would be required to make it a tarball there (or, conversely, if there is a way to force CMake to use `unzip` rather than `cmake -E tar xfz`.

**Comment by sjackman** [comment]
Here's the official tarball release of `libdivsufsort`: https://github.com/y-256/libdivsufsort/archive/2.0.1.tar.gz

**Comment by rob-p** [comment]
I prefer to have it bundled *within* RapMap (but am willing to hear argument against this).  Specifically, this allows that I have control over the availability (i.e. if the official repo disappears, RapMap will continue to build).  Of course, the bundled zip was from a slightly updated version of the official `libdivsufsort` that incorporates a fix into the `CMakeLists.txt` file where the original failed.  It would certainly be easy to just move the bundled version into a tarball rather than a zip without any hassle.

**Comment by sjackman** [comment]
It's still only a hypothesis that moving to a tarball would fix my issue. I noticed that once I hacked around this one error by using `unzip` instead, it seems to be working. Still, I think using a `tarball` rather than `zip` file is good style anyway.

**Comment by sjackman** [comment]
The cmake `archive_write_finish_entry(): Can't restore time` issue affects both `.zip` files and `.tar.gz` files.

**Comment by sjackman** [comment]
I've found a workaround that works for me! `cmake -E` fails wth Linux 2.6.18 (CentOS 5.11) but succeeds with Linux 2.6.32 (CentOS 6.6). So I'm building Salmon on a newer box, then I can run it on our ancient cluster. Closing.
