### ISSUE TITLE
OS X Binary not compatible with Sierra

### ISSUE THREAD

**Issue by remyschwab** [COMBINE-lab/salmon#103]
I'm getting a memory allocation error when I try to run the salmon binary after updating my OS. Here is the error:

salmon(65515,0x7fffdb32f3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffdb325000

**Comment by rob-p** [comment]
Hi @remyschwab,

  Yes, this is a known issue and is a result of an incompatibility with jemalloc (which we use as our memory allocator).  JEmalloc has issued a fix and this will be present in the next release.  For the time-being, I can provide you with an updated binary if that would help.

--Rob

**Comment by remyschwab** [comment]
Yes that would be great! Thank you for the quick response. How can I contact you?

**Comment by rob-p** [comment]
GitHub supports uploading files directly in the issues, so I'll compile the updated binary and I'll drop it right here (I'll do this today, but it might be an hour or so).  Once you have it, you can confirm if it works for you (I'm still on 10.11, so I'll have to build it there, but with the updated dependency).

**Comment by rob-p** [comment]
Hi @remyschwab,

  Can you try this binary?

--Rob 

[Salmon-0.7.3-pre_OSX_10.11.tar.gz](https://github.com/COMBINE-lab/salmon/files/581439/Salmon-0.7.3-pre_OSX_10.11.tar.gz)

**Comment by remyschwab** [comment]
It's still not working. If I type ./bin/salmon I get:

salmon(68460,0x7fffdb32f3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffdb325000
version : 0.7.1

So maybe it's working okay but it's still printing the error message.

**Comment by rob-p** [comment]
Indeed!  It looks like my script packaged the wrong version (0.7.1).  I'm re-compiling now; give me a sec.

**Comment by rob-p** [comment]
Ok, please try this one.

[Salmon-0.7.3-pre_OSX_10.11.tar.gz](https://github.com/COMBINE-lab/salmon/files/581462/Salmon-0.7.3-pre_OSX_10.11.tar.gz)

**Comment by remyschwab** [comment]
I'm actually still getting the same error.

**Comment by rob-p** [comment]
Is it at least saying `version : 0.7.3` at this point?  If so, then I think that it may be the case that the build has to happen on an OS 10.12 box (or at least with the latest version of XCode).

**Comment by remyschwab** [comment]
Ah okay yes it is saying 0.7.3.

**Comment by rob-p** [comment]
Ok, that's interesting.  I am certain this is the error, because I had a student compiling salmon on OS 10.12 come to my office yesterday and we were able to fix the issue with exactly the change I'm using here.  I have one more idea (and one more shot before I try upgrading to 10.12).  Could you try the binary attached below?

[Salmon-0.7.3-pre_OSX_10.11.tar.gz](https://github.com/COMBINE-lab/salmon/files/581546/Salmon-0.7.3-pre_OSX_10.11.tar.gz)

**Comment by remyschwab** [comment]
No error so far! Thanks a bunch. I'll let you know if I get any more errors

**Comment by rob-p** [comment]
Great!

**Comment by rob-p** [comment]
Updated to resolve a short options conflict and fix issue #111 (which only occurred on the develop branch with the combination of `--useVBOpt` and `--numGibbsSamples`). [Salmon-0.7.3-pre_OSX_10.12.tar.gz](https://github.com/COMBINE-lab/salmon/files/665033/Salmon-0.7.3-pre_OSX_10.12.tar.gz)

**Comment by jjv5** [comment]
Has Sierra issue been fixed? Binary release Salmon-0.8.2_macOS_10.12.tar.gz
still gives malloc error under OSX 10.12.

**Comment by rob-p** [comment]
Hi @jjv5,

  This error should be fixed.  The binary works for me without error (or that strange jemalloc warning) on OS X 10.12.4.  The relevant library should be statically linked in, so I doubt it's a path problem.  You could also try the [conda build](https://anaconda.org/bioconda/salmon) to see if that works for you.

**Comment by jjv5** [comment]
Is there a different binary somewhere perhaps? 

I a downloading:   

https://github.com/COMBINE-lab/salmon/releases/download/v0.8.2/Salmon-0.8.2_macOS_10.12.tar.gz


And get this: 

Salmon-0.8.2_macOS_10.12.tar.gz
100%[=====================================================>]   2.64M  
326KB/s    in 6.6s     

2017-04-18 09:43:33 (409 KB/s) - 'Salmon-0.8.2_macOS_10.12.tar.gz' saved
[2766997/2766997] 

MacBook-Air:salmon jjv5$ tar zxf Salmon-0.8.2_macOS_10.12.tar.gz 

MacBook-Air:salmon jjv5$ cd Salmon-0.8.2_macOX_10.12/bin/ 

MacBook-Air:bin jjv5$ ./salmon -h 

salmon(43548,0x7fffdc0c23c0) malloc: *** malloc_zone_unregister() failed
for 0x7fffdc0b8000 

Salmon v0.8.2 

Usage:  salmon -h|--help or 

        salmon -v|--version or 

        salmon -c|--cite or 

        salmon [--no-version-check] <COMMAND> [-h | options] 

Commands: 

     cite  Show salmon citation information 

     index Create a salmon index 

     quant Quantify a sample 

     swim  Perform super-secret operation 

MacBook-Air:bin jjv5$ sw_vers 

ProductName: Mac OS X 

ProductVersion: 10.12.4 

BuildVersion: 16E195

On 2017-04-18 09:33, Rob Patro wrote:

> Hi @jjv5 [1], 
> 
> This error should be fixed. The binary works for me without error (or that strange jemalloc warning) on OS X 10.12.4. The relevant library should be statically linked in, so I doubt it's a path problem. You could also try the conda build [2] to see if that works for you. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/jjv5
[2] https://anaconda.org/bioconda/salmon
[3]
https://github.com/COMBINE-lab/salmon/issues/103#issuecomment-294845429
[4]

**Comment by rob-p** [comment]
I think that's the right binary.  You can check the sha256 sum:

```
rob at Robs-MacBook-Pro in ~/Salmon-0.8.2_macOX_10.12
$ shasum -a256 bin/salmon
7be1c57e1a83956cc9c18f75aed3b2376c93595de7dec215041fe3065528b527  bin/salmon
```

You can also check the libraries that `salmon` is seeing:

```
rob at Robs-MacBook-Pro in ~/Salmon-0.8.2_macOX_10.12
$ otool -L bin/salmon
	bin/salmon:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	@rpath/libtbbmalloc_proxy.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
```

but, again, the library of interest with respect to this message (jemalloc) is linked statically.  Out of curiosity, is this message a warning or error (i.e. does salmon run or return a non-zero exit code).  The message you're seeing is actually expected if jemalloc was compiled without debug mode turned off (because apple did some funny business with the allocator in OS X 10.12).

**Comment by jjv5** [comment]
salmon does run and completes normally so I guess it's just the warning
from jemalloc.  

Is this expected for sailfish also? I get the same message about malloc.
 

On 2017-04-18 09:55, Rob Patro wrote:

> I think that's the right binary. You can check the sha256 sum:
> 
> rob at Robs-MacBook-Pro in ~/Salmon-0.8.2_macOX_10.12
> $ shasum -a256 bin/salmon
> 7be1c57e1a83956cc9c18f75aed3b2376c93595de7dec215041fe3065528b527  bin/salmon
> 
> You can also check the libraries that salmon is seeing:
> 
> rob at Robs-MacBook-Pro in ~/Salmon-0.8.2_macOX_10.12
> $ otool -L bin/salmon
> bin/salmon:
> /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
> /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
> /usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
> @rpath/libtbbmalloc_proxy.dylib (compatibility version 0.0.0, current version 0.0.0)
> @rpath/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
> @rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
> /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
> 
> but, again, the library of interest with respect to this message (jemalloc) is linked statically. Out of curiosity, is this message a warning or error (i.e. does salmon run or return a non-zero exit code). The message you're seeing is actually expected if jemalloc was compiled without debug mode turned off (because apple did some funny business with the allocator in OS X 10.12). 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/COMBINE-lab/salmon/issues/103#issuecomment-294852033
[2]

**Comment by rob-p** [comment]
Well, I still don't have a good explanation for why you're seeing the warning.  Using the same executable on OS X 10.12.4 (my laptop) I don't see it.  However, it _is_ only a warning and should in no way affect the functionality of Salmon.  Sailfish uses the same memory allocator, so if you see the warning with Salmon I'd expect the same from Sailfish.  I'm a bit tied up with things this week, but I'll take a look to see if there are any clues as to what might be causing this warning to show up.
