### ISSUE TITLE
salmon quant fails when the input is a bam file and the --seqBias or --gcBias arguments is included

### ISSUE THREAD

**Issue by tomsing1** [COMBINE-lab/salmon#104]
The documentation states

>If your alignments for the sample you want to quantify appear in multiple .bam/.sam files, then you can simply provide the Salmon -a parameter with a (space-separated) list of these files.

But I somehow can't get that to work. I have two bam files, each of them with (different) STAR alignments to the same reference. When I pass either one of them, salmon works just fine, e.g. with the following commands:

```
salmon quant -t transcripts.fasta  -l IU  -p 2 -o quantitation/quant.sf  -a run1/Aligned.toTranscriptome.out.bam
# or
salmon quant -t transcripts.fasta  -l IU  -p 2 -o quantitation/quant.sf  -a run2/Aligned.toTranscriptome.out.bam
```
But when I try to pass both of them, I get the following error:

```
salmon quant -t transcripts.fasta  -l IU  -p 2 -o quantitation/quant.sf)  -a run1/Aligned.toTranscriptome.out.bam run2/Aligned.toTranscriptome.out.bam

Version Info: This is the most recent version of Salmon.
# salmon (alignment-based) v0.7.2
# [ program ] => salmon
# [ command ] => quant
# [ targets ] => { transcripts.fasta }
# [ libType ] => { IU }
# [ threads ] => { 2 }
# [ output ] => { sample1/quantitation }
# [ alignments ] => { run1/Aligned.toTranscriptome.out.bam run2/Aligned.toTranscriptome.out.bam }
Library format { type:paired end, relative orientation:inward, strandedness:unstranded }
Logs will be written to quantitation/logs
numQuantThreads = 2
parseThreads = 2
Checking that provided alignment files have consistent headers . . . done
Populating targets from aln = "run1/Aligned.toTranscriptome.out.bam", fasta = "transcripts.fasta" . . .replaced 0 non-ACGT nucleotides with random nucleotides
done

processed 0 reads in current roundSegmentation fault (core dumped)
```

The `Checking that provided alignment files have consistent headers . . . done` line seems to indicate that both bam files were recognized and that the headers matched. 

Any hints on what might be going on?

**Comment by tomsing1** [comment]
Ok, I realized that the Segmentation fault was not caused by passing multiple bam files, but by including either the  `--seqBias` or  `--gcBias` arguments. 

The following command generates the segmentation fault:
```
salmon quant  -t transcripts.fasta -g gene_annotations.gtf  -l IU -p 8  -o quantitation -a Aligned.toTranscriptome.bam --seqBias --gcBias
```

and returns the following output before exiting:

```
# salmon (alignment-based) v0.7.2
# [ program ] => salmon
# [ command ] => quant
# [ targets ] => { transcripts.fasta }
# [ geneMap ] => { gene_annotations.gtf }
# [ libType ] => { IU }
# [ threads ] => { 8 }
# [ output ] => { quantitation }
# [ alignments ] => {Aligned.toTranscriptome.bam }
# [ seqBias ] => { }
# [ gcBias ] => { }
Library format { type:paired end, relative orientation:inward, strandedness:unstranded }
Logs will be written to quantitation/logs
numQuantThreads = 4
parseThreads = 4
Checking that provided alignment files have consistent headers . . . done
Populating targets from aln = "Aligned.toTranscriptome.bam", fasta = "transcripts.fasta" . . .WARNING: Transcript ENSMUST00000185127 appears in the reference but did not appear in the BAM
WARNING: Transcript ENSMUST00000180893 appears in the reference but did not appear in the BAM
WARNING: Transcript ENSMUST00000206884 appears in the reference but did not appear in the BAM
WARNING: Transcript ENSMUST00000181916 appears in the reference but did not appear in the BAM
WARNING: Transcript ENSMUST00000202657 appears in the reference but did not appear in the BAM
[truncated]

replaced 3 non-ACGT nucleotides with random nucleotides
done


processed 0 reads in current round
```
follow by the segmentation fold.

The same command without the `--seqBias --gcBias` arguments succeeds. Perhas bias correction is not supported (or even necessary) when quantifying from a bam file?

**Comment by rob-p** [comment]
Hi @tomsing1,

  Thanks for following up on this --- I was scratching my head about why multiple libraries might be causing an issue.  Both `--seqBias` and `--gcBias` are relatively new features, and have definitely undergone more testing under the "quasi-mapping" codepath than the alignment-based codepath (though it's passed our internal regression tests on both).  That being said, bias correction is equally valid regardless of whether you're using quasi-mapping or quantifying from a bam file directly.  I'd be happy to take a look if you can provide a small example (a subset of the reads in the bam file?) that triggers the behavior.  One thought might be that, for some reason, positions in the bam file could disagree with what's provided in the corresponding fasta.  However, that's just a guess and I'd have to try and debug the segfault once I can reproduce it.  Thanks again for the detailed error report and the update!

--Rob

**Comment by tomsing1** [comment]
Hi Rob,

thanks a lot for your quick response and apologies for misdiagnosing my problem earlier.

## Data sources

The dataset I am looking at is from the SRA e.g. [this experiment](http://www.ebi.ac.uk/ena/data/view/SRR1033785).

My workflow uses thes following genome sequence:
* Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
  * ftp://ftp.ensembl.org/pub/release-86/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz)

the following transcripts fasta files (concatenated before use):
* Mus_musculus.GRCm38.cdna.all.fa.gz
  * ftp://ftp.ensembl.org/pub/release-86/fasta/mus_musculus/cdna/Mus_musculus.GRCm38.cdna.all.fa.gz
* Mus_musculus.GRCm38.ncrna.fa.gz
  * ftp://ftp.ensembl.org/pub/release-86/fasta/mus_musculus/ncrna/Mus_musculus.GRCm38.ncrna.fa.gz

and this gene annotation file
*  Mus_musculus.GRCm38.86.gtf.gz
  * ftp://ftp.ensembl.org/pub/release-86/gtf/mus_musculus/Mus_musculus.GRCm38.86.gtf.gz

all from ensembl version 86.

## Workflow

- I built a STAR index with the GTF and genome FASTA files listed above. 
- The FASTQ files were extracted from the SRA experiment with [fastq-dump](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump).
- Reads were aligned with STAR to the index and `unsorted` alignments to the transcriptome were returned (this keeps the paired-ends next to each other).

I noticed that the cDNA FASTA files from ensembl include the transcript version, e.g. `ENSMUST00000178537.1` in the FASTA header. The GTF file specifies the transcript id and its version in different fields. Therefore, the STAR index does not include the version suffix. Instead, only the transcript ids are listed, e.g. `ENSMUST00000178537`.

To provide a FASTA file with transcript identifiers that match those in STAR's BAM file, I pre-processed Ensembl's FASTA file with the following command:

```
wget ftp://ftp.ensembl.org/pub/release-86/fasta/mus_musculus/cdna/Mus_musculus.GRCm38.cdna.all.fa.gz
gunzip Mus_musculus.GRCm38.cdna.all.fa.gz
cut -f1 -d "." Mus_musculus.GRCm38.cdna.all.fa > transcripts_unversioned.fa

head transcripts_unversioned.fa
>ENSMUST00000178537
GGGACAGGGGGC
>ENSMUST00000178862
GGGACTGGGGGGGC
>ENSMUST00000196221
ATGGCATAT
>ENSMUST00000179664
ATGGCATATCA
>ENSMUST00000177564
ATCGGAGGGATACGAG
[truncated]
```

Then I try to run `salmon`:

```
wget ftp://ftp.ensembl.org/pub/release-86/gtf/mus_musculus/Mus_musculus.GRCm38.86.gtf.gz
gunzip Mus_musculus.GRCm38.86.gtf.gz
salmon quant  -t transcripts_unversioned.fa -g Mus_musculus.GRCm38.86.gtf -l IU -p 1  -o quantitation -a subsample.bam --seqBias --gcBias
```

but get the segmentation fault. Omitting the `--seqBias --gcBias` options makes it work.

Perhaps you can already spot where I am doing something wrong? If not, you can find the subsample.bam file [here](https://drive.google.com/open?id=0BzX9viKJksNtak0xako0VXptLW8). (The other files are publically available, as shown above.)

Does that help? Please let me know if there is anything I can do to help you understand this better.
Best,
Thomas

**Comment by mikelove** [comment]
If it's useful, I made an example where you can run beginning to end to reproduce (didn't see this thread beforehand)

Download these:

```
ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
ftp://ftp.ensembl.org/pub/release-87/gtf/homo_sapiens/Homo_sapiens.GRCh38.87.gtf.gz

ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR188/ERR188297/ERR188297_1.fastq.gz
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR188/ERR188297/ERR188297_2.fastq.gz
```

Using STAR 2.5.2b

```
star --runThreadN 6 \
     --runMode genomeGenerate \
     --genomeDir ensembl87 \
     --genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa \
     --sjdbGTFfile Homo_sapiens.GRCh38.87.gtf \
     --sjdbOverhang 100

star --runThreadN 6 \
     --genomeDir ensembl87 \
     --readFilesIn ERR188297_1.fastq ERR188297_2.fastq \
     --outFileNamePrefix star/ \
     --outSAMtype BAM Unsorted \
     --quantMode TranscriptomeSAM
```

Then, following Thomas, I chop the version numbers from the FASTA

```
cut -f1 -d "." Homo_sapiens.GRCh38.cdna.all.fa > transcripts_unversioned.fa
```

Now Salmon v0.7.2

```
Salmon-0.7.2_linux_x86_64/bin/salmon quant -t transcripts_unversioned.fa -l IU -p 6 -a star/Aligned.toTranscriptome.out.bam -o align_test
```

**Note**: nothing in `libParams` dir...

```
Salmon-0.7.2_linux_x86_64/bin/salmon quant --gcBias -t transcripts_unversioned.fa -l IU -p 6 -a star/Aligned.toTranscriptome.out.bam -o align_testGC
```

This produces segfault:

```
^M^MESC[0;32mprocessedESC[0;31m 0 ESC[0;32mreads in current roundESC[0;0m/nas02/home/m/i/milove/.lsbatch/1481837415.333618.shell: line 9: 29198 Segmentation fault      (core dumped)
```

**Comment by rob-p** [comment]
Hi @mikelove,

  Thanks for the easy-to-reproduce example!  I'm at the point where I'm running Salmon, and before it starts quantifying, I get a stream of warnings like this:

```
WARNING: Transcript ENST00000458158 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000628972 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000439459 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000619909 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000445188 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000619770 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000572276 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000435490 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000627090 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000628916 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000420073 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000622069 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000415908 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000626581 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000445948 appears in the reference but did not appear in the BAM
WARNING: Transcript ENST00000574204 appears in the reference but did not appear in the BAM
```

Are you getting these as well?

**Comment by mikelove** [comment]
Yes, i get these as well both with our without gcBias.

**Comment by rob-p** [comment]
Ok, I have a backtrace of where the issue is coming from.  I think it might be due to either (1) some missing txps between the BAM and fasta or (2) a difference in the recorded lengths.

**Comment by rob-p** [comment]
Yes, this is certainly *an* issue.  My check goes one way (i.e., it emits a warning if things we find in the fasta file were not in the BAM header), but not the other, more dangerous way (i.e., there are things in the BAM header that we don't find in the FASTA file).  In this case, there are many transcripts that appear in the BAM header (and presumably have mappings), but are not in the fasta file.  Here are some examples

```
ERROR: Transcript ENST00000630276 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000429962 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000415237 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000450652 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000384843 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000602568 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000384229 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000420508 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000608317 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000424410 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000417463 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000623071 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000447720 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000436681 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000416615 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000431488 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000411581 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000624642 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000564901 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000617743 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000516211 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000612964 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000448260 appeared in the BAM index, but was not in the provided FASTA file
ERROR: Transcript ENST00000516334 appeared in the BAM index, but was not in the provided FASTA file
```

One question is what should we do in this case (we can't do bias modeling without the sequences, so the options are bail or turn bias modeling off).  The other question is why is this happening?

**Comment by rob-p** [comment]
Ok, the missing transcripts (from the reference FASTA) were definitely *the* problem.  I created a transcript fasta using the genome FASTA and GTF file that were fed to STAR.  Specifically, I used the command:

```
$ ./gffread -w all_transcripts.fa -g Homo_sapiens.GRCh38.dna.primary_assembly.fa Homo_sapiens.GRCh38.87.gtf
```

this produced transcript fasta that led to no warnings (fasta sequences not present in BAM) or errors (BAM sequences not present in fasta).  This also allowed quantification (with bias correction) to run to completion.  @mikelove, can you validate that this fixes things on your end?  If so, perhaps @tomsing1 could also validate that this is the same root cause of the issue for him?  In that case, I think that the right thing for me to do is to merge in the change that yells very loudly and bails if we find BAM header entries not present in the transcriptome FASTA.

**Comment by mikelove** [comment]
Thanks Rob for the quick investigation. I'll check tomorrow and I agree
with warning and quit as the best you can do. You could even suggest in the
warning to build the fasta as you have here from GTF and genome...

**Comment by mikelove** [comment]
I can confirm this avoids the problem. Thanks Rob. I used rsem-prepare-reference with the GTF and genome FASTA and used the transcripts.fa produced by rsem with salmon quant. No problems.

One minor thing I noticed is that the `libParams` dir is empty with or without GC bias still. Is that expected with the alignment based quantification?

**Comment by rob-p** [comment]
Hi Mike,

  Glad to hear this fixes it.  I pushed a commit that does the check, prints out a useful error message (that suggests how you can make a compatible transcriptome fasta) and then bails.  Regarding the `libParams` directory --- that is actually a somewhat anachronistic directory anyway.  Currently, I've been moving all of the parameters into their own (gzipped) files in the `aux_info` directory. I've kept `libParams` there for backward compatibility sake, but I think it's confusing if the fld appears in multiple places, but the other parameters appear somewhere else, so perhaps it's time to remove it (and note such in the next version's release notes).

**Comment by tomsing1** [comment]
Thanks a ton, @rob-p and @mikelove , for following up on this issue. Following your solution, I generated a new transcript FASTA file from Ensembl's mouse GTF and primary assembly genome FASTA files with [gffread](http://ccb.jhu.edu/software/stringtie/gff.shtml) instead of using Ensembl's cDNA FASTA files directly. That solved the issue for me as well. Awesome!

**Comment by rgranit** [comment]
I've encountered a very similar scenario - I've used STAR for alignment and next ran salmon quant with transcripts data.. I'm also getting the error:

`[2019-01-21 23:11:38.495] [jointLog] [critical] Please provide a reference FASTA file that includes all targets present in the BAM header
If you have access to the genome FASTA and GTF used for alignment`

But the correction suggested above using gttread does not solve my issue.. any suggestions?
