### ISSUE TITLE
Error with installing Salmon v0.7.2

### ISSUE THREAD

**Issue by mns1972** [COMBINE-lab/salmon#112]
Hi,
I seem to be having problems with installing Salmon on my mac.
I've tried doing this using 
**1. brew install salmon:**
brew install salmon
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/science).
==> Updated Formulae
homebrew/science/seqan

==> Installing salmon from homebrew/science
==> Downloading https://github.com/COMBINE-lab/salmon/archive/v0.7.2.tar.gz
Already downloaded: /Users/sangrim/Library/Caches/Homebrew/salmon-0.7.2.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/salmon/0.7.2 -DCMA
==> make install
🍺  /usr/local/Cellar/salmon/0.7.2: 6 files, 8.5M, built in 7 minutes 8 seconds
sangrim@C02Q7CT1G8WN:~/bin$> salmon
**salmon(2034,0x7fffbc21a3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffbc210000**

and also,
**2. compiling from the osx tarball
the installation seemingly succeeds,**
Install the project...
/usr/local/Cellar/cmake/3.7.1/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Up-to-date: /Users/../bin/salmon-0.7.2/lib
-- Up-to-date: /Users/../bin/salmon-0.7.2/lib/pkgconfig
-- Installing: /Users/../bin/salmon-0.7.2/bin/salmon
-- Installing: /Users/../bin/salmon-0.7.2/lib/libsalmon_core.a

Installation complete. Please ensure the following paths are set properly.

Please add /Users/../bin/salmon-0.7.2/bin to your PATH
Please add /Users/../bin/salmon-0.7.2/lib to your DYLD_FALLBACK_LIBRARY_PATH

...and then make test, hangs...
Running tests...
/usr/local/Cellar/cmake/3.7.1/bin/ctest --force-new-ctest-process 
Test project /Users/maheshsangrithi/bin/salmon-0.7.2/build
    Start 1: unit_tests
........Ctrl+C to cancel...
then if ./salmon is run, I get the same error...
salmon(2034,0x7fffbc21a3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffbc210000

Thanks in advance for your help.

**Comment by rob-p** [comment]
Hi @mns1972,

  Thanks for reporting this issue.  Are you on Sierra?  There is a known problem with libjemalloc (the memory allocator we use) under OSX 10.12.  This has been fixed upstream, and is fixed in the develop branch of Salmon (so the fix will make it into the next release).  For the time-being.  Could you tell me if the binary below works for you?

--Rob

[Salmon-0.7.3-pre_OSX_10.12.tar.gz](https://github.com/COMBINE-lab/salmon/files/657454/Salmon-0.7.3-pre_OSX_10.12.tar.gz)

**Comment by mns1972** [comment]
Thanks very much for such a such a speedy response - Yes I do have Mac OSX Sierra running.
This solution seems to work!
Many thanks indeed,
-Mahesh

**Comment by rob-p** [comment]
Great; glad to hear it.  I'm going to close this issue since this fix is already in develop and will make it to the next release.  At that point, the fix should make it to homebrew as well.
