### ISSUE TITLE
geneMap doesn't detect GFF3

### ISSUE THREAD

**Issue by jblachly** [COMBINE-lab/salmon#114]
Hi Rob and team,

the geneMap option wasn't automatically detecting my gff file as a transcript->gene mapping in the correct format, instead treating it as a simple mapping and yielding interestingly a single result in `quant.gene.sf`, "UTR" (which lies in column 3 of the GFF; unclear to me why it didn't pull from column 2 instead, yielding gene names "Ensembl" and "Havana").

Anyway, I found that Salmon is really only matching on the extension `.gtf` , **instead of `.gtf or .gff` as the help text indicates** :
```
 -g [ --geneMap ] arg                  File containing a mapping of
                                        transcripts to genes.  If this file is
                                        provided Salmon will output both
                                        quant.sf and quant.genes.sf files,
                                        where the latter contains aggregated
                                        gene-level abundance estimates.  The
                                        transcript to gene mapping should be
                                        provided as either a GTF file, or a in
                                        a simple tab-delimited format where
                                        each line contains the name of a
                                        transcript and the gene to which it
                                        belongs separated by a tab.  The
                                        extension of the file is used to
                                        determine how the file should be
                                        parsed.  Files ending in '.gtf' or
                                        '.gff' are assumed to be in GTF format;
                                        files with any other extension are
                                        assumed to be in the simple format.

```
 The offending comparison in `SalmonUtils.cpp` is here:
https://github.com/COMBINE-lab/salmon/blob/335c34b196205c6aebe4ddcc12c380eb47f5043a/src/SalmonUtils.cpp#L2241

While I have brought this to attention, it would be nice to also check for the extension `gff3` as well, since this is what Gencode supplies (and many people tend to append the `3` to the extension in practice).

Kind regards and thanks for doing great science

**Comment by rob-p** [comment]
Hi @jblachly,

  Thanks for pointing this out.  The underlying parser we use should also support gff (&gff3), so I should probably just expand the extension set.  I'll ping back here once the relevant changes have been made on the develop branch.  I'll also note that, generally, we now recommend [tximport](https://bioconductor.org/packages/release/bioc/html/tximport.html) as the way to aggregate transcript-level abundance estimates to the gene level, since it provides some nice multi-sample functionality and also allows the user to choose from a few different ways in which the aggregation can be performed.  If you're doing any of your downstream analysis in R, it's worth a look.

--Rob

**Comment by jblachly** [comment]
@rob-p By all means I agree with respect to tximport (after reading that F1000 paper). Still, it is very convenient to quickly have summarized gene-level TPMs to share with collaborators or for plotting purposes.

**Comment by rob-p** [comment]
Hi @jblachly,

  Thanks again for the kind words!  I agree that this option is useful for producing some quick gene-level results to show to collaborators.  I've just pushed a fix that should allow parsing of (well-formated) files that end in any of {.gtf, .GTF, .gff, .GFF, .gff3, .GFF3}.  Furthermore, going over the relevant bug revealed a latent potential bug that could pop up when there was a transcript in the salmon index that was absent from the GTF/GFF file.  So this commit fixes this as well.  All of this is present on the develop branch, but these changes will make it into the upcoming release (which should hit soon, if you care to wait for it).
