### ISSUE TITLE
strand specific quantification not working

### ISSUE THREAD

**Issue by dominik-handler** [COMBINE-lab/salmon#116]
Hi, 

I am trying to quantify a set of transcripts with salmon. I would like to quantify both the sense and antisense reads independently.
No matter what I tried so far, I have been successful to generate a strand specific output (sense or antisense).

I am using the following commands:
`salmon quant -i  ~/salmon_X -l U -r decollapsed.fa -o salmon-U -p 1`
`salmon quant -i  ~/salmon_X -l SF -r decollapsed.fa -o salmon-SF -p 1`
`salmon quant -i  ~/salmon_X -l SR -r decollapsed.fa -o salmon-SR -p 1`

This is part of the results I get back into the quant.sf files (settings indicated in the header row):

SF   |        |                 |         |          |   | SR   |        |                 |         |          |   | U    |        |                 |         |          |
------|--------|-----------------|---------|----------|---|------|--------|-----------------|---------|----------|---|------|--------|-----------------|---------|----------|
 Name | Length | EffectiveLength | TPM     | NumReads |   | Name | Length | EffectiveLength | TPM     | NumReads |   | Name | Length | EffectiveLength | TPM     | NumReads |
 A    | 7439   | 7238.57         | 566.807 | 2447.37  |   | A    | 7439   | 7238.57         | 566.807 | 2447.37  |   | A    | 7439   | 7238.57         | 566.807 | 2447.37  |
 B    | 6995   | 6794.57         | 2282.92 | 9252.63  |   | B    | 6995   | 6794.57         | 2282.92 | 9252.63  |   | B    | 6995   | 6794.57         | 2282.92 | 9252.63  |
 C    | 7567   | 7366.57         | 2052.26 | 9018     |   | C    | 7567   | 7366.57         | 2052.26 | 9018     |   | C    | 7567   | 7366.57         | 2052.26 | 9018     |
 D    | 3409   | 3208.57         | 1720.03 | 3292     |   | D    | 3409   | 3208.57         | 1720.03 | 3292     |   | D    | 3409   | 3208.57         | 1720.03 | 3292     |
 E    | 4648   | 4447.57         | 1102.16 | 2924     |   | E    | 4648   | 4447.57         | 1102.16 | 2924     |   | E    | 4648   | 4447.57         | 1102.16 | 2924     |
 F    | 6126   | 5925.57         | 75495.1 | 266846   |   | F    | 6126   | 5925.57         | 75495.1 | 266846   |   | F    | 6126   | 5925.57         | 75495.1 | 266846   |
 G    | 7404   | 7203.57         | 1147.33 | 4930     |   | G    | 7404   | 7203.57         | 1147.33 | 4930     |   | G    | 7404   | 7203.57         | 1147.33 | 4930     |
 H    | 7650   | 7449.57         | 139.749 | 621      |   | H    | 7650   | 7449.57         | 139.749 | 621      |   | H    | 7650   | 7449.57         | 139.749 | 621      |

This is the content of one of the cmd_info.json files:

> {
    "salmon_version": "0.7.2",
    "index": "~/salmon_X",
    "libType": "U",
    "unmatedReads": "decollapsed.fa",
    "output": "salmon-U",
    "threads": "1",
    "auxDir": "aux_info"
}

Am I doing something wrong here, or is this a problem with Salmon?

Thank you and all the best,
Dominik

**Comment by rob-p** [comment]
Hi Dominik,

  Salmon's *default* model handles strand specificity by assigning a very small, but non-zero prior value for a read to originate from an orientation different than that which is specified.  This has the effect, for reads that map in both directions, to *strongly* prefer the orientation consistent with the provided library type.  However, if a read maps *only* in a discordant manner, that mapping is nonetheless used.  If you truly want to ignore reads mapping in a manner inconsistent with the provided library type (i.e., drop them on the floor), you can achieve this by setting `--incompatPrior 0.0`.  This will tell Salmon to assign a 0 probability to any mapping that is not in accord with the provided library format type.

Best,
Rob

**Comment by dominik-handler** [comment]
Dear Rob,

Thank you for the quick reply. That totally solved my problem.
I will play around a bit more, because in this case Salmon definitely over-corrected the bias in the default settings (we do have sense and antisense transcription from these genes).

When I understand the thing more and I found something useful for you, I will write you again.

All the best,
Dominik
