### ISSUE TITLE
Mention default number of threads in readthedocs.io

### ISSUE THREAD

**Issue by emilyburke** [COMBINE-lab/salmon#118]
Could you please mention in your documentation, where you discuss the option for multiple threads (`http://salmon.readthedocs.io/en/latest/salmon.html#p-numthreads`) that the default number of threads requested by Salmon jobs is greater than 1. My jobs were running very slowly - turns out they were fighting over cores on a single node. I discovered each job was using 24 cores through checking `salmon quant --help-reads`. Mentioning that the default is much greater than 1 would be useful knowledge in the option summary writeup. Thank you!!

**Comment by rob-p** [comment]
Hi @emilyburke,

  Absolutely; sorry for the oversight and the confusion.  We'll update the documentation to mention this.

**Comment by rob-p** [comment]
Ok, I've updated the docs and added an explicit note about this in commit 95866337bde0feb57a0c3231efdfa26c847ba141.  It has propagated to the documentation now.  Thanks again for reporting this and offering this suggestion.

**Comment by emilyburke** [comment]
Perfect, thank you for the quick update!
Emily
