### ISSUE TITLE
Bioconda update to 0.8.1?

### ISSUE THREAD

**Issue by sschmeier** [COMBINE-lab/salmon#128]
I guess you are working on it?

Cheers,

    Seb

**Comment by sschmeier** [comment]
Cheers, Seb

**Comment by rob-p** [comment]
Homebred-Science is still having some issues (but I don't think it's salmon's fault).  However 0.8.2 is now available via bioconda :) https://github.com/bioconda/bioconda-recipes/pull/4208.  Let me know if you have any problems.

--Rob
