### ISSUE TITLE
Unexpected behavior when no reads are mapable / alpha to small

### ISSUE THREAD

**Issue by schelhorn** [COMBINE-lab/salmon#130]
Currently, `salmon` fails hard (termination with return code `1`) when no reads are mapable; that limits its applicability when screening for pathogens such as viruses that are not expected to express their factors in every sample. From my point of view that leads to [unexpected behavior in bcbio](https://github.com/chapmanb/bcbio-nextgen/issues/1883), which is also reflected in an issue [raised here](https://github.com/COMBINE-lab/salmon/issues/119). 

I would like to (re-)raise these issues here and encourage a change to `salmon` that leads to a more graceful behavior in such outlier cases, i.e. quantitation values of `0` for all quantified features instead of the hard error.

**Comment by rob-p** [comment]
Hi @schelhorn,  I agree.  Though having no mapping reads is "catastrophic" in the common intended use case for Salmon, I think we should have a more graceful handling.  Especially, since it's easy to diagnose.  I'll fix this in the next release.

**Comment by schelhorn** [comment]
Excellent, thanks!

**Comment by rob-p** [comment]
Hi @schelhorn,

  I've implemented these changes in the latest commit.  Now, the behavior if fewer than 10 reads are assigned sample-wide will be to output a `quant.sf` file with all 0s and to record in the `meta_info.json` file the quant error that led to this output.  Does this seem reasonable?  Also, do you suggest that, even in this case, the return code be 0?  In some sense, something very unexpected happened (i.e. you had no --- or by default, fewer than 10 --- mapping reads), so signifying that at the process level might be useful.  However, if you require that every "valid" run of salmon return with code 0, I can see an argument against returning a non-standard status in this case.

**Comment by schelhorn** [comment]
Thanks for fixing - all fine by me.
