### ISSUE TITLE
Broken linked files cause salmon indexing to pause (indefinitely) without throwing an error

### ISSUE THREAD

**Issue by halexand** [COMBINE-lab/salmon#134]
We tried to run salmon with broken linked files (as in, we accidently linked to the wrong directory). This led to salmon getting to the kmer counting stage and then permanently pausing there (see output below). You can see a version of the broken protocol here: https://github.com/ngs-docs/2017-ucsc-metagenomics/blob/cd417dc4b384b668eda2a477fd805ebb3b30cd00/salmon_tutorial.rst

So, it would be nice if salmon could compensate for this misstep on our part and notify us if a broken linked file is given as input, rather than just pausing. 

`tx160085@js-104-35:~/Salmon-0.7.2_linux_x86_64/data$ salmon index -t metagG.ffn -i transcript_index -
-type quasi -k 31
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and minor bug fixes; please upgrade at your
earliest convenience.
###
index ["transcript_index"] did not previously exist  . . . creating it
[2017-04-23 17:02:32.614] [jLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers`

Thank you!

**Comment by halexand** [comment]
We are entering this so that we don't forget it during the workshop; we'll check newer versions of salmon when we get a  chance. @ctb @taylorreiter

**Comment by rob-p** [comment]
Hi @halexand,

  Please do let me know if this is fixed for you in the latest release.  I believe it's the same as the issue reported [here](https://github.com/COMBINE-lab/salmon/issues/105), which has indeed been fixed since v0.8.0.

Thanks!
Rob
