### ISSUE TITLE
RapMap and JSON parsing error salmon 0.8.2

### ISSUE THREAD

**Issue by sudeep71** [COMBINE-lab/salmon#135]
Hi,

I am running the latest version of Salmon 0.8.2 and I am getting the following error. I did remake the transcript index with the new version of salmon. I get no errors when i compile or run the "make test".  

Logs will be written to salmon_output_A9039/logs
[2017-05-08 08:59:23.370] [jointLog] [info] parsing read library format
[2017-05-08 08:59:23.370] [jointLog] [info] There is 1 library.
[2017-05-08 08:59:23.395] [stderrLog] [error] Encountered exception [JSON Parsing failed - provided NVP (SeqHash) not found] when loading index.
[2017-05-08 08:59:23.395] [stderrLog] [error] The index was likely build with an older (and incompatible) version of RapMap.  Please re-build the index with a compatible version.

Using boost 1.64, Clang 3.9, on a linux box.

Any help will be appreciated.

Thanks

**Comment by rob-p** [comment]
Hi @sudeep71,

  Can you upload the JSON files in your index directory?  The problem seems to be that fields that are expected to exist in the index are missing.  Since you built Salmon from source yourself, if you built it in the same directory as a previous version, did you run `cmake ..` first?  Since the newest version depends on upstream changes in RapMap, those external dependences need to be re-fetched.  In fact, I'd suggest that you remove (or move) the entire build directory, and then make a new one to start the build process from scratch.

--Rob

**Comment by sudeep71** [comment]
Hi @rob-p,

i have pasted the three .json file data below. The way i installed was by first installing boost (./bootstrap.sh --prefix=/usr/local), and setting up boost. I did install clang 3.9 too. Then i did use 
cmake -DBOOST_ROOT=/usr/local, make and sudo make install and make test. Then i copied the executable made in bin to /usr/local/bin as sudo. May be it's me using sudo make install which is goofing stuff..

Let me try to reinstall without "sudo"

I have used salmon 0.8.1, with no problems on another machine. So on this machine this is a fresh install. I do think there is a script which does fetch Rapmap..

Thanks

Sudeep

#header.json

    "value0": {
        "IndexType": 1,
        "IndexVersion": "q5",
        "UsesKmers": true,
        "KmerLen": 31,
        "BigSA": false,
        "PerfectHash": false,
        "SeqHash": "bc7ce7a64f79aeb355818ffc5050bf682f281160738498d11dbc3330b67c4889",
        "NameHash": "3843f236fc87b02e5c477daa29053725d376d8725c10ec23ee2225e8fab6326e"
    }
}

#refino.json
{
    "ReferenceFiles": [
        "Equus_caballus.EquCab2.cds.all.fa"
    ]
}

#versioninfo.json

{
    "indexVersion": 2,
    "hasAuxIndex": false,
    "auxKmerLength": 31,
    "indexType": 1
}

**Comment by sudeep71** [comment]
hi @rob-p 

I figured it out. Just needed to set my PATHS correct for it to work!!!

Thanks
Sudeep

**Comment by Darlingfuer** [comment]
@sudeep71 Hi there, I run into the same error when I use salmon. Would please tell me what you did to set a correct PATH ? Thanks!

**Comment by sudeep71** [comment]
When you compile the program, the last few lines tell you to make links to
the salmon executable and the LIB file. I forgot the lib file and was
getting this error. You can run the executable from the area of install
(works fine) or create a path to /urs/local/bin or any other folder you
want to install. You need to do this for both the files.

For making path in linux:
https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux

Hope this helps
