### ISSUE TITLE
Build Issues: /bin/ld: cannot find -lz

### ISSUE THREAD

**Issue by JakeGoodall** [COMBINE-lab/salmon#141]
**Hi there,**

**So I'm trying to install Salmon-0.8.2 but I'm having a few issues. I should note upfront that I'm working on a cluster and therefore I do not have root privileges.** 

**Anyway, when going through the build process I wasn't able to install boost using salmons flags, so I installed it independently. I was then able to make it to the 'make' stage, but the got to this point:**

[  7%] Built target liblzma
[ 14%] Built target libbz2
[ 21%] Built target libdivsufsort
[ 29%] Built target liberal
[ 37%] Built target libgff
[ 38%] Performing build step for 'libbwa'
utils.c:33:18: fatal error: zlib.h: No such file or directory
#include <zlib.h>
                    ^
compilation terminated.
make[3]: *** [utils.o] Error 1
make[2]: *** [libbwa-prefix/src/libbwa-stamp/libbwa-build] Error 2
make[1]: *** [CMakeFiles/libbwa.dir/all] Error 2
make: *** [all] Error 2

**I resolved this by making a custom script which told make where to look for zlib:**

export C_INCLUDE_PATH=/users/work/jake/bin/zlib-1.2.11/
export CPLUS_INCLUDE_PATH=/users/work/jake/bin/zlib-1.2.11/
make

**Executing that script allowed me to progress a little but I'm now receiving the following error message:**

[  7%] Built target liblzma
[ 14%] Built target libbz2
[ 21%] Built target libdivsufsort
[ 29%] Built target libcereal
[ 37%] Built target libgff
[ 38%] Performing build step for 'libbwa'
/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[3]: *** [bwa] Error 1
make[2]: *** [libbwa-prefix/src/libbwa-stamp/libbwa-build] Error 2
make[1]: *** [CMakeFiles/libbwa.dir/all] Error 2
make: *** [all] Error 2

**I'm not the best command line user so my 'fixes' might not be the best approach. Still I'm not really sure how to approach this new error message. Google doesn't turn up much so any advice you could give it would be greatly appreciated.**

**Comment by k3yavi** [comment]
You can try `sudo apt-get install zlib1g-dev`.
If you don't have root privilege then you might have to provide the path to the library file of the zlib.

**Comment by JakeGoodall** [comment]
I think the issue surrounding make not finding zlib has been resolved. Its probably confusing that I included it, the detail was more so me just highlighting that I'm trying to build the program in a non-standard way by invoking a script that tell 'make' where to find zlib. The script, which seems to be working for zlib is the following. 
$   export C_INCLUDE_PATH=/users/work/jake/bin/zlib-1.2.11/
$   export CPLUS_INCLUDE_PATH=/users/work/jake/bin/zlib-1.2.11/
$   make

Anyway, I think the issue now is ld. Or more specifically I guess it can't find the ld -lz command. Could it be that my ld version is old and doesn't contain the -lz command? Also do you know what exactly ld is?

**Comment by k3yavi** [comment]
ld is just the GNU linker.
I still think it's not able to find the zlib **library** file since the error at `-lz` where `-l` gives the namespace of the library.
If you are confident about the inclusion of the `Zlib` then can you try clearing the cmake cache (i.e. remove the file CMakeCache.txt) and build again?

**Comment by JakeGoodall** [comment]
Okay, so I've made some progress. After deleting the Cache.txt file I tried to build again at which point I noticed the following:
**WARNING: Target "salmon" requests linking to directory "/users/work/jake/bin/zlib-1.2.11/".  Targets may link only to libraries.  CMake is dropping the item.**
**WARNING: Target "unitTests" requests linking to directory "/users/work/jake/bin/zlib-1.2.11/".  Targets may link only to libraries.  CMake is dropping the item.**

So I actually went back a step and check my initial make command in the /build/ directory. It also had the same issue and therefore wasn't building correctly. I started the install again from ../salmon-0.8.2/build/ using the following: 

cmake -DBOOST_ROOT=/users/work/jake/bin/boost_1_64_0/ -DZLIB_LIBRARY=/users/work/jake/bin/zlib-1.2.11/zlib.h .. 

It seemed to work nicely and I got all the build files to propagate into the ../salmon-0.8.2/build/ directory. From here I ran 'make' which did a whole bunch of things I hadn't seen it do yet, so assumably it was working as intended. This is until it got to the following stage:

Scanning dependencies of target libbwa
[ 48%] Creating directories for 'libbwa'
[ 49%] Performing download step for 'libbwa'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    167      0 --:--:-- --:--:-- --:--:--   167
  0     0    0  219k    0     0   123k      0 --:--:--  0:00:01 --:--:--  326k
bwa-master.tar.gz: OK
bwa-0.7.12.3/.gitignore
bwa-0.7.12.3/.travis.yml
bwa-0.7.12.3/COPYING
bwa-0.7.12.3/ChangeLog
bwa-0.7.12.3/Makefile
bwa-0.7.12.3/NEWS.md
bwa-0.7.12.3/QSufSort.c
bwa-0.7.12.3/QSufSort.h
bwa-0.7.12.3/README-alt.md
bwa-0.7.12.3/README.md
bwa-0.7.12.3/bamlite.c
bwa-0.7.12.3/bamlite.h
bwa-0.7.12.3/bntseq.c
bwa-0.7.12.3/bntseq.h
bwa-0.7.12.3/bwa.1
bwa-0.7.12.3/bwa.c
bwa-0.7.12.3/bwa.h
bwa-0.7.12.3/bwakit/
bwa-0.7.12.3/bwakit/README.md
bwa-0.7.12.3/bwakit/bwa-postalt.js
bwa-0.7.12.3/bwakit/run-HLA
bwa-0.7.12.3/bwakit/run-bwamem
bwa-0.7.12.3/bwakit/run-gen-ref
bwa-0.7.12.3/bwakit/typeHLA-selctg.js
bwa-0.7.12.3/bwakit/typeHLA.js
bwa-0.7.12.3/bwakit/typeHLA.sh
bwa-0.7.12.3/bwamem.c
bwa-0.7.12.3/bwamem.h
bwa-0.7.12.3/bwamem_extra.c
bwa-0.7.12.3/bwamem_pair.c
bwa-0.7.12.3/bwape.c
bwa-0.7.12.3/bwase.c
bwa-0.7.12.3/bwase.h
bwa-0.7.12.3/bwaseqio.c
bwa-0.7.12.3/bwashm.c
bwa-0.7.12.3/bwt.c
bwa-0.7.12.3/bwt.h
bwa-0.7.12.3/bwt_gen.c
bwa-0.7.12.3/bwt_lite.c
bwa-0.7.12.3/bwt_lite.h
bwa-0.7.12.3/bwtaln.c
bwa-0.7.12.3/bwtaln.h
bwa-0.7.12.3/bwtgap.c
bwa-0.7.12.3/bwtgap.h
bwa-0.7.12.3/bwtindex.c
bwa-0.7.12.3/bwtsw2.h
bwa-0.7.12.3/bwtsw2_aux.c
bwa-0.7.12.3/bwtsw2_chain.c
bwa-0.7.12.3/bwtsw2_core.c
bwa-0.7.12.3/bwtsw2_main.c
bwa-0.7.12.3/bwtsw2_pair.c
bwa-0.7.12.3/example.c
bwa-0.7.12.3/fastmap.c
bwa-0.7.12.3/is.c
bwa-0.7.12.3/kbtree.h
bwa-0.7.12.3/khash.h
bwa-0.7.12.3/kopen.c
bwa-0.7.12.3/kseq.h
bwa-0.7.12.3/ksort.h
bwa-0.7.12.3/kstring.c
bwa-0.7.12.3/kstring.h
bwa-0.7.12.3/ksw.c
bwa-0.7.12.3/ksw.h
bwa-0.7.12.3/kthread.c
bwa-0.7.12.3/kvec.h
bwa-0.7.12.3/main.c
bwa-0.7.12.3/malloc_wrap.c
bwa-0.7.12.3/malloc_wrap.h
bwa-0.7.12.3/maxk.c
bwa-0.7.12.3/pemerge.c
bwa-0.7.12.3/qualfa2fq.pl
bwa-0.7.12.3/utils.c
bwa-0.7.12.3/utils.h
bwa-0.7.12.3/xa2multi.pl
[ 50%] No patch step for 'libbwa'
[ 50%] No update step for 'libbwa'
[ 51%] No configure step for 'libbwa'
[ 51%] Performing build step for 'libbwa'
/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[3]: *** [bwa] Error 1
make[2]: *** [libbwa-prefix/src/libbwa-stamp/libbwa-build] Error 2
make[1]: *** [CMakeFiles/libbwa.dir/all] Error 2
make: *** [all] Error 2

So as you said I'd say its having issued finding the zlibs library. Similar to how I used 'DZLIB_LIBRARY=/users/work/jake/bin/zlib-1.2.11/zlib.h' to specify the zlib library for make, is there a way to do it for the make command?

Sorry for the very basic questions.... I'm kind of learning as I go.

**Comment by k3yavi** [comment]
Even I am not sure how to add the flags in the make command explicitly.
But, I'd suggest you can try couple of things:
Like I said before installing zlib to apt-get/brew would be the easiest.
If not can you try `-DZLIB_LIBRARY=/users/work/jake/bin/zlib-1.2.11/` i.e. remove `zlib.h`.
As you can see I am learning on the go too 😜

**Comment by JakeGoodall** [comment]
Unfortunately I can't use apt-get/brew/yum to install zlib since I'm not root on my cluster. This is why I installed zlib-1.2.11 separately. 

Make doesn't seem to allow the same commands as cmake so `-DZLIB_LIBRARY=/users/work/jake/bin/zlib-1.2.11/` or any variation of it isn't accepted. I guess I'll keep plugging away to see if I can resolve the issue. There isn't any build files that I could modify to include the directory path to zlib?

**Comment by k3yavi** [comment]
Actually I meant the following command:
`cmake -DBOOST_ROOT=/users/work/jake/bin/boost_1_64_0/ -DZLIB_LIBRARY=/users/work/jake/bin/zlib-1.2.11/`.
Also you try [linuxbrew](http://linuxbrew.sh/) for which you don't need root access.

**Comment by JakeGoodall** [comment]
So after struggling, and failing for a little bit I looked into linuxbrew - its pretty much the best thing ever. I'm honestly not sure what my original issue was derived from but using linuxbrew to install the dependancies and then salmon itself worked perfectly. Honestly much easier to install it this way. 

Salmon seems to be working now so I'd say my install issues are resolved. Thanks for your help, and an extra thanks for introducing my to linuxbrew, its going to make my work a lot easier.
