### ISSUE TITLE
Salmon homebrew install broken

### ISSUE THREAD

**Issue by standage** [COMBINE-lab/salmon#142]
I have updated my homebrew index and installed Salmon on my Macbook (0S X Sierra). However, when I run `salmon` or `salmon -h` on the command line I get the following error message.

```
salmon(41538,0x7fffc4f5a3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffc4f50000
```

`brew doctor` doesn't show any unexpected issues. Any ideas what might be going on?

Thanks!

**Comment by rob-p** [comment]
Hrmmm --- there was definitely an issue with the jemalloc allocator that Salmon uses by default with OSX Sierra.  We have subsequently pulled in the (upstream) fixes that resolve this.  Unfortunately, we've been having some issues getting Hombrew's CI to be happy with the latest version of Salmon (they are still on v0.7.2, I believe).  So, as far as suggestions, I could offer the following:

  1) The latest Salmon (0.8.2) should work fine on both linux and OSX via bioconda (though I don't know if this is heresy to you or not ;P).
  2) Also, my development box is OS X Sierra, so the pre-compiled binaries should work as well.
  3) See if you have any ideas of how to move the 0.8.2 PR forward [in linuxbrew](https://github.com/Homebrew/homebrew-science/pull/5284).  I will get to this eventually, but likely not until after I return from ISMB.

Best,
Rob

**Comment by standage** [comment]
Ok, not urgent. I installed 0.8.2 from source with no problem, so I'll just use that for now. I have just come to take homebrew's convenience for granted!

**Comment by tseemann** [comment]
@standage 0.8.2 is working in Brew now.
