### ISSUE TITLE
Salmon quant segfaults when using multiple BAMs

### ISSUE THREAD

**Issue by tobi-te** [COMBINE-lab/salmon#145]
Hi,

I have the problem that salmon quant exits with a segfault when more than one BAM file is provided. 
If the BAM files are provided one at a time, no error or segfault happens and salmon wickedly fast quantificates the transcripts. The first used BAM files where shuffled (with samtools bamshuf) as recommended in the docs.

To exclude an error on my side I did:
- try unshuffled BAM files --> Segfault
- try older Salmon Version (7.2) --> Segfault
- build Salmon from source --> Segfault
- use different transcriptdata (see below) --> Segfault

The segfault happens after all reads (in all files) are processed:
`processed 48000000 reads in current roundSegmentation fault`

### Example workflow:

Get the read data from [here](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?run=ERR1433122)  for example with SRA Toolkit:
`vdb-dump -f fastq --gzip --output-file test.fastq.gz ERR1433122`

Then use STAR:

First build a genome index for the reference transcriptset from [here](https://ics.hutton.ac.uk/atRTD/) and the [TAIR10 genome](https://www.arabidopsis.org/download/index-auto.jsp?dir=%2Fdownload_files%2FGenes%2FTAIR10_genome_release%2FTAIR10_chromosome_files)
You probably have to rename the chromosomes either in the .gtf or .fas file, to have consistent names.

`STAR --runThreadN 4 --runMode genomeGenerate --genomeDir genome_index/ --genomeFastaFiles TAIR10_chr_all_edited.fas  --sjdbGTFfile AtRTD2_19April2016.gtf --sjdbOverhang 100`

Then map:

`STAR --runThreadN 4 --genomeDir genome_index --readFilesCommand zcat --readFilesIn test.fastq.gz --sjdbOverhang 100 --sjdbGTFfile AtRTD2_19April2016.gtf --outFileNamePrefix mapping/ --quantMode TranscriptomeSAM`

and make a .fa file from the genome and the .gtf with:
`gffread -w gff_merged.fa -g TAIR10_chr_all_edited.fas AtRTD2_19April2016.gtf`

Now make a copy of the "Aligned.toTranscriptome.out.bam" (for the sake of simplicity) and try
`salmon quant -l A -a Aligned.toTranscriptome.out.bam Aligned.toTranscriptome.out_copy.bam -t gff_merged.fa -o ./out/`

Then the above mentioned segfault happens.

The only workaround I found is to merge the BAM files of the replicates with "samtools merge".

Any idea why the segfault appears?

Cheers,
Tobi

**Comment by k3yavi** [comment]
Hi @tobi-te ,

Thanks for the bug report we will try to correct it in our next release.
In the mean time you can make it work by swapping [line](https://github.com/COMBINE-lab/salmon/blob/master/include/BAMQueue.tpp#L540) by `scram_close(fp_);` and compiling it again.

Thanks!

**Comment by tobi-te** [comment]
Thanks for the fast support. With the fix it works like a charm.
