### ISSUE TITLE
salmon index missing

### ISSUE THREAD

**Issue by jiaxing912** [COMBINE-lab/salmon#146]
I downloaded Salmon-0.8.2_linux_x86_64, and I decompressed it.
When I ran salmon, it worked.
But  when I ran salmon index, I got a mistake as follow:

Version Info: This is the most recent version of Salmon.
exception : [the option '--index' is required but missing]. Exiting.
 
Please help me.

**Comment by k3yavi** [comment]
Hi,
When running salmon index command please specify --index flag and then path to the directory where index should be stored.
For more information use salmon index -h.

**Comment by jiaxing912** [comment]
Thanks you so much!
salmon index -h  worked
