### ISSUE TITLE
"salmon cite" behaves like "salmon -h"

### ISSUE THREAD

**Issue by tseemann** [COMBINE-lab/salmon#149]
```
% salmon cite

Version Info: This is the most recent version of Salmon.
Salmon v0.8.2

Usage:  salmon -h|--help or
        salmon -v|--version or
        salmon -c|--cite or
        salmon [--no-version-check] <COMMAND> [-h | options]

Commands:
     cite  Show salmon citation information
     index Create a salmon index
     quant Quantify a sample
     swim  Perform super-secret operation
```

It seems I need to do `salmon -c` instead

**Comment by rob-p** [comment]
Hi @tseemann,

  I can definitely implement the behavior you suggest (i.e. cite as a `<COMMAND>`), but right now it is an option.  So you can run `salmon -c` or `salmon --cite`, but not `salmon cite`.

--Rob

**Comment by tseemann** [comment]
I don't mind what you do, but currently it says `cite` is a <COMMAND>, but it isn't?

```
Commands:
     cite  Show salmon citation information
     index Create a salmon index
     quant Quantify a sample
     swim  Perform super-secret operation
```

**Comment by rob-p** [comment]
Ahh, serves me right for trying to write that help message by hand!  I'll remove `cite` from the list of "commands" in the next release.

**Comment by rob-p** [comment]
These are resolved in develop and will be fixed in the next release.
