### ISSUE TITLE
tbb-2017_U3.tgz did not match expected SHA256! Exiting.

### ISSUE THREAD

**Issue by teshomem** [COMBINE-lab/salmon#153]
Performing download step for 'libtbb'
tbb-2017_U3.tgz: FAILED
sha256sum: WARNING: 1 of 1 computed checksum did NOT match
tbb-2017_U3.tgz did not match expected SHA256! Exiting.
make[2]: *** [libtbb-prefix/src/libtbb-stamp/libtbb-download] Error 1
make[1]: *** [CMakeFiles/libtbb.dir/all] Error 2
make: *** [all] Error 2
-----------------------------------------------------------
command used
cmake -DBOOST_INCLUDEDIR=/local/genome/packages/boost/1.57.0/include/ -DBOOST_LIBRARYDIR=/local/genome/packages/boost/1.57.0/lib/ -DCMAKE_INSTALL_PREFIX=/local/genome/packages/salmon/0.8.2

------------------------------------------------------------------------
boost/1.57.0      
gcc/4.9.4

**Comment by k3yavi** [comment]
Hi @teshomem ,

We are working on resolving this issue just waiting for few other things to resolve before making a new tagged release.
In the meantime you can resolve this issue by replace the hash in [this](https://github.com/COMBINE-lab/salmon/blob/master/CMakeLists.txt#L522) line by `00a8b2798c498507572e24c2db7bf4896f05b760a38ed9ba566ffd348a7c6cef `.

**Comment by teshomem** [comment]
Hi @k3yavi,

Thank you so much.
