### ISSUE TITLE
Handling transcript variants

### ISSUE THREAD

**Issue by teshomem** [COMBINE-lab/salmon#154]
Hi,

The gene has multiple transcript variants and all of them included when we produced the transcript index. After we run salmon we get the following, for example

```
* rna16   2134    1885    0.357692        13.4961
* rna15   2142    1893    0       0
* rna14   2227    1978    0.644159        25.5039
```

My question is , which transcripts are relevant to proceed with sleuth? Is it possible to make salmon to report the quantification per gene like HTSeq if all variants need to be considered?

**Comment by rob-p** [comment]
Hi @teshomem,

  If you want to proceed with transcript-level differential expression, _all transcripts are relevant_.  That is, the relevant tools (e.g. DESeq2, limma-voom, Sleuth, etc.) will expect to be provided with _all_ quantified isoforms for each gene.  They will then automatically apply their own filtering criteria to determine which transcripts to actually test for DE. 

  If you want to proceed with DE at the gene level (and hence want to aggregate the quantification information from the level of transcripts to genes), the easiest option is to use the [tximport](http://bioconductor.org/packages/release/bioc/html/tximport.html) package.  It can import all of the quantifications from multiple runs of Salmon, aggregate them to the gene level, and produce a count matrix that can then be used with traditional count-based gene-level DE tools.  I would recommend the pipeline Salmon => tximport => DESeq2 for gene-level DE analysis.

  Finally, the best place for questions like this, that don't have to do with a specific bug or feature request for the Salmon software, is the [Google user group](https://groups.google.com/forum/#!forum/sailfish-users).  This way, other users will be more likely to provide you with feedback and help answer your questions.

**Comment by teshomem** [comment]
Thank you so much @rob-p
