### ISSUE TITLE
Can I combine quants from SE and PE reads from replicates of same sample in Salmon Quasi-mapping mode?

### ISSUE THREAD

**Issue by wondersandy** [COMBINE-lab/salmon#156]
Dear Dr. Patro,

First of all, my apologies as I want to make it clear that I have just posted this same question on Bioconductor community as well in a hope to get a quick reply. 

I have put great amount of effort to find out answer to this question on internet. Couldn't find it anywhere (bioconductor, biostars, seqanswers, github etc.).

I have 3 replicates for each sample and one of the replicates from each sample is single-end and other two are paired-end as SE and PE were processed at different facilities (I know I have to do batch correction in downstream analysis). Now I want to use transcript level abundance from quant.sf file which I derived for each replicates using Salmon's quasi-mapping pipeline (used appropriate flags for SE and PE reads). All these (SE & PE) reads are strand specific. 

My question is, can I use quant.sf directly from these replicates for downstream DE analysis using tximport or do SE or PE requires separate kind of processing before I can use them together as replicates for downstream analysis. I am planning to use limma-voom for my DE analysis.

Thank you so much for your time and apologies if the question was answered already.
Sandip Darji

**Comment by rob-p** [comment]
Hi @wondersandy, 

  It looks like @mikelove [got around to answering this almost immediately ;P](https://support.bioconductor.org/p/100693/), so I'm going to close this issue.  Please let us know if you have any further questions.

Best,
Rob

**Comment by wondersandy** [comment]
Oopps. I am sorry I forgot I opened an issue on Github as well. Yes @mikelove did address the issue on Bioconductor support site. Thank you for your response.

Sandip
