### ISSUE TITLE
Library format checking for stranded libraries gives uninformative debugging messages

### ISSUE THREAD

**Issue by mdshw5** [COMBINE-lab/salmon#16]
I've just been testing Salmon using Illumina TruSeq stranded (dUTP) libraries. Using either `ISF` (correct libType) or `ISR` I get a __ton__ of messages like this:

```
expected = Library format { type: }
paired end, relative orientation:inwardexpected = Library format { type:paired end, relative orientation:Library format { type:paired end, relative orientation:inwardpaired endinward, strandedness:, relative orientation:inward, strandedness:(sense, antisense) }
observed = Library format { type:paired end, relative orientation:inward, strandedness:(antisense, sense) }
(sense, antisense)expected = , strandedness:(sense, antisense), strandedness:(sense, antisense) }
observed =  }
Library format { type:paired end, relative orientation:inward, strandedness:(sense, antisense) }
observed = Library format { type:paired end, relative orientation:inward, strandedness:(antisense, sense) }
expected = Library format { type:observed = Library format { type: }
paired endLibrary format { type:paired end, relative orientation:, relative orientation:inward, strandedness:(sense, antisense) }
observed = Library format { type:paired end, relative orientation:inward, strandedness:observed = inward, strandedness:(antisense, sense) }
(antisense, sense) }paired end, relative orientation:inward, strandedness:(antisense, sense) }
expected = Library format { type:paired end, relative orientation:inward, strandedness:(sense, antisense)expected = Library format { type:Library format { type:
 }paired endpaired endexpected = Library format { type:paired end, relative orientation:
, relative orientation:inwardinward, strandedness:(sense, antisense)observed = , strandedness:(antisense, sense) }
 }
observed = Library format { type:paired end, relative orientation:inward, strandedness:(antisense, sense) }expected = Library format { type:, relative orientation:Library format { type:paired end
```
and so on...

It seems that the [`LibraryFormat` class](https://github.com/COMBINE-lab/salmon/blob/a6a4fe0dcf71674a59eb901d5ec6933df40de7f2/src/LibraryFormat.cpp#L52) is performing this check, and that the string format method is producing all of this output on stderr. 

I believe that the Salmon index I'm using contains some transcript sequences from the "wrong" strand, and it would be helpful if the program gave information about the observed mapping (maybe just the transcript sequence ID) so that I could track down the error during index generation. 

It also seems that all of the above error output contains no line terminators, although maybe this has been fixed in a more recent version.

```
-bash-4.1$ salmon --version
version : 0.4.0
```

cc @jmerkin

**Comment by rob-p** [comment]
@mdshw5 --- Salmon has definitely become less "complain-y" in the newer versions.  That is, it will no longer spew out error messages for all of the fragments that show up in an unexpected orientation.  However, the summary statistics are currently very "summary".  There is a file in the quantification directory called `libFormatCounts.txt` that summarizes the number of alignments seen in the different orientations etc.

However, I *really* like your idea of recording the "violating" transcripts.  That is, we could maintain some "threshold" beyond which if there are these many "incorrectly" mapping fragments for a transcript, the transcript is recorded and reported to the user as potentially being in the wrong orientation in the index.

**Comment by rob-p** [comment]
I still like the idea of tagging potentially violating transcripts, but I think that the existing issue is reasonably well-resolved with the combination of (1) the new format of reporting incompatible mappings (i.e. if there is any compatible mapping of a read, then the entire read is considered as "compatible") and (2) the ability to write the actual mappings out, so that they can be inspected if desired.
