### ISSUE TITLE
Qual Encoding question

### ISSUE THREAD

**Issue by gianfilippo** [COMBINE-lab/salmon#170]
Hi,

I just tried Salmon and had a very low (23%) mapping rate on files that were mapped above 70% with tophat.
The files are old, and they were generated with CASAVA 1.5 (Phred+64)
Does Salmon assume Phred+33 quality scores ?
Thanks

**Comment by rob-p** [comment]
Hi @gianfilippo,

  No; in fact, the quality scores are not even relevant to Salmon's default mapping algorithm.  How long are the reads?  Salmon's default minimum match length may be too long if you are dealing with old, short reads (e.g. 50bp or less).  In that case, I would recommend building the index with a smaller value of `k` --- e.g. like k = 21 or k = 23.

**Comment by gianfilippo** [comment]
Hi,

thanks for the prompt reply!! :)

My reads are PE 75 bp.

**Comment by gianfilippo** [comment]
Hi,
thanks for the

**Comment by rob-p** [comment]
Sure;  the other thing you may want to consider is what is in your index.  For example, if you had a ribo-zero protocol here, you may get a higher mapping rate if you include rRNA.  Otherwise, is there a significant degree of intron retention?

**Comment by gianfilippo** [comment]
This was done using polyA selection. I do not expect much intron retention. The reads come from a normal control.
I used the quasi-mapping mode. Perhaps I should try the alignment based mode and see if there is any difference. 
What do you think ?
Perhaps I did not generate the index correctly ?

**Comment by rob-p** [comment]
Interesting.  So, the question is then where the reads are going that are mapped by TopHat2 but not by Salmon.  Since Salmon indexes _only_ the transcriptome, then anything not explicitly included in the index cannot be mapped to.  So my guess is that there is likely something in the genome, but not in the transcriptome, to which TopHat2 is able to map the reads.  It also wouldn't hurt to see how the mapping rate changes if you build the Salmon index with a smaller `k`.

**Comment by gianfilippo** [comment]
ok. I will try to rebuild the index with a smaller k and remap.
I will also try the alignment based mode.
Just to make sure, below is how I generated the Salmon index:
I am using the GRRCh37.75 (Homo_sapiens.GRCh37.75.dna.toplevel.fa)
and Gencode.v19
I removed the CHR from gencode GTF file
I generated then genome index using Bowtie2-build and used the rsem-prepare-reference to extract transcripts from gencode
rsem-prepare-reference --gtf gencode.gtf --bowtie2 GRCh37.fa gencode.transcript
Finally, I generated the Salmon index
salmon index -t gencode.transcript.fa -i gencode.transcript_index --type quasi -k 31

Unless there si something obviously wrong, that you can see, I will go ahead with the two runs and get back to you
Thanks for your help!

**Comment by roryk** [comment]
If you are getting a lot of reads mapping to the genome but not quantified with Salmon, a good thing to check for is genomic DNA contamination.  If you count up read mapping to genes with featureCounts or something similar you can detect genomic DNA contamination by looking at the numbers that fall into intergenic regions.

**Comment by gianfilippo** [comment]
thanks. I will look into it

**Comment by gianfilippo** [comment]
Hi,

I think I identify the issue. The FASTQ files for some samples were, somehow, altered. I know they were compressed with QUIP and archived. Somehow, in the process something (or someone) altered the files. 
My origina tophat mapping was ok. My tophat mapping on some of these latest files, in reality, shows a high rate of  multimappers. It turns out that the quality scores are also not what they were supposed to be. After various attempts, I manage to, at least, get the files to the point where they can be used. Now Salmon is working properly, as far as mapping rate and number of processed reads.

Many thanks for your help
