### ISSUE TITLE
Cannot combine distributions that live in a different space

### ISSUE THREAD

**Issue by antonkulaga** [COMBINE-lab/salmon#175]
I have misterious "hits: 17435551, hits per frag:  1.34457 Cannot combine distributions that live in a different space!" error for the paired reads.
Here are the parameters:
```bash
salmon quant -i /pipelines/indexes/GRAY_WHALE/salmon/graywhale_anton --threads 8 -l A -r /pipelines/results/graywhale/transcriptome/trinity_out_dir/Trinity-GG.fasta -1 /pipelines/results/graywhale/transcriptome/ours/kidney/trimmed/GWkidneymother_S1_L001_R1_001_trimmed.fastq.gz -2 /pipelines/results/graywhale/transcriptome/ours/kidney/trimmed/GWkidneymother_S1_L001_R2_001_trimmed.fastq.gz -o transcripts_quant
```
All the files and folders are avaluabe for download, just add reads_1: http://pipelines1.westeurope.cloudapp.azure.com/ before /pipelines. Like this:

http://pipelines1.westeurope.cloudapp.azure.com/pipelines/results/graywhale/transcriptome/ours/kidney/trimmed/GWkidneymother_S1_L001_R1_001_trimmed.fastq.gz

http://pipelines1.westeurope.cloudapp.azure.com/pipelines/results/graywhale/transcriptome/ours/kidney/trimmed/GWkidneymother_S1_L001_R2_001_trimmed.fastq.gz

**Comment by rob-p** [comment]
Hi @antonkulaga,

  This is not a particularly useful error message (_sorry for that_), but this is a result of passing both un-paired (`-r`) and paired-end (`-1,-2`) reads to salmon together.  This is actually not supported, as the single-end and paired-end models are actually a bit different.  I will fix the error checking so that a useful message is printed out if these options are passed in together.  Can you let me know if the program runs correctly if you use just the paired-end reads?

**Comment by antonkulaga** [comment]
@rob-p I think I have only paired-end reads there, have not I?

**Comment by antonkulaga** [comment]
Ah, got it. I think I forgot accidently kept -r parameter, will try to re-run without it

**Comment by antonkulaga** [comment]
Sorry, it was my mistake, so I close this

**Comment by rob-p** [comment]
No worries! Glad this got resolved.

**Comment by oxpeter** [comment]
If this feature is not supported, is there a reason that Salmon is allowed to run through the entire quantification process before throwing the error? Wouldn't it be beneficial to check that the -r and -1 -2 flags are not all called simultaneously? You could always add an override flag if there is some use case for adding all together...

**Comment by oxpeter** [comment]
nm - I just re-read the above and realized @rob-p  already suggested just that. Sorry for being redundant! PS I am very grateful for the existence of Salmon. Thanks to all contributors!
