### ISSUE TITLE
NumThreads (Consumer Threads) should be reduced too?

### ISSUE THREAD

**Issue by k3yavi** [COMBINE-lab/salmon#178]
https://github.com/COMBINE-lab/salmon/blob/4baa73e27d8368b7dc92fb43b7c9a15b58efa917/src/SalmonQuantify.cpp#L1569

**Comment by k3yavi** [comment]
Too many typos, lack of sleep, I guess! but I think it's rather off by 2 for the paired parser, one for main thread and one/two for parsing thread.

**Comment by rob-p** [comment]
The parsing thread (only 1 by default) is alwys assumed. It is not possible to disable that thread, so it is always assumed to exist. However, outside of the mapping phase, it does no work. So, we ignore its existence elsewhere.
