### ISSUE TITLE
how can i get the index of human?

### ISSUE THREAD

**Issue by DawnEve** [COMBINE-lab/salmon#186]
how can i get the transcriptome of human? I can only find genome of human.

**Comment by rob-p** [comment]
Hi @DawnEve,

  One way is to grab the transcriptome directly from Gencode.  For example, you can get the human protein-coding transcriptome [here](ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.pc_transcripts.fa.gz), or the more comprehensive (though less confident) transcript sequences [here](ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.transcripts.fa.gz).  Alternatively, you can use the human genome and a GTF or GFF file that annotates the transcripts to extract those sequences that correspond to an annotated feature.  However, for well-annotated organisms like human and mouse, I find the first option easier.

Best,
Rob

**Comment by mdshw5** [comment]
I think @rob-p meant to include links in his reply. The download page is [here](https://www.gencodegenes.org/releases/current.html), and you're likely looking for this file:

ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.pc_transcripts.fa.gz

**Comment by rob-p** [comment]
@mdshw5 --- good call!  Thanks for chiming in.  I edited that response on my phone and seem to have failed to include the links :(.

**Comment by DawnEve** [comment]
Thanks for your reply. 
I think this info should be added and highlighted in the manual, if you want your tool to be used more often, as not many people like me don't have a comprehensive knowloge about where these resources can be obtained.

I wasted for almost a whole afternoon searching manual ,google,and stackoverflow, and turned to HTSeq at last. I will try this if I have time later.

**Comment by rob-p** [comment]
Hi @DawnEve,

  Thanks for your feedback, and I'm sorry this caused you such a headache.  You're right that it would be a good idea to link to the most common transcriptomes for model organisms (e.g. human and mouse) directly in the documentation.  I'll add this in the future.

Best,
Rob
