### ISSUE TITLE
conda installs v 0.8.2 (Mac)

### ISSUE THREAD

**Issue by jirazoqui** [COMBINE-lab/salmon#194]
Hi, I follow the instructions for conda - mediated installation, it installs v 0.8.2 not v 0.9.1

**Comment by rob-p** [comment]
This is really strange; the latest version for Mac should be 0.9.1 (see [here](https://anaconda.org/bioconda/salmon)).  Does anything change if you do a conda update/upgrade?

**Comment by jirazoqui** [comment]
That's what I thought... But no. Updating conda did not solve the problem

Best wishes,
Javier
(Sent from my iPhone)

On Feb 9, 2018, at 6:34 PM, Rob Patro <notifications@github.com<mailto:notifications@github.com>> wrote:


This is really strange; the latest version for Mac should be 0.9.1 (see here<https://anaconda.org/bioconda/salmon>). Does anything change if you do a conda update/upgrade?

**Comment by rob-p** [comment]
I'm happy to help however i can, but perhaps we should open a ticket over at bioconda? You can tag me there when you vreate it if you wish. One thought, what if you specify the version explicitly?

**Comment by pdellorusso** [comment]
same thing happened to me using the conda install

**Comment by rob-p** [comment]
I can't seem to reproduce this locally (OSX 10.13.1).  However, what happens if you try:

`> conda install salmon=0.9.1`

do you see this version as available?  Does it try to install it?

**Comment by jirazoqui** [comment]
Looks like I have some sort of conflict going on:

UnsatisfiableError: The following specifications were found to be in conflict:
  - libboost -> libcxx >=4.0.1 -> clangdev ==5.0.0 -> llvmdev ==5.0.0
  - libcxx 4.0.0* -> clangdev ==4.0.0 -> llvmdev ==4.0.0
Use "conda info <package>" to see the dependencies for each package.

[https://sites.google.com/site/ummslogos/_/rsrc/1489610858836/home/apple-icon-76x76.png]

Javier E. Irazoqui, PhD
Associate Professor
Department of Microbiology and Physiological Systems
UMass Medical School

368 Plantation Street
Albert Sherman Center
Room AS8.1053
Worcester, MA 01605

(774) 455-3797
Skype: javierirazoqui


Confidentiality Notice:
This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential, proprietary and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender immediately and destroy or permanently delete all copies of the original message.

On Feb 11, 2018, at 11:01 PM, Rob Patro <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't seem to reproduce this locally (OSX 10.13.1). However, what happens if you try:

> conda install salmon=0.9.1

do you see this version as available? Does it try to install it?

**Comment by pdellorusso** [comment]
Hey Rob, I wound up just installing it using the tar.gz and no issues

**Comment by rob-p** [comment]
Sure @pdellorusso, thanks for letting me know! I've raised the bioconda issue over on their issues page, so hopefully that's something they can fix without too much trouble.

**Comment by mbargull** [comment]
Hi @jirazoqui and @pdellorusso,
beware that if you install via a `.tar.gz` file, you make `conda` ignore *all* dependencies. It's somewhat equivalent to `conda install --no-deps ...` and thus I wouldn't recommend doing something like that.
Until we fix the dependencies in Bioconda, can you, if possible, use a separate Conda environment for `salmon` with `conda create -c bioconda -c conda-forge --name salmon salmon`. In this new environment you wouldn't have any dependency version conflict.

**Comment by jirazoqui** [comment]
good suggestion

[https://sites.google.com/site/ummslogos/_/rsrc/1489610858836/home/apple-icon-76x76.png]

Javier E. Irazoqui, PhD
Associate Professor
Department of Microbiology and Physiological Systems
UMass Medical School

368 Plantation Street
Albert Sherman Center
Room AS8.1053
Worcester, MA 01605

(774) 455-3797
Skype: javierirazoqui


Confidentiality Notice:
This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential, proprietary and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender immediately and destroy or permanently delete all copies of the original message.

On Feb 12, 2018, at 12:21 PM, Marcel Bargull <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jirazoqui<https://github.com/jirazoqui> and @pdellorusso<https://github.com/pdellorusso>,
beware that if you install via a .tar.gz file, you make conda ignore all dependencies. It's somewhat equivalent to conda install --no-deps ... and thus I wouldn't recommend doing something like that.
Until we fix the dependencies in Bioconda, can you, if possible, use a separate Conda environment for salmon with conda create -c bioconda -c conda-forge --name salmon salmon. In this new environment you wouldn't have any dependency version conflict.

**Comment by Maya0801** [comment]
Hi!
I installed version 0.8.2 (on linux) by using the command:
conda install -c bioconda salmon 

Is there an update on how to get the newer version?

Thanks!

**Comment by rob-p** [comment]
Hi Maya,

  You can try the solution posed over in issue #192. That should install the newer version via bioconda.  I'll also mention that version 0.10 should land sometime early this coming week, so keep an eye out for this update 

Best,
Rob

**Comment by Maya0801** [comment]
Thank you! it worked!
