### ISSUE TITLE
Index/versionInfo.json doesn't seem to exist

### ISSUE THREAD

**Issue by pdellorusso** [COMBINE-lab/salmon#197]
Hi,

I'm running into an issue with quant and hope you could help. Get this  error message saying my index/versionInfo.json does not seem to exist (screenshot attached). I have single end reads spread across 5 fastq files per sample. Just trying to run one sample as a test before looping it. 

I have tried building an index both with Salmon v 0.8.1 using a conda install as well as salmon v0.9.1 installing directly the binary on a linux computing cluster. 

I've attached a screenshot of the indexing process (it boots me out at the end but I cant tell from the outputs if it was cut short, last thing it notes is writing sequence data to the file). I've also attached a screenshot of the generated index folder contents. The index is the most recent Ensembl FASTA cDNA download for mouse. I tried indexing a transcripts FASTA file from Gencode as well and am running into the same issue, so dont think its the specific reference. The reference transcript files are 54 and 56mb respectively, so no issues downloading and transferring to our cluster. 

Any thoughts are much appreciated! Thanks!

Paul

![screen shot 2018-02-12 at 15 37 54](https://user-images.githubusercontent.com/23369975/36214991-d3b453ec-1178-11e8-8331-d641a334c47b.png)
![screen shot 2018-02-12 at 12 41 33](https://user-images.githubusercontent.com/23369975/36214993-d3bf729a-1178-11e8-9c78-38158e423b9b.png)
![screen shot 2018-02-12 at 15 33 53](https://user-images.githubusercontent.com/23369975/36214994-d3cb52cc-1178-11e8-9f74-6cfd554ccb0a.png)
![screen shot 2018-02-12 at 15 35 16](https://user-images.githubusercontent.com/23369975/36214995-d3d50376-1178-11e8-81c3-90de0a347763.png)

**Comment by raungar** [comment]
having the same issue ``` def do_salmon(paired,R1,R2):

	if not os.path.exists("output/hs.grch39.index"):
		print("building salmon index")
		os.system("salmon index -t output/Homo_sapiens.GRCh38.cdna.all.fa.gz -i output/hs.grch39.index")
	if not os.path.exists("output/quants"):
		os.mkdir("output/quants")
	print("salmon quanitification")
	if(paired=="False"):
		print("single end salmon")
		os.system(str("salmon quant -i output/hs.grch39.index -l A -r output/rna/"+R1+".fastq.gz -p 8 -o quants/"+R1))
	else:
		os.system(str("salmon quant -i output/hs.grch39.index -l A -1 output/rna/"+R1+".fastq.gz -2 output/rna/"+R2+".fastq.gz -p 8 -o quants/"+R1+"_"+R2))```
<img width="874" alt="screen shot 2019-02-25 at 1 32 56 pm" src="https://user-images.githubusercontent.com/18176863/53370193-efa79a80-3901-11e9-8e53-cc1e422efeef.png">

**Comment by rob-p** [comment]
Hi Rachel,

  So it looks like `output/hs.grch39.index/versionInfo.json` doesn't exist here?  Are there any other messages that show up during indexing?  Also, v0.8.1 is very outdated at this point.  It might be worth checking if this issue is still popping up if you grab the latest version (available both as a linux binary from the releases page, as well as via bioconda).

**Comment by raungar** [comment]
Hi Rob-

Might be worth noting that ``` conda install -c bioconda salmon ``` automatically installs v0.8.1 for me, but followed your previous suggestion to upgrade to v0.12.0 (https://github.com/COMBINE-lab/salmon/issues/192).

Even with this upgrade, I still have the same issue where versionInfo.json is not outputted at all 

<img width="1080" alt="screen shot 2019-02-25 at 2 19 55 pm" src="https://user-images.githubusercontent.com/18176863/53372728-7d868400-3908-11e9-9564-ced6045d5a88.png">
<img width="1197" alt="screen shot 2019-02-25 at 2 24 35 pm" src="https://user-images.githubusercontent.com/18176863/53372992-27fea700-3909-11e9-9210-18d6282fe630.png">
<img width="1240" alt="screen shot 2019-02-25 at 2 24 49 pm" src="https://user-images.githubusercontent.com/18176863/53372996-292fd400-3909-11e9-8c57-c8835cb3fa0d.png">

**Comment by rob-p** [comment]
Thanks for the quick reply.  Do you have a place you could share the contents of `outputs/hs.grch39.index`?  It seems to me that the index is clearly not being fully constructed, but it would be ideal to compare this with an index that I know is correct and look for specific differences.

Thanks,
Rob

**Comment by raungar** [comment]
Absolutely! And thank you for your quick responses! Just trying to make an index from Homo_sapiens.GRCh38.cdna.all.fa.gz (ftp://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz) to use for a ENCODE fastq file (test file is https://www.encodeproject.org/files/ENCFF163DLM/@@download/ENCFF163DLM.fastq.gz). I'm working from a cluster computer in a salmon environment with biopython as the only other thing installed 
<img width="750" alt="screen shot 2019-02-25 at 2 50 38 pm" src="https://user-images.githubusercontent.com/18176863/53374317-d1936780-390c-11e9-8370-51504ffb0996.png">


Index is here: https://drive.google.com/file/d/1iKD-qfJKIViePE7Uu_1Wsp8z71oGipjN/view?usp=sharing

**Comment by rob-p** [comment]
A follow up on this (with a lot of help from @raungar; thanks!) led to the conclusion that the problem was that insufficient memory was allocated to the cluster job during indexing (indexing this transcriptome takes ~4.3G).  Allocating more memory to the job resolves the issue.  The strange thing is that the cluster manager seemed to kill the job rather than refuse to allocate the memory (which would have resulted in a `bad_alloc` exception that would have made the problem clear).  So, if you're indexing with salmon on a cluster and see this behavior, be aware of the memory allocation and that the cluster software may surreptitiously kill the process rather than simply fail to allocate the memory!
