### ISSUE TITLE
Fragment length as an user input

### ISSUE THREAD

**Issue by Melkaz** [COMBINE-lab/salmon#2]
Could we please input the mean fragment length of the library when using single-end data ?

**Comment by rob-p** [comment]
Hi @Melkaz,
  These options have been added as of commit c207d0f28e5782f9a16747a72ac6f06c277fd4ed.  There are some new options, all of which have reasonable defaults (the ones that were hard coded before).  The relevant options here are: `--fldMean` which you can use to specify the expected mean length of the fragment distribution and `--fldSD` which you can use to specify the expected standard deviation of the fragment length distribution.  These values are used to set the *prior* on the fragment length distribution.  This means that if you're using paired-end reads, the observations will overwhelm this prior quickly and we'll learn the empirical distribution.  If you're using single-end data, then the prior won't really be updated and the values you specify above are what will be used in practice (e.g. to compute effective transcript lengths).  Please let us know if you run into any trouble using this new feature.

--Rob
