### ISSUE TITLE
Gencode Flag Not Recognized in Salmon v0.9.1 for OSX

### ISSUE THREAD

**Issue by pdellorusso** [COMBINE-lab/salmon#200]
I tried to run salmon v0.9.1 (for Mac OSX, downloaded from the conda page) using the '--gencode' flag and am getting an error that the option is unrecognized. I have SE reads

salmon quant -i ~/path/to/index/gencodemouse_index -l A --seqBias --gcBias --gencode \
	-r <(gunzip -c 19_S34_L004_R1_001.fastq.gz 19_S34_L005_R1_001.fastq.gz 19_S34_L006_R1_001.fastq.gz 19_S34_L007_R1_001.fastq.gz 19_S34_L008_R1_001.fastq.gz) \
	-o ~/output/directory/SalmonQuantsGencode/19_S34_Quants

Exception : [unrecognised option '--gencode']. Exiting.
Pauls-MacBook-Pro:fastq pdellorusso$ salmon -h
salmon(51580,0x7fffadd90340) malloc: *** malloc_zone_unregister() failed for 0x7fffadd81000
Salmon v0.9.1

**Comment by rob-p** [comment]
Hi @pdellorusso,

  This is because the `--gencode` flag is only relevant during indexing.  That is, you should pass the `--gencode` flag to Salmon when building the index, but not when subsequently performing quantification.

**Comment by pdellorusso** [comment]
Got it, thanks Rob!
