### ISSUE TITLE
Salmon error message: salmon quant was invoked improperly

### ISSUE THREAD

**Issue by grantcramer** [COMBINE-lab/salmon#209]
I used salmon 0.9.1 successfully a few weeks ago. I am using the latest update according to miniconda. Now after typing in this script in the command line in my Terminal on my Mac, I get the following error message. I have tried to trouble shoot but I have not been able to solve the problem. 

salmon quant -i cs_index -l A -r fastqtrimd/BOD19_5R1trimd.fastq.gz -o quant/BOD19_5R1_quant —seqBias --gcBias --writeUnmappedNames

Here is the error message in the command line:

Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
### [ writeUnmappedNames ] => { }
Logs will be written to BOD19_5R1_quant/logs
[2018-03-19 12:13:21.295] [jointLog] [info] parsing read library format
[2018-03-19 12:13:21.295] [jointLog] [info] There is 1 library.
[2018-03-19 12:13:21.402] [jointLog] [info] Loading Quasi index
[2018-03-19 12:13:21.403] [jointLog] [info] Loading 32-bit quasi index
Exception : [Failed to read 8 bytes from input stream! Read 0]
salmon quant was invoked improperly.
For usage information, try salmon quant --help
Exiting.
[2018-03-19 12:13:21.403] [stderrLog] [info] Loading Suffix Array 

Does anyone have any ideas what is wrong? Sorry I am a novice!

**Comment by rob-p** [comment]
Hi @grantcramer,

  Is this the same index you used before?  Were there any issues with indexing?  Could you provide a link to the transcriptome you are mapping against?  We could see if we can reproduce the error on our end.

--Rob

**Comment by grantcramer** [comment]
Hi Rob,

Yes, this was the same index I used before. There were no issues when I built the index before. In fact everything went very smoothly. Super easy!
I am using a different computer (laptop) instead of my office computer.

Here is a link to my index that I built:
https://nevada.box.com/s/b7wx8rnwae4dzak6m04u0lgxalv1kxh6

Here is a link to the transcriptome that was used in the build: Sorry my NevadaBox is very slow copying many files so I have copied the transcriptome again to the following Dropbox folder:

https://www.dropbox.com/s/3ux7lz84qrx5ybd/CS_clean.primary.corrected_loci.CDS.fasta?dl=0

Thanks for your help!

Grant




Grant R. Cramer
Professor
Department of Biochemistry and Molecular Biology, Howard Building Room 205, Mail Stop 330
University of Nevada, Reno
Reno, NV 89557
(775) 784-4204
cramer@unr.edu<mailto:cramer@unr.edu>
http://www.ag.unr.edu/cramer/

On Mar 19, 2018, at 1:43 PM, Rob Patro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @grantcramer<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrantcramer&data=01%7C01%7Ccramer%40unr.edu%7Cfa8af76ea22140f38e4008d58dda106b%7C523b4bfc0ebd4c03b2b96f6a17fd31d8%7C1&sdata=Rv5JuLm0kNlPPfQOshcc%2FUGmEC2g%2B0wIXVmdmIXnbCk%3D&reserved=0>,

Is this the same index you used before? Were there any issues with indexing? Could you provide a link to the transcriptome you are mapping against? We could see if we can reproduce the error on our end.

--Rob

**Comment by rob-p** [comment]
Hi @grantcramer,

  I was able to successfully index and map against the fasta file you link above (on linux).  I was also able to index and map against the index on OSX, using the salmon from bioconda (v 0.9.1).  So, I'm not _yet_ able to reproduce this.  It seems the file you uploaded for your pre-built index is no longer available, so I couldn't try that out.  I'd be happy to give it a try if you can put it up on dropbox or some such.  Otherwise, I wonder if there could be some sort of binary compatibility issue.  Did you build the index on the same machine you're quantifying on?  The OSX I tested on is 10.13.1.

Best,
Rob

**Comment by grantcramer** [comment]
Hi Rob,
Thanks for your help and advice. No, I built the index on my office machine. I will return home this weekend to give salmon a try on my office computer. In the meantime, I will try rebuilding the index on my laptop to see if that makes things work. I will get back to you when I have some answers just to let you know what happened.
All the best,
Grant

Grant R. Cramer
Professor
Department of Biochemistry and Molecular Biology, Howard Building Room 205, Mail Stop 330
University of Nevada, Reno
Reno, NV 89557
(775) 784-4204
cramer@unr.edu<mailto:cramer@unr.edu>
http://www.ag.unr.edu/cramer/

On Mar 22, 2018, at 6:21 PM, Rob Patro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @grantcramer<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrantcramer&data=01%7C01%7Ccramer%40unr.edu%7C54d34feceb114e30a61b08d5905c7a7b%7C523b4bfc0ebd4c03b2b96f6a17fd31d8%7C1&sdata=w1ED%2B5ZBUY6Z8fTiIs62IZJizv0HcvVzw8CtfEdK32E%3D&reserved=0>,

I was able to successfully index and map against the fasta file you link above (on linux). I was also able to index and map against the index on OSX, using the salmon from bioconda (v 0.9.1). So, I'm not yet able to reproduce this. It seems the file you uploaded for your pre-built index is no longer available, so I couldn't try that out. I'd be happy to give it a try if you can put it up on dropbox or some such. Otherwise, I wonder if there could be some sort of binary compatibility issue. Did you build the index on the same machine you're quantifying on? The OSX I tested on is 10.13.1.

Best,
Rob

**Comment by grantcramer** [comment]
Hi Rob,
That seemed to be the problem. I rebuilt the index on my laptop and salmon worked perfectly on my laptop!
Thanks,
Grant


On Mar 22, 2018, at 6:21 PM, Rob Patro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @grantcramer<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrantcramer&data=01%7C01%7Ccramer%40unr.edu%7C54d34feceb114e30a61b08d5905c7a7b%7C523b4bfc0ebd4c03b2b96f6a17fd31d8%7C1&sdata=w1ED%2B5ZBUY6Z8fTiIs62IZJizv0HcvVzw8CtfEdK32E%3D&reserved=0>,

I was able to successfully index and map against the fasta file you link above (on linux). I was also able to index and map against the index on OSX, using the salmon from bioconda (v 0.9.1). So, I'm not yet able to reproduce this. It seems the file you uploaded for your pre-built index is no longer available, so I couldn't try that out. I'd be happy to give it a try if you can put it up on dropbox or some such. Otherwise, I wonder if there could be some sort of binary compatibility issue. Did you build the index on the same machine you're quantifying on? The OSX I tested on is 10.13.1.

Best,
Rob

**Comment by rob-p** [comment]
Great!  I'm glad this resolved the issue.  I'll try and add something to the FAQ about potential binary compatibility issues.
