### ISSUE TITLE
Salmon crashes with 'terminate called recursively std::length_error'

### ISSUE THREAD

**Issue by alexg9010** [COMBINE-lab/salmon#210]
Hi,

I am using salmon quant v0.91 to map some reads against ce11 genome. 

But the run fails with a cryptic error message, maybe you can help me sort this out.
```
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
### salmon (mapping-based) v0.9.1
### [ program ] => salmon
### [ command ] => quant
### [ index ] => { /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/salmon_index }
### [ libType ] => { A }
### [ threads ] => { 8 }
### [ mates1 ] => { /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/trimmed_reads/rluc_2_R1.fastq.gz }
### [ mates2 ] => { /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/trimmed_reads/rluc_2_R2.fastq.gz }
### [ output ] => { /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/salmon_output/rluc_2 }
### [ seqBias ] => { }
### [ gcBias ] => { }
### [ geneMap ] => { /data/akalin/Base/Annotation/ce11/ENSEMBL91/Caenorhabditis_elegans.WBcel235.91.gtf }
Logs will be written to /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/salmon_output/rluc_2/logs
[2018-03-21 10:00:03.272] [jointLog] [info] parsing read library format
[2018-03-21 10:00:03.272] [jointLog] [info] There is 1 library.
[2018-03-21 10:00:03.517] [stderrLog] [info] Loading Suffix Array
[2018-03-21 10:00:03.501] [jointLog] [info] Loading Quasi index
[2018-03-21 10:00:03.506] [jointLog] [info] Loading 32-bit quasi index
[2018-03-21 10:00:03.846] [stderrLog] [info] Loading Transcript Info
[2018-03-21 10:00:03.980] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-03-21 10:00:03.995] [stderrLog] [info] There were 35448 set bits in the bit array
[2018-03-21 10:00:04.001] [stderrLog] [info] Computing transcript lengths
[2018-03-21 10:00:04.001] [stderrLog] [info] Waiting to finish loading hash
[2018-03-21 10:00:40.560] [stderrLog] [info] Done loading index
[2018-03-21 10:00:40.560] [jointLog] [info] done
[2018-03-21 10:00:40.560] [jointLog] [info] Index contained 35448 targets




terminate called after throwing an instance of 'terminate called recursively
std::length_error'
```

Best,
Alex

**Comment by rob-p** [comment]
Hi @alexg9010,

  This is absolutely a cryptic error message.  I'm *guessing* it may have something to do with the de-serialization of the index.  Would you be able to provide the file on which you build the index?  I can see if I can reproduce this error locally.

Best,
Rob

**Comment by alexg9010** [comment]
Hi Rob,

The file that I am building the index on is a cdna.all fasta file from Ensembl, 
exactly this one here : ftp://ftp.ensembl.org/pub/release-91/fasta/caenorhabditis_elegans/cdna/Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz . 

It was unzipped and then used with `salmon index`. 
This is the log of the indexing process:
```
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
[2018-03-20 17:41:44.417] [jLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
[2018-03-20 17:41:48.639] [jointLog] [warning] Entry with header [W03F8.6d], had length less than the k-mer length of 31 (perhaps after poly-A clipping)
Elapsed time: 4.82575s

[2018-03-20 17:41:49.262] [jointLog] [warning] Removed 414 transcripts that were sequence duplicates of indexed transcripts.
[2018-03-20 17:41:49.263] [jointLog] [warning] If you wish to retain duplicate transcripts, please use the `--keepDuplicates` flag
Replaced 0 non-ATCG nucleotides
Clipped poly-A tails from 20 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 0.0570225s
Writing sequence data to file . . . done
Elapsed time: 0.286971s
[info] Building 32-bit suffix array (length of generalized text is 56718041)
Building suffix array . . . success
saving to disk . . . done
Elapsed time: 0.959095s
done
Elapsed time: 8.1189s
^M^Mprocessed 0 positions^M^Mprocessed 1000000 positions^M^Mprocessed 2000000 positions^M^Mprocessed 3000000 positions^M^Mprocessed 4000000 positions^M^Mprocessed 5000000 positions^M^Mprocessed 6000000 positions^M^Mprocessed 7000000 positions^M^Mprocessed 8000000 positions^M^Mprocessed 9000000 positions^M^Mprocessed 10000000 positions^M^Mprocessed 11000000 positions^M^Mprocessed 12000000 positions^M^Mprocessed 13000000 positions^M^Mprocessed 14000000 positions^M^Mprocessed 15000000 positions^M^Mprocessed 16000000 positions^M^Mprocessed 17000000 positions^M^Mprocessed 18000000 positions^M^Mprocessed 19000000 positions^M^Mprocessed 20000000 positions^M^Mprocessed 21000000 positions^M^Mprocessed 22000000 positions^M^Mprocessed 23000000 positions^M^Mprocessed 24000000 positions^M^Mprocessed 25000000 positions^M^Mprocessed 26000000 positions^M^Mprocessed 27000000 positions^M^Mprocessed 28000000 positions^M^Mprocessed 29000000 positions^M^Mprocessed 30000000 positions^M^Mprocessed 31000000 positions^M^Mprocessed 32000000 positions^M^Mprocessed 33000000 positions^M^Mprocessed 34000000 positions^M^Mprocessed 35000000 positions^M^Mprocessed 36000000 positions^M^Mprocessed 37000000 positions^M^Mprocessed 38000000 positions^M^Mprocessed 39000000 positions^M^Mprocessed 40000000 positions^M^Mprocessed 41000000 positions^M^Mprocessed 42000000 positions^M^Mprocessed 43000000 positions^M^Mprocessed 44000000 positions^M^Mprocessed 45000000 positions^M^Mprocessed 46000000 positions^M^Mprocessed 47000000 positions^M^Mprocessed 48000000 positions^M^Mprocessed 49000000 positions^M^Mprocessed 50000000 positions^M^Mprocessed 51000000 positions^M^Mprocessed 52000000 positions^M^Mprocessed 53000000 positions^M^Mprocessed 54000000 positions^M^Mprocessed 55000000 positions^M^Mprocessed 56000000 positions
khash had 29386942 keys
saving hash to disk . . . done
Elapsed time: 75.4197s
[2018-03-20 17:43:53.055] [jLog] [info] done building index
```

**Comment by rob-p** [comment]
Hi @alexg9010,

  Thanks for the info.  I grabbed this transcriptome and indexed it, and then I grabbed the gtf file and executed this `quant` command with the same parameters (except, of course, for the read set).  Unfortunately, I was unable to trigger the same behavior.  On my machine (Ubuntu 16.10 x86-64) the index loaded successfully and quantification completed.  Can you provide some more details about the system on which you are running?  Would you be able to share the actual index file that you created?  In relation to [issue 209](https://github.com/COMBINE-lab/salmon/issues/209), is the index being used on the same machine where it was created (from what you've posted, however, I believe it is)?

Thanks,
Rob

**Comment by alexg9010** [comment]
Hi @rob-p 

I am running salmon in cluster environment, so it is possible that the index was actually created on a different node than it was used on. 

Here is the link to the all files that the indexing produced: https://www.dropbox.com/sh/gd42go2j9nzjd5h/AAAzlJ04p3Ll6hlyxpXSPe9pa?dl=0

So for now the easiest solution would be to run the indexing and quantification on the same node, or not on cluster at all?

Best,
Alex

**Comment by mdshw5** [comment]
It's possible that `Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz` was corrupted during your FTP download, since there's no error correction aside from TCP checksums. You might want to check your file just to make sure:

```shell
$ md5 Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz 
MD5 (Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz) = 3979cd3a2d5fe408b6261ae5b1d0c4de
```

**Comment by alexg9010** [comment]
@mdshw5 I checked the md5sum of the file that I was using before and it had a different value, so I downloaded again, this time the md5sum matched.
```
$ md5sum Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz
3979cd3a2d5fe408b6261ae5b1d0c4de  Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz
```
I rerun the indexing and quantification, but still get exactly the same error. 

Next I am running it locally (not the cluster) to check wether this solves the issue.

**Comment by alexg9010** [comment]
Hi @rob-p , @mdshw5 , 

I did a local run, it crashed again, but now at least with some more information and a core dump. 
So the process failed with this error:
```
/bin/bash: line 1: 31345 Aborted                 (core dumped) /home/agosdsc/pigx/pigx_rnaseq/.guix-profile/bin/salmon quant -i /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/salmon_index -l A -p 8 -1 /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/trimmed_reads/N2_1_R1.fastq.gz -2 /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/trimmed_reads/N2_1_R2.fastq.gz -o /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/salmon_output/N2_1 --seqBias --gcBias -g /data/akalin/Base/Annotation/ce11/ENSEMBL91/Caenorhabditis_elegans.WBcel235.91.gtf >> /scratch/AG_Akalin/agosdsc/projects/mrg1_rnaseq/analysis_v2/logs/salmon_quant_N2_1.log 2>&1
```
I uploaded the files and the dump, such that you can try to debug this: 
https://1drv.ms/f/s!AqRdeUKlw8lFjDV7eDqqQbN7cQPa

**Comment by rob-p** [comment]
Hi @alexg9010,

  This is great; thanks for providing all of the output details.  I just did quantification on your specific reads (and I tried it using the latest Salmon from bioconda on my Mac, so it was different from the environment I used before).  Again, I was able to quantify successfully.  However, I see that your files contain a core dump which should let me at least find out where the error is popping up in your run.  Could you provide system details so I know how I should be analyzing the core file (specifically, is this run on OSX or Linux?  Was this a pre-compiled binary or did you compile it?  Was it compiled with gcc or clang (and which version)?).  Thanks again for your help in trying to reproduce this.

**Comment by alexg9010** [comment]
Hi @rob-p,

The system that I am running on is CentOS Linux release 7.4.1708, salmon was compiled locally with gcc and the version of gcc that I am using is 5.4.0. 
I hope that this helps you do find the reason for the crash.

**Comment by alexg9010** [comment]
Hi @rob-p,

Do you have any update on this yet?

Best,
Alex

**Comment by rob-p** [comment]
Hi @alexg9010 ,

  A apologize profusely for dropping the ball on this.  Would it be possible to test with the latest release of salmon?  I am still not able to reproduce this behavior on any of our test machines.

**Comment by alexg9010** [comment]
Hi @rob-p,

Actually I have to apologize, because about one month ago I got it running, after using an updated version of our guix installation (hpc package manager). I still do not know what actually caused that issue, but it seems to be fixed now. 
So sorry for bothering you so long and thanks for digging into this!

**Comment by rob-p** [comment]
No worries @alexg9010, thanks for letting me know and glad you got it working!
