### ISSUE TITLE
 Library not loaded: @rpath/libtbbmalloc_proxy.dylib

### ISSUE THREAD

**Issue by Rfriedmancolumbia** [COMBINE-lab/salmon#215]
./salmon index -t Mus_musculus.GRCm38.cdna.all.norm.fasta -i GRCm38.cdna.all_index --type quasi -l 31

Dear Salmon list,

I am using the Salmon 0.8.1 binary for Mac OS X, Sierra, 10.12.8. I am trying to set up an mm10
mouse index. I downlaod the mouse cDNAs from Ensembl, and normlized the ends with galaxy.
I am running evelything in lib in case there are path issues.
Here is my directory:

c2b2afmd2:lib friedman$ ls
Mus_musculus.GRCm38.cdna.all.fa	libtbbmalloc_proxy.dylib
libtbb.dylib			salmon
libtbbmalloc.dylib

Here is my attemot to build an index:

c2b2afmd2:lib friedman$ ./salmon index -t Mus_musculus.GRCm38.cdna.all.norm.fasta -i GRCm38.cdna.all_index --type quasi -l 31
dyld: Library not loaded: @rpath/libtbbmalloc_proxy.dylib
  Referenced from: /Applications/Salmon-0.8.2_macOX_10.12/lib/./salmon
  Reason: image not found
Abort trap: 6

I would greatly appreciate any help that you might be able ot give.

Thanks and best wishes,
Rich
Richard A. Friedman, PhD
Associate Research Scientist,
Biomedical Informatics Shared Resource
Herbert Irving Comprehensive Cancer Center (HICCC)
Lecturer,
Department of Biomedical Informatics (DBMI)
Room 825
Irving Cancer Research Center     
Columbia University Herbert and Florence Irving Medical Center
1130 St. Nicholas Ave
New York, NY 10032
(212)851-4765 (voice)
raf4@cumc.columbia.edu

http://www.columbia.edu/~raf4/index.html

“Will there still be "Classics Illustrated” by the time I have children? I cannot
imagine raising kids without "Classics Illustrated” .” -Rose Friedman, age 20

**Comment by rob-p** [comment]
Hi Rich,

  The issue with pre-compiled OSX binaries is that they are difficult to make portable across OSX versions.  This is why we strongly suggest installing Salmon (especially for OSX) through [Bioconda](https://bioconda.github.io/).  This greatly eases installation and updating, and doesn't require admin privileges. On OSX, you can try the following:

```
$ conda config --add channels conda-forge
$ conda config --add channels bioconda
$ conda create -n salmon salmon=0.9.1
 ```

This should take care of all relevant dependencies as well as e.g. library locations and placement.  Could you please give this a try and let me know if it works for you?

Best,
Rob

**Comment by Rfriedmancolumbia** [comment]
Rob,
Rob,

Thank you. It worked. I was able to make my index without error messages.

Best wishes,
Rich

**Comment by rob-p** [comment]
Great; glad to hear it worked!

Best,
Rob
