### ISSUE TITLE
Installing Salmon

### ISSUE THREAD

**Issue by caggtaagtat** [COMBINE-lab/salmon#216]
Hi, I'm just starting with RNA-Seq and tryed to install salmon on the HPC of my university. However I get following error message when recompiling with "$ make". 

```
[  6%] Built target libbz2
[ 13%] Built target libgff
[ 19%] Built target libbwa
[ 26%] Built target libjellyfish
[ 27%] Performing build step for 'libstadenio'
Making all in io_lib
Making all in progs
libtool: link: /usr/bin/cc -o convert_trace convert_trace.o  ../io_lib/.libs/libstaden-read.a -lz -lm -lpthread -llzma -lbz2
/usr/bin/ld: cannot find -lbz2
../io_lib/.libs/libstaden-read.a(libstaden_read_la-open_trace_file.o): In function `find_file_url':
open_trace_file.c:(.text+0xd26): warning: the use of `tempnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
make[5]: *** [convert_trace] Fehler 1
make[4]: *** [all-recursive] Fehler 1
make[3]: *** [all] Fehler 2
make[2]: *** [libstadenio-prefix/src/libstadenio-stamp/libstadenio-build] Fehler 2
make[1]: *** [CMakeFiles/libstadenio.dir/all] Fehler 2
make: *** [all] Fehler 2

```

Does this have anything to do with "bzip2" or "libbz2" and how would I provide missing paths to cmake?
I have bzip2 but not libbz2 availible on my system.

I would be gratefull for any help.

**Comment by roryk** [comment]
Heya, there are precompiled binaries available which might be easier to install. https://github.com/COMBINE-lab/salmon/releases/download/v0.9.1/Salmon-0.9.1_linux_x86_64.tar.gz is a link to them. Another option would be to use bioconda:

https://bioconda.github.io/

which is awesome if you are just starting out doing RNA-seq, since you won't have to spend time trying to get all of the tools to compile.

**Comment by caggtaagtat** [comment]
Thank you so much for your fast response! I was overwhelmed with the difficulties during compilation on my cluster with restricted rights.

So i would use salmon than like this for single end reads from reverse stranded data of three samples after unpacking the precompiled file?:

/path_to_salmin/bin/salmon quant -i transcripts_index -l SR -r reads_a.fq reads_b.fq reads_c.fq -o transcripts_quant
