### ISSUE TITLE
Error while loading shared libraries: libtbbmalloc_proxy.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Nazeeefa** [COMBINE-lab/salmon#219]
Command used:

> path/to/salmon quant -t fasta_file -l A -a bam_file -o output_dir

any idea how to solve this issue? sorry if it has already been discussed, can't seem to find any information on it except for other tools - [example](https://github.com/ndaniel/fusioncatcher/issues/40)

**Comment by rob-p** [comment]
Hi @nazeeefa,

  In this case, you need to make sure the relevant path is in your library path.  Try the following:

```
LD_LIBRARY_PATH=path/to/salmondir/lib:$LD_LIBRARY_PATH path/to/salmon quant -t fasta_file -l A -a bam_file -o output_dir
```

If that works you can make the change to the library path automatic at login by putting 

```
ecport LD_LIBRARY_PATH=path/to/salmondir/lib:$LD_LIBRARY_PATH 
```
In your `.bashrc` file and then opening a new terminal (assuming you are using a bash compatible shell).

Best,
Rob

**Comment by Nazeeefa** [comment]
Hi Rob, this has already been done.

**Comment by rob-p** [comment]
Hi Nazeeefa,

  Is the relevant file `libtbbmalloc_proxy.so.2` actually present in that directory?  What are the contents of `path/to/salmondir/lib`?  If you are in an environment with bioconda, you can also try installing tbb through that system as well to ensure you have the shared library.  Unfortunately, TBB is pretty much the one library that is not possible to link statically.

  Also, which shell are you using?  The syntax for exporting an environment variable is different in different shells.

**Comment by Nazeeefa** [comment]
Hi Rob,

TBB was already installed. It's the path to TBB files was missing in .bashrc, it seems to work fine now! I am using bash. Cheers!

**Comment by rob-p** [comment]
Hi Nazeeefa,

  Great; glad to hear it's working now.  Sorry about the hiccup!

Best,
Rob

**Comment by moukail** [comment]
try this command:
# ldconfig
