### ISSUE TITLE
Exception : [ERROR: Failed to open file filename.bam, exiting!

### ISSUE THREAD

**Issue by mentat25** [COMBINE-lab/salmon#222]
Hello,

Hoping you can help troubleshoot a salmon quant failure. We're running V0.9.1. BAM files are transcriptome aligned using OSA aligner. The program is calling out a malformed key:pair? The salmon_quant.log is blank.

> ./bin/salmon quant -t transcripts.fa -l A -a A549_S1_001.bam -o A549_S1_quant &
[1] 10291
us1salxngst01> Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
# salmon (alignment-based) v0.9.1
# [ program ] => salmon
# [ command ] => quant
# [ targets ] => { transcripts.fa }
# [ libType ] => { A }
# [ alignments ] => { A549_S1_001.bam }
# [ output ] => { A549_S1_quant }
Logs will be written to A549_S1_quant/logs
Malformed key:value pair at line 44017: "@PG    ID:OSA  IsCdna:True 
ReferenceLibraryID:Human.B37.3_RefGene20121217  VN:7.2"
============
Exception : [ERROR: Failed to open file A549_S1.bam, exiting!]
============
./bin/salmon alignment-quant was invoked improperly.
For usage information, try ./bin/salmon quant --help-alignments
Exiting.

**Comment by mdshw5** [comment]
It looks like your @PG header line is malformed because the @PG record identifier should be capitalized. 

`@pg ID:OSA IsCdna:True ReferenceLibraryID:Human.B37.3_RefGene20121217 VN:7.2`

would become:

`@PG ID:OSA IsCdna:True ReferenceLibraryID:Human.B37.3_RefGene20121217 VN:7.2`

You can fix this by running:

```shell
$ samtools view -H A549_S1.bam > header
$ sed -i "s/@pg/@PG/" header
$ samtools reheader header A549_S1.bam
```

**Comment by mdshw5** [comment]
I meant to point you to page 3/4 of the SAM specification for context: https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf

**Comment by mentat25** [comment]
Thanks Matt for the response and fix, unfortunately the error persists;
Might need to re-align using a different pipeline?

> Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
# salmon (alignment-based) v0.9.1
# [ program ] => salmon
# [ command ] => quant
# [ targets ] => { transcripts.fa }
# [ libType ] => { A }
# [ alignments ] => { A549_S1_001.bam }
# [ output ] => { A549_S1_quant }
Logs will be written to A549_S1_quant/logs
Malformed key:value pair at line 44017: "@PG    ID:OSA  IsCdna:True     ReferenceLibraryID:Human.B37.3_RefGene20121217  VN:7.2"
============
Exception : [ERROR: Failed to open file A549_S1_001.bam, exiting!]
============
./bin/salmon alignment-quant was invoked improperly.
For usage information, try ./bin/salmon quant --help-alignments
Exiting.

**Comment by mentat25** [comment]
Sorry,

> Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
# salmon (alignment-based) v0.9.1
# [ program ] => salmon
# [ command ] => quant
# [ targets ] => { transcripts.fa }
# [ libType ] => { A }
# [ alignments ] => { A549_S1_001.bam }
# [ output ] => { A549_S1_quant }
Logs will be written to A549_S1_quant/logs
Malformed key:value pair at line 44017: "@PG    ID:OSA  IsCdna:True     ReferenceLibraryID:Human.B37.3_RefGene20121217  VN:7.2"
============
Exception : [ERROR: Failed to open file A549_S1_001.bam, exiting!]
============
./bin/salmon alignment-quant was invoked improperly.
For usage information, try ./bin/salmon quant --help-alignments
Exiting.

**Comment by mentat25** [comment]
hmmmm I re-pasted the updated error twice but it still reverts back to original post?

Malformed key:value pair at line 44017: "**@PG**    ID:OSA  IsCdna:True     ReferenceLibraryID:Human.B37.3_RefGene20121217  VN:7.2"

**Comment by mentat25** [comment]
Strange the updated error message has @PG not @pg

**Comment by mentat25** [comment]
"@PG"

**Comment by mentat25** [comment]
OK why does this page auto correct @PG (capital P) to @pg (lower case p)

**Comment by mentat25** [comment]
PG

**Comment by mentat25** [comment]
ok its the asperand (“At” sign) sorry

**Comment by mdshw5** [comment]
Ah. Yeah, it's @github autocorrecting the text to an existing username. :/
