### ISSUE TITLE
Tell to cmake the different places for the dependencies

### ISSUE THREAD

**Issue by euduca** [COMBINE-lab/salmon#225]
The jellyfish is installed in a non standard place.

How to tell cmake where jellyfish is installed?

I tried the "-DJELLYFISH_ROOT" parameter but  it didn't work.

My best regards.

**Comment by rob-p** [comment]
Hi @euduca,

  This is a good idea.  Currently, there is no easy way to do this apart from hacking the CMake file.  If salmon doesnt find jellyfish in a standard location, it just ferches its own copy.  Fortunately, in the newest release (scheduled to drop this coming week), we've dropped the dependency on libjellyfish.

Best,
Rob

**Comment by rob-p** [comment]
Hi Duca,

  In that case, i might suggest grabbing the precompiled linux executables.  They should be widely compatible across many linux distros since they are built on an ancient CentOS version.

Best,
Rob

**Comment by euduca** [comment]
Ok!

I will do  that!

Best,
Duca.
