### ISSUE TITLE
"Bus error: 10" or "Segmentation fault: 11" with version 0.10 and --validateMappings

### ISSUE THREAD

**Issue by knokknok** [COMBINE-lab/salmon#228]
Compiled from source (https://github.com/COMBINE-lab/salmon/archive/v0.10.0.tar.gz) on OS X 10.13.4 (Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64)

The error generally occurs in the first 2000000 fragments (tried with paired-end samples, either IU or ISR)

\#\#\# salmon (mapping-based) v0.10.0
\#\#\# [ program ] => salmon
\#\#\# [ command ] => quant
\#\#\# [ index ] => { salmon010.index }
\#\#\# [ libType ] => { A }
\#\#\# [ mates1 ] => { L001_R1.fastq.gz }
\#\#\# [ mates2 ] => { L001_R2.fastq.gz }
\#\#\# [ validateMappings ] => { }

**Comment by rob-p** [comment]
Hi @knokknok ,

  Thanks for reporting this (and for testing out 0.10.0 so quickly)!  Is this read set & reference txome available to try and reproduce this?  Also, would it be possible to check if this occurs using the bioconda-packaged release?

--Rob

**Comment by knokknok** [comment]
> Is this read set & reference txome available to try and reproduce this?

Unfortunately no, it's a generated fasta file (it used to work with 0.9.1 without "validateMappings" though)

[info] Building 32-bit suffix array (length of generalized text is 462349554)
processed 462000000 positions
khash had 208056876 keys

> Also, would it be possible to check if this occurs using the bioconda-packaged release?

Still a seg fault but I now have the following message:
WARNING: Could not associate known library type with read!
WARNING: PE compatibility function called with SE read!
expected: Library format { type:paired end, relative orientation:inward, strandedness:unstranded }, observed: Library format { type:, relative orientation:, strandedness: }
Segmentation fault: 11

**Comment by rob-p** [comment]
Hi @knokknok,

  Would it be possible to share a small subset of these reads that reproduce the issue?  Basic thoughts : does it work without `--validateMappings`?  Are the read files synchronized (i.e. are there the same number of left and right reads)?

**Comment by rob-p** [comment]
Sure --- we'll just leave the issue open and when you have a chance we can dig in further.  Once I can reproduce the issue, I can dig down to see the underlying cause.

**Comment by knokknok** [comment]
I have tried to dichotomise my transcript db. The 2nd transcript in the attached file, crashes with the 2x12 paired-end fastq I have tried (ISR or IU).

index was generated with:
salmon index -t test.fa --gencode -k 31 -i index

quantification with:
salmon quant -i index -l A -1 /tmp/r1.fastq.gz -2 /tmp/r2.fastq.gz --validateMappings -o test

**Comment by knokknok** [comment]
Forgot the file...
[test.fa.gz](https://github.com/COMBINE-lab/salmon/files/2057739/test.fa.gz)

**Comment by knokknok** [comment]
However, I don't seem to have the problem on linux (4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)...

**Comment by rob-p** [comment]
Hi @knokknok ,

  Thanks for sharing the data that reproduces this; interesting if it's OSX specific!  I'll try and reproduce and dig into this today --- but I have to upgrade my minor version of OSX first.

**Comment by rob-p** [comment]
Hi @knokknok ,

  Also, will any set of reads reproduce this issue for you, or can you share a small subset of reads that trigger the issue for you on OSX?  Thanks!

**Comment by knokknok** [comment]
The attached files should crash
[r1.fastq.gz](https://github.com/COMBINE-lab/salmon/files/2058569/r1.fastq.gz)
[r2.fastq.gz](https://github.com/COMBINE-lab/salmon/files/2058570/r2.fastq.gz)

**Comment by rob-p** [comment]
Thanks; I'll let you know what I find!

**Comment by rob-p** [comment]
Ok, this bug should now be fixed on the `develop` branch (it was a bug upstream in rapmap where I used <= instead of < in a std::sort comparison --- though I'm not sure why it only broke on OSX).

**Comment by rob-p** [comment]
I will close this once I'm able to apply the patch for your other issue.  At that point, I will bump everything to 0.10.1 and cut a new release.

**Comment by knokknok** [comment]
Thanks!
Did you push to GitHub? I don't see it...

**Comment by rob-p** [comment]
The bug was actually in RapMap, which is automatically fetched from that GitHub repo during the build.  [This](https://github.com/COMBINE-lab/RapMap/commit/7f0aa53e815b98b7d0d2e6e1927e0558b9d25975) is the commit that fixes the bug.  So, if you checkout salmon from the develop branch and do a clean build (i.e. removing the build folder) then you should have the fix.

**Comment by knokknok** [comment]
Thanks!
