### ISSUE TITLE
JSON Parsing failed - provided NVP (SeqHash) not found when loading index... older version of RapMap

### ISSUE THREAD

**Issue by rbenel** [COMBINE-lab/salmon#232]
Hi, 
I just downloaded the salmon.10.0 version and indexed my transcriptome using the https://www.gencodegenes.org/releases/current.html --> FASTA files --> trasnscript sequences. When I try to run Salmon I receive the above error message. The last time I ran Salmon I used 9.1 and this trasncriptome from ensembl ftp://ftp.ensembl.org/pub/release-92/fasta/homo_sapiens/cdna/...
What is going on here? 

The header.json file looks like this: 
{
    "value0": {
        "IndexType": 1,
        "IndexVersion": "q3",
        "UsesKmers": true,
        "KmerLen": 31,
        "BigSA": false,
        "PerfectHash": false
    }
}

**Comment by rob-p** [comment]
Interesting.  One thing that changed is that we finally upgraded the Docker image used in our continuous integration server from CentOS5 to CentOS6; I wonder if that might cause some portability issues.  Could you try installing via Bioconda to see if that executable gives you the same trouble?

**Comment by rbenel** [comment]
OK, I will try. Do I need to do anything to the binary before installing salmon via bioconda.

**Comment by rob-p** [comment]
Nope; nothing special.  Once you've installed conda, you simply do:

```
$ conda config --add channels conda-forge
$ conda config --add channels bioconda
$ conda create -n salmon salmon=0.10.1
```

then it will give you instructions on how to activate the environment to run salmon.

**Comment by rbenel** [comment]
OK. I successfully installed conda and entered the salmon env and then created the index (I hope correctly, as I am new to the conda env), but now I want to run my samples on our cluster at the university where I do now have permissions to install from source, and therefore the binary version of salmon is installed there. Will there be an incompatibility problem, if I indexed the trasncriptome on my local computer and run salmon using the binary?

**Comment by rob-p** [comment]
Hi @rbenel ,

  As long as you are running on a machine with (1) the same binary layout (i.e. 64-bit, little endian etc.) and (2) using the same version of Salmon (i.e. >= 0.10) then this _should_ work.  Can you try with a small sample to see if it gives you any issues?  If it works for one sample, than at least there are no binary incompatibilities in the index.

**Comment by rbenel** [comment]
Hi @rob-p, 
So I can't update you on if it worked, because the cluster is using the 10.0 version (because we can't install anything from source), and I ran into this bug, ( Error in function boost::math::digamma<double>(double): numeric overflow] #229) for all of my samples, which you mention in the thread that this was fixed in the 10.1 version. Any idea when the binary for 10.1 will be out?

**Comment by rob-p** [comment]
Can you try [this](https://github.com/COMBINE-lab/salmon/files/2074498/salmon-latest_linux_x86_64.tar.gz) executable?

**Comment by rbenel** [comment]
I can try. I will need to send the executable to the administrator of the cluster and request for it to be installed.

**Comment by rbenel** [comment]
Hi @rob-p, 
I have successfully run the Salmon analysis, but I should add that the admin of the cluster utilized the executable you sent, but I used conda to install salmon 10.1, the executable you sent me for some reason didn't index the transcriptome correctly, I received the same error I initially started this post for...
Thank you so much for all of your help, I'll post here how it goes. :)
