### ISSUE TITLE
Error during Salmon installation

### ISSUE THREAD

**Issue by EPunzi** [COMBINE-lab/salmon#235]
Hi, I'm trying to install Salmon on a local server, but I get the following error:

```[ 81%] Building CXX object src/CMakeFiles/unitTests.dir/__/external/install/src/rapmap/rank9b.cpp.o
/usr/local/salmon-0.9.1/external/install/src/rapmap/rank9b.cpp: In constructor ‘rank9b::rank9b(const uint64_t*, uint64_t)’:
/usr/local/salmon-0.9.1/external/install/src/rapmap/rank9b.cpp:41:53: warning: suggest parentheses around ‘-’ inside ‘<<’ [-Wparentheses]
    counts[ pos + 1 ] |= ( c - counts[ pos ] ) << 63 - 9 * j;
                                                     ^
[ 82%] Building C object src/CMakeFiles/unitTests.dir/__/external/install/src/rapmap/bit_array.c.o
Linking CXX executable unitTests
/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [src/unitTests] Error 1
make[1]: *** [src/CMakeFiles/unitTests.dir/all] Error 2
make: *** [all] Error 2
```

What can I do?

**Comment by rob-p** [comment]
Hi @EPunzi ,

  There are a couple of options.  First, I see you're using an older release of Salmon. I strongly suggest grabbing [the latest release](https://github.com/COMBINE-lab/salmon/releases/tag/v0.10.2).  What you posted here is actually a warning, not an error.  What is preventing compilation looks to be a linking error (i.e. your compiler cannot find -lstdc++).  If the newest salmon doesn't compile cleanly for the easiest thing to do is to install [through bioconda](https://anaconda.org/bioconda/salmon).  Please let me know if either of these are successful, or, if not, what issues you run into.

--Rob

**Comment by EPunzi** [comment]
Hi @rob-p ,

I tried both ways. Classic installation (not through bioconda) gave me this error:

```
In file included from /usr/local/salmon-0.10.2/include/eigen3/Eigen/Core:420:0,
                 from /usr/local/salmon-0.10.2/include/eigen3/Eigen/Dense:1,
                 from /usr/local/salmon-0.10.2/include/SalmonUtils.hpp:21,
                 from /usr/local/salmon-0.10.2/include/ReadPair.hpp:7,
                 from /usr/local/salmon-0.10.2/include/AlignmentGroup.hpp:15,
                 from /usr/local/salmon-0.10.2/include/AlignmentLibrary.hpp:12,
                 from /usr/local/salmon-0.10.2/src/SalmonQuantifyAlignments.cpp:39:
/usr/local/salmon-0.10.2/include/eigen3/Eigen/src/Core/AssignEvaluator.h:90:50: warning: enum constant in boolean context [-Wint-in-bool-context]
     MaySliceVectorize  = bool(MightVectorize) && bool(DstHasDirectAccess)
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
make[2]: *** [src/CMakeFiles/salmon.dir/SalmonQuantifyAlignments.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/salmon.dir/all] Error 2
make: *** [all] Error 2
```

I also tried installing it through bioconda. Apparently, it installs it correctly, but when I try to use Trinity (I'm installing Salmon as a Trinity requirement) this is what happens: 

```
salmon: /opt/conda/conda-bld/salmon_1528409373758/work/salmon-0.10.2/include/eigen3/Eigen/src/Core/util/Memory.h:161: void* Eigen::internal::aligned_malloc(std::size_t): Assertion `(size<16 || (std::size_t(result)%16)==0) && "System's malloc returned an unaligned pointer. Compile with EIGEN_MALLOC_ALREADY_ALIGNED=0 to fallback to handmade alignd memory allocator."' failed.
Error, cmd:
salmon --no-version-check quant -i /home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/read_partitions/Fb_0/CBin_0/c30.trinity.reads.fa.out/Trinity.fasta.tmp.salmon.idx -l U -r /home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/read_partitions/Fb_0/CBin_0/c30.trinity.reads.fa.out/single.fa -o salmon_outdir -p 1 --minAssignedFrags 1
 died with ret (6) at /usr/local/trinityrnaseq-Trinity-v2.6.6/util/support_scripts/../../PerlLib/Process_cmd.pm line 19.
        Process_cmd::process_cmd("salmon --no-version-check quant -i /home/federicoplazzi/test_"...) called at /usr/local/trinityrnaseq-Trinity-v2.6.6/util/support_scripts/salmon_runner.pl line 26
Trinity run failed. Must investigate error above.
warning, cmd: /usr/local/trinityrnaseq-Trinity-v2.6.6/util/support_scripts/../../Trinity --single "/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/read_partitions/Fb_0/CBin_0/c30.trinity.reads.fa" --output "/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/read_partitions/Fb_0/CBin_0/c30.trinity.reads.fa.out" --CPU 1 --max_memory 1G --run_as_paired --SS_lib_type F --seqType fa --trinity_complete --full_cleanup   failed with ret: 512, going to retry.
succeeded(0), failed(1)   100% completed.

We are sorry, commands in file: [FailedCommands] failed.  :-(

Error, cmd: /usr/local/trinityrnaseq-Trinity-v2.6.6/trinity-plugins/BIN/ParaFly -c recursive_trinity.cmds -CPU 4 -v -shuffle  died with ret 256 at /usr/local/bin/Trinity line 2581.
        main::process_cmd("/usr/local/trinityrnaseq-Trinity-v2.6.6/trinity-plugins/BIN/P"...) called at /usr/local/bin/Trinity line 3244
        main::run_partitioned_cmds("recursive_trinity.cmds") called at /usr/local/bin/Trinity line 2239
        main::run_recursive_trinity("/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/ch"...) called at /usr/local/bin/Trinity line 2001
        main::run_chrysalis("/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/in"..., "/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/bo"..., 200, 500, "RF", "/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/bo"..., "/home/federicoplazzi/test_Trinity_Assembly/trinity_out_dir/bo"...) called at /usr/local/bin/Trinity line 1664
        main::run_Trinity() called at /usr/local/bin/Trinity line 1317
        eval {...} called at /usr/local/bin/Trinity line 1316

Trinity run failed. Must investigate error above.
```

Do you have any suggestions?

**Comment by rob-p** [comment]
Hi @EPunzi,

  The trinity-based installation error looks quite cryptic.  It suggests what to do to fix it, but it seems like something that shouldn't be happening in the first place.  I would be happy to see if I could figure out what's going on with the "manual" installation.  Could you provide more of the compiler output?  What you have included above shows a warning, but I can't see what's causing the actual compiler *error* (what compiler & OS version are you using?).  Finally, could you let me know if [this](https://github.com/COMBINE-lab/salmon/files/2099291/salmon-latest_linux_x86_64.tar.gz) pre-compiled linux-x86-64 binary works for you?

**Comment by EPunzi** [comment]
Hi @rob-p ,

we managed to successfully install Salmon and run Trinity. We compiled Salmon ourselves and we managed to find where the error is located, that is in a Boost file. 
I'm not sure if this information is useful for you, but in order to correctly install Boost, we had to modify the file boost_1_67_0/boost/lockfree/spsc_queue.hpp by adding the line `#include <boost/next_prior.hpp>` among the other inclusions of that file. After editing it and compiling Salmon again, it works properly.

Thank you for your support!

**Comment by rob-p** [comment]
Hi @EPunzi,

  I'm glad you were able to get this to work.  Thanks for the detailed feedback.  This is, indeed, interesting to us.  Though, it looks like it's a bug in the Boost build.  Could you let me know what OS (& version), and compiler you're using?  I can report this upstream to Boost.

Thanks again!
Rob

**Comment by EPunzi** [comment]
Hi @rob-p ,

I'm using a Centos server, centos-release-7-1.1503.el7.centos.2.8.x86_64, the CMake version required is CMake3 and the compiler is g++ 7.3.1.

**Comment by rob-p** [comment]
Great; thanks so much, @EPunzi --- I'll take a look at this upstream and report it if it's not a known issue.

**Comment by knokknok** [comment]
Hi Rob,
Any reason why v0.11 is not on conda?

**Comment by rob-p** [comment]
Hi @knokknok,

  The problem (https://github.com/bioconda/bioconda-recipes/pull/9943) is that conda is in the middle of updating their build system which is breaking a bunch of packages.  Right now, salmon on linux builds OK but there is an OSX issue.  I think the consensus now is in favor of skipping OSX until the we figure out what is wrong or until the new build system is in place.

**Comment by knokknok** [comment]
Ok, thanks for the fast reply!

**Comment by rob-p** [comment]
No problem.  The linux build has just been merged upstream in bioconda-recipes (https://github.com/bioconda/bioconda-recipes/pull/9943#issuecomment-408112204), so that build for 0.11 should appear in condo soon.
