### ISSUE TITLE
 [error] umi indexing of jellyfish failing. Please report on github

### ISSUE THREAD

**Issue by Munfred** [COMBINE-lab/salmon#237]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
- Alevin

**Describe the bug**
I got the error copied below, it said to report on GitHub so I'm doing that

**To Reproduce**
Steps and data to reproduce the behavior:
- The Jupyter notebook I was using is in the attached zip file
[alevin-default-eduardo.zip](https://github.com/COMBINE-lab/salmon/files/2096615/alevin-default-eduardo.zip)

Specifically, please provide at least the following information:

  * Which version of salmon was used? 
Salmon 0.10.2
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
 Installed with bioconda
  * Which reference (e.g. transcriptome) was used? 
This transcriptome: https://drive.google.com/open?id=1XcsFUxJM6XaYEKh9BYdUoAyJSlWJLIiW. 
It's a mouse transcriptome with 3 additional transcripts at the end
  * Which read files were used?
  * Which which program options were used?
`salmon alevin -lISR -1 ./H2_S5_L003_R1_001.fastq.gz -2 H2_S5_L003_R2_001.fastq.gz --chromium -i salmon_index -p 8 -o alevin_output --tgMap txp2gene.tsv`

**Desktop (please complete the following information):**
 - OS:  CentOS
 - Version:
Linux login1 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core

**Additional context**
```
Version Info: This is the most recent version of Salmon.
Logs will be written to alevin_output/logs
### salmon (single-cell-based) v0.10.2
### [ program ] => salmon 
### [ command ] => alevin 
### [ libType ] => { ISR }
### [ mates1 ] => { ./H2_S5_L003_R1_001.fastq.gz }
### [ mates2 ] => { H2_S5_L003_R2_001.fastq.gz }
### [ chromium ] => { }
### [ index ] => { salmon_index }
### [ threads ] => { 8 }
### [ output ] => { alevin_output }
### [ tgMap ] => { txp2gene.tsv }


[2018-06-12 21:01:31.327] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2018-06-12 21:01:31.330] [alevinLog] [info] Processing barcodes files (if Present) 

 
processed 141 Million barcodes

[2018-06-12 21:08:38.126] [alevinLog] [info] Done barcode density calculation.
[2018-06-12 21:08:38.126] [alevinLog] [info] # Barcodes Used: 140111660 / 141062078.
[2018-06-12 21:08:42.014] [alevinLog] [info] Knee found left boundary at  127 
[2018-06-12 21:08:55.712] [alevinLog] [warning] Gauss Prediction 12274 Too far from knee prediction skipping it
[2018-06-12 21:08:55.712] [alevinLog] [info] Learned InvCov: 255.229 normfactor: 12656.9
[2018-06-12 21:08:55.712] [alevinLog] [info] Total 327(has 200 low confidence) barcodes
[2018-06-12 21:08:55.895] [alevinLog] [info] Done True Barcode Sampling
[2018-06-12 21:08:56.092] [alevinLog] [info] Done populating Z matrix
[2018-06-12 21:08:56.093] [alevinLog] [info] Done indexing Barcodes
[2018-06-12 21:08:56.094] [alevinLog] [info] Total Unique barcodes found: 1530568
[2018-06-12 21:08:56.094] [alevinLog] [info] Used Barcodes except Whitelist: 4828
[2018-06-12 21:08:56.124] [alevinLog] [info] Done with Barcode Processing; Moving to Quantify

[2018-06-12 21:08:56.124] [alevinLog] [info] parsing read library format
[2018-06-12 21:08:56.124] [jointLog] [info] There is 1 library.
[2018-06-12 21:08:56.183] [jointLog] [info] Loading Quasi index
[2018-06-12 21:08:56.184] [jointLog] [info] Loading 32-bit quasi index
[2018-06-12 21:08:56.184] [stderrLog] [info] Loading Suffix Array 
[2018-06-12 21:08:56.530] [stderrLog] [info] Loading Transcript Info 
[2018-06-12 21:08:56.675] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-06-12 21:08:56.724] [stderrLog] [info] There were 36191 set bits in the bit array
[2018-06-12 21:08:56.729] [stderrLog] [info] Computing transcript lengths
[2018-06-12 21:08:56.729] [stderrLog] [info] Waiting to finish loading hash
[2018-06-12 21:08:58.508] [jointLog] [info] done
[2018-06-12 21:08:58.508] [jointLog] [info] Index contained 36191 targets
[2018-06-12 21:08:58.508] [stderrLog] [info] Done loading index




processed 0 Million fragments
processed 1 Million fragments
processed 1 Million fragments
processed 2 Million fragments
processed 2 Million fragments
processed 3 Million fragments
processed 3 Million fragments
hits: 169917, hits per frag:  0.0489674[2018-06-12 21:09:22.500] [jointLog] [error] umi indexing of jellyfish failing.
Please report on github
```

**Comment by k3yavi** [comment]
Hi @Munfred ,
Thanks for showing interest in our tool and raising the issue.
Can you please check the `H2_S5_L003_R1_001.fastq.gz` file somewhere around 3 Million reads (from top) if the length of the `FASTQ` entry is of length 26?
If you can share top 4/5 Million reads from the `FASTQ`, I can take a look too.

**Comment by Munfred** [comment]
Hi thanks for the quick reply!
The length does not seem to be 26, it's shorter than that
Here are the first 5M reads: https://drive.google.com/open?id=1mOmjyuOrAnK1zFjB_4DP003-mH6OpKYa
And here is the genome: https://drive.google.com/open?id=1j97pmzsfVX2Cflxk1O31xpDakIk59fRr

**Comment by k3yavi** [comment]
Hi @Munfred ,
Is it 10x single-cell data ? Also in 10x is it using v2 Chemistry?
The way you are running alevin is specifically for 10x v2 data. If it's v1 you can find how to use alevin in v1 mode [here](https://combine-lab.github.io/alevin-tutorial/2018/running-alevin/). 
If it's V2 and you still get this error, then it means either the `Fastq` were not made properly or the reads / CB+UMI pair has to be filtered out.

Currently `Alevin` fails if it observe a `Fastq` sequence of length less than 26 (16 CB + 10 UMI), if you think your dataset is from a real sample and follows the 10x `mkfastq` procedure, then we can work on handling these cases internally in Alevin, or another workaround would be to just filter out these set of reads from the Fastq using some external script.

**Comment by Munfred** [comment]
Hi Avi, the data is from a 10x chromium run with v2 chemistry.

I was able to get it to work by using Trim Galore! (https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/) and using the option `--length 26` to drop reads that has less than 26 length (a few dozen of them). If this is a common issue, perhaps it might be interesting to add a flag to tell Alevin to ignore reads below a certain length.

I was also able to use a mouse transcriptome with a few extra custom sequences added, by also adding them manually on the `tgx` file. Perhaps you might want to expand the `Trancript to Gene Mapping`  (https://combine-lab.github.io/alevin-tutorial/2018/setting-up-resources/) part of the tutorial to explain how to handle custom genes manually (I was also not familiar with awk and took me a while to understand what was happening). 

Finally, in the `Understanding Output` part (https://combine-lab.github.io/alevin-tutorial/2018/output-format/) you might want to elaborate a little more on how to read the `quants_mat.gz` binary matrix that is outputed. I could not figure that out, so I ran Salmon again with the flag `--dumpCsvCounts`. I suspect that most other people will also want the csv file, so you might want to make that kind of output default.

Many thanks for the good work, documentation and assistance!

**Comment by k3yavi** [comment]
Hi @Munfred , thanks for all the useful comments and glad to hear that you were able to run alevin successfully. 
I agree, in the next release we can work on adding the flag for ignoring the reads below a certain length.
Regarding the Transcript to gene Mapping file, all `bioawk` script does it to generate a `tsv` file with the first column as transcript name (as present in the reference) and the second column is the relevant gene id to the transcript. We have described the format [here](http://salmon.readthedocs.io/en/latest/alevin.html) but we can also update the tutorial to reflect the same more clearly.

I agree with your last point too, we are working on writing a python parser, to parse the binary format and would update the tutorial soon with the relevant code.

Thanks again for using our tool and let us know if you have any other feedback / suggestion regarding improving the alevin pipeline.

**Comment by k3yavi** [comment]
Hi @Munfred ,

As promised we have updated the [tutorial](https://combine-lab.github.io/alevin-tutorial/2018/output-format/) to read-in the binary format of the Alevin's output and can now be easily imported without using `--dumpCsvCounts`. If you are interested in looking at code to parse the binary format it can be found [here](https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L8).

Thanks again for request .
