### ISSUE TITLE
no bin folder

### ISSUE THREAD

**Issue by kayDaramola** [COMBINE-lab/salmon#238]
Hi, just downloaded salmon, unpacked with tar, but I don't seem to find the bin folder containing the salmon binary file

Thanks
Kay

**Comment by rob-p** [comment]
Hi @kayDaramola ,

  The download you will get from the releases page is the source.  You will either need to build / compile it from source or, alternatively, install the binary using bioconda (recommended).  Finally, you can try [this](https://github.com/COMBINE-lab/salmon/files/2099291/salmon-latest_linux_x86_64.tar.gz) pre-compiled binary for Linux, though we are trying to move to bioconda for all binary distribution as it makes support easier by removing a major variable.

**Comment by kayDaramola** [comment]
Thanks for the reply
I actually tried the one on conda, but it says segmentation fault.

I will look at the one you provided, thanks

Kay
