### ISSUE TITLE
No .sf output file on RNA Seq with Salmon

### ISSUE THREAD

**Issue by Tj-Idowu** [COMBINE-lab/salmon#239]
Hi,
I am having trouble with salmon on linux,  I downloaded salmon through bioconda and was following your "GETTING STARTED" tutorial, followed the code exactly and it all worked fine except I am not getting the quant.sf file for any of the samples. I also tried it on my own mRNA fastq files and the same thing happened. I am able to get all the other files like the log in its own directory. The log files are empty though so I was not able to get any information as to what is wrong. I am not getting any errors either so I don't really know where to start looking.
Any help you can give would be much appreciated.
Thank you,
Tj.

**Comment by rob-p** [comment]
Hi TJ,

  Can you paste the terminal output of salmon and the results of `ls -la` on the resulting quantification directory?

Thanks,
Rob

**Comment by Tj-Idowu** [comment]
Hi Rob,
Thanks for the quick response I attached a file of screeenshots from the terminal in a pdf document.
Thanks,
Tj.
[Salmon_screenshot.pdf](https://github.com/COMBINE-lab/salmon/files/2124016/Salmon_screenshot.pdf)

**Comment by rob-p** [comment]
Hi @Tj-Idowu,

  My hypothesis here is that Salmon did not run properly to completion.  Can you provide me with the console output that appears when you run Salmon at the command line?  That output text will help me identify if there seems to be a problem (and if so, what it may be).

**Comment by Tj-Idowu** [comment]
![salmon](https://user-images.githubusercontent.com/32261407/41860825-889b4178-7897-11e8-9801-08ebbc787fb3.png)

**Comment by rob-p** [comment]
Thanks @Tj-Idowu,

  So, indeed, it looks like this is the problem.  The mapping is completing, but you seem to be encountering a segmentation fault at the end of the run (before the abundance estimation finishes).  Could you tell me what OS and version you're using, and how you installed Salmon?  My guess is a binary incompatibility somewhere.

--Rob

**Comment by Tj-Idowu** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Linux version 4.13.0-45-generic (buildd@lgw01-amd64-011) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #50~16.04.1-Ubuntu SMP

I installed Salmon using the command on https://anaconda.org/bioconda/salmon
"conda install -c bioconda salmon"

**Comment by rob-p** [comment]
Hi @Tj-Idowu,

  Thanks for the details.  The fact that the bioconda install is giving problems is disconcerting, as that should be properly linked against all of the correct libraries etc.  I do wonder if it might have something to do with all of the package rebuilding and upgrading that has been going on in bioconda.  Would you be able to give [this binary](https://github.com/COMBINE-lab/salmon/files/2099291/salmon-latest_linux_x86_64.tar.gz) a try, and let me know if it works?  It was built on our continuous integration server, and should be compatible with a wide variety of different platforms.

**Comment by Tj-Idowu** [comment]
It worked. Thank you
