### ISSUE TITLE
salmon-0.10.2: Exception : [unrecognised option '--numThreads=16']. Exiting.

### ISSUE THREAD

**Issue by mmokrejs** [COMBINE-lab/salmon#241]
Hi,
  `salmon quant` understands `-p 16` but not `--numThreads=16` nor `--numThreads 16`. Is the documentation http://salmon.readthedocs.io/en/latest/salmon.html correct?

**Comment by rob-p** [comment]
Indeed.  It looks like the option name changed at some point in the past, but the documentation didn't follow suite.  The appropriate long-form option is `--threads`.  I'll update this in the docs.

**Comment by mmokrejs** [comment]
Great.
