### ISSUE TITLE
salmon docker failing while loading hash

### ISSUE THREAD

**Issue by tacazares** [COMBINE-lab/salmon#243]
I have been trying to use the salmon docker container available on docker hub. When I run salmon quant I am able to load all of the files and start the program, but I get a killed message while loading hash. I get an empty log file and empty folders created after the container is killed.

**To Reproduce**
I run the following command to run the container:
`docker run -v /Users/caz3so/workspaces/salmon_docker:/temp -w /temp -ti combinelab/salmon`

The following is the output:
<img width="1389" alt="screenshot 2018-06-27 11 15 56" src="https://user-images.githubusercontent.com/31480706/41983246-8296bb76-79fb-11e8-9710-c38ec051b7e7.png">

**Expected behavior**
I have salmon installed on my machine and was able to run these files with no problem. It is only when I am using the docker container, so it could be a docker related problem. 

**Desktop (please complete the following information):**
I am using a 2017 Macbook pro with 16 GB 2133 MHz LPDDR3 memory and a 2.8 GHz Intel Core i7 processor.

**Comment by rob-p** [comment]
Hi @tacazares ,

  Thank you for reporting this issue, and for following the issue template!  I have at least one other instance of Docker + OSX causing a problem for people, so it seems like this may be the underlying cause.  Nonetheless, I'll see if we can investigate this further to figure out _why_ it might be happening.

**Comment by rob-p** [comment]
One thought might be that on OSX, I think docker sets a very low default RAM limit (2G?).  That's insufficient for loading the entire human txome index.  You could try [setting this](https://docs.docker.com/docker-for-mac/#advanced) to a larger value (e.g. 6 or 8G should suffice).

**Comment by tacazares** [comment]
This worked! I just adjusted the maximum memory and swap memory that docker was able to use in the preferences in the docker application. Thanks a lot!

**Comment by rob-p** [comment]
No worries; thanks for trying it out so quickly!
