### ISSUE TITLE
Error in the tutorial

### ISSUE THREAD

**Issue by Hoohm** [COMBINE-lab/salmon#244]
The git clone doesn't work

```
git clone git@github.com:COMBINE-lab/salmon.git
cd salmon; mkdir build; cd build
cmake ..
make install
```

This should work:
```
git clone https://github.com/COMBINE-lab/salmon.git
```

**Comment by Hoohm** [comment]
Another error:
There is a whitespace after the last slash.

```
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/ gencode.v28.pc_transcripts.fa.gz

```

Corrected
```
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.pc_transcripts.fa.gz

```

**Comment by rob-p** [comment]
Thanks, @Hoohm --- I'll go correct these.

**Comment by rob-p** [comment]
Interestingly, I can't find the errant space.  I wonder if it has something to do with how the page was rendered at a specific resolution / in a specific browser...

**Comment by k3yavi** [comment]
Hi @rob-p, 

I think @Hoohm was talking about the Alevin-tutorial, https://github.com/COMBINE-lab/alevin-tutorial/commit/a9f299dbeaba91c4805e5e8df834f8b89f709e6c
should fix it. Although there is a overflow from the code block now, will look into that later.
Closing this for now.
