### ISSUE TITLE
Error bar on TPM estimation

### ISSUE THREAD

**Issue by AngryMaciek** [COMBINE-lab/salmon#246]
Dear Authors,

Is there any way to get the information on the uncertainty of the TPM quantification per transcript? It would be useful to have some kind of measure on the range the inferred expression may vary...

Best!
Maciek

**Comment by rob-p** [comment]
Hi @AngryMaciek,

  You can get either Gibbs samples from the posterior, or bootstrap estimates.  To get the former, you pass `--numGibbsSamples <nsamp>` to salmon, and to get the latter, you pass `--numBootstraps <nsamp>`.  Either way, samples will be written to a binary, gzipped file in `aux_dir/bootstrap/ bootstraps.gz` (we decided to keep a uniform file name regardless of the sampling type, however the type of sampling performed can be derived from `aux_dir/meta_info.json`).

  Two things to point out here.  First, the binary file format can be converted to TSV if you prefer using [this script](https://github.com/COMBINE-lab/salmon/blob/master/scripts/ConvertBootstrapsToTSV.py).  Second, these are samples over the number of reads assigned to the transcripts (not the TPMs directly).  However, you could easily convert samples over the number of reads to samples over the TPMs by applying the TPM formula (i.e. TPM_i = 10^6 * (num_reads_i / effective_length_i) / (sum_j  (num_reads_j / effective_length_j))).
