### ISSUE TITLE
Salmon result missing some isoforms

### ISSUE THREAD

**Issue by RicardoPluto** [COMBINE-lab/salmon#255]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon
**Describe the bug**
The cDNA fasta file contains 176241 ENSTs,but the result file only contains 166667 ENSTs.
**To Reproduce**
Steps and data to reproduce the behavior:
The steps and data are as follows. 
Specifically, please provide at least the following information:

  * Which version of salmon was used? v0.9.1
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
downloaded executable
  * Which reference (e.g. transcriptome) was used? 
Homo_sapiens.GRCh38.cdna.all.fa obtained from Ensembl release 83
  * Which read files were used? 
GSE41009
  * Which which program options were used? 
Building index: salmon index -t filepath/Homo_sapiens.GRCh38.cdna.all.fa -i V83-homo_index --type quasi -k 31
Quantification: salmon quant -p 50 -i filepath/V83-homo_index -l IU -1 ESC-SRR574820_1.fastq ESC-SRR574821_1.fastq -2 ESC-SRR574820_2.fastq ESC-SRR574821_2.fastq -o ESC-quantification

**Expected behavior**
The result file should contain all the ENSTs existed in cDNA fasta file.
**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]
uname -a
Linux mn1 2.6.32-431.29.2.2.ky3.1.x86_64 #1 SMP Thu Sep 25 10:15:09 CST 2014 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	NeoKylin
Description:	NeoKylin release 3.2 (Carambola)
Release:	3.2
Codename:	Carambola
**Additional context**

**Comment by rob-p** [comment]
Hi @RicardoPluto,

  This is the expected behavior, I think.  When salmon indexes transcripts it collapses exact duplicates (transcripts with perfectly identical sequence).  In the salmon index directory, there is a file called “duplicate_clusters.tsv”.  This is a 2-column tsv file where the first column lists a retained transcript and the right column lists a discarded duplicate.  A transcript can represent multiple discarded sequences, in which case it appears multiple times in the first column.  This will allow you to see the sequence duplicate clusters.  If quantified, all transcripts in these clusters would obtain identical quantification estimates.

If you really want to go through with quantification of sequence duplicates.  You can pass `--keepDuplicates` to the salmon indexing command.  This will tell salmon not to discard these duplicates, and they will appear in the output quantifications.

Please let me know if this resolves your issue.

Best,
Rob

**Comment by RicardoPluto** [comment]
Thanks for your great help!
Sincerely,
Ricardo

**Comment by uros-sipetic** [comment]
Hi @rob-p, just a quick question about these duplicates - do you maybe know if RSEM handles this in the same way?
By this I mean, I believe that RSEM does not collapse duplicate transcripts, so I'm curios whether the expression levels are then handled in the same way as when the --keepDuplicates flag is passed to Salmon, i.e. divided across all duplicates?
I'm just asking to see if and how I can cross-compare the expression values between different quantification tools (RSEM and Salmon in this case)
Thanks for any answers once again!

**Comment by rob-p** [comment]
Hi @uros-sipetic,

  RSEM _does not_ collapse duplicates.  This means that it will return quantification estimates for all of the sequence identical transcripts separately.  A common scenario may be that it will split the abundances evenly, but this may not always be the case, depending on e.g. the initialization of the EM algorithm etc.

  The easiest way to try and compare the estimates as closely as possible would probably be to use the `duplicate_clusters.tsv` file produced by salmon to explicitly collapse (add up) the abundances of the duplicate transcripts from the RSEM quantifications before comparing.

  As always, we'd be interested to hear if you find anything interesting!

Best,
Rob

**Comment by uros-sipetic** [comment]
Here's what I got
For a single sample, analyzed both with RSEM (with STAR aligner) and with Salmon in SA mode with collapsed duplicates, on GRCh38 FASTA and ensembl91 GTF, here are the TPM values for some ~30 transcripts that Salmon collapsed: 
<img width="549" alt="Screen Shot 2020-05-14 at 9 40 04 PM" src="https://user-images.githubusercontent.com/16819349/81978250-88bbf180-962b-11ea-8283-2b51511576da.png">

Note: RSEM reported the same TPM values for all duplicate transcripts that Salmon collapsed. 
So in the table above, there's Salmons TPM and RSEM TPMs for that single transcript, and the total TPM when adding all collapsed transcripts.

Now, I know that different approaches are used here (alignment with STAR + EM in RSEM, versus Selective Alignment in Salmon), and that some TPM values will be different.
But from based on some of the 'similar' values from this table, I could gather that the situation is just as you described @rob-p, i.e. where the Salmon_TPM and the RSEM_TPM_total columns are in similar values, I assume that these are the transcripts for which both RSEM and Salmon reported similar expressions
