### ISSUE TITLE
Documentation on ReadTheDocs references Salmon 0.8.1 (latest is 0.11.0)

### ISSUE THREAD

**Issue by lparsons** [COMBINE-lab/salmon#259]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
Both

**Describe the bug**
When viewing http://salmon.readthedocs.io/en/latest/index.html, the page header described Salmon 0.8.1. Is the documentation out of date, or is that simply not an updated version number?

**To Reproduce**
View http://salmon.readthedocs.io/en/latest/index.html

**Expected behavior**
Salmon 0.11.0 is the latest release, thus I expected the latest version of the documentation to reflect that.

**Comment by rob-p** [comment]
Hi @lparsons,

  Thanks for bringing this to our attention.  There are just too many different places to remember to bump the version.  This one was in the Python configuration script for the ReadTheDocs pages.  Anyway, I've finally properly scripted the "version_bump" process, so this should happen automatically in the future (and is fixes as of 0.11.1).

Best,
Rob
