### ISSUE TITLE
Salmon Binary for Osx while Bioconda is down

### ISSUE THREAD

**Issue by k3yavi** [COMBINE-lab/salmon#260]
While Bioconda is working on resolving the issue for osx deployment of salmon (>v10.2). the following binary can be used for osx based testing of Salmon/Alevin.

Note: The code has been compiled on Osx High Sierra (v 10.13.2) and can potentially create problem with other versions of osx.

**Comment by k3yavi** [comment]
[salmon-latest_linux_x86_64.tar.gz](https://github.com/COMBINE-lab/salmon/files/2237580/salmon-latest_linux_x86_64.tar.gz)
 Mac-Osx v 10.13.2

**Comment by k3yavi** [comment]
Hi @junaruga , Although the above attached binary has been mistakenly named as for linux it should work with MacOsx Sierra. The current recommended way of installing salmon is through bioconda or docker, but unfortunately currently bioconda system is down for MacOsx releases. You can try using docker if the above binary doesn't works for you.

Let us know how it goes.

**Comment by junaruga** [comment]
@k3yavi all right. I will try it later, and let you know! Thank you.

**Comment by junaruga** [comment]
@k3yavi let me share my status.

> salmon-latest_linux_x86_64.tar.gz
> Mac-Osx v 10.13.2

I downloaded the binary file. And it works! :) Thanks.

In other words, I downloaded below binary file on release page.
https://github.com/COMBINE-lab/salmon/releases/download/v0.11.2/salmon-0.11.2-linux_x86_64.tar.gz

But it did not work like this.

```
$ wget https://github.com/COMBINE-lab/salmon/releases/download/v0.11.2/salmon-0.11.2-linux_x86_64.tar.gz
$ tar xzvf salmon-0.11.2-linux_x86_64.tar.gz
$ cd salmon-0.11.2-linux_x86_64/
$ ./salmon --help
-bash: ./salmon: cannot execute binary file
```

I have not tried to install by bioconda yet.

**Comment by k3yavi** [comment]
Cool, glad to hear that the above binary works for you. The binary on the release page was for linux that's why you were getting that error. As we progress, I'll keep updating the version for Macosx here, until the conda build is fixed for Osx.

Also I've update the name of the file above just to avoid the confusion, thanks for the tip .

**Comment by junaruga** [comment]
@k3yavi all right. Thank you for that. That's helpful!
