### ISSUE TITLE
conda salmon 10.1 indexing

### ISSUE THREAD

**Issue by rbenel** [COMBINE-lab/salmon#262]
Hi Rob, 
After successfully finishing my DE analysis on gene expression, I want to use the package IsoformSwitchAnalyzeR which as mentioned here [https://github.com/COMBINE-lab/salmon/issues/214](url) must utilize the `--keepDupicates ` argument when indexing the transcriptome with gencode annotations. As I read this only after, I need to re-run my analysis, but would *really* like to use the initial version 10.1 which I have installed as well as which is on the cluster. When I enter the conda environment, I receive an update that the newest version is available and I should update.. is there any way to force salmon to index the transcriptome with the current (10.1) version? 

```
Version Info: ### A newer version of Salmon is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
salmon v0.10.1
```
Thanks

**Comment by rob-p** [comment]
Hi @rbenel,

  This message is just salmon letting you know a newer version is available.  The installed version should function perfectly fine.  If you really want to avoid the message, you can pass `--no-version-check` *before* the salmon command; e.g.:

` salmon --no-version-check index ...`

Best,
Rob

**Comment by rbenel** [comment]
OK, but thew indexing doesn't start... which is why I thought there was an issue.

**Comment by rbenel** [comment]
Thanks! Got it
