### ISSUE TITLE
Alevin Segmentation fault after reading Cellular Barcodes.

### ISSUE THREAD

**Issue by juugii** [COMBINE-lab/salmon#264]
Hello,
salmon 0.11.1, on CentOS 7.
Tested with install from precompiled binaires, and from bioconda/conda 4.5.9

(1) salmon -h is fine, but salmon [command] -h takes lots of time, and ends up with
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon

It could be related to any bad local proxy settings. Is there any way to skip the upgrade information lookup as a command-line option ?

(2) segmentation error with alevin
### [ tgMap ] => { tx2gene.tsv }

[2018-08-03 14:31:41.793] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2018-08-03 14:31:41.810] [alevinLog] [info] Processing barcodes files (if Present) 
processed 109 Million barcodes
segmentation error (core dumped)

No any other logs available, programs stopped.

Best,
juugii.

**Comment by rob-p** [comment]
Dear @juugii,

  Thanks for reporting these.  Regarding 

(1) : Yes, it is possible to skip the version check.  Simply place `--no-version-check` before any command. For example:

```
salmon --no-version-check index <... parameters for indexing>
```

and 

```
salmon --no-version-check quant <... parameters for quantification>
```
This will let you avoid the network timeout.

Regarding issue (2), it's difficult to say what's happening without seeing the data.  I'm looping in @k3yavi to help take a look into this.

**Comment by k3yavi** [comment]
Hi @juugii , it looks like you are using 10x data and you might need `--chromium` flag to tell alevin the type of datasets. Although it should have given error message much before starting reading the CB. I'll look into this but can confirm if you have given the flag to alevin or not?

**Comment by juugii** [comment]
Rob,

Thanks for the --no-version-check option, I did not see it.

regarding issue (2)

I have been able to process these files without any problem with other
tools.
I have the same problem with the 10x pbmc4k fastq files:

salmon --no-version-check alevin -p 10 -lISR -1
/path/to/downloads/10xPBMC/pbmc4k_S1_L001_R1_001.fastq.gz -2
/path/to/downloads/10xPBMC/pbmc4k_S1_L001_R2_001.fastq.gz -i
/path/to/salmonIndex -o alevin_output --tgMap tx2gene.tsv
Logs will be written to alevin_output/logs
### salmon (single-cell-based) v0.11.1
### [ program ] => salmon
### [ command ] => alevin
### [ threads ] => { 10 }
### [ libType ] => { ISR }
### [ mates1 ] => {
/path/to/downloads/10xPBMC/pbmc4k_S1_L001_R1_001.fastq.gz }
### [ mates2 ] => {
/path/to/downloads/10xPBMC/pbmc4k_S1_L001_R2_001.fastq.gz }
### [ index ] => { /path/to/salmonIndex }
### [ output ] => { alevin_output }
### [ tgMap ] => { tx2gene.tsv }


[2018-08-03 19:20:57.848] [jointLog] [info] Fragment incompatibility
prior below threshold.  Incompatible fragments will be ignored.
[2018-08-03 19:20:57.867] [alevinLog] [info] Processing barcodes files
(if Present)


processed 189 Million barcodes

Segmentation error (core dumped)



Avi,

You are right, I did miss the --chromium option. However, I just tried
again with the above command with --chromium and I still get the
segmentation error.

**Comment by k3yavi** [comment]
I am assuming you gave the `--chromium` to `pbmc_4k` data too and it's throwing error, since the above log doesn't seems to have it. I am puzzled because it should have complained much before starting reading the fastq. Can you please try the following command: 
```
salmon alevin -p 10 -lISR --chromium --no-version-check  -1 /path/to/downloads/10xPBMC/pbmc4k_S1_L001_R1_001.fastq.gz -2 /path/to/downloads/10xPBMC/pbmc4k_S1_L001_R2_001.fastq.gz -i /path/to/salmonIndex -o alevin_output --tgMap tx2gene.tsv
```

**Comment by juugii** [comment]
Sorry if I wasn't clear. I did try with and without the --chromium
option, with the same error.

I just have try the exact command you provided (including the --chromium
flag), with option in the same order.

The command log is then:
### salmon (single-cell-based) v0.11.1
### [ program ] => salmon
### [ command ] => alevin
### [ threads ] => { 10 }
### [ libType ] => { ISR }
### [ chromium ] => { }
### [ mates1 ] => {
/path/to/downloads/10xPBMC/pbmc4k_S1_L001_R1_001.fastq.gz }
### [ mates2 ] => {
/path/to/downloads/10xPBMC/pbmc4k_S1_L001_R2_001.fastq.gz }
### [ index ] => { /path/to/salmonIndex }
### [ output ] => { alevin_output }
### [ tgMap ] => { tx2gene.tsv }

Now it seems to work. I'll tell you if the whole alignment is
successfull when it will end.

Note that when I use the --chromium flag earlier in the command, ie:

salmon --no-version-check --chromium alevin -p 10 -lISR -1 [...]

The log contains:
### salmon (single-cell-based) v0.11.1
### [ program ] => salmon
### [ command ] => alevin
### [  ] => { alevin }
### [ threads ] => { 10 }
### [ libType ] => { ISR }

**Comment by juugii** [comment]
I realize my mistake, I was confused by the error message.
Pseudoaligment seems to work now.

[...]
[2018-08-03 20:13:23.083] [jointLog] [info] Computed 312565 rich
equivalence classes for further processing
[2018-08-03 20:13:23.083] [jointLog] [info] Counted 120065952 total
reads in the equivalence classes
[2018-08-03 20:13:23.084] [jointLog] [warning] Found 9775 reads with `N`
in the UMI sequence and ignored the reads.
Please report on github if this number is too large
[2018-08-03 20:13:23.084] [jointLog] [info] Mapping rate = 63.2442%

[2018-08-03 20:13:23.084] [jointLog] [info] finished quantifyLibrary()
[2018-08-03 20:13:26.208] [alevinLog] [info] Starting optimizer


ERROR: Txp to Gene Map not found for 203027 transcripts. Exiting(salmon)

I just have a problem with my tx2gene file. Here is the head of my file:

ENST00000013125	MAP4K5
ENST00000215368	EFNA2
ENST00000200453	PPP1R15A
ENST00000202028	EPB41L1
ENST00000204679	GNPTG
ENST00000175506	ASNS
ENST00000215574	CDC34
ENST00000167106	VASH1
ENST00000074304	INPP4A
ENST00000055077	RFC2

The transcript ID is probably not consistent with the one from the
alevin output. However, I used to perform some pseudo-alignments using
salmon on bulk RNAseq with the same transcriptome references and the
same tx2gene file that I used here (postprocessed using R) and it work.
What could be wrong here? Could you provide me with an example of the
tx2gene file needed?

**Comment by k3yavi** [comment]
[This](https://combine-lab.github.io/alevin-tutorial/#blog) tutorial might help.
Are you using gencode reference transcriptome ?

**Comment by juugii** [comment]
ensembl reference transcriptome. I have seen the tutorial, but I don't
use bioawk. I use plain awk, but I am lost on the gtf fields mentionned.
For the tx2gene file, are the (1) transcript_id and the (2) gene_name
fields the required informations ?

**Comment by k3yavi** [comment]
Yes, for gencode the tsv file would like as following:
```
ENST00000456328.2       ENSG00000223972.5
ENST00000450305.2       ENSG00000223972.5
ENST00000488147.1       ENSG00000227232.5
ENST00000619216.1       ENSG00000278267.1
ENST00000473358.1       ENSG00000243485.5
ENST00000469289.1       ENSG00000243485.5
ENST00000607096.1       ENSG00000284332.1
ENST00000417324.1       ENSG00000237613.2
ENST00000461467.1       ENSG00000237613.2
ENST00000606857.1       ENSG00000268020.3
```
Basically the error is popping because it is not able to map the name of the transcript in your reference `fasta` file to the name of the transcript in the `tsv` file.
How does head of the `fasta` looks like or 
```
grep "^>" /path/to/fasta | head 
```

**Comment by juugii** [comment]
Yes, in the gtf file, I don't have any .[0-9] (transcript version)
suffixes for the transcripts, while I have some on the fasta file
header. So it is the fasta feature identifier extracted from the header
that is used, not the transcript_id (without its suffix) from the gtf
file ? I'll rebuild a correct tx2gene file then.

Le 03/08/2018 à 20:59, Avi Srivastava a écrit :
> Yes, for gencode the tsv file would like as following:
> ```
> ENST00000456328.2       ENSG00000223972.5
> ENST00000450305.2       ENSG00000223972.5
> ENST00000488147.1       ENSG00000227232.5
> ENST00000619216.1       ENSG00000278267.1
> ENST00000473358.1       ENSG00000243485.5
> ENST00000469289.1       ENSG00000243485.5
> ENST00000607096.1       ENSG00000284332.1
> ENST00000417324.1       ENSG00000237613.2
> ENST00000461467.1       ENSG00000237613.2
> ENST00000606857.1       ENSG00000268020.3
> ```
> Basically the error is popping because it is not able to map the name of the transcript in your reference `fasta` file to the name of the transcript in the `tsv` file.
> How does head of the `fasta` looks like or 
> ```
> grep "^>" /path/to/fasta | head 
> ```
>

**Comment by k3yavi** [comment]
I guess we never pass the `GTF` file to salmon.

**Comment by juugii** [comment]
I see, thanks for the information.
The conversation is going outside the scope of the original issue, that is already solved. I can close it. Many, many thanks for you fast and excellent support, to both of you. I should be able to solve my tx2gene issue now.
