### ISSUE TITLE
Segmentation fault in bioconda installation

### ISSUE THREAD

**Issue by NatPRoach** [COMBINE-lab/salmon#268]
Hello,
I'm running in to problems trying to run salmon quant. I've installed the latest version 0.11.2 via bioconda, and successfully constructed an index of the C. elegans Wormbase WS265 transcriptome with the following settings:

`salmon index -k 21 -p 24 -t ${txome_reference} -i ${index_path}`

but upon running quant with the following command:

`salmon quant -i ${index_path} -o ${out_prefix} -l IU -1 ${mate1_reads} -2 ${mate2_reads}
`

I get a segmentation fault error midway through running:

```hits: 122146249, hits per frag:  2.10747
processed 58500001 fragments
hits: 123209453, hits per frag:  2.11344
processed 59000000 fragments
hits: 124280773, hits per frag:  2.10932

/cm/local/apps/slurm/var/spool/job28571481/slurm_script: line 39:  1187 Segmentation fault      salmon quant -i ${index_path} -o ${out_prefix} -l IU -1 ${mate1_reads} -2 ${mate2_reads}
```

If it helps I'm running this on the following SRA data:
> SRR016679
> SRR016680
> SRR016681

This is running on a CentOS release 6.9 cluster. The script in which salmon is being called is being run through SLURM 17.11.7 workload management software.

I tried installing a older version of salmon ( 0.9.1 )  through conda and ended up with the same error running that version. 
I've also tried downloading the source and compiling, but am running in to an error upon calling make:

```libtool: compile:  /usr/bin/cc -DHAVE_CONFIG_H -I. -I.. -I.. -MT libstaden_read_la-cram_io.lo -MD -MP -MF .deps/libstaden_read_la-cram_io.Tpo -c cram_io.c -o libstaden_read_la-cram_io.o
cram_io.c:66:18: error: lzma.h: No such file or directory
cram_io.c: In function 'lzma_mem_deflate':
cram_io.c:1389: error: 'LZMA_OK' undeclared (first use in this function)
cram_io.c:1389: error: (Each undeclared identifier is reported only once
cram_io.c:1389: error: for each function it appears in.)
cram_io.c:1389: error: 'LZMA_CHECK_CRC32' undeclared (first use in this function)
cram_io.c: In function 'lzma_mem_inflate':
cram_io.c:1399: error: 'lzma_stream' undeclared (first use in this function)
cram_io.c:1399: error: expected ';' before 'strm'
cram_io.c:1405: error: 'LZMA_OK' undeclared (first use in this function)
cram_io.c:1405: error: 'strm' undeclared (first use in this function)
cram_io.c:1420: error: 'LZMA_RUN' undeclared (first use in this function)
cram_io.c:1421: error: 'LZMA_STREAM_END' undeclared (first use in this function)
cram_io.c:1434: error: 'LZMA_FINISH' undeclared (first use in this function)
make[5]: *** [libstaden_read_la-cram_io.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [libstadenio-prefix/src/libstadenio-stamp/libstadenio-build] Error 2
make[1]: *** [CMakeFiles/libstadenio.dir/all] Error 2
make: *** [all] Error 2```

**Comment by NatPRoach** [comment]
I apologize, I misread one of the previous threads on segmentation faults. Upon downloading and running the precompiled linux binary provided in this thread https://github.com/COMBINE-lab/salmon/issues/261#issuecomment-409436938 the program ran to completion. Sorry for that!

**Comment by scottx611x** [comment]
FWIW I'm experiencing this same behavior (`salmon quant` segfaults with 0.9.1 & 0.11.2 from bioconda) on my SLURM cluster. Ref #271 

@NatPRoach If you ever end up figuring out a solution for bioconda installs for this please let me know!

**Comment by rob-p** [comment]
I'm quite curious why this issue would plauge bioconda builds and not the pre-compiled binary.  I wonder if it is worth cross-referencing this issue over on bioconda-recipes to get their input.

**Comment by stepbystepcode** [comment]
Successfully installed and ran salmon on Arch Linux using the AUR binary package. Works great![link](https://aur.archlinux.org/packages/salmon)
