### ISSUE TITLE
Documentation currently omits the need for index type

### ISSUE THREAD

**Issue by ctb** [COMBINE-lab/salmon#27]
http://sailfish.readthedocs.org/en/latest/salmon.html#using-salmon doesn't talk about the need for a '--type' argument to salmon index.

**Comment by rob-p** [comment]
The salmon docs are in a separate location [http://salmon.readthedocs.org/en/latest/](http://salmon.readthedocs.org/en/latest/) --- the requirement for the `--type` argument should be there.

**Comment by ctb** [comment]
OK, so do I file an issue on the sailfish project to get them to put a new link in, or what? :)

**Comment by rob-p** [comment]
So, I've already updated the docs *here* (i.e. the doc tag in the ReadMe should  should point to the link I give above).  I believe the right thing to do over in the Sailfish docs is to just remove any documentation about Salmon (since the projects are now maintained in separate repos each with their own docs).

**Comment by ctb** [comment]
k!

On Sun, Nov 01, 2015 at 08:48:45AM -0800, Rob Patro wrote:
> So, I've already updated the docs *here* (i.e. the doc tag in the ReadMe should  should point to the link I give above).  I believe the right thing to do over in the Sailfish docs is to just remove any documentation about Salmon (since the projects are now maintained in separate repos each with their own docs).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/COMBINE-lab/salmon/issues/27#issuecomment-152843180
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by rob-p** [comment]
Ok --- The sailfish docs should be updated as well [http://sailfish.readthedocs.org/en/master/](http://sailfish.readthedocs.org/en/master/).  Let me know if you see something different (i.e. if you still see the salmon instructions over there).

**Comment by ctb** [comment]
Currently still there: http://sailfish.readthedocs.org/en/latest/salmon.html?highlight=salmon - will look later.

**Comment by rob-p** [comment]
Thanks for checking. It's a latest vs. master issue; should be fixed on all branches now.

**Comment by ctb** [comment]
Not yet :)

**Comment by rob-p** [comment]
Fought RTD a bit, but now it looks good from my end (make sure your browser isn't caching the page) ... hopefully this resolves it!

**Comment by ctb** [comment]
resolved! thx.

**Comment by rob-p** [comment]
Great!  Thanks for putting up with my embarrassing struggle to get RTD to do what I wanted :).

**Comment by ctb** [comment]
:) I've been there!
