### ISSUE TITLE
Barcode not found in frequency table

### ISSUE THREAD

**Issue by gianfilippo** [COMBINE-lab/salmon#284]
Hi,

I am trying to process scRNAseq Chromium data using alevin. I already have results from cellranger and I wanted to compare them with alevin.

I use the following command line
salmon alevin -lISR -1 Fastq1a.fastq.gz Fastq1b.fastq.gz -2  Fastq2a.fastq.gz Fastq2b.fastq.gz --chromium -i gencode.v25.transcripts_index -p 20 -o AlevinOUT --tgMap gencode.v25.txp2gene.tsv --dumpCsvCounts --whitelist 737K-august-2016.txt

I get the following error message at the end of the output
[alevinLog] [error] Barcode not found in frequency table

If I run the exact same files using without the --whitelist flag/file I get some results for a very small set of barcodes. Interestingly the barcodes found by alevin (I only checked 2 or 3) are also in the 737K-august-2016.txt file. 

My first question is why alevin does not "count" barcodes (zero frequency) with the barcode file, and does estimate frequency for some (at least) barcodes without the barcode file. Considering that the barcodes in the latter case are also found in the whitelist file. 

My second question is more about difference between alevin and cellranger. I do get estimated counts for a large number of barcodes (thousands) using cellranger, while barely on the order of a few hundreds, at best, using alevin.

Thanks

**Comment by k3yavi** [comment]
HI @gianfilippo ,
I think #245 might help understanding the problem better.
Specifically to answer your questions, I am guessing `737K-august-2016.txt` is all the set of Cellular Barcodes(CB) being whitelisted by 10xGenomics protocol while in Alevin when you are giving external whitelist it assumes that the user is pretty confident about the presence of *all* the given CBs in their experiment. for example if you want to compare Alevin and cellranger apple to apple then you might have to give the `barcodes.tsv`(usually is present along with the `mtx` file) generated by the cellranger. (after removing `-1` from the CB names). 
`[alevinLog] [error] Barcode not found in frequency table`: This error means some of the CB given externally through the whitelist command seems to have no reads at all which violates the above assumption, you can potentially skip this error by using `--debug` flag with alevin (only if have version v0.11.3) but this mode has is yet to be extensively tested.
In case where you don't externally give whitelist CB, Alevin uses knee and KDE based method to identify the cutoff on the knee (and later correct for it) of the CB distribution. Based on your specific dataset it is possible that the method might be overshooting and aggressively identifying less number of clusters. If you can share the log and some part of your data then we can take a look what's going on. Hope this helps.

**Comment by gianfilippo** [comment]
Hi,

thanks for the prompt reply and suggestions. I rerun it as you suggested, using the cellranger generated barcode file and it looks much better now.

I am attaching the log files. How much of the FASTQ files would you need ?

Thanks
[salmon_quant.log.txt](https://github.com/COMBINE-lab/salmon/files/2343857/salmon_quant.log.txt)
[alevin.log.txt](https://github.com/COMBINE-lab/salmon/files/2343858/alevin.log.txt)

**Comment by gianfilippo** [comment]
Hi,

sorry about it.

Here they are

[alevin.log](https://github.com/COMBINE-lab/salmon/files/2346583/alevin.log)
[salmon_quant.log](https://github.com/COMBINE-lab/salmon/files/2346584/salmon_quant.log)

**Comment by k3yavi** [comment]
Hi @gianfilippo ,
Thanks for forwarding the logs.
It does look like Alevin knee selection is over-shooting and allowing only ~250 cells as a whitelist.
Although not very frequent but we do have observed this behavior with Alevin knee selection in couple of other experiments and are working on more robust thresholding. I am closing this issue regarding the barcode frequency but will open a new one regarding the aggressive thresholding and would tag you in too, in case you wan't to track.

**Comment by gianfilippo** [comment]
Great!

Thanks
