### ISSUE TITLE
Large number of errors about non-existent positions in the reads

### ISSUE THREAD

**Issue by bsipos** [COMBINE-lab/salmon#289]
**Describe the bug**
I am trying to quantify long reads mapped using minimap2 and I am getting a large number of the following messages:

```
[2018-09-10 12:42:32.972] [jointLog] [warning] CIGAR = 106c16M1D7M1D8M1D26M1D55M3D8M1D32M2I14M1I8M1I52M1D14M1I2M1I19M1I1M1I7M11D28M1D5M3I40M1D5M1I5M1I6M1I13M147c
[2018-09-10 12:42:32.972] [jointLog] [warning] (in update()) CIGAR string for read [e6b69e2f-1bf2-4fd5-bace-d4d213164026] seems inconsistent. It refers to non-existant positions in the read!

```

**To Reproduce**
  * Which version of salmon was used?
salmon version: salmon 0.11.3, minimap2 version: 2.9-r720
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
Installed through bioconda.
  * Which reference (e.g. transcriptome) was used?
Ensembl [cDNA collection](http://ftp.ensembl.org/pub/release-93/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz).
  * Which read files were used?
Nanopore reads.
  * Which which program options were used?
salmon quant -p {threads} -t {input.trs} -l SF -a {input.bam} -o {output.tsv_dir}

**Desktop (please complete the following information):**
  Ubuntu 14.04.5 LTS

**Additional context**
I am wondering whether the issue is caused by the fact that minimap2 does not include sequences in the secondary alignments. The errors disappear if I filter for primary alignments only.

**Comment by rob-p** [comment]
Hi @bsipos,

  This is caused primarily by salmon's desire to apply an error model (by default) to the CIGAR strings.  For secondary alignments, as you note, minmap2 doesn't write the read string, and so when salmon is trying to score the alignments under the error model, it can't find the relevant characters in the read.  In general, it's not clear to me if one would actually want to apply the error model (designed primarily for short reads) when quantifying long reads (this is something we are currently testing in the lab).  For the time being, I'd probably recommend disabling the error model when quantifying alignments from long reads (`--noErrorModel`).  In that case, the errors should hopefully go away.  Please let me know, and we'll be sure to keep you updated on best practices for long reads as we figure things out.

**Comment by bsipos** [comment]
Hi @rob-p,

Thanks for the tip, using `--noErrorModel` indeed got rid of the error messages. Also, any advice regarding the best practices using salmon on nanopore data are welcome.

Best,
Botond

**Comment by mirresimons** [comment]
Hi @bsipos did you solve this cause you closed it? I was just trying salmon out and I got the same warning (and lots).

**Comment by austin-abbvie** [comment]
I attempted to use the new --ont error model that has been developed for Salmon but am getting the same error mentioned here.

**To Reproduce**

Which version of salmon was used?
salmon version: salmon 1.5.1, minimap2 version: 2.20-r1061
How was salmon installed (compiled, downloaded executable, through bioconda)?
Installed through bioconda.
Which reference (e.g. transcriptome) was used?
Custom generated transcriptome (Stringtie2, merged with ensembl release 104 Hg38)
Which read files were used?
Nanopore reads.
Which which program options were used?
salmon quant -p {threads} -t {input.trs} -l MSF -a {input.bam} -o {output.tsv_dir} --ont
Desktop (please complete the following information):
Ubuntu 20.04.2 LTS

**Comment by rob-p** [comment]
Hi @austin-abbvie,

  Thanks for the report.  Would you be able to share the offending BAM file and reference? I'm also tagging @gmarcais for input / ideas.

Thanks,
Rob

**Comment by austin-abbvie** [comment]
> Hi @austin-abbvie,
> 
> Thanks for the report. Would you be able to share the offending BAM file and reference? I'm also tagging @gmarcais for input / ideas.
> 
> Thanks,
> Rob

I'll have to check with my manager to see if this is something I'm allowed to do. I also just attempted to use the --noErrorModel instead of --ont, but now I'm getting a `segmentation fault (core dumped)` after about 2M reads. These BAMs have been through a lot so I'm going to check to make sure they haven't been corrupted in some way
