### ISSUE TITLE
symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

### ISSUE THREAD

**Issue by TSL-RamKrishna** [COMBINE-lab/salmon#290]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)? Salmon

**Describe the bug**
I downloaded salmon-0.11.3-linux_x86_64.tar.gz file and extracted it. There  is no makefile or install.sh files, just the bin. lib, sample_data. Therefore no any installation steps. The bin and lib were put in environment paths PATH and LD_LIBRARY_PATH.
When I run trinity command i get following error:

Trinity version: Trinity-v2.6.6
-ERROR: couldn't run the network check to confirm latest Trinity software version.

Tuesday, September 11, 2018: 14:29:38	CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /path/to/trinity/2.6.6/x86_64/util/support_scripts/ExitTester.jar 0
Error: dl failure on line 893
Error: failed /path/to/java/8u131/x86_64/jre/lib/amd64/server/libjvm.so, because /path/to/bin/salmon/0.11.3/x86_64/lib/libm.so.6: symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Error, cmd: java -Xmx64m -XX:ParallelGCThreads=2  -jar /path/to/trinity/2.6.6/x86_64/util/support_scripts/ExitTester.jar 0 died with ret 1536 at /path/to/bin/core/../..//trinity/2.6.6/x86_64/bin/Trinity line 2581.
	main::process_cmd('java -Xmx64m -XX:ParallelGCThreads=2  -jar /path/to...') called at /path/to/bin/core/../..//trinity/2.6.6/x86_64/bin/Trinity line 2666
	eval {...} called at /path/to/bin/core/../..//trinity/2.6.6/x86_64/bin/Trinity line 2665
	main::test_java_failure_capture() called at /path/to/bin/core/../..//trinity/2.6.6/x86_64/bin/Trinity line 1159

I get similar error while just checking for java version
$ java -version

Error: dl failure on line 893
Error: failed /tsl/software/testing/java/8u131/x86_64/jre/lib/amd64/server/libjvm.so, because /tsl/software/testing/bin/core/../..//salmon/0.11.3/x86_64/lib/libm.so.6: symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

**To Reproduce**
Steps and data to reproduce the behavior:

Specifically, please provide at least the following information:

  * Which version of salmon was used? 0.11.3
  * How was salmon installed (compiled, downloaded executable, through bioconda)? downloaded executables
  * Which reference (e.g. transcriptome) was used?  no reference
  * Which read files were used? fastq
  * Which  program options were used? Trinity options

**Expected behavior**

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX] CentOS
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by rob-p** [comment]
Hi @TSL-RamKrishna,

  Thanks for the report.  However, it's not exactly clear to me how this is related specifically to salmon.  Generally, if the libm you have is _newer_ than the one salmon was built with, you should be OK.  So, one option would be to simply remove the `libm.so.6` from the salmon `lib` directory and see what happens.

**Comment by TSL-RamKrishna** [comment]
Thanks for the reply. Yes I tried just renaming the library file and it worked.

**Comment by geekyouth** [comment]
lib64/libc.so.6错误导致的系统崩溃
https://gliderhx.github.io/2020/04/08/lib64-libc.so.6%E9%94%99%E8%AF%AF%E5%AF%BC%E8%87%B4%E7%9A%84%E7%B3%BB%E7%BB%9F%E5%B4%A9%E6%BA%83/

```
sln /usr/lib64/libc-2.17.so /lib64/libc.so.6
sln /usr/lib64/ld-2.17.so /usr/lib64/ld-linux-x86-64.so.2
```
