### ISSUE TITLE
alevin: correcting CB and dumpfq related error

### ISSUE THREAD

**Issue by dbrg77** [COMBINE-lab/salmon#291]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
alevin

**Describe the bug**

Hello there, I just started to try `alevin` and really liked it.

Recently, I was trying to use alevin to correct the CB and add to read2 fastq.

salmon version: v0.11.2

This is the command I use:

`salmon alevin -l ISR --chromium -1 r1.fq.gz -2 r2.fq.gz -i salmon_index -p 12 --whitelist known_cb.txt --noQuant --dumpfq --tgMap gene_map.tsv -o alevin_out > alevin_out/corrected_r2.fq`

example of r1.fq:

```
@D00323:881:HH577BCX2:1:1101:1815:1951
GGTTGCGAGATATGTTACGACGTGCT
+
AG<<G.AGGAGAG.A.IIIIIIIIII
@D00323:881:HH577BCX2:1:1101:1963:1952
TAACAGCTCGTGCTGGTACATTGCTT
+
GGGGGIIIGIIIIIIIIIIIIIIIII
@D00323:881:HH577BCX2:1:1101:1900:1954
GAGACTTTCTAGTCGATCTACTGCCC
+
GGGGGIIIIIGGGGIGIIIIIIIIII
```

example of r2.fq:

```
@D00323:881:HH577BCX2:1:1101:1815:1951
AGGTTGCAGTGAGCTGAGATCGTGCCACTGCACTCTAGCCACCACACCTGGCTAATTTTTGTATTTTTAAGTAGAGACAGAGTTTCGCTATGTTGGCCAG
+
AAA<GGGGA<G.GAGAGA.GGAGAGG.G.GGAAGGG.<.<GGGGGGIIGGGGAGGAGGAGGIIA.AAGAGGIGGAG.<AG.AGGGGAAGGGGGIIGGAG.
@D00323:881:HH577BCX2:1:1101:1963:1952
TAATACCGCTTTAGCTACATCTCAGATCTGGGTAAGTCATGTCTGCATTTTCAATAATTTCATTTTTTAAACTTCTACCTTAATTCTGATGTTTACTCAT
+
GAGGAGGGGAGGIGGGGGGGGIIGGGGGIIGIIGGGGGGGGGGGGGGGGIIIIGIIGGIIGGAGIIIIIGGGGIGGAGAGIIIGGGGGGGIIIIGGGIII
@D00323:881:HH577BCX2:1:1101:1900:1954
GCTTCATATAGTCTTACCTTTCTGAGGACCAATTTGGCTGAATTCTCTGCTTTCTAATCTGACTCCTTATGGGGGATCCCTGCTATAGAGATGTAGACCA
+
GGAGAGGGGAGGIIIGGGIGIIIIIIGIGIIGGGIIIIIIIGGGGGGGIGGGGGGGGGGGGGGIIGIGGGGIGGGAGGIGIGIGGGGGGIGGGIIGGIGG
```

example of `known_cb.txt`:

```
GGATAGGGTCATAGCT
GGATAGGGTTAGAGAT
GGATAGGGTTGCCTGG
GGATAGGGTACGCAAG
GGATAGGGTAACGGAC
GGATAGGGTCAACAGG
GGATAGGGTAACGGCA
GGATAGGGTTTGTCTT
GGATAGGGTGCTAGTT
GGATAGGGTACGACCC
```

According to the documentation, `dumpfq` will output the reads to `stdout`, and here is the content of `alevin_out/corrected_r2.fq`:

```
Version Info: This is the most recent version of Salmon.
Sequence-Size 17greater than specified 16.
Please report the issue on Github.
```

In addition, we have some protocol under development, where CBs/UMIs are not in the read1.fq and read2.fq. They are rather in the index reads from illumina (i5 and i7).

After calling `bcl2fastq`, we normally get 4 fastqs for each sample:

```
R1.fastq
R2.fastq
I1.fastq
I2.fastq
```

Both `R1.fastq` and `R2.fastq` contain important gene/genome information, it is the combination of the sequence in `I1.fastq` and `I2.fastq` that define cells. Is this something that `alevin` might support in future. In this case, if I know exact the sequence of I1 and I2, what the `whitelist.txt` file should look like?

Thank you!

Regards,
Xi

**Comment by k3yavi** [comment]
Hi @dbrg77 ,
Thanks for raising the issue and the very interesting future direction.
A quick question regarding the error, can you please check if the length of _all_ the externally given whitelisted CB are of length 16 ?

Extracting the CB/UMI from bcl or generalizing the input format for PE is indeed in our todo list. Specially with the introduction of combinatorial barcoding of single cells, as you said, the information might be in multiple files and has to be extracted right. It's definitely in our priority list and one would hope to support this in future. However, if your use case is different from above then we should definitely chat about that in little more details.

**Comment by dbrg77** [comment]
Hi @k3yavi , thank you for the reply.

Yes, you are right, it seems the problem is indeed in the whitelist `known_cb.txt`. However, I cannot seem to find out what exactly is going on with the file. When I wrote a python script to check the length of each cell barcode in `known_cb.txt`, _all_ of them are 16 bp long. This is the python script:

```
$ cat print_length.py
with open('known_cb.txt') as fh:
    for i in fh:
        print(len(i))
```

since each line has 16 bp barcode and a `\n` character, it outputs 17, which is expected. However, when I used `awk` to check the length, I expected `awk` to output 16, but it actually output 17:

```
$ awk '{print length($0);}' known_cb.txt | head -2
17
17
```

There might be some hidden characters that I missed. Any idea what's going?

Now, I have cleaned the `known_cb.txt`, and `alevin` runs without problem.

For combinatorial indexing, good to known that it will be supported in future. I guess depending on assays, it needs to be a bit more flexible than the current options. The current options have only `--chromium` and `--dropseq` available. However, there are a few different combinatorial indexing assays.

For `sci-RNA-seq`, the cell barcodes are within `I1.fastq`, `I2.fastq` and `R1.fastq`. Only `R2.fastq` is useful for gene quantification.

For `sci-ATAC-seq`, the cell barcodes (this is just my educational guess) are within `I1.fastq` and `I2.fastq`, and both `R1.fastq` and `R2.fastq` contain useful information from the genome.

For other plate-based method, there will be well barcodes and plate barcodes, which could be located in any of those 4 fastq files depends on the design. The cell barcodes will be a combination of well barcodes and plate barcodes.

Thank you very much for the help.

Regards,
Xi

**Comment by k3yavi** [comment]
HI @dbrg77 ,

Thanks for the tips on sci-seq and sci-car seq. We have put both in our todo list and would let you know once we have a stable version.

re error: I am not sure why would there be an extra count under `awk`, although based on the editor/environment I think they sometimes use `\r\n` as the newline operator but don't trust me on this one it's just a hunch.

I am closing this issue for now, feel free to open it if you have any other question.
