### ISSUE TITLE
Dereplication step

### ISSUE THREAD

**Issue by OnlyHigh** [COMBINE-lab/salmon#299]
Hello, 
I saw in a google group post (https://groups.google.com/forum/#!topic/sailfish-users/hPKjIKpNyAo) that Salmon has the option to depreplicate transcripts. Is there an option to obtain a fasta file with the dereplicate transcripts? 

Thanks in advance, 
Luis Alfonso.

**Comment by rob-p** [comment]
Hi @OnlyHigh,

  Indeed, the _default_ behavior of salmon is to de-duplicate transcripts (to avoid that behavior and allow salmon to index duplicate transcripts, you need to pass the `--keepDuplicates` flag to the indexer).  When it does this, it will log the duplicate transcripts in the index.  If you look in the directory containing the salmon index, you will find a file called `duplicate_clusters.tsv`.  This is a 2 column TSV file with a row for each transcript that was collapsed during indexing. The first column says which retained transcript was identical to the collapsed transcript.  We do not write down the specific sequence of these transcripts, but with the original fasta file on which the index was built, you can easily extract this.

Best,
Rob

**Comment by rob-p** [comment]
Hi @OnlyHigh,

  Since I believe my response above resolves this issue, I'm closing this issue now.  However, if you have further questions, please feel free to re-open.

Best,
Rob
