### ISSUE TITLE
Remove FPKM from results

### ISSUE THREAD

**Issue by Blahah** [COMBINE-lab/salmon#3]
R/FPKM are widely misused in practise and in the literature. It has been known since at least 2011 ([RSEM paper](http://www.biomedcentral.com/1471-2105/12/323)) that they are not suitable for comparison between samples due to the library-specific normalisation factor. Unfortunately, most people use them that way.

TPM has all the benefits of R/FPKM but has the added benefit that the normalisation factor (1,000,000) is stable between samples. There is therefore no reason to use R/FPKM.

Salmon already promotes good practice in many ways, including reporting TPM. It should further promote good practise by not including FPKM in its results.

**Comment by rob-p** [comment]
In the latest release (along with other, even **more-awesome** new features), FPKM has been dropped from the output.
