### ISSUE TITLE
Salmon ignores "S" in --libtype ISF

### ISSUE THREAD

**Issue by ctb** [COMBINE-lab/salmon#30]
Hi, we're having trouble with salmon on a stranded library -- we're executing

```
salmon index --index idx --transcript equCabs.fa --type quasi
```

and then

```
salmon quant -i idx -1 leftReads.fq -2 rightReads.fq --libType ISF -o xxx.quant
```

We then get the warning that there is a big strand bias in an unstranded protocol, despite having specified stranded (S) in libType.  Inspection of the libFormatCounts.txt file confirms this, with "expected format" specifying "strandedness:unstranded".

**Comment by rob-p** [comment]
I opened an issue in the ngs notes about this.  I need to update the docs; the library format string should come before the reads (I.e. -1, -2, -r).
