### ISSUE TITLE
Comment regarding thread usage and output from the quantification

### ISSUE THREAD

**Issue by william1swe** [COMBINE-lab/salmon#302]
Hello, 

While running the quantifications of my samples while quasi-mapping, the resulting created quant folders remain empty following the shell script is done running. An example of this would be from the "Getting Started" tab: 

#!/bin/bash
for fn in data/DRR0161{25..40};
do
samp=`basename ${fn}`
echo "Processing sample ${samp}"
salmon quant -i athal_index -l A \
         -1 ${fn}/${samp}_1.fastq.gz \
         -2 ${fn}/${samp}_2.fastq.gz \
         -p 8 -o quants/${samp}_quant
done 

Once this is done, the created folders are empty, whereas I would expect them to continue to quant files. Of note, I do sometimes get complete quantification of one or two samples (again, referring to the A.thaliana example used in the "Getting Started" tab. My, albeit limited, experience might suggest that my case might be a matter of number of threads used/made available. I would appreciate any feed back/confirmation on this. As a reference, I was initially running this on a quad core (3.1 GHz Intel Core i7) MacBook Pro.

Thank you for taking the time to consider this, most likely, simple issue

**Comment by william1swe** [comment]
Fixed

**Comment by rob-p** [comment]
Great, thanks for closing this.  What was the problem?
