### ISSUE TITLE
Segmentation fault 11 with bioconda build

### ISSUE THREAD

**Issue by dougbarrows** [COMBINE-lab/salmon#303]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon

**Describe the bug**

I had an older version of salmon that works (v0.8.2) that I believe was not compiled with Bioconda. I am now trying to get the latest version through Bioconda and with the same "salmon quant" command (See below) that works on the old version, I get a "segmentation fault 11" error and it never actually quantifies any reads. Do you know why this would happen?

**To Reproduce**
Steps and data to reproduce the behavior:

Specifically, please provide at least the following information:

  * Which version of salmon was used?
0.11.3
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
Bioconda
  * Which reference (e.g. transcriptome) was used?
gencode.v27.transcripts.fa
  * Which read files were used?
fastq
  * Which which program options were used?
-l A, single end 

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

```
salmon quant -i ~/Reference_indexes/humangencodev27_transcripts_index_20181023 -l A -r ~/Downloads/ENCFF600FYP.fastq.gz -o ./salmon_test/ENCFF600FYP_quant
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon
### salmon (mapping-based) v0.11.3
### [ program ] => salmon 
### [ command ] => quant 
### [ index ] => { ~/Reference_indexes/humangencodev27_transcripts_index_20181023 }
### [ libType ] => { A }
### [ unmatedReads ] => { ~/Downloads/ENCFF600FYP.fastq.gz }
### [ output ] => { ./salmon_test/ENCFF600FYP_quant }
Logs will be written to ./salmon_test/ENCFF600FYP_quant/logs
[2018-10-23 20:11:13.424] [jointLog] [info] Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored.
[2018-10-23 20:11:13.425] [jointLog] [info] parsing read library format
[2018-10-23 20:11:13.425] [jointLog] [info] There is 1 library.
[2018-10-23 20:11:13.513] [stderrLog] [info] Loading Suffix Array 
[2018-10-23 20:11:13.513] [jointLog] [info] Loading Quasi index
[2018-10-23 20:11:13.513] [jointLog] [info] Loading 32-bit quasi index
[2018-10-23 20:11:14.645] [stderrLog] [info] Loading Transcript Info 
[2018-10-23 20:11:14.975] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-10-23 20:11:15.031] [stderrLog] [info] There were 199,612 set bits in the bit array
[2018-10-23 20:11:15.042] [stderrLog] [info] Computing transcript lengths
[2018-10-23 20:11:15.042] [stderrLog] [info] Waiting to finish loading hash
[2018-10-23 20:11:20.618] [stderrLog] [info] Done loading index
[2018-10-23 20:11:20.618] [jointLog] [info] done
[2018-10-23 20:11:20.618] [jointLog] [info] Index contained 199,612 targets




Segmentation fault: 11
```

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
OSX
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21

**Additional context**

**Comment by dougbarrows** [comment]
Thank you! After unzipping and putting in my path and trying to run “salmon –version” I get the following error:


dyld: lazy symbol binding failed: Symbol not found: _os_unfair_lock_lock

  Referenced from: /Users/douglasbarrows/Tools/salmon_0.11.4-pre_OSX/bin/./salmon (which was built for Mac OS X 10.13)

  Expected in: /usr/lib/libSystem.B.dylib



dyld: Symbol not found: _os_unfair_lock_lock

  Referenced from: /Users/douglasbarrows/Tools/salmon_0.11.4-pre_OSX/bin/./salmon (which was built for Mac OS X 10.13)

  Expected in: /usr/lib/libSystem.B.dylib



Trace/BPT trap: 5

Is that something you have seen before?

**Comment by rob-p** [comment]
Hrmm, that's a missing / different system library.  Do the instructions [here](https://github.com/COMBINE-lab/salmon/issues/295#issuecomment-421417111) help at all?

**Comment by dougbarrows** [comment]
I still had the same error on that computer after following the instructions on the other thread. However, that computer is a bit older (OS 10.11.3), and when I used that OSX binary on my newer computer in lab (OS 10.13.4) it is working perfectly well so far. Thank you!

**Comment by rob-p** [comment]
Hi @dougbarrows --- just wanted to inform you that v0.12.0 has been released and is now also available via bioconda for both linux and osx.  The osx segfault issue has been resolved.
