### ISSUE TITLE
Problem Installing From Source

### ISSUE THREAD

**Issue by nate422** [COMBINE-lab/salmon#309]
Hello, I am trying to install this Salmon 0.11.3 from source but I am running into the following error when running make:

[ 80%] Linking CXX executable unitTests
../../external/install/lib/libstaden-read.a(libstaden_read_la-open_trace_file.o): In function `find_file_url':
open_trace_file.c:(.text+0xd2c): warning: the use of `tempnam' is dangerous, better use `mkstemp'
libsalmon_core.a(SalmonUtils.cpp.o): In function `salmon::utils::conflicting_options(boost::program_options::variables_map const&, char const*, char const*)':
SalmonUtils.cpp:(.text+0x5318): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
SalmonUtils.cpp:(.text+0x53b7): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libsalmon_core.a(SalmonUtils.cpp.o): In function `salmon::utils::validateOptionsMapping_(SalmonOpts&, boost::program_options::variables_map&)':
SalmonUtils.cpp:(.text+0xd13f): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libsalmon_core.a(SalmonUtils.cpp.o): In function `salmon::utils::processQuantOptions(SalmonOpts&, boost::program_options::variables_map&, int)':
SalmonUtils.cpp:(.text+0xeb97): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
SalmonUtils.cpp:(.text+0xec0a): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libsalmon_core.a(SalmonUtils.cpp.o):SalmonUtils.cpp:(.text+0xf846): more undefined references to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/unitTests] Error 1
make[1]: *** [src/CMakeFiles/unitTests.dir/all] Error 2
make: *** [all] Error 2

I have the following environment variables set:

INCLUDE=/opt/boost-1.67.0/include:/opt/gcc-8.2.0/include
C_INDLUE_PATH=/opt/boost-1.67.0/include
LD_LIBRARY_PATH=/opt/boost-1.67.0/lib:/opt/gcc-8.2.0/lib64:/opt/gcc-8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0
CPLUS_INCLUDE_PATH=/opt/boost-1.67.0/include:/opt/gcc-8.2.0/include
CXX=/opt/gcc-8.2.0/bin/g++
CC=/opt/gcc-8.2.0/bin/gcc

My cmake command was simply cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/salmon ../

Thanks!

-Nate

**Comment by rob-p** [comment]
Hi Nate,

  Can you tell me / do you know how boost was compiled?  The error you're getting looks like what happens when the version of boost against which salmon is attempting to link was not built with >= C++11.  Basically, the newest version of salmon requires C++14 (which GCC 8 obviously supports).  However, there are binary incompatibilities between pre-C++11 and post-C++11 code libraries.  So, whatever version of boost you link against must have been compiled with at least `--std=c++11`.  One option is to let salmon fetch and build boost for you by putting `-DFETCH_BOOST=TRUE` in the cmake configuration flags when calling `cmake`.

Best,
Rob

**Comment by nate422** [comment]
Rob,

Brilliant - I forgot that I built the boost libraries from whatever version of gcc was on the standard distribution.  I have included -DFETCH_BOOST=TRUE, do you know why I am receiving the following error regarding a missing when executing make?

using gcc :  : /opt/gcc-8.2.0/bin/g++  )
[  6%] Performing build step for 'libboost'
opt.jam: No such file or directory
/opt/salmon/external/boost_1_66_0/tools/build/src/build/toolset.jam:43: in toolset.using
ERROR: rule "opt.init" unknown in module "toolset".
/opt/salmon/external/boost_1_66_0/tools/build/src/build-system.jam:461: in process-explicit-toolset-requests
/opt/salmon/external/boost_1_66_0/tools/build/src/build-system.jam:527: in load
/opt/salmon/external/boost_1_66_0/tools/build/src/kernel/modules.jam:295: in import
/opt/salmon/external/boost_1_66_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build
/opt/salmon/external/boost_1_66_0/boost-build.jam:17: in module scope
make[2]: *** [libboost-prefix/src/libboost-stamp/libboost-build] Error 1
make[1]: *** [CMakeFiles/libboost.dir/all] Error 2
make: *** [all] Error 2

Thanks for all your help!

Nate

**Comment by abelew** [comment]
Greetings,
  I recently ran across this problem.  In my invocation, I noticed that the boost build process was running with a b2 command which looked like:

cd /cbcb/sw/RedHat-7-x86_64/common/local/salmon/0.12.0/src/salmon-0.12.0/external/boost_1_66_0 && CC=/opt/local/stow/gcc-8.1.0/bin/gcc CXX=/opt/local/stow/gcc-8.1.0/bin/g++ /cbcb/sw/RedHat-7-x86_64/common/local/salmon/0.12.0/src/salmon-0.12.0/external/boost_1_66_0/b2 -d0 -j2 --with-iostreams --with-atomic --with-chrono --with-container --with-date_time --with-exception --with-filesystem --with-graph --with-graph_parallel --with-math --with-program_options --with-system --with-locale --with-timer toolset=/opt/local/stow/gcc-8.1.0/bin/gcc toolset=/opt/local/stow/gcc-8.1.0/bin/gcc cxxflags=-std=c++14 "cxxflags= -std=c++14 -I/cbcb/sw/RedHat-7-x86_64/common/local/salmon/0.12.0/src/salmon-0.12.0/external/install/include -L/cbcb/sw/RedHat-7-x86_64/common/local/salmon/0.12.0/src/salmon-0.12.0/external/install/lib" link=static install

and was generated in the file:
CMakeFiles/libboost.dir/build.make

which I then edited to ensure that all the toolset entries were set to 'toolset=gcc'.
Rerunning the make then passed without error.
