### ISSUE TITLE
Make test failed

### ISSUE THREAD

**Issue by vivekabarath** [COMBINE-lab/salmon#315]
I just now installed Salmon 0.12.0-alpha by compiling it on Ubuntu 18.04 successfully and ran the make and make install commands.

While running the make test command I get the following output...
----------------------------------------------------------------------------------------
Running tests...
Test project /scratch/Programes/salmon-0.12.0-alpha
    Start 1: unit_tests
1/2 Test #1: unit_tests .......................***Failed    0.01 sec
    Start 2: salmon_read_test_quasi
2/2 Test #2: salmon_read_test_quasi ...........   Passed    1.06 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   1.07 sec

The following tests FAILED:
	  1 - unit_tests (Failed)
Errors while running CTest
Makefile:151: recipe for target 'test' failed
make: *** [test] Error 8
----------------------------------------------------------------------------------------
Why is this test failing?
It is OK.
I am new to Salmon.

with best regards,
Baradwaj

**Comment by rob-p** [comment]
Hi @vivekabarath,

  The final v0.12.0 has been released and is available via both the release page on github and via bioonda, so I recommend you use the official version.  Regarding your specific question, the failure of the unit tests should not be a problem and doesn't affect salmon.  However there was previously an issue that could cause the `make test` to fail if `make install` was not run first.  This should be resolved in the latest release as well.

Best,
Rob
