### ISSUE TITLE
Corrected: segmentation fault 11 on salmon tutorial

### ISSUE THREAD

**Issue by michael-brent** [COMBINE-lab/salmon#318]
Apologies for the previous empty post. I think I know how to do this now!

Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?

salmon

Describe the bug
I am getting a consistent segmentation fault 11 when running on the salmon tutorial on the provided arabidopsis data set.

To Reproduce

Which version of salmon was used?
salmon v0.11.3 on MacBook Pro (15-inch, 2016) macOS Sierra 10.12.6.

How was salmon installed (compiled, downloaded executable, through bioconda)?
bioconda

Which reference (e.g. transcriptome) was used?
To the best of my knowledge I followed the instructions in the tutorial at:
https://combine-lab.github.io/salmon/getting_started/

This describes where the data come from and how I invoked salmon.

Which read files were used?
See above.

Which which program options were used?
I used the bash script from
https://combine-lab.github.io/salmon/getting_started/

Expected behavior

I expected an output indicating successful quantification.

Screenshots

I couldn't figure out how to insert a picture, but here is the text from "terminal" window.
`(salmon) MacBook-Pro-2:salmon-tutorial brent$ bash quant_tut_samples.sh
Processing sample DRR016125
Version Info: Could not resolve upgrade information in the alotted time.
Check for upgrades manually at https://combine-lab.github.io/salmon

salmon (mapping-based) v0.11.3
[ program ] => salmon
[ command ] => quant
[ index ] => { athal_index }
[ libType ] => { A }
[ mates1 ] => { data/DRR016125/DRR016125_1.fastq.gz }
[ mates2 ] => { data/DRR016125/DRR016125_2.fastq.gz }
[ threads ] => { 8 }
[ output ] => { quants/DRR016125_quant }
Logs will be written to quants/DRR016125_quant/logs
[2018-11-24 15:08:09.785] [jointLog] [info] Fragment incompatibility prior below threshold. Incompatible fragments will be ignored.
[2018-11-24 15:08:09.785] [jointLog] [info] parsing read library format
[2018-11-24 15:08:09.785] [jointLog] [info] There is 1 library.
[2018-11-24 15:08:09.877] [jointLog] [info] Loading Quasi index
[2018-11-24 15:08:09.877] [jointLog] [info] Loading 32-bit quasi index
[2018-11-24 15:08:09.877] [stderrLog] [info] Loading Suffix Array
[2018-11-24 15:08:10.319] [stderrLog] [info] Loading Transcript Info
[2018-11-24 15:08:10.423] [stderrLog] [info] Loading Rank-Select Bit Array
[2018-11-24 15:08:10.432] [stderrLog] [info] There were 40,812 set bits in the bit array
[2018-11-24 15:08:10.435] [stderrLog] [info] Computing transcript lengths
[2018-11-24 15:08:10.435] [stderrLog] [info] Waiting to finish loading hash

quant_tut_samples.sh: line 2: 914 Segmentation fault: 11 salmon quant -i athal_index -l A -1 ${fn}/${samp}_1.fastq.gz -2 ${fn}/${samp}_2.fastq.gz -p 8 -o quants/${samp}_quant
(salmon) MacBook-Pro-2:salmon-tutorial brent$ `

Desktop (please complete the following information):

MacBook Pro (15-inch, 2016) macOS Sierra 10.12.6.

Additional context
I appreciate any help you can offer and I apologize in advance if there's something obvious I should have read or known about. (it seems like the lines below that are preceded by ### are coming out in fold face. They are not meant to.)

**Comment by rob-p** [comment]
Hi @michael-brent ,

  Did you, by any chance, install via bioconda?  There is a known issue with the bioconda build on OSX.  Can you try [this](https://github.com/COMBINE-lab/salmon/files/2383948/salmon_0.11.4-pre_OSX.tar.gz) pre-compiled binary in the meantime to see if it works for you?

**Comment by michael-brent** [comment]
Hi,

Yes, I did install with bioconda. Thanks for the link to the precompiled
version, which I downloaded and unzipped. I'm sorry to be so ignorant (my
unix knowledge is 25 years out of date) but how/where should I install
this?

Also, currently "which salmon" gives me the bioconda version. I guess I
will need to add the path to the precompiled version on the end of my PATH
environment variable?

Thanks,
Michael

**Comment by egreen2** [comment]
I am also running the same MacOS 10.12.6 and having a similar issue. I cannot get the provided binary to work either. I still get segmentation fault. The index seems to build but quantifying any samples is where I receive 'segmentation fault: 11'. Thanks for any advice.

**Comment by egreen2** [comment]
I can also upgrade my 10.12.6 Sierra to Mojave if you have a working binary for that. Let me know. Thanks so much.

**Comment by rob-p** [comment]
Hi @egreen2,

  Both @k3yavi and I have Mojave machines, so we could easily provide you with a binary that works on that version of MacOS (we use salmon on MacOS, on our laptops and desktops, regularly).

**Comment by egreen2** [comment]
That would be great. I will upgrade to Mojave now. I don't know if it is helpful, but the last binary of Salmon I could get to work on MacOS 10.12.6 was the provided Salmon-0.8.2_macOX_10.12.

**Comment by k3yavi** [comment]
Hi @egreen2 ,
I think the attached binary should work for MacOsx mojave
[Salmon-0.12.0.alpha_macOX_10.14.tar.gz](https://github.com/COMBINE-lab/salmon/files/2631346/Salmon-0.12.0.alpha_macOX_10.14.tar.gz)

**Comment by egreen2** [comment]
This is working perfectly. Thank you so much.

**Comment by k3yavi** [comment]
Glad to hear that. We'd recommend switching to bioconda version once ready, for future bug fixes and would let you know once it is ready.

**Comment by rob-p** [comment]
Hi @egreen2 --- just wanted to inform you that v0.12.0 has been released and is now also available via bioconda for both linux and osx.  The osx segfault issue has been resolved.
