### ISSUE TITLE
How to convert TPM to FPKM from Salmon output

### ISSUE THREAD

**Issue by HamletShaoE** [COMBINE-lab/salmon#32]
Hi, I really like salmon, it's really fast. Somehow I need FPKM rather than TPM. I got the output with 3 values out: Length, TPM and NumReads.
In RSEM, they have both length (which equal to the length I got from salmon and is an integer) and effective length (which is used for transition between FPKM and TPM).
It seems that effective length is the term used to calculate TPM and also for transition. Also, this effective length varies from sample to sample, hence I could not use that value from RSEM to make the transition. So what should I do, to get this effective length or just get the FPKM?

Thank you!

'
l_bar = \sum_i TPM_i / 10^6 * effective_length_i (i goes through every transcript),
FPKM_i = 10^3 / l_bar * TPM_i.
'

**Comment by rob-p** [comment]
Hi @HamletShaoE --- what version of Salmon are you using?  If you are using the latest version, in addition to the `quant.sf` file, there is a file in the output directory called `stats.tsv`.  The format of this file is a list of key-value pairs.  The first key-value pair lists the total number of observed fragments in the input (and can be ignored for your purposes).  Each subsequent line lists a transcript id followed by that transcript's computed effective length.  You can simply take these values and join them (in the database / data frame sense) with the main quantification results.

I should note that the next version of Salmon (v0.6.0), which should be out shortly, in addition to including a number of improvements and new features, will make these effective length values easier to get at --- they will appear in the main `quant.sf` file (versions compiled from the develop branch will already do this).  For the time being, however, the `stats.tsv` file is the place to get this info.

Finally, I'd mention that, though I don't know your use case, I'd be cautious of using FPKM any place that TPM might be used instead.  Within a sample, they are proportional (thus the equation you provide), but between samples, FPKM values have un-necessary variation based on the average lengths of the expressed transcripts in the samples; an arbitrary variation for which TPM corrects.

**Comment by xflicsu** [comment]
Hello ROB,
I got TPM and NumReads values from Salmon. Now, I will identify differential expression of 6 time points samples. Can I use NumReads directly to edgeR/DEseq2?

**Comment by rob-p** [comment]
Hi @xflicsu,

  Are you attempting to identify differential expression at the gene level, or at the transcript level?  If you want to use the NumReads values at the transcript level, you'll just need to round them to integers (as required by DEseq2 — I'm not sure if edgeR has this requirement or not).  If you want to do differential expression at the gene level, you'll need to aggregate the counts to the gene level.  The [tx-import](https://github.com/Bioconductor-mirror/tximport) package should make this relatively easy and painless, and can prepare the data directly for use with DEseq2 or edgeR.

**Comment by xflicsu** [comment]
Thanks for your response! I focus on both transcript level and gene level.
I have another question: I got low mapping rate (less than 20%) of tot-RNA-seq and Nascent-seq. So,  is it mean that Salmon is not suitable for pre-mRNA detection? How can I promote the mapping rate?

**Comment by vals** [comment]
@xflicsu Did you include "unspliced" transcript sequences in your reference? I could imagine your mapping rate goes down if you are not putting the intronic regions in the reference (so that intronic reads don't map)... You can get those unspliced transcript sequences e.g. from Ensembl BioMart.
