### ISSUE TITLE
error: segmentation fault

### ISSUE THREAD

**Issue by phickner** [COMBINE-lab/salmon#320]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

**Describe the bug**

**To Reproduce**
Steps and data to reproduce the behavior:

Specifically, please provide at least the following information:

  * Which version of salmon was used?
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
  * Which reference (e.g. transcriptome) was used?
  * Which read files were used?
  * Which which program options were used?

**Expected behavior**

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by Miserlou** [comment]
You forgot to include the bug report.

**Comment by Miserlou** [comment]
Did you find a repro for this?

**Comment by k3yavi** [comment]
ah @Miserlou , I think the tag was the confusion, removed that.
Thanks for the heads up, no we were not able to find the cause of this, since the report is incomplete.

**Comment by rob-p** [comment]
@Miserlou : I was assuming that this is actually the predecessor of #323, which is still open (@k3yavi, can we remove "fixed in latest release" tag, until we know?).

**Comment by k3yavi** [comment]
Yep done.

**Comment by rob-p** [comment]
@Miserlou : it's also worth noting that the error message preceding the segfault in #323 is coming from the library (libstaden) that we use to parse SAM/BAM files.  So, it's something where I think we will need a BAM that exhibits whatever triggers that behavior.
