### ISSUE TITLE
@RG lines are at odds with binary encoded reference data Segmentation fault

### ISSUE THREAD

**Issue by phickner** [COMBINE-lab/salmon#323]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

I am using a version that was compiled in Trinity
module load conda/trinity-2.8.4
source activate trinity-2.8.4
salmon --version salmon 0.11.3

**Describe the bug**

@RG lines are at odds with binary encoded reference data 
Segmentation fault

**To Reproduce**
Steps and data to reproduce the behavior:

salmon quant -t Cp_cds.fa -l ISR -a SB1.bam -o salmon_SB1

**Summary** 
I mapped the reads to a de novo transcriptome assembly using BWA-mem. I then use Salmon to get counts for RNAseq analysis using the alignment based mode. This has worked well for the nine previous samples, but the last 3 samples throw the error above (different species and reference transcriptome assembly). Maybe a problem with the bam file? If no not sure how the read groups etc, could be a problem unless there is a problem with the fastq files. But they came from the same run/machine/lane (Illumina NextSeq 500) as six other samples that have not caused problems.

**Comment by rob-p** [comment]
Hi @phickner,

  Do you have a sample data-set you could share that replicates the issue?  Salmon doesn't really use the `@rg` flag for anything, so I'd want to debug this by doing a backtrack and seeing what function is causing the segfault.

**Comment by rob-p** [comment]
Hi Paul,

  Can you try using [this](https://script.google.com/a/cs.stonybrook.edu/macros/s/AKfycbxXxZZzRrl0g6KFXNOqG9fworPhmFdGJeNvSsqNTA/exec) link to upload the files?  Maybe just zip up the bam and transcriptome together and upload that via the link?  Let me know if this works for you.

--Rob

**Comment by phickner** [comment]
Hi Rob,
I attached the transcriptome to the email. I am uploading the bam file to
the link you sent. It might take awhile. The attached transcriptome is
small because we are interested in only the chemoreceptor genes.


Paul

**Comment by rob-p** [comment]
Hi Paul,

  Did you reply to the github issue via e-mail and attach it there?  In that case, it won't show up.  If you post a response via the github interface, you can just drag and drop the file into the text box to have it uploaded.

**Comment by phickner** [comment]
Here is the reference genome. I'm uploading the bam file now. 
Thanks,
Paul 



[Cp_cds.txt](https://github.com/COMBINE-lab/salmon/files/2626378/Cp_cds.txt)

**Comment by phickner** [comment]
Attached is a screenshot, too. 
![screenshot](https://user-images.githubusercontent.com/16500958/49181719-174c8e00-f326-11e8-9c03-bce81af9dac9.png)

**Comment by rob-p** [comment]
Hi @phickner,

  Any update on this?  How does the BAM file look under ValidateSamFile or some such?

**Comment by phickner** [comment]
My issue was resolved. Thanks.
