### ISSUE TITLE
Can be fragment start position distribution be inferred with less than 5 million reads?

### ISSUE THREAD

**Issue by vals** [COMBINE-lab/salmon#33]
Are the results from inferring the fragment start distribution really bad for fewer reads?

The data I'm working on usually have ~1 million reads per sample.

**Comment by rob-p** [comment]
I haven't done too much testing with the quality of inferring the fragment start position distribution with few samples.  5 million is probably overkill, as it's a fairly low-dimensional model --- you could try setting the number of burnin fragments to a lower number.

**Comment by vals** [comment]
Is this the `--numAuxModelSamples` parameter?

**Comment by rob-p** [comment]
I would try and set both `--numAuxModelSamples` and `--numPreAuxModelSamples` to the same (lower) value --- maybe 100-200k.
