### ISSUE TITLE
Could not fetch RapMap during installation 

### ISSUE THREAD

**Issue by evofish** [COMBINE-lab/salmon#331]
Hello all, 

I really wish Salmon was easier to install. 

When running: 

_cmake -DFETCH_BOOST=TRUE -DCMAKE_INSTALL_PREFIX='/home/.../salmon-master/'_

I get the following message: 

_Making Release build
running /home/Documents/apps/salmon-master/scripts/fetchRapMap.sh 2>&1
/home/Documents/apps/salmon-master/scripts/fetchRapMap.sh: line 33: curl: command not found
-- fetch RAPMAP exit code 127

CMake Error at CMakeLists.txt:265 (message):
  Could not fetch RapMap source [fetchRapMap.sh returned exit code 127].

-- Configuring incomplete, errors occurred!
See also "/home/krablab/Documents/apps/salmon-master/CMakeFiles/CMakeOutput.log".
See also "/home/krablab/Documents/apps/salmon-master/CMakeFiles/CMakeError.log"._

This seems to be an issue that keeps coming up. What is the proper way to solve it? 
Thanks in advance

**Comment by rob-p** [comment]
Hi @evofish,

  Unless you jave a particular reason to build from source, it is much easier to install salmon via bioconda, or to simply download our pre-compiled executable from the releases page.  Nonetheless, your error stems from not having the `curl` program installed, which is used by the build system to automatically fetch all dependencies.

**Comment by evofish** [comment]
Thanks for the fast reply, after many tries I was able to install it with Bioconda.

**Comment by rob-p** [comment]
Sure, thanks for letting me know you were able to install via bioconda.  I'll try to make these build errors more informative.
