### ISSUE TITLE
salmon version message in sam file

### ISSUE THREAD

**Issue by red-plant** [COMBINE-lab/salmon#342]
Dear Dr. Patro and collaborators,
When using salmon with the --writeMappings option, and directioning the STDOUT to a file, the line "Version Info: This is the most recent version of salmon." ends up as the first in the sam file. Which is a shame because it takes quite some to re write the whole file for a single line. I tried the -q option but is not working.

**Comment by red-plant** [comment]
Dear Dr. Patro and collaborators,
When using salmon with the --writeMappings option, and directioning the STDOUT to a file, the line "Version Info: This is the most recent version of salmon." ends up as the first in the sam file. Which is a shame because it takes quite some to re write the whole file for a single line.  I tried the -q option but is not working.

**Comment by red-plant** [comment]
> can you try using `--no-version-check` ?

Thanks Avi,
Sorry for the silly bother.
Regards,
Jose.

**Comment by k3yavi** [comment]
No worries, glad it worked out.
