### ISSUE TITLE
Loading index exception

### ISSUE THREAD

**Issue by PhilPalmer** [COMBINE-lab/salmon#345]
## Describe the bug
When I run the following command:
```
salmon quant --threads 1 --libType=U -i index -r SRR493367.fastq.gz -o SRR493367
```

I get the following error(s) even though the same version of kallisto was used for the indexing & quantifiation:
```
Encountered exception [JSON Parsing failed - provided NVP (SeqHash512) not found] when loading index.
The index was likely build with an older (and incompatible) version of RapMap.  Please re-build the index with a compatible version.
```

## To Reproduce
- Install docker 
- Download transcriptome:
```
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_27/gencode.v27.transcripts.fa.gz
```
- Run docker container (warning 2GB):
```
docker run -v $PWD -w $PWD:$PWD -it lifebitai/rnaseq-nf-dseq2 bash
```
- Download reads (warning reads are 2.3GB:
```
fastq-dump SRR493367
```
- Index transcriptome:
```
salmon index --threads 1 -t gencode.v27.transcripts.fa.gz -i index
```
- Run quantification cmd above

<br />
Specifically, please provide at least the following information:

  * Which version of salmon was used? v0.12.0
  * How was salmon installed? Download precompliied binary and made Dockerfile with the following:
```Dockerfile
COPY ./salmon-0.12.0_linux_x86_64/bin /usr/local/bin
COPY ./salmon-0.12.0_linux_x86_64/lib /usr/local/lib

RUN chmod -R u+x /usr/local/bin

ENV PATH="$PATH:/usr/local/bin"
```
  * Which reference (e.g. transcriptome) was used? gencode.v27.transcripts.fa.gz
  * Which read files were used? SRR493367.fastq.gz
  * Which which program options were used? See above

I encountered this error when running this [Nextflow pipeline](https://github.com/PhilPalmer/RNASeq-nf-dseq2). More details can be found [here](https://deploit.lifebit.ai/public/jobs/5c6eca93758e8300a8740a59) 

Any ideas what the problem may be? I am not sure if it is a problem with my installation of Salmon, the [data](https://www.ncbi.nlm.nih.gov/sra/?term=SRR493367), the command or something else.

Any help would be much appreciated. 
Thanks in advance

**Comment by rob-p** [comment]
Hi @PhilPalmer,

Thanks for the detailed bug report.  In the index folder that is created, there should be a file called `header.json`.  Can you please paste the contents of that file here?  If it's not a version issue, then this issue can perhaps occur if there is a binary incompatibility between the place where the index was written and where it is being used; is this the same machine?

Thanks,
Rob

**Comment by PhilPalmer** [comment]
Hi @rob-p,

Thanks for the prompt response.

I think I may have realised my mistake. It seems like a silly mistake where I wasn't, in fact, using the same version of salmon for the indexing and quantification. 

Also yes they would have been running on different machines.

I will try to test this and get back to you.
Thanks again

**Comment by rob-p** [comment]
Was it a version issue?

**Comment by PhilPalmer** [comment]
@rob-p yes, I think it was a problem with the version
