### ISSUE TITLE
Why lower mapping rate with PE data than SE from same data set?

### ISSUE THREAD

**Issue by jdrnevich** [COMBINE-lab/salmon#349]
We were given some test data - ~400,000 150 PE on two samples from a MiSeq run on a mosquito. They wanted to know recommended sequencing depth and whether they needed 150 PE or if they could get away with 100 SE. There is a decent-ish genome and transcriptome for the species (https://www.ncbi.nlm.nih.gov/genome/?term=aedes+albopictus), so we ran the 150 PE and artificially created 100 SE from R1 through our pipeline, which includes STAR plus Salmon. The STAR results were expected: 100 SE had ~40% mulitmapping / ~48% unique in genes and 150 BP improved to ~30% multimapping / ~57% unique in genes. Surprisingly, Salmon showed the opposite: 100 SE had a ~70% mapping rate while 150 PE has only a ~57% mapping rate. 

We thought at first that Salmon maybe wasn't counting fragments if both ends didn't map but the answer in issue #31 says Salmon should be counting single-end mapped towards quantification. The first line in the salmon_quant.log file says "Fragment incompatibility prior below threshold.  Incompatible fragments will be ignored." I couldn't find much in salmon quant --help-reads about fragment priors and then I found it was in pretty much all salmon_quant.logs we have, so that may not be the problem. We also thought the trouble may have something to do with the small number of fragments, so we ran through some mouse 150 PE + artificial 100 SE, that had 40M reads and also subsampled to 400K reads, but the salmon mapping rates were pretty much the same (~75%) regardless of type/length of reads or sequencing depth.

So what do you think could be going on? I am worried that Salmon's "better" mapping percentage of 100 SE is not accurately measuring expression. We didn't test 150 SE because that is not a sequencing option with NovaSeq, but we could try it if you think it would help to figure out what is going on.

Thanks,
Jenny

**Comment by rob-p** [comment]
Hi Jenny,

  Would you be able to share a small sampled set of reads (the first few million) for both the 150 and 100bp datasets?  That way we could investigate the mapping statistics in more detail.  Also, could you provide the output quant directories, which would let us look some of the statistics that salmon dumps?

Thanks!
Rob

**Comment by jdrnevich** [comment]
Hi Rob,

Thanks for getting back so quickly. Let me verify with the PI that it is OK to share the data with you. These are tiny datasets already - only ~0.4 million reads. The tarball is about 200 MB. How shall I get it to you? I can put it on box.com and email you the link.

**Comment by rob-p** [comment]
> I can put it on box.com and email you the link.

That would be great :).

**Comment by jdrnevich** [comment]
Will do. One more question: "output quant directories" - just the quant.sf files, or the entire output directory per sample?

**Comment by rob-p** [comment]
The actual quant directory --- the most relevant information regarding mapping rate is actually in some of the metadata files (like meta_info.json and friends).

**Comment by rob-p** [comment]
Thanks again @jdrnevich for sharing the data for debugging purposes.  For anyone seeing similar behavior or following this issue, the resolution is as follows:

The mapping rate difference for between 100bp and 150bp reads (for both single-end and paired-end) becomes very small, and consistent with the "high" mapping rate of ~76-79% when using salmon v0.13.1 with `--validateMappings`.  Thus, the recommendation here (and in general) is to process the data using the latest version of salmon and ensuring to use the `--validateMappings` option.  Also, thanks to @jdrnevich for suggesting that the importance of this feature be highlighted in the documentation to the same extent it is in the release notes.
