### ISSUE TITLE
Alevin - annotate for RNA velocity (request)

### ISSUE THREAD

**Issue by caleblareau** [COMBINE-lab/salmon#353]
This would be super useful if you could pull it off... My sense would be that one could add an annotation in the bam tags and then quantify at the end of the computation... 

http://velocyto.org/

**Comment by roryk** [comment]
To do this you'd need to do whole genome alignments or otherwise align to genes with introns since the RNA velocity it looking at intronic counts to estimate the amount of pre-mRNA in the cell.

**Comment by k3yavi** [comment]
My apologies for the late reply. Please checkout our latest preprint [here](https://www.biorxiv.org/content/10.1101/2020.03.13.990069v1.full.pdf).
We explore the intricacies with generating unspliced counts and/or RNA velocity in detail .
