### ISSUE TITLE
Loading binary data with `alevin_df = parser.read_quants_bin('./salmon_folder')` is slow

### ISSUE THREAD

**Issue by Munfred** [COMBINE-lab/salmon#354]
Hi, I have noticed that when following the instructions (https://combine-lab.github.io/alevin-tutorial/2018/output-format/) for loading binary data it can sometimes be very slow.

I am using the command:
 `alevin_df = parser.read_quants_bin('./salmon_folder')`

However loading the raw output of a normal run with ~120k barcodes takes upwards of an hour. Is there another way to load the binary output?

Thanks

**Comment by k3yavi** [comment]
Hi @Munfred ,

Apologies for the delayed response.
Thanks for your very important question. We are aware of the problem and are extensively working on improving the downstream processing of the alevin output. Unfortunately, in current form there is no other direct way of loading alevin output matrix. We are thinking of alternative options like using `loompy` but it's a work in progress. We will definitely inform here once we have a simpler working version.

**Comment by k3yavi** [comment]
Hi @Munfred ,

Thanks for raising the issue. We have significantly modified the mapping algorithm and the output format of alevin in the latest release, the manuscript for changes in the mapping algorithm can be found in the [this](https://www.biorxiv.org/content/10.1101/657874v1) preprint. We have updated the relevant parsers in the python channel too. In practice we have observed significant difference in the size, although we think there is still room for improvement and we are working on improving it. Let us know how it works out for you.

**Comment by Munfred** [comment]
Thanks for the heads up!

**Comment by k3yavi** [comment]
The latest recommended way is through [tximport](https://github.com/mikelove/tximport). In case you need to check more benchmarks comparing different output format, please check [EDS](https://github.com/COMBINE-lab/EDS/blob/master/README.md). Closing this issue but feel free to reopen in case you still have problems.
