### ISSUE TITLE
Automatically infer read orientation

### ISSUE THREAD

**Issue by rob-p** [COMBINE-lab/salmon#36]
Suggested by @mdshw5: As is done by BWA-mem, use a small batch of reads to infer the most likely library orientation.  The user should also be able to explicitly provide the library type, which will by-pass the inference and impose the user's choice on the fragment compatibility function.

**Comment by mdshw5** [comment]
Sounds great. I like the idea of allowing the user to override this parameter selection as well...
cc @jmerkin

**Comment by jeremywzh** [comment]
It will be good to have this feature to automatically infer the most likely library type by downsampling. Waiting for this feature to be implemented!!!

**Comment by rob-p** [comment]
This is the behavior of the automatic `A` or `a` library type in 0.7.0.  So I think this issue / improvement is resolved.
