### ISSUE TITLE
Feature Request: check for gencode while creating index

### ISSUE THREAD

**Issue by alexvpickering** [COMBINE-lab/salmon#366]
This came up in #336

When building a gencode-based index with `salmon index` without the `--gencode` flag, the index that is generated won't work when subsequently running e.g. `salmon alevin`. This can be a pain to figure out the mistake (missing `--gencode` flag).

Perhaps some sort of quick grep of the index file name for `'gencode'` or within the file for multiple `'|'`s (used for gencode field separator but not ensembl) should be done to check if it's gencode followed by a warning/error if the --gencode flag is missing? Another possibility could be to just auto-detect if the index is gencode using the above tests, removing the need for the `--gencode` flag. Thank you

**Comment by k3yavi** [comment]
Thanks again @alexvpickering .
We have fixed this in the develop branch and it will be part of the salmon from the next release which we plan to release very soon.

**Comment by rob-p** [comment]
Now (since v0.14.0), the `index` command will issue a warning if you don't pass `--gencode` but the fasta being indexed looks to be gencode.
