### ISSUE TITLE
[Alevin] Question: should --mrna file only supply mtDNA genes or nuclear as well?

### ISSUE THREAD

**Issue by alexvpickering** [COMBINE-lab/salmon#367]
Thanks for the awesome tool!

Just wanted to confirm what the intended usage is as, for e.g. [scPipe](https://github.com/LuyiTian/scPipe) uses all mitochondrial genes in `calculate_QC_metrics` (whether from nuclear or mitchondrial DNA).

I am guessing that since the model for alevin is using the fraction of mitochondrial reads, the `--mrna` file should include only mtDNA (from mitochondrial genome) genes. It seems to be the case that nuclear mitochondrial genes are both up- and down-regulated with damage (**C**: *mtDNA*, *Mitochondria up*, *Mitochondria down* in figure below):

May also be a good idea to clarify in  `salmon alevin --help`.

![image](https://user-images.githubusercontent.com/15719520/58443291-f3d08900-80a5-11e9-82ef-0c7debd7ac2a.png)
[source](https://www.ncbi.nlm.nih.gov/pubmed/26887813)

**Comment by k3yavi** [comment]
Thanks for the kind word @alexvpickering and bringing this to our attention.
It does makes sense to have this clarified in alevin docs. We use `mRNA` for optional whitelisting at the end and you are right about aleivn using the fraction of reads from the mtRNA as a feature, so if the reads are both up and down regulated then the feature would not be very useful as it might cancel out the overall effect. May be we can use more fine grained at per gene level information as a feature but currently we have not put enough thoughts into it but we will clarify this in the alevin docs.

**Comment by k3yavi** [comment]
We have updated the docs. Thanks for the heads up . We are closing this issue for now,
