### ISSUE TITLE
nuclei/dronc-seq analysis

### ISSUE THREAD

**Issue by Acribbs** [COMBINE-lab/salmon#370]
A question regarding alevin.

I have dronc-seq and nuclei scRNA-seq data and I was wondering if it would be possible to analyse this data using alevin? I would expect that the majority of the transcripts would be pre-mRNA and therefore would have introns.

Would it be correct to 1) make a reference transcriptome from a GTF containing pre-mRNAs or 2) generate it from gtf of genes or 3) go back to relying on alignment based methods?

**Comment by k3yavi** [comment]
HI @Acribbs ,

Thanks for the very interesting question.
I think the first question in my mind is, do you need intron level deduplicated counts ? If yes, then sadly concatenating the pre-mrna sequence into the transcriptome sequences is probably not a good idea, as in general, the length of intronic sequences are much longer than that of exonic sequence and it may bias alevin deduplication algorithm. However, if you don't need the number of unspliced deduplicated counts and as the nuceli scRNA-seq has more pre-mRNA data if the question is regarding the aligning to genome v transcriptome then we just proposed a solution in our latest [preprint](https://www.biorxiv.org/content/10.1101/657874v1?rss=1). The new SA method is already integrated into salmon but you may have to index the genome+transcriptome using our scripts from [here](https://github.com/COMBINE-lab/SalmonTools).

Hope it helps !

**Comment by Acribbs** [comment]
Hi @k3yavi, very nice paper thanks for sharing!

Also, thank you for the information. I assume there is no umi deduplication/correction in the new SA method? This is what I really appreciate about alevin and I don't know if you are considering handling umi's in your new method?

**Comment by k3yavi** [comment]
Hi @Acribbs ,

Thanks for your kind words.
Basically, modularity is very important part of the whole salmon framework. Alignment and quantification are two separate module and they are all interconnected, so the optimizations in one is automatically propagated to another. As a result, the optimizations of SA done in the alignment stage got propagated to both alevin (single-cell) and salmon (bulk) RNA-seq quantification.

As a summary, from 0.14.0 onwards alevin can automatically utilize the benefits of SA if the reference is indexed following the scripts we shared in the SalmonTools repo.

Hope it answers your question.

**Comment by Acribbs** [comment]
Brilliant! This will be a great help! Thanks for your help, looking forward to trying this out. Will close this issue now.
