### ISSUE TITLE
Feature request: RefSeq datasets

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [COMBINE-lab/salmon#373]
Hi,

Sorry if this has been covered before, but is it possible to build a RefSeq based transcriptome and decoys. If this is not something you plan on doing, can you share the build requirements so I can build my own datasets please?

thanks

**Comment by k3yavi** [comment]
Hi @PeteCausey-Freeman ,

You can access the script and the requirements [here](https://github.com/COMBINE-lab/SalmonTools). Look for `generateDecoyTranscriptome`.

**Comment by PeteCausey-Freeman** [comment]
Brilliant. Thanks.

**Comment by k3yavi** [comment]
I think the issue is resolved here, closing it but feel free to reopen.
