### ISSUE TITLE
[Alevin] Question: output samples more than input.

### ISSUE THREAD

**Issue by hliu5259** [COMBINE-lab/salmon#375]
I followed the instruction to do deal will 9253 samples, however I got 10323 output in the matrix. 
Did anyone know the reason for that?

Bests,
Hongyu

**Comment by k3yavi** [comment]
Hi @hliu5259 ,
can you forward the log ?
There can be multiple reasons, did you gave external whitelist ? When you say 9253 samples do you mean 9253 cells ? How did you fix the number of cells ?

**Comment by hliu5259** [comment]
Hi, this is the log. I give the external whitelist which inculed 9185 barcodes.  
Yeah, I mean the 9253 cells. It comes from the output from the paper. 


Bests,
Hongyu

**Comment by k3yavi** [comment]
I think you forgot to attach the log file ?

**Comment by hliu5259** [comment]
I already attach the file. Can you see it right now?


Bests

**Comment by k3yavi** [comment]
Closing the issue due to relevant files are not provided, feel free reopen in case you still face any issue.
