### ISSUE TITLE
[Alevin] Feature Request: Quantify all CBs but still output standard whitelist

### ISSUE THREAD

**Issue by alexvpickering** [COMBINE-lab/salmon#377]
The use case is to allow using [SoupX](https://github.com/constantAmateur/SoupX) which removes ambient reads from cell lysis (the soup). Here is what SoupX does with cellranger output:

1) loads the .mtx file in the  `raw_gene_bc_matrices` directory output by cellranger as argument `tod` to `SoupX::SoupChannel`. 

2) Subsets this matrix to those in `barcodes.tsv` inside the `filtered_gene_bc_matrices` directory as the argument to `toc`.

It looks like to use SoupX with alevin would require quantification for all barcodes, not just those that pass the initial alevin whitelist. I guess I would need alevin to perform the initial whitelisting (to get the `toc` argument to `SoupX::SoupChannel`), but then ignore it and quantify all barcodes so that the `tod` matrix can be provided. The approach I am currently using:

1) Run `alevin --keepCBFraction 1 --maxNumBarcodes 4294967295` to get quants for all barcodes.

2) rerun alevin normally to get whitelisted cells (both from initial and final whitelisting)

It would be nice not to have to run alevin twice in order to achieve this result. Perhaps an option so that alevin could proceed to quantify all barcodes but still output a whitelist.

Thank you

**Comment by k3yavi** [comment]
I think this was fixed ? If not feel free to reopen.
