### ISSUE TITLE
[Alevin] fails to output quants_mat.mtx.gz when invoked with --dumpMtx --keepCBFraction 1

### ISSUE THREAD

**Issue by alexvpickering** [COMBINE-lab/salmon#379]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

alevin

**Describe the bug**
salmon alevin fails to output quants_mat.mtx.gz file when invoked with flags `-dumpMtx --keepCBFraction 1 --maxNumBarcodes 4294967295`

Specifically, please provide at least the following information:

  * Which version of salmon was used?
0.14.0
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
downloaded executable
  * Which reference (e.g. transcriptome) was used?
human_GENCODEv29.tar.gz with decoys from README

**Expected behavior**

Save a quants_mat.mtx.gz file

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.
![image](https://user-images.githubusercontent.com/15719520/59559081-16730500-8fb5-11e9-8bbd-faf2b99a02e7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version
```
uname -a
Linux desktop 4.15.0-51-generic #55~16.04.1-Ubuntu SMP Thu May 16 09:24:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

```
Related to #377

**Comment by k3yavi** [comment]
Hi @alexvpickering ,

Thanks for raising the issue. It seems #377 and #379 are connected .
Alevin is in fact suppose to output whitelist.txt file when provided with the flags you provided.
I think what's happening in your case is since `--keepCBFraction 1`, alevin is using all the CB for quantification and it couldn't find (any or very low) CB from the low confidence region needed for the whitelisting. 
Basically in the above screenshot, alevin never finished. It should have failed more gracefully, I'll make sure of that in the next release. In the meantime you can use the exit code 0 or "Finished Optimizer" log for successful finish. Also, try playing with the lower values for the `keepCBFracion` may be around (0.4 / 0.5) and `--freqThreshold` for changing the minimum frequency of a CB to consider, currently set to 10. You can also follow https://github.com/COMBINE-lab/salmon/issues/362 for more details.

**Comment by alexvpickering** [comment]
Hi @k3yavi,

I tried lowering `keepCBFraction` to 0.4 and `freqThreshold` to 0 but still failed to get a `.mtx` file produced. Again exited with `Done making feature Matrix`.

**Comment by k3yavi** [comment]
Is it possible for you to share the alevin log, then I can explain better the numbers ?

**Comment by alexvpickering** [comment]
[alevin.log](https://github.com/COMBINE-lab/salmon/files/3303575/alevin.log)
[salmon_quant.log](https://github.com/COMBINE-lab/salmon/files/3303576/salmon_quant.log)

**Comment by k3yavi** [comment]
okies, I think I see the issue. So look at the following lines in the log:
```
[2019-06-17 21:21:44.518] [alevinLog] [info] Total 824863
[2019-06-17 21:22:47.680] [alevinLog] [info] Total Unique barcodes found: 3474567
```
What it means is alevin found total: `3,474,567` unique CB in the whole sample and keeps `824,863` CB for further processing which is ~23% of the CB. So all the `keepCBFraction` values above 0.23 would have no effect. If you wan't to generate the `whitelist.txt`, alevin has to have some low confidence CB to learn from, so I am guessing in your case any value from 0.15-0.20 should ideally work. Having said that, I am still exploring why even setting `freqThreshold` to 0, alevin not considers all `3M` CB for processing, I guess there is some kind of filter which is coming into the picture but I might need a bit more time to explore that. I will update here once I figure it out.

Thanks again for raising the issue and investing your time in improving alevin.

**Comment by alexvpickering** [comment]
Thank you @k3yavi for all your help and for developing such a useful tool!

So in order to get counts for low-UMI barcodes I would have to do the following:

1) Determine the number of possible CBs that alevin can keep `--noQuant --keepCBFraction 1 --freqThreshold 0`

2) Re-run alevin with `--keepCBFraction` less than keep/total.

My understanding is that this will output a different whitelist than if I omit `--keepCBFraction` as it will assume all kept CBs are high quality? As such I would also have to:

3) Re-run alevin and omit `-keepCBFraction`.

**Comment by k3yavi** [comment]
A couple of question before you fix the pipeline to do this though: 
* In general what fraction of the CB does SoupX expects to have from 1-10 CB ?
* In our experience. a usual setup has <1% of the High confidence CB which alevin reports at the end. If you are keeping 10% of the CB then you already have >9% of the low quality stuff. I might have to read the SoupX paper again but I feel it's a lot of low quality data to begin with.
* Can you check what was the frequency of the last CB which was reported ? Because I do see
`Skipped 330862 barcodes due to No mapped read` in the log which mean even if there was >0 reads for the CB that doesn't map to the reference and alevin end up skipping it.

**Comment by k3yavi** [comment]
Oh 1 more thing, since you are going to use `whitelist.txt`. There was a bug I recently resolved, please try using the develop branch of salmon. you can get details from this issue https://github.com/COMBINE-lab/salmon/issues/374 .

**Comment by alexvpickering** [comment]
1) SoupX is generally working with the raw output from Cell Ranger. I beleive they use all 1-10CBs, and state something to the effect that the soup expression profile estimate is of good quality because there are such a large fractions of droplets in this range.

2) I see your point. Maybe the SoupX pipeline could be improved by using low count but high confidence CBs.

3) raw_cb_frequency.txt was also not written. Here is the last line of featureDump.txt (line 494,002):


| CB	| CorrectedReads	| MappedReads	| DeduplicatedReads |	MappingRate	| DedupRate	| MeanByMax |	NumGenesExpressed	| NumGenesOverMean	| mRnaFraction	| rRnaFraction	| ArborescenceCount |
| ------ |  ------ 	|  ------ 	|  ------  |	 ------ 	|  ------ 	|  ------  |	 ------ 	|  ------ 	|  ------ 	|  ------ 	|  ------  |
|AAAAATGGTTGCTCCT|	2	|1	|1	|0.5|	0|	1	|1|	0	|1	|0|	0|

Thanks for the heads up on `whitelist.txt`

**Comment by k3yavi** [comment]
Oki, so I have updated a couple of things in the latest commit on the develop branch, which should make the things more streamlined. 

* `maxNumBarcodes`: As you have initially used `maxNumBarcodes` which is by default set to 100k it means. by default alevin quantifies 100k CBs which includes both the low and high confidence CB count. You can change this number accordingly to set the universe of the top CB to quantify.
* `KeepCBFraction` : It defines what fraction of `maxNumBarcodes` to be used as the high confidence barcodes and should definitely generate the quants for. If set to 1 then everything is high confidence and the whitelisting cannot be performed. Thanks to this issue, alevin will not fail without error when there is no low confidence CB is found instead it checks if the number of low confidence CB is less than `lowRegionMinBarcodes` (default to 200), alevin will warn and not perform the whitelisting.
* `freqThreshold`: This is used to filter out most obvious cases to filter out CB with frequency less than set by the parameter (default to 10).

Hope this help ! I am also testing on my end for any other potential bug. Please let me know if you get a chance to check the develop branch .

**Comment by alexvpickering** [comment]
Thanks @k3yavi - building the `develop` branch currently and will let you know if I encounter any issues.

I thought of another approach to obtain at least a sample of 1-10UMI CBs:

 - Run alevin with standard options, then parse `raw_cb_frequency.txt` for a sample of 1-10UMI CBs and using them as input to `--whitelist` option for additional run of alevin with `--freqThreshold 0 --maxNumBarcodes 4294967295`

`--whitelist`:

> This is an optional argument, where user can explicitly specify the whitelist CB to use for cell detection and CB sequence correction. If not given, alevin generates its own set of putative CBs.

I did the above and everything completed fine. I took a sample of 50,000 1-10UMI CBs of which ~30,000 ended up in `quants_mat.mtx.gz`  (I'm assuming the difference is because of CB equivalence relationships within the supplied whitelist). Of these, ~50% had counts <= 10 (I'm assuming those with more counts had CB equivalence relationships across all CBs for which they were assigned reads).

Does the above approach seem reasonable?

**Comment by k3yavi** [comment]
Yep that sounds reasonable to me.
In case you wan't to avoid multiple round of alevin runs, the idea in the develop branch is to use `--freqThreshold 0 --maxNumBarcodes 4294967295 --keepCBFraction 0.95` i.e. maxNumBarcodes is almost infinity which will force alevin to consider all CB for processing while keeping 95% of the CB as high confidence and hopefully the last 5% would be `>200` CBs which will make alevin run whitelisting.

Thanks again for testing alevin and its features !

**Comment by alexvpickering** [comment]
Ah okay that would be awesome to be able to accomplish that in one run. 

My worry was that by using `--keepCBFraction 0.95` (which I believe gets translated into '--forceCells` value) I wouldn't get the same `whitelist.txt` output (aka the ~1500 cells based on the knee finding then final naive bayes QC) because I am essentially telling alevin to consider the majority of CBs as whitelisted. Is that not the case?

**Comment by k3yavi** [comment]
Oh yes, that's correct. lol it's funny although makes me glad, that you know more about alevin than me!
You are right, that will essentially force alevin to use top 95% of the cells as the high confidence which is not always desirable. I am still thinking how can we make the whole ecosystem better so that user don't have to go through all this customizations. Do you have any thoughts about that ?

**Comment by alexvpickering** [comment]
Hard to say - I definitely don't know the code base or algorithm details better than you. The thing that jumps to mind is separation of finding equivalent CBs/quantification and whitelisting. For example:

1) `salmon alevin --quantifyAll`: could do no whitelisting (knee or otherwise) and output a sparse matrix of counts for all CBs (binning counts by equivalences).

2) `salmon alevin --runQC --rrna path/to/rrna.txt --mrna path/to/mrna.txt path/to/quants_mat.gz`: could just do whitelisting via whatever combination of knee and/or NB modelling on the counts from `1)`. 

I think you're much better positioned to know if the above makes sense or is reasonable. One advantage of separating CB mapping/quantification and whitelisting is that it would be relatively straightforward to run automatic cell QC filtering from the output of kallisto or Cell Ranger. There seems to be a definite lack of automation in this area (only other thing I have come across is [`cellity`](https://bioconductor.org/packages/release/bioc/html/cellity.html) which seems to be more hands on).

**Comment by k3yavi** [comment]
Actually that's a very nice idea! Thanks for sharing it. If we can modularize it into multiple independent components that would reduce the overall complexity and might help differentiate the use cases. I'll definitely raise this in our next alevin meeting. Although, it might take some time to get back regarding this but I will poke back here once we have some progress.

Thanks again !

**Comment by k3yavi** [comment]
I think the issue here is resolved, but feel free to reopen if you have any issues.

**Comment by deevdevil88** [comment]
H1, while this issue was solved, im just a bit confused, if i want to generate a quant matrix of all CBS including those in the range of 1-10 reads, how do i do this in the most streamlined way. As there has been a lot of discussion about this and many release of alevin since then.

Will using FreqThreshold 0 --maxNumBarcodes 4294967295 do the trick? or do i also need to use --KeepCBFraction 1.0
