### ISSUE TITLE
Feature tags in 10Xv3?

### ISSUE THREAD

**Issue by pinin4fjords** [COMBINE-lab/salmon#381]
Really simple question: can Alevin deal with the additional feature tags possible from 10Xv3? If not, will it at some point?

**Comment by k3yavi** [comment]
Hi @pinin4fjords ,

Thanks for the question, do you mean the longer UMI/CB length or you are talking about some other feature ?

**Comment by pinin4fjords** [comment]
I mean the additional barcodes you can get with this protocol if people use CITE-seq like approaches, see https://www.10xgenomics.com/solutions/single-cell/. 

On 18 June 2019 23:53:55 BST, Avi Srivastava <notifications@github.com> wrote:
>Hi @pinin4fjords ,
>
>Thanks for the question, do you mean the longer UMI/CB length or you
>are talking about some other feature ?
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/COMBINE-lab/salmon/issues/381#issuecomment-503341361

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by k3yavi** [comment]
Hi @pinin4fjords ,

It took a while but I just wanted to let you know that alevin can now process the feature barcodes.
Please checkout the following tutorial for more step-by-step process
https://combine-lab.github.io/alevin-tutorial/2020/alevin-features/
