### ISSUE TITLE
Pre-computed Decoy Transcriptomes from Model Organisms

### ISSUE THREAD

**Issue by tamuanand** [COMBINE-lab/salmon#385]
If it is possible, it would be a good idea to have pre-computed decoy transcriptomes from different model organisms

- rat
- arabidopsis
- bovine
- fly
- honeybee
- yeast
- soybean

**Comment by k3yavi** [comment]
Hi @tamuanand ,

The decoy sequence for these organism based on ensembl sequence and annotation can be found [here](http://bit.ly/30yn3FJ).

**Comment by tamuanand** [comment]
@k3yavi  Thanks a lot
