### ISSUE TITLE
Salmon requires g++ 5.2 or higher - Version unrecognised while cmaking

### ISSUE THREAD

**Issue by TizianaS92** [COMBINE-lab/salmon#388]
Hello, I'm trying to install Salmon on my CentOS 7 system, as suggested here:
https://salmon.readthedocs.io/en/latest/building.html#installation

I decided to get the cmake `-DFETCH_BOOST=TRUE` option, in spite of having installed Boost. 
I get this error (here is the full log):

`cmake -DFETCH_BOOST=TRUE`

> Salmon requires g++ 5.2 or greater.

https://pastebin.com/UmVJw0Ae

This is particularly odd.
I have installed a recent GCC version and even rebuilt Boost after it...

As you can see, if I type 

> gcc --version
> g++ --version

By root and user, I always get...

> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

and 

> g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

On another tutorial, I found that I should open a bash instead while installing gcc/g++, with the instruction:

`scl enable devtoolset-7 bash`

When I run 

> gcc --version
> g++ --version

By root and user, this time the proper version is recognised!

> gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

and

> g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

As you can see, this time the latest version is recognised. I'm quite sure the bash was open even when I rebuilt Boost...

But even though I re-open the bash before cmaking Salmon, it will always complain about an outdated version, having it opened or not won't make any difference.

I'm also attaching the log files generated by Salmon:

CMakeCache.txt => https://pastebin.com/shdCpDde
CMakeLists.txt => https://pastebin.com/16AeRnyL

Also, while installing Boost, I got this:

> 
> The following directory should be added to linker library paths:
> 
>     /mnt/d8e73111-db5e-4011-87aa-e4d64fb8c1e9/DATA/Software/boost/boost_1_70_0/stage/lib

What could the problem be? Why can't it recognise the right version? Did I mess up with anything? Thanks in advance!

**Comment by rob-p** [comment]
Hi @TizianaS92,

  One problem is that CMake is rather annoying with caching environment variables and versions.  Could you see what happens if you `rm -fr` your `build` directory and then try again (this will obliterate `CMakeCache.txt` and the `CMakeFiles` subdirectory.

**Comment by TizianaS92** [comment]
Thank you for your answer!
I re-built everything and it worked.
