### ISSUE TITLE
Cannot quantify transcripts with transcriptome bam and transcripts sequence files

### ISSUE THREAD

**Issue by Sylarair** [COMBINE-lab/salmon#394]
Hi! I am facing a problem when I try to use salmon quant to quantify transcripts.

The command is:
 `gffread -w hg19.genome_annotation.fa -g hg19.fa gencode.v19.chr_patch_hapl_scaff.annotation.gtf`
 `salmon quant -t hg19.genome_annotation.fa -l a -a HepG2_rep1.bam -o HepG2_quant`

The two files contents are like this:

<img width="632" alt="Screen Shot 2019-07-08 at 5 48 27 PM" src="https://user-images.githubusercontent.com/18133362/60844893-b3861f80-a1a8-11e9-89c4-afc7b179c1af.png">

<img width="712" alt="Screen Shot 2019-07-08 at 5 48 54 PM" src="https://user-images.githubusercontent.com/18133362/60844896-b719a680-a1a8-11e9-9b6d-3ec4c0e30bf6.png">

But I didn't get any quantification results, the running results are here.

<img width="700" alt="Screen Shot 2019-07-08 at 7 12 57 PM" src="https://user-images.githubusercontent.com/18133362/60848393-6c9e2700-a1b4-11e9-8067-3014763206ea.png">

Could anyone help me with this? Many thanks!

**Comment by tamuanand** [comment]
Hi @Sylarair 

I think there is a typo with your libtype argument - i think it should be uppercase 'a'

like this: `-l A`

**Comment by Sylarair** [comment]
Hi @tamuanand 

Thanks for your reply. Your suggestion is right, and it should be '-l A'. I also figure out that the main cause of my problem is due to the incorrect gtf annotation file choose, and further the incomplete match of transcripts name between hg19.genome_annotation.fa and bam.
