### ISSUE TITLE
Documentation: Add Alevin-specific references to Alevin readthedocs

### ISSUE THREAD

**Issue by robertamezquita** [COMBINE-lab/salmon#395]
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1670-y

Just to make it that much easier to cite :)

**Comment by k3yavi** [comment]
Nice catch Robert ! I'll updat the doc.

**Comment by k3yavi** [comment]
I've updated the doc and it should me available with the next release or the docs from the develop branch. Thanks again.
