### ISSUE TITLE
Aggregating salmon results with tximport doesn't work for C. elegans

### ISSUE THREAD

**Issue by bzpola** [COMBINE-lab/salmon#397]
the bug primarily related to salmon (bulk mode) 

The output from Salmon when running fastq samples from the worm C. elegans and the transcription file (Caenorhabditis_elegans.WBcel235.cdna.all.fa.gz) results in transcript names that are different from that that are found in the tx2gene that is usually used.
For example  - Salmon gives TPMS for the gene "F54D7.7", but in all C. elegans related databases, the gene is referred to as "F54D7.7.1". The option of ignoring transcript version is not helping since it cuts it to F54D7 (gets rid of the .7.1, while the .7 is informative).
I understand this is a result from the mis-match between the cDNA file and the tx2gene (made from Ensembl), but this is something that I thought would have a rigorous solution. any advice please?

Thanks

**Comment by mikelove** [comment]
You can just edit the extra ID (which isn’t in the FASTA) from the tx2gene table. For more details feel free to post with code to the Bioc support site.
