### ISSUE TITLE
Options when aligning to decoy and transcriptome

### ISSUE THREAD

**Issue by jckhearn** [COMBINE-lab/salmon#399]
Hi,

I just wanted to check if I'm following the documentation correctly. I have created a decoy-aware index and want to run salmon (v0.14.1) with the following options:

`salmon quant --dumpEq --validateMappings --rangeFactorizationBins 4 -l A -i $index --seqBias --gcBias -p 40 --geneMap $genemap -o $1.quants.25 -1 $read1 -2 $read2`

I am confused as to whether the documentation (https://salmon.readthedocs.io/en/latest/salmon.html) is recommending to combine "--validateMappings"  with "--mimicBT2" or "--mimicStrictBT2" or not. Secondly, selective mapping is now highly recommended in conjunction with a decoy-aware transcriptome in the first note, but a later note states:  

"For the time being, if you wish to quantify using quasi-mapping, you should not build a decoy-augmented index."

Given the above command should I go back to a non-decoy aware transcriptome? 

Thank you for any help and clarifications!

**Comment by rob-p** [comment]
Hi @jckhearn,

  The documentation could definitely be more clear, so let me try and clarify here and make a note to clean up the documentation more as well.  I'll answer in reverse order:

> Given the above command should I go back to a non-decoy aware transcriptome?

No.  What the statement in the documentation means to convey is that if you are using the basic quasi-mapping algorithm (not selective-alignment as enabled by `--validateMappings`,  `--mimicBT2` or `--mimicStrictBT2`), then you should not be using a decoy-aware transcriptome.  We have not tested the effect of decoys on the basic quasi-mapping approach, and though that may be supported in the future, it is not right now.  However, if you are using any flavor of selective-alignment, then please _do_ use the decoy-aware transcriptome.  

Regarding "combining" `--validateMappings`,  `--mimicBT2` and `--mimicStrictBT2`, this is not possible.  That is, you should view `--mimicBT2` and `--mimicStrictBT2` as "meta-flags" that enable selective-alignment and also set a few other options that are meant to mimic the BT2 behavior more closely.  We generally do _not_ recommend `--mimicStrictBT2`, and so the main choice is between simply using `--validateMappings` vs. `--mimicBT2`.  The main differences here are that `--mimicBT2` sets slightly more sensitive parameters to find alignments, but is also stricter in what it reports.  The biggest differences is that `--validateMappings` will allow orphaned mappings (where one end of a paired-end fragment aligns but the mate doesn't), while `--mimicBT2` will not allow such mappings.

--Rob

**Comment by jckhearn** [comment]
Perfect! Thanks for the in-depth explanations.
Jack
