### ISSUE TITLE
Alevin -single cell mode

### ISSUE THREAD

**Issue by shivagit123** [COMBINE-lab/salmon#407]
alevin (single-cell mode)

**Describe the bug**
Getting error " Size of the feature file doesn't match" in the log file while starting to make feature Matrix

Latest version of Salmon was used

**Comment by k3yavi** [comment]
Hi, is it possible to share the logs and the minimal version of the data on which we can replicate the bug?

**Comment by shivagit123** [comment]
Hi, this got rectified by using ENSEMBL gene ids rather than gene symbol/gene names.
Other issues are : none of my mitochondrial and ribosomal gene lists are able to find in the reference index.
The log file attached:
[alevin.log](https://github.com/COMBINE-lab/salmon/files/3430327/alevin.log)
The index reference genome is from gencodeV31.pc.transcripts.fa.gz from gencode human
The txptogene contains list of ENST* -- > ENSG*

**Comment by k3yavi** [comment]
Hi @shivagit123 ,

can you share the list of the Mitochondrial and Ribosomal genes you are giving to alevin ?

**Comment by shivagit123** [comment]
I've attached the list . They are ensembl ids.
[human_EnsemblG_mitochondrion_geneset.txt](https://github.com/COMBINE-lab/salmon/files/3444417/human_EnsemblG_mitochondrion_geneset.txt)

[human_EnsemblG_ribosomal_geneset.txt](https://github.com/COMBINE-lab/salmon/files/3444418/human_EnsemblG_ribosomal_geneset.txt)

**Comment by k3yavi** [comment]
Ok so it seems these lists have subversions after the gene names like `ENSG*.1` can you check if the transcript and gene names in your reference also have the sub versions ?

**Comment by shivagit123** [comment]
Yes, I do have names with versions in the reference (gencode db)- gencode.v31.pc_transcripts.fa.gz.

**Comment by k3yavi** [comment]
Hi @shivagit123 , are you working on Windows ? or at least the mrna and ribo rna files you forwarded are `dos` formatted. If you convert their carriage return to unix format alevin will start to recognize the gene ids. Unfortunately we do not support windows based file format in salmon ecosystem.

**Comment by shivagit123** [comment]
Thanks .It works now
