### ISSUE TITLE
Getting quants for transcript ids in alevin

### ISSUE THREAD

**Issue by mkarikom** [COMBINE-lab/salmon#409]
Is there a way to have alevin give me quantification of mapped transcript ids, as salmon normally would for bulk data?

**Comment by k3yavi** [comment]
Hi @mkarikom ,

Thanks for your question.
Short answer is alevin won't quantify at transcript level .
Long answer: Alevin is designed to work with 3'-end single cell data. One of the inherent problem with the 3' data is as the reads are coming from only one end of the mRNA molecule it's difficulty to resolve the mapping of read at per transcript level, the problem gets even more difficult as the 3' data is usually SE. Also at single cell level even the depth of sequencing ( per cell level ) is very low the information is not enough to quantify at transcript level with good confidence, hence alevin quantifies the single-cell data at per-gene level.

Hope it helps !
