### ISSUE TITLE
Alevin for Quartz-Seq2

### ISSUE THREAD

**Issue by dritoshi** [COMBINE-lab/salmon#416]
Dear alevin team,

I am a developer of Quartz-Seq2 ([Sasagawa Y. et al. Genome Biol. 2018](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1407-3); [Mereu E. et al. bioRxiv](https://www.biorxiv.org/content/10.1101/630087v1)), one of 3’ tagged-end single-cell RNA sequencing. Could you add `Rule` of Quartz-Seq2 protocol to SingleCellProtocols.hpp?

```
    struct QuartzSeq2v31 : Rule{
      //Quartz-Seq2 v3.1 starts from 5 end with 14 length
      //barcode and 8 length umi & iupac can be
      //changed
      QuartzSeq2v31(): Rule(14, 8, BarcodeEnd::FIVE, 268435456){}
    };

    struct QuartzSeq2v32 : Rule{
      //Quartz-Seq2 v3.2 starts from 5 end with 15 length
      //barcode and 8 length umi & iupac can be
      //changed
      QuartzSeq2v32(): Rule(15, 8, BarcodeEnd::FIVE, 1073741824){}
    };
```

Best,
Itoshi

**Comment by k3yavi** [comment]
Hi @dritoshi ,

Thanks for your request. I'd be happy to add the support for Quartz-seq2 into alevin but it'd be great if you can answer a few questions for us. Is it possible to share some reads/fastq file on which we can test alevin ? Also, please excuse my ignorance, what type of PCR amplification is performed in `Quartz-seq2` protocol, is it CelSeq type IVT (linear) amplification or Drop-Seq type template switching PCR amplification ?

**Comment by dritoshi** [comment]
Hi @k3yavi,

Thank you very much for your prompt reply. Quartz-Seq2 uses PCA-based amplification and poly-A tailing reaction instead of template switching for tagging PCR primer site on 3'-end of the first-strand cDNA and 5'-end second-strand cDNA. Sequencing library structure of Quartz-Seq2 is very similar to Drop-Seq and chromium. Length of cell barcode is 14 bases (version 3.1) or 15 bases (version 3.2). UMI length is 8 bases. Cell barcode and UMI include Read1. Transcript sequences contain Read2.

I would like to share whitelists and reads of Quartz-Seq2.

* [Whitelist for Quartz-Seq2 (v3.1)](https://www.dropbox.com/s/dbxzb1jkobmhqfn/CellBarcode_QuartzSeq2_v31.txt?dl=0)
* [Whitelist for Quartz-Seq2 (v3.2)](https://www.dropbox.com/s/3ixygi7556sg6h2/CellBarcode_QuartzSeq2_v32.txt?dl=0)
* [SRA file](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2656450)
* [FASTQ file](https://www.ebi.ac.uk/ena/data/view/SRX2899963)

Fig. 1. Overview of Quartz-Seq2 experimental processes. ([Sasagawa Y. et al. 2018](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1407-3))
![image](https://user-images.githubusercontent.com/33778/63138048-cbf12180-c013-11e9-8528-90d17356c2a6.png)

**Comment by k3yavi** [comment]
Thanks @dritoshi for the data and info. Let me play a bit with the data over the weekend. It should be very straightforward to add but I might have to check some unit test. I'll keep you updated.

**Comment by k3yavi** [comment]
Hi @dritoshi ,

As per your request I've added the support for Quartz-seq2 data in the alevin framework with https://github.com/COMBINE-lab/salmon/commit/f6905b1d1dc6cf6bc4597927ad3be637ba615c9a and should be available with next salmon release. Currently the develop branch has to be compile from source to use the following command line argument.
![image](https://user-images.githubusercontent.com/8772521/63282768-8df73600-c27d-11e9-832d-f4a1232f17f6.png)

Currently I just have on flag i.e. quartzseq2 which assumes 15 length CB and 8 length UMI. Unfortunately adding multiple versioned is gonna be little complicated as I might have to discuss with the alevin team and that might take some time. As you can check through the new code through the commit (linked above) adding just the Rule of new protocol is not enough and we might have to add some helper code with each new protocol which increases the redundancy in the code. Currently we are in the process of figuring out a better way to handle new protocols.
Having said that it should not stop users from using alevin with previous version of quartzseq2, you can use the following command line triplet as `--end 5 --barcodeLength 14 --umiLength 8` along with you other alevin flag and it's gonna behave just like `QuartzSeq2v31` you specified above.

If possible, It'd be great if you can share some of the results you get while comparing Quartz-seq2 pipeline with alevin.

Hope this helps !

**Comment by dritoshi** [comment]
Thank you so much! We are going to use the new version. Of course, we will share you some results of comparing Q2 pipeline with Alevin. We usually used the drop-seq pipeline.

**Comment by k3yavi** [comment]
Sounds good, just wanted to give you the heads up, as we are working on some other part of the salmon pipeline, currently I can't give you an ETA when would the new version of salmon be available. If For the time being the choice are either you can compile the develop branch of salmon or I can forward you a linux usable salmon binary.

**Comment by dritoshi** [comment]
Could you send me a Linux unstable salmon binary?

**Comment by dritoshi** [comment]
Thank you very much!

**Comment by k3yavi** [comment]
It's now available in latest stable release, closing the issue but feel free to reopen if you have any issues.

**Comment by dritoshi** [comment]
I'm sorry my late response. I will check the latest stable release. I will contact you if we find any problems. Thanks!
