### ISSUE TITLE
Strand bias is very high

### ISSUE THREAD

**Issue by thu1911** [COMBINE-lab/salmon#422]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon
**Describe the bug**
I used the default parameters to run salmon on mouse sample. But I got the warning:

`Detected a *potential* strand bias > 1% in an unstranded protocol check the file:`

**To Reproduce**
`"expected_format": "IU",
    "compatible_fragment_ratio": 1.0,
    "num_compatible_fragments": 10869138,
    "num_assigned_fragments": 10869138,
    "num_frags_with_concordant_consistent_mappings": 10212463,
    "num_frags_with_inconsistent_or_orphan_mappings": 1088473,
    "strand_mapping_bias": 0.5258466052704426,
    "MSF": 0,
    "OSF": 0,
    "ISF": 4842274,
    "MSR": 0,
    "OSR": 0,
    "ISR": 5370189,
    "SF": 593930,
    "SR": 494543,
    "MU": 0,
    "OU": 0,
    "IU": 0,
    "U": 0`

Specifically, please provide at least the following information:

  * Which version of salmon was used?    
"salmon_version": "0.14.1"

  * How was salmon installed (compiled, downloaded executable, through bioconda)?  bioconda

  * Which reference (e.g. transcriptome) was used?
gencode mouse VM22

  * Which read files were used?

Downloaded from sra（Just ordinary Illumina reads)

  * Which which program options were used?

```
salmon quant -i $mm10_whole_index -l A \
    -1 $fastq1 \
    -2 $fastq2 \
    -p 20 --validateMappings -o $output_whole
```

**Expected behavior**
Why Strand bias is very high?

**Desktop (please complete the following information):**
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rob-p** [comment]
Hi @thu1911,

  The strand bias here is actually quite moderate.  The calibration of `strand_bias` is such that a value of 0.5 means there is no bias (i.e. half of the fragments start with read 1 on the forward strand and half start with read 1 on the reverse complement strand).  Your value is `"strand_mapping_bias": 0.5258466052704426`, so you are pretty close to the ideal value of 0.5, though there is a _slight_ bias in the data.  I wouldn't be concerned about this assuming you were assuming an unstranded protocol.

Best,
Rob

**Comment by thu1911** [comment]
> Hi @thu1911,
> 
> The strand bias here is actually quite moderate. The calibration of `strand_bias` is such that a value of 0.5 means there is no bias (i.e. half of the fragments start with read 1 on the forward strand and half start with read 1 on the reverse complement strand). Your value is `"strand_mapping_bias": 0.5258466052704426`, so you are pretty close to the ideal value of 0.5, though there is a _slight_ bias in the data. I wouldn't be concerned about this assuming you were assuming an unstranded protocol.
> 
> Best,
> Rob

Thank you for help. I thought it should be around 0 when worked with unstranded protocols. Thank you for reply.
