### ISSUE TITLE
Alevin with single-cell RNA Barcoding sequencing (SCRB-seq) data

### ISSUE THREAD

**Issue by rcosentino** [COMBINE-lab/salmon#429]
Hi Salmon Team,

I have single-cell sequencing data generated with an approach derived from SCRB-seq approach (https://www.nature.com/articles/s41467-018-05347-6). The data looks more less like Drop-Seq or 10x genomics, 1st read contains the Barcode (first 6 bases) and the UMI (next 10 bases) and the second read contains the sequence. I am posting a few reads as example:
1st read:
```
@L183:482:CD3CPANXX:3:1207:1245:2065 1:N:0:0
NAGTCAGCAATACCCT
+
#<=?B=FGGBGGGEFG
@L183:482:CD3CPANXX:3:1207:1351:2052 1:N:0:0
NCGGAGAGTGCAGTGT
+
#<=BAGGGGGGGGGGG
```

2nd read:
```
@L183:482:CD3CPANXX:3:1207:1245:2065 3:N:0:0
ATGTACGATATGGAAAGCGTGGGTAGAGTTTTTTATTTTTACACGTGTAG
+
BBBBBE;F0E/FGCF>D1E=>/AGGGGGEGGGGGF>1=FEGGGGGGGG>E
@L183:482:CD3CPANXX:3:1207:1351:2052 3:N:0:0
CATGCATACTCTCATACGCAAATAAAAAAGTAAAAAGAAACAAAGACAGA
+
@BB@0FGG@CFGGCFFG>G;>/@>@DFEDDFGD@GGGEGGGGGGGGGGGG

```

 I made trial runs with the `--dropseq` or `--chromium` settings, it kind of ran through but the resulting matrix is empty.. probably because the expected barcode and UMI structure is different or not?... do you think it can be easily changed or that I could set that information as input?

Best,

Raúl

**Comment by k3yavi** [comment]
Yep try --end 5 --umiLength 6 --barcodeLength 10

**Comment by rcosentino** [comment]
Thanks!
