### ISSUE TITLE
Allocation error building pufferfish index using v0.99.0 beta1

### ISSUE THREAD

**Issue by mdshw5** [COMBINE-lab/salmon#432]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
Both likely.
**Describe the bug**
Trying to build the new pufferfish index format, I receive a memory allocation error near the end of the index build process.

**To Reproduce**
Steps and data to reproduce the behavior:

Specifically, please provide at least the following information:

  * Which version of salmon was used?
 v0.99.0 beta1
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
Downloaded from Github release
  * Which reference (e.g. transcriptome) was used?
gencode v25 with some "extra" stuff added - mainly introns for each unprocessed transcript.
  * Which read files were used?
None
  * Which which program options were used?
-p 8 (though I've used the default as well)

**Expected behavior**
I expected the indexing process to complete.

**Screenshots**
[pisces_bug.log](https://github.com/COMBINE-lab/salmon/files/3692191/pisces_bug.log)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version RHEL7
**Additional context**

I'm attempting to build an index that's quite large, and am very excited to try the new pufferfish  graph-based index. Please let me know how I can help out - if it would be useful I can try to build the index using your standalone library as well.

**Comment by mdshw5** [comment]
The relevant parts of the log are here:
```
[2019-10-04 10:37:22.243] [ff::console] [warning] Removed 89618 transcripts that were sequence duplicates of indexed transcripts.
[2019-10-04 10:37:22.243] [ff::console] [warning] If you wish to retain duplicate transcripts, please use the `--keepDuplicates` flag
[2019-10-04 10:37:22.318] [ff::console] [info] Replaced 1,775,734,603 non-ATCG nucleotides
[2019-10-04 10:37:22.318] [ff::console] [info] Clipped poly-A tails from 422 transcripts
wrote 593292 cleaned references
seqHash 256 : bd425816a78195ed31cf17ce9df99c2bf56bff98f0df5ace1e958b263d805390
seqHash 512 : 845b625de6f8f018796e464f7c49f6596d2b31b28a58771d56ece24b3d9cad98b8189572ff43d6a3eb8ef24b5d3bc5ac0f89845a57e3682498a56a1bc920e7b7
nameHash 256 : 3bd11eac1e6b05e93689676ca056c165e7c26723c4b137fd284bb8b40ef5df62
nameHash 512 : e68449cfd99f5968182735275b00779b8a396e413a3629beef933e51bd18902c821c26e2a5461c687d023ef85168e58d76bacd5fe1f0a3111bfccc34af9c4035
[2019-10-04 10:37:37.931] [console] [info] Filter size not provided; estimating from number of distinct k-mers
[2019-10-04 10:38:33.012] [console] [info] ntHll estimated 2765935300 distinct k-mers, setting filter size to 2^36
Threads = 8
Vertex length = 31
Hash functions = 5
Filter size = 68719476736
Capacity = 2
Files:
test_pufferfish_index/ref_k31_fixed.fa
--------------------------------------------------------------------------------
Round 0, 0:68719476736
Pass    Filling Filtering
1       385     3124
2       1258    2
True junctions count = 5437144
False junctions count = 4410615
Hash table size = 9847759
Candidate marks count = 26276463
--------------------------------------------------------------------------------
Reallocating bifurcations time: 6
True marks count: 20290262
Edges construction time: 5004
--------------------------------------------------------------------------------
Distinct junctions = 5437144

approximateContigTotalLength: 1543877663
counters:
49076 936 921 40
Exception : [std::bad_alloc]
./testing/src/novartis-pisces/pisces/redist/salmon/bin/salmon index was invoked improperly.
For usage information, try ./testing/src/novartis-pisces/pisces/redist/salmon/bin/salmon index --help
Exiting.
```

**Comment by rob-p** [comment]
Hi @mdshw5,

  Thanks for the detailed report (and trying out the new version).  Could you provide some details about the system you're running on?  For example, how much memory is available?  Also, how easy would it be to provide the actual fasta you are trying to index (for us to attempt to reproduce this locally)?

Best,
Rob

**Comment by mdshw5** [comment]
Here's a link to the original transcriptome, along with a zip archive of the output salmon created: https://novartisnam-my.sharepoint.com/:f:/g/personal/shirlma2_novartis_net/Enk0c5zQMgZElcK6fgIOFbMBbKyvtrFDKtcpIL-D3zqppQ

**Comment by rob-p** [comment]
Hi @mdshw5,

  Thanks for sharing the file.  I was able to build the transcriptome.  The final index on this is ~15G.   Here are the stats from the run on our machine:

```
~/salmon/build/issue432$ du -h big_idx/
15G     big_idx/
~/salmon/build/issue432$ cat indexing_time.txt
9737.34user 339.95system 21:11.51elapsed 792%CPU (0avgtext+0avgdata 14894700maxresident)k
1232inputs+150622584outputs (0major+99352946minor)pagefaults 0swaps
```

so the peak construction memory was about the same and the build took 21m with 16 threads.  If you have a place, I can share the built index.  What were the stats of the machine on which you were building? Was there sufficient RAM allocated?

**Comment by mdshw5** [comment]
Wow. Thanks for getting back so fast. I’ll update more info about the machine. It’s got 16GB of RAM and only 3GB of swap, so I do think it was memory pressure. In fact, I just looked through the system kernel messages and found the OOM routine killed my process:

```Out of memory: Kill process 12997 (R) score 846 or sacrifice child                                      │10-03 22:39 INFO     Encountered FastxParser destructor while parser was still marked active (or while parsing threads were 
Killed process 12997, UID 1506502601, (R) total-vm:17105100kB, anon-rss:15306012kB, file-rss:12kB 
```

Sorry I didn’t check this earlier!
