### ISSUE TITLE
alevin on 5'-tagged scRNAseq

### ISSUE THREAD

**Issue by carneiro-m** [COMBINE-lab/salmon#439]
Hi, 
I was wondering if alevin could be used on 5'-tagged scRNAseq (10x chemistry) gene expression and V(D)J libraries.

Thanks

**Comment by k3yavi** [comment]
Hi @carneiro-m ,
Yes, you just have to change the library type to `-lISF` from `-lISR`.
One caveat though, unfortunately, even if the data has read sequence on both its end, alevin will use only one end for mapping.

**Comment by carneiro-m** [comment]
> Hi @carneiro-m ,
> Yes, you just have to change the library type to `-lISF` from `-lISR`.
> One caveat though, unfortunately, even if the data has read sequence on both its end, alevin will use only one end for mapping.

Hi @k3yavi, thank you so much.

**Comment by rfarouni** [comment]
So which --chemistry flag in Cell Ranger does the change to -lISF correspond to? Is it `SC5P-R2` or `fiveprime`? https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count
