### ISSUE TITLE
Unrecognised option  '--numBootstraps 100' 

### ISSUE THREAD

**Issue by claudiadast** [COMBINE-lab/salmon#440]
I am trying to run Salmon (v0.14.1) in a linux environment with the following command:

`salmon quant -i /index -l A -1 PBS_2-R1.fastq.gz -2 PBS_2-R2.fastq.gz --numBootstraps 100 -o /scratch`

However, I get the error:

`(mapping-based mode) Exception : [unrecognised option '--numBootstraps 100'].`

When I run the command without the `--numBootstraps 100` argument it works fine. Is this error arising because I'm running in mapping-based mode? Can you not use numBootstraps in this mode?

**Comment by rob-p** [comment]
Did you fihure out what was wrong?
