### ISSUE TITLE
libtbbmalloc.so.2 in docker image

### ISSUE THREAD

**Issue by CloXD** [COMBINE-lab/salmon#447]
Hello,
I'm trying to run the docker image on a cluster to quantify fastq files using the mapping mode. 
I'm using it with singularity ( already used it on another cluster and it worked perfectly).

Here the command:
singularity exec docker://combinelab/salmon:latest salmon quant --validateMappings -l A -p ${threads} -o ./salmon_map  -i ${salmon_index}  -1 ${file_1} -2 ${file_2}

And the error:
salmon: error while loading shared libraries: libtbbmalloc.so.2: cannot open shared object file: No such file or directory

I suspect that it's missing inside the image and that in the other cluster it was running because it was taking the one outside the image ( the cluster where it worked had lots of libraries and softwares available, in this other you need to load the modules).

Cheers
Claudio

**Comment by rob-p** [comment]
Hi @CloXD 

  The library is in the container in `/usr/local/lib`, but isn't being found by default for some reason.  Can you try the following?

```
singularity exec -e "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" docker://combinelab/salmon:latest salmon quant --validateMappings -l A -p ${threads} -o ./salmon_map -i ${salmon_index} -1 ${file_1} -2 ${file_2}
```

and let me know if that works for you.  I'll have to figure out how to make sure it's in the path by default.

**Comment by CloXD** [comment]
Hi,
it goes literally in panic: 

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/sylabs/singularity/internal/pkg/util/uri.Split(0x7ffd422b2b65, 0x1f, 0xc00003c195, 0xc0004852f0, 0xc0004e5c78, 0x929217)
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/internal/pkg/util/uri/uri.go:104 +0x13e
github.com/sylabs/singularity/cmd/singularity/cli.replaceURIWithImage(0x19d2a60, 0xc0000b8900, 0x11, 0x12)
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/cmd/singularity/cli/actions.go:189 +0x5d
github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).execute(0x19d2a60, 0xc000030160, 0x12, 0x12, 0x19d2a60, 0xc000030160)
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:755 +0x4ed
github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19d65c0, 0x0, 0xf6, 0xfc0b01)
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/sylabs/singularity/vendor/github.com/spf13/cobra.(*Command).Execute(0x19d65c0, 0x4, 0x1133611)
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/sylabs/singularity/cmd/singularity/cli.ExecuteSingularity()
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/cmd/singularity/cli/singularity.go:114 +0x110
main.main()
	/tools/others_tools/Go/go-1.11.2/src/github.com/sylabs/singularity/cmd/singularity/cli.go:16 +0x20
```
with -e you clean environment before running container.
I haven't found how to add the environmental variable, but logging in as shell and exporting the variable, it works ( or at least, I discover that I have to rebuild the index since it was built with the old verision in RapMap).

I'll see if there is another way to import the variable or I'll build an image with the env
Thanks 
Claudio

**Comment by rob-p** [comment]
Interesting!  That looks docker / singularity related.  I pushed an updated latest tag with the proper ld library path.  Perhaps pulling thay again will resolve it?

**Comment by CloXD** [comment]
The singularity error must be related to the -e argument... I'll try tomorrow, but I think that will solve the problem, thank you very much!
