### ISSUE TITLE
Best way to convert ensembl ID to gene symbol

### ISSUE THREAD

**Issue by vertesy** [COMBINE-lab/salmon#448]
Hi,

I am testing Alevin, and would like to compare against Cell Ranger on my data set. While primary mapping statistics indicate more reads mapped, I would like to compare the results in the final analysis, in Seurat. Many steps rely on HGNC Gene symbols as opposed to Ensemble IDs.

### What is the best way to convert ensembl IDs to gene symbol in Alevin?

Alevin (aligned as in this [gist](https://gist.github.com/k3yavi/c501705ed2d29b12b0d10cf78b3ed001#file-alevin-default-ipynb), imported to R in this [tutorial](https://combine-lab.github.io/alevin-tutorial/2018/running-alevin/)) returns ensembl IDs in format like "ENSG00000215910.7".

```R
require("fishpond")
require("tximport")
  
  files <- file.path("[...]/alevin/quants_mat.gz")
  file.exists(files)
  txi <- tximport(files, type="alevin");
  rownames( txi$counts)
``` 

I am currently converting these using biomart with suboptimal adaptations:

```R
    BiocManager::install("biomaRt")
    require('biomaRt')
    mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
    genes <- rownames(txi$counts)
    df$id <- NA
    meta.genes <- getBM(attributes = c("ensembl_gene_id","external_gene_name", "description"), 
                           values = genes, mart = mart )
```
Manual adaptations:

1. I trim IDs after dot ("ENSG00000215910.7" → "ENSG00000215910”)
2. I remove NA values (not all trimmed gene IDs are found in biomaRt)
3. I add up counts of genes (per ENS.ID) with the same gene symbol, e.g. “Y_RNA” or “HSPA14”

```R
    g.LookUp = meta.genes[,2]; names(g.LookUp) = meta.genes[,1]
    
    # 1. Trim
    ensembl_ID.simple =str_split_fixed(genes,pattern = '\\.',  n=2)[,1]
    
    genes.converted = g.LookUp[ensembl_ID.simple]
    any.duplicated(genes.converted)
    
    # ...etc
```

Is there a better way to convert IDs, possibly implemented in Alevin / Salmon?

**Comment by k3yavi** [comment]
I was wondering how did you create the transcript to gene map file for Alevin? The gene names in the t2g file doesn't have to be ensemble IDs , if you have the gtf that might have the gene symbols too, no ?

**Comment by vertesy** [comment]
Thanks Avi!

I created the transcript to gene map file for Alevin as in this [gist](https://gist.github.com/k3yavi/c501705ed2d29b12b0d10cf78b3ed001#file-alevin-default-ipynb):
```bash
wget -nv ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/gencode.v31.primary_assembly.annotation.gtf.gz
bioawk -c gff '$feature=="transcript" {print $group}' <(gunzip -c gencode.v31.primary_assembly.annotation.gtf.gz) | awk -F ' ' '{print substr($4,2,length($4)-3) "\t" substr($2,2,length($2)-3)}' -> txp2gene.tsv
```
*I repaced the assumed extra space `- > txp2gene.tsv` to `-> txp2gene.tsv`*

I am not aware of a GTF with gene symbols (and I guess during the alignment & counting process it would be not good to use these imprecise but convenient labels)

**Comment by k3yavi** [comment]
Right, to generate the transcript to gene symbol use this
```
bioawk -c gff '$feature=="transcript" {print $group}' <(gunzip -c gencode.v31.primary_assembly.annotation.gtf.gz) | awk -F ' ' '{print substr($4,2,length($4)-3) "\t" substr($8,2,length($8)-3)}' > txp2gene_symbol.tsv
```

There are two options either you can use the above file directly with alevin or generate Ensemble gene ids to gene symbol map and change the gene names in R for the output which you already have.
```
bioawk -c gff '$feature=="transcript" {print $group}' <(gunzip -c gencode.v31.primary_assembly.annotation.gtf.gz) | awk -F ' ' '{print substr($2,2,length($2)-3) "\t" substr($8,2,length($8)-3)}' > gene2symbol.tsv
```

Hope it helps.

**Comment by vertesy** [comment]
Thanks a lot, I will try it!

**Comment by k3yavi** [comment]
Closing this now, feel free to open if you still have issue
