### ISSUE TITLE
Salmon depends on Staden depends on xz for lzma.h

### ISSUE THREAD

**Issue by sjackman** [COMBINE-lab/salmon#45]
https://travis-ci.org/Homebrew/homebrew-science/jobs/114404533#L1110-L1115

```
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/local/Library/ENV/4.3/clang -DHAVE_CONFIG_H -I. -I.. -I..    -I/usr/local/include -L/usr/local/lib -MT libstaden_read_la-cram_io.lo -MD -MP -MF .deps/libstaden_read_la-cram_io.Tpo -c -o libstaden_read_la-cram_io.lo `test -f 'cram_io.c' || echo './'`cram_io.c
libtool: compile:  /usr/local/Library/ENV/4.3/clang -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/local/include -L/usr/local/lib -MT libstaden_read_la-cram_io.lo -MD -MP -MF .deps/libstaden_read_la-cram_io.Tpo -c cram_io.c -o libstaden_read_la-cram_io.o
cram_io.c:66:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated.
make[5]: *** [libstaden_read_la-cram_io.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [libstadenio-prefix/src/libstadenio-stamp/libstadenio-build] Error 2
make[1]: *** [CMakeFiles/libstadenio.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by rob-p** [comment]
Indeed — do you know if there's a fork of lzma on GitHub that I can pull from (if there's not a version locally installed on the target)?

**Comment by sjackman** [comment]
I'd rather not bundle the dependency. Troubleshooting bundled dependencies is crazy making. The `cmake` script could check that the dependency is satisfied and report an error message if it's not. Or I suppose install the dependency if it's not satisfied. Perhaps that's what you were thinking.
In any case, here's the web site: http://tukaani.org/xz/
and git repository: http://git.tukaani.org/
Here's a GitHub mirror. I don't know whether it's current: https://github.com/nobled/xz

**Comment by rob-p** [comment]
Exactly, I meant that if the dep is not already satisfied, I'll pull the source and compile and install it locally (not that I would bundle the dependency with salmon).

**Comment by sjackman** [comment]
Sure, works for me. Is it possible to add an argument that indicates that the dependencies (like `xz`) should be provided by the host, and any missing dependencies are an error?

**Comment by sjackman** [comment]
Salmon also depends on `libz` when compiling `bwa`.
https://gist.github.com/anonymous/a50569adddca1b8605f7#file-02-make-L118-L120
```
/usr/bin/gcc-4.8 -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  utils.c -o utils.o
utils.c:33:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
```

**Comment by sjackman** [comment]
It's ignoring the environment variable `$CPPFLAGS` which has the search path for `zlib.h`.
```
$ env |grep CPPFLAGS
CPPFLAGS=-isystem/home/linuxbrew/.linuxbrew/include
```

**Comment by rob-p** [comment]
I'll have to check if the ignoring of the `CPPFLAGS` is a problem with bwa's build system, or if I'm simply neglecting to pass the environment along properly.

**Comment by sjackman** [comment]
It's a problem with BWA's Makefile. https://github.com/lh3/bwa/blob/master/Makefile#L25

**Comment by rob-p** [comment]
I think this is resolved, right?  Since Salmon builds properly in homebrew-science?  The next release should solve the external package hashing requirement that they now want to enforce.
