### ISSUE TITLE
I installed latest version of salmon through git clone for trinityrnaseq but unable to run trinity

### ISSUE THREAD

**Issue by shanmugavadivelps** [COMBINE-lab/salmon#452]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

**Describe the bug**
I installed latest version of salmon through git clone for trinityrnaseq. When i run trinity using a command "perl Trinity --seqType fq --left reads_1.fq --right reads_2.fq --CPU 6 --max_memory 20G' I am getting a message to install salmon. kindly give me a solution for this

**To Reproduce**
Trinity Trinity-v2.8.5 requires salmon to be installed.  Get it here: https://combine-lab.github.io/salmon/  at Trinity line 3870.

Specifically, please provide at least the following information:

  * Which version of salmon was used?
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
**Expected behavior**

**Screenshots**
iipr@iipr-ubuntu:~/trinityrnaseq-Trinity-v2.8.5$ perl Trinity --seqType fq --left reads_1.fq --right reads_2.fq --CPU 6 --max_memory 20G

     ______  ____   ____  ____   ____  ______  __ __
    |      ||    \ |    ||    \ |    ||      ||  |  |
    |      ||  D  ) |  | |  _  | |  | |      ||  |  |
    |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
      |  |  |    \  |  | |  |  | |  |   |  |  |___, |
      |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
      |__|  |__|\_||____||__|__||____|  |__|  |____/

    Trinity-v2.8.5

Left read files: $VAR1 = [
          'reads_1.fq'
        ];
Right read files: $VAR1 = [
          'reads_2.fq'
        ];
Trinity version: Trinity-v2.8.5
** NOTE: Latest version of Trinity is v2.8.6, and can be obtained at:
	https://github.com/trinityrnaseq/trinityrnaseq/releases

Trinity Trinity-v2.8.5 requires salmon to be installed.  Get it here: https://combine-lab.github.io/salmon/  at Trinity line 3870.
iipr@iipr-ubuntu:~/trinityrnaseq-Trinity-v2.8.5$ ^C

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Version18.04

**Additional context**

**Comment by k3yavi** [comment]
Can  you try installing trinity through bioconda ? It seems like an environment related issue.

Since it's outside the scope of salmon tool and seems to be an issue with trinity, closing this issue but feel free to reopen if the bioconda solution didn't work.
