### ISSUE TITLE
salmon on ribosome profiling data

### ISSUE THREAD

**Issue by Zhuxitong** [COMBINE-lab/salmon#454]
Hello, I am wondering if salmon can be used to quantift ribosome profiling data(Ribo-seq) ? Because I saw that in the index step, the k-mer is 31 by default. However ribo-seq reads is usually less than 30bp.

So can I use salmon on my Rino-seq data?

**Comment by rob-p** [comment]
Hi @Zhuxitong, 

  You can easily change the k-mer length used for indexing by passing the desired value to the `-k` option of the `index` command.  So, that part isn't technically a problem.  The bigger issue is that Ribo-seq data doesn't follow the same basic model as RNA-seq data.  That is, the coverage variation in RNA-seq is more often an issue to be corrected (e.g. evidence of bias during library prep / sequencing), whereas it is integral to the interpretation of Ribo-seq data (i.e. the peaks are primary features of interest).  Therefore, it's not clear to me that using any RNA-seq abundance estimation software on Ribo-seq data "off-the-shelf" is conceptually the right thing to do, though you are welcome to experiment with it.  However, there is some interesting work on combining transcript abundance profiles with Ribo-seq data to infer isoform-level information in the Ribo-seq data.  For example, [this recent pre-print](https://www.biorxiv.org/content/10.1101/582031v3) provides a pipeline for this.
