### ISSUE TITLE
Will this salmon quant warning affect the result?

### ISSUE THREAD

**Issue by diyang1354** [COMBINE-lab/salmon#457]
warnings in the form of '[warning] len : *, but txp.RefLenght : *' appeared in the running log.
How did this occurred? Will this affect the quantification?
salmon version : v1.0.0
reference genome: ensembl GRCh38 release 96
****gentrome and decoy generating command:****
grep "^>" $home/Ensembl_human_v96/Homo_sapiens.GRCh38.dna.primary_assembly.fa | cut -d " " -f 1 > decoys_new.txt
sed -i.bak -e 's/>//g' decoys_new.txt
cat $home/Ensembl_human_v96/Homo_sapiens.GRCh38_v96.cdna.all.fa $home/Ensembl_human_v96/Homo_sapiens.GRCh38.dna.primary_assembly.fa > $home/Ensembl_human_v96/gentrome.fa.gz
        
****salmon index command:****
        salmon index -t $home/Ensembl_human_v96/gentrome.fa.gz -d 
         $home/Ensembl_human_v96/decoys.txt -p 12 -i ${home}/NGS/salmon_index_human_v96

****salmon quant command:****
	salmon quant -i ${home_path}/NGS/salmon_index_human_v96 -l A \
	-1 ${fastq1} -2 ${fastq2} --validateMappings -p 12 --gcBias \
	-o $count_path/${sample_name} 
![image](https://user-images.githubusercontent.com/51859749/69779623-8f70bc80-11e3-11ea-9c94-6be4b9819d28.png)

**Comment by k3yavi** [comment]
Hi @diyang1354 ,

It's an expected behavior as salmon can't index transcripts with length less than the kmer length.
If you wan't to include some these transcripts back into the index and quantify with them you might wanna use `-k ` flag while indexing with the smaller kmer length.
