### ISSUE TITLE
Can salmon handle transcripts with Ns and highly fragmented genome?

### ISSUE THREAD

**Issue by jdrnevich** [COMBINE-lab/salmon#459]
I've been tasked with analyzing some old RNA-Seq data from trap-jaw ant. There is a genome assembly that's not bad except it's in 37K fragments. There is also a transcriptome assembly done with SOAPdenovo-Trans in scaffolding mode, so there are transcripts with stretches of Ns based on length estimates from mate-pair sequencing. Do you think Salmon would have a problem with the Ns in the transcripts or doing selective alignment to a highly fragmented genome? Or should I just try it and see what happens?
Thanks!

**Comment by k3yavi** [comment]
Hi @jdrnevich ,

Thanks for checking. Usually the decoys i.e. genome used for selective alignment also has series of Ns in them and I think they either not indexed or replaced by random sequence (@rob-p  can clarify) but it's worth running salmon on the reference and check how does the results look.

**Comment by jdrnevich** [comment]
OK, I'll give it a go and let you know if I run into any trouble. Thanks, @k3yavi !

**Comment by k3yavi** [comment]
Marking this as close but feel free to reopen.
