### ISSUE TITLE
undefined reference to boost::program_options::validate

### ISSUE THREAD

**Issue by sjackman** [COMBINE-lab/salmon#46]
Here's a gist of the logs:
https://gist.github.com/sjackman/8b0c2be77efeb9507ca3#file-02-make-L4938

**Comment by sjackman** [comment]
To reproduce this error:
```sh
docker run linuxbrew/linuxbrew brew install gcc homebrew/science/salmon
```

**Comment by rob-p** [comment]
This looks (maybe) like an incompatibility between libc++ and libstdc++.

**Comment by rob-p** [comment]
Also, this appears to be:

1. A very old version of Salmon (0.4.2)
2. Using GCC 5.0, to which I have not yet moved (and which isn't installed on any machines where I have access).  Is it easy to check if this pops up with 4.8.x or 4.9.x as well?

**Comment by sjackman** [comment]
> A very old version of Salmon (0.4.2)

Right. Sorry. I've just updated Homebrew-science to Salmon 0.6.0. https://github.com/Homebrew/homebrew-science/pull/3407

**Comment by sjackman** [comment]
Yeah! Salmon compiled! Using Ubuntu Trusty with GCC 4.8.4 and Salmon 0.6.0.

No luck with GCC 5.3. My guess as to this issue (undefined reference) is that it's possibly mixing boost headers from one installation of boost that it found in /usr and boost libraries from another installation installed by Linuxbrew.

**Comment by sjackman** [comment]
No, I take that back. Boost isn't installed in `/usr/` of this system. There's only one boost install.
Perhaps it's mixing compilers GCC 4.8.4 for some modules and 5.3 for others.

**Comment by rob-p** [comment]
Has this been resolved?

**Comment by sjackman** [comment]
Yes. I built salmon 0.7.2 from source using GCC 5.3.

**Comment by mjsteinbaugh** [comment]
I seem to be having this same problem attempting to compile salmon 0.7.2 using GCC 5.3 (linuxbrew) on our server cluster. Works fine on my Mac though. Any ideas? I can post the log.

**Comment by sjackman** [comment]
May as well post `brew gist-logs salmon` for the record.
I'll build a precompiled binary bottle for salmon 0.7.2.

**Comment by sjackman** [comment]
Bottled. Try again now, Michael.
```sh
brew update
brew install salmon
```

**Comment by mjsteinbaugh** [comment]
Perfect that works!
