### ISSUE TITLE
bioconda install doesn't work if channels aren't set up correctly

### ISSUE THREAD

**Issue by ctb** [COMBINE-lab/salmon#480]
On a fresh conda install,

```
conda create -n slm2 -y -c bioconda salmon
```
yields a broken salmon:
```
$ conda activate slm2
(slm2) ggg298-43@farm:~$ salmon
salmon: error while loading shared libraries: libboost_iostreams.so.1.60.0: cannot open shared object file: No such file or directory
```

This seems to be because I'm missing conda-forge; this:

```
conda create -n slm3 -y -c conda-forge -c bioconda salmon
conda activate slm3
salmon
```
works fine!

Nothing needs to be done, and I will update as I debug, but I wanted to put this here for google bait.

**Comment by ctb** [comment]
it's not clear if the right fix is to pin the boost version [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/salmon/meta.yaml), or just to go with the "always use conda-forge on installs" strategy in the documentation. I will consult with experts.

**Comment by roryk** [comment]
This is the first time I've heard the term "google bait" and I love it.

**Comment by ctb** [comment]
On Wed, Jan 29, 2020 at 08:26:12AM -0800, Rory Kirchner wrote:
> This is the first time I've heard the term "google bait" and I love it.

:)

worst thing ever: finding that your google bait for an unresolved problem
from 3 years ago is ...still unresolved.

**Comment by ctb** [comment]
experts tell me that you just need to be darned sure that conda-forge is a high priority channel, above bioconda, as [per instructions](https://bioconda.github.io/user/install.html#set-up-channels); that specifying multiple channels with `-c` explicitly is poor practice because it's so error prone; and that if I'm teaching people that, I'm a bad teacher.

:)

I'll look at the salmon documentation to make sure it's accurately represented there and then close this issue.

**Comment by ctb** [comment]
*shrug* conda isn't mentioned in the salmon docs so I'll just leave this here for people who are trying to use bioconda and run into this error. peace out!
