### ISSUE TITLE
Salmon 1.1.0 auto update check stalled

### ISSUE THREAD

**Issue by cihanerkut** [COMBINE-lab/salmon#486]
`salmon` command gives as expected:

```
salmon v1.1.0

Usage:  salmon -h|--help or
        salmon -v|--version or
        salmon -c|--cite or
        salmon [--no-version-check] <COMMAND> [-h | options]

Commands:
     index Create a salmon index
     quant Quantify a sample
     alevin single cell analysis
     swim  Perform super-secret operation
     quantmerge Merge multiple quantifications into a single file
```

However, `salmon index --help` freezes without any CPU usage. `strace` shows it's trying to connect to an IP address, which belongs to GitHub but out of commission right now.

```
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 6
epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLET, {u32=509961152, u64=140196832437184}}) = 0
ioctl(6, FIONBIO, [1])                  = 0
connect(6, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("185.199.108.153")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(4, EPOLL_CTL_MOD, 6, {EPOLLIN|EPOLLPRI|EPOLLOUT|EPOLLERR|EPOLLHUP|EPOLLET, {u32=509961152, u64=140196832437184}}) = 0
epoll_wait(4, ^Cstrace: Process 4488 detached
```

Waiting long enough, it tries another IP address, which is also broken.

My Salmon is compiled with GCC 8.2.0 / gompi2019a toolset using EasyBuild. It runs on Centos 7.

Passing `--no-version-check` solves the problem but this option isn't displayed on main help screen, I found it somewhere in the source.

**Comment by cihanerkut** [comment]
The same with version 1.2.0.

**Comment by rob-p** [comment]
Hi @cihanerkut,

  First, thanks for reporting this, and going through the trouble to give the `strace` information.  Second, salmon won't auto-update anyway.  That would be quite slick, but there's not a good and reliable way to do that with natively-compiled programs that I know of.

  However, the most surprising thing is that you are finding the call to the version check ip to be hanging for any significant amount of time.  The timeout should be pretty quick.  How long does it hang when you do `salmon index --help`?  I'll look into it on our end as well.

**Comment by cihanerkut** [comment]
Hi @rob-p,

The first attempt timed out in 2 min 7 sec.

```
22:06:42 socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 6
22:06:42 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLET, {u32=497378240, u64=139780208026560}}) = 0
22:06:42 ioctl(6, FIONBIO, [1])         = 0
22:06:42 connect(6, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("185.199.109.153")}, 16) = -1 EINPROGRESS (Operation now in progress)
22:06:42 epoll_ctl(4, EPOLL_CTL_MOD, 6, {EPOLLIN|EPOLLPRI|EPOLLOUT|EPOLLERR|EPOLLHUP|EPOLLET, {u32=497378240, u64=139780208026560}}) = 0
22:06:42 epoll_wait(4, [{EPOLLIN|EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=497378240, u64=139780208026560}}], 128, -1) = 1
22:08:49 poll([{fd=6, events=POLLOUT}], 1, 0) = 1 ([{fd=6, revents=POLLOUT|POLLERR|POLLHUP}])
22:08:49 getsockopt(6, SOL_SOCKET, SO_ERROR, [110], [4]) = 0
22:08:49 close(6)                       = 0
```

**Comment by rob-p** [comment]
@EricDeveaud,

  Does passing `--no-version-check` resolve the issue?  This flag goes before any other command and disables this behavior.  For example:

```
salmon --no-version-check index -t <gentrome.fa> -d decoys.txt -i index
```

or 

```
salmon --no-version-check quant -i index -la -1 reads_1.fq.gz -2 reads_2.fq.gz -o quant_dir
```
There should be _no_ network access when using this flag.

**Comment by EricDeveaud** [comment]
yes `--no-version-check` does the trick, but among all the users of the cluster I'm pretty sure some of them will forgot ;-)

on our  local installation I disabled the getVersionMessage even if salmon handle the no network cleanly. (I tested using `unshare -n salmon whatever you want`)
NB debian maintainer also  disabled the phone home call in their packages

sorry if it it may sound harsh

**Comment by cihanerkut** [comment]
Just an idea. Would it be possible to assign an environment variable, such as SALMON_NO_VERSION_CHECK, whose existence overrides version checking? This wouldn't break compatibility with older scripts because they wouldn't have the variable in the first place. In non-networked nodes, an admin can simply set this variable and users will run salmon as usual.

**Comment by rob-p** [comment]
@cihanerkut,

  Yes; this is a nice solution and I think it wouldn't be too hard!

**Comment by rob-p** [comment]
@cihanerkut and @EricDeveaud,

  We just released 1.2.1, which is on the release page, and dockerhub, and should propagate to bioconda soon.  It adds support for the `SALMON_NO_VERSION_CHECK` environment variable.  If you set `SALMON_NO_VERSION_CHECK` to either `1` or `TRUE` in the environment where salmon is running, it will skip the version check.  I hope this helps!

--Rob

**Comment by EricDeveaud** [comment]
thanks

**Comment by cihanerkut** [comment]
Thank you very much!
