### ISSUE TITLE
wh

### ISSUE THREAD

**Issue by yueli711** [COMBINE-lab/salmon#487]
Hello, 
 
I tried to use alevinQC, in it's manual it said:

note that currently, in order to generate the full set of files, alevin must be invoked with the `--dumpFeatures` flag

```
baseDir
  |--alevin
  |    |--featureDump.txt
  |    |--filtered_cb_frequency.txt
  |    |--MappedUmi.txt
  |    |--quants_mat_cols.txt
  |    |--quants_mat_rows.txt
  |    |--quants_mat.gz
  |    |--raw_cb_frequency.txt
  |    |--whitelist.txt
  |--aux_info
  |    |--meta_info.json
  |--cmd_info.json

```
I do not have `filtered_cb_frequency.txt` and `MappedUmi.txt` files.

Following is my command:

`
li@li-HP-Pavilion-Desktop-590-p0xxx:~/salmon-latest_linux_x86_64/bin$ ./salmon alevin -l ISR -1 fastqs/pbmc_1k_v3_S1_L001_R1_001.fastq.gz -2 fastqs/pbmc_1k_v3_S1_L001_R2_001.fastq.gz --chromium --dumpFeatures --dumpMtx -i index -p 8 -o alevin_output --tgMap txp2gene.tsv`

Which flag I have to invoke that I can have filtered_cb_frequency.txt and MappedUmi.txt files?

Thanks in advance for great help!

Best,

Yue

**Comment by k3yavi** [comment]
Hi Yue,
I think those files are needed for the older version of the software, with the latest one all the information is in the featureDump.txt file. Tried using alevinQc with what you have it will auto recognize it.

**Comment by yueli711** [comment]
Hello k3yavi,

Thank you so much for your quick response!

Thank you again!

Best,

Yue
