### ISSUE TITLE
what is the definition of "cell barcode collapsing" in elvinQC R package

### ISSUE THREAD

**Issue by yueli711** [COMBINE-lab/salmon#488]
Hello,

What is the meaning of the following figure?

Summay plot of cell barcode collapsing.

Plot the original frequency of each cell barcode in the original whitelist against the frequency after collapsing similar cell barcodes.

Thanks in advance for any help!

Best,

Yue

![Screenshot from 2020-02-26 17-35-02](https://user-images.githubusercontent.com/40526984/75399979-d0a06780-58cb-11ea-8f96-c71897951d00.png)

**Comment by k3yavi** [comment]
Hi,
Basically Alevin performs CB sequence correction within 1 distance hamming ball, the intuition being the set of real CB should ideally be more than 1 edit distance away.
Here I think the x axis gives you the count of reads for a CB before sequence correction and on y axis post sequence correction.

Hope it helps

**Comment by k3yavi** [comment]
Also if possible please raise the alevinQC related questions on the alevinQC repo. Our R magicians can you help you much better with the package .
