### ISSUE TITLE
question about unstranded library

### ISSUE THREAD

**Issue by lijing28101** [COMBINE-lab/salmon#492]
Hi, I like salmon for RNA-Seq quantification. To better quantify my data, I have some questions.
I compared the number of reads in quant.sf file with the unique counts and ambiguous counts in ambig_info.tsv. Some final estimation are similar to the sum of unique+ambiguous, some closed to unique, and some closed to ambiguous. I want to know how did you estimate the final counts to combine the unique and ambiguous counts?
For the unstranded library, did you use the same algorithm to estimate the final counts as the stranded library? I test some sequences for unstranded library, the estimation for reverse complement sequence is same. Is there a better way to estimate the transcripts anti-overlapping with another one in unstranded library?

Thanks,
Jing

**Comment by rob-p** [comment]
Hi @lijing28101,

  Thanks for your interest in salmon.  The answer to your first question:

>  I want to know how did you estimate the final counts to combine the unique and ambiguous counts?

is actually a huge part of the method behind salmon.  Salmon uses a statistical estimation procedure to determine what abundances for the transcripts are most likely given the observed data (read alignments).  You can read about the method in detail [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5600148/pdf/nihms849351.pdf) and about some subsequent improvements [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5870700/) and [here](https://www.biorxiv.org/content/10.1101/657874v2).

 > For the unstranded library, did you use the same algorithm to estimate the final counts as the stranded library? 

The difference between stranded and unstranded is that in the stranded library, we set the conditional probability of alignments that don't agree with the specified strandedness to be a very-low, user-adjustable value (`--incompatPrior` : 0 by default).  The underlying inference methodology is identical.  Strand specificity, if the library was sequenced that way, provides extra signal to the quantification algorithm.  However, that is an external source of information, and is only available if the library itself was strand-specific.
