### ISSUE TITLE
Alevin: custom fastQ R1 

### ISSUE THREAD

**Issue by davidecrs** [COMBINE-lab/salmon#494]
Hi, 

After my data preprocessing, I have a custom fastQ R1 composed just with the BC and the UMI. 
My BC has length 18nt and the UMI has length 8nt. So the sequence in R1 has total length 26nt. 
This is an example:

```
@NB501072:248:HNKTFBGXC:1:11101:8054:1048:TGCGTNATAGTAGCCATCGCATTGCGCGNATTACCTCTGAGCNGAAAGTAAAACGACGNTTAGGACTT 1
TAATAGGCGAATAGTAAAACGNTTAG
+
A#EEEEEEE#EEEEEEEEEEE#EEEE
```

I was wondering if there is a specific way to use Alevin with this kind of data. 
This is because I had to process raw data from Illumina / BioRad ddSeq.

**Comment by k3yavi** [comment]
Yep use --end 5 --umiLength 8 --barcodeLength 18

**Comment by davidecrs** [comment]
Great ! Thank you !!!

**Comment by davidecrs** [comment]
> Yep use --end 5 --umiLength 8 --barcodeLength 18

Thanks again, I forgot, however, to specify that the sequence is composed first of BC and then of UMI (BC + UMI) (I'm not sure if it was clear in the issue).
Does the command remain the same?

**Comment by k3yavi** [comment]
Yep that's the expected order for the command .
If the umi is first you might have to change --end 3.
