### ISSUE TITLE
The index version file human_index/versionInfo.json doesn't seem to exist.  Please try re-building the salmon index.

### ISSUE THREAD

**Issue by azbukinanadezda** [COMBINE-lab/salmon#495]
Hi!
Trying to quant reads but have this mistake:

![image](https://user-images.githubusercontent.com/38889294/77089732-3e493a80-6a17-11ea-9696-893f9dbf454b.jpeg)
But the index directory contains versionInfo.json file!
![image](https://user-images.githubusercontent.com/38889294/77089869-6c2e7f00-6a17-11ea-8baa-84c6ad97c931.jpeg)

What can be a problem here?

**Comment by rob-p** [comment]
In the quant command ,you pass `human_index`, but in the `ls`, it is `hum_index`.  Is this the problem?

**Comment by azbukinanadezda** [comment]
damn yes, that is. Thanks a lot, excuse me for this typo question(
