### ISSUE TITLE
salmon 1.1.0 and 1.0.0 core-dump under Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by tony-travis** [COMBINE-lab/salmon#500]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon
**Describe the bug**
salmon 1.1.0 and 1.0.0 core-dump when attempting to build an index under Ubuntu 18.04 LTS
**To Reproduce**
Steps and data to reproduce the behavior:
```
root@firefly:/usr/local/src/salmon# salmon-1.1.0_linux_x86_6/bin/salmon index -k 31 -i index -t sample_data/transcripts.fasta
Version Info:   This is the most recent version of salmon.
[2020-04-07 21:11:41.237] [jLog] [info] building index
out : index
[2020-04-07 21:11:41.240] [puff::index::jointLog] [info] Running fixFasta

[Step 1 of 4] : counting k-mers
Illegal instruction (core dumped)

root@firefly:/usr/local/src/salmon# salmon-0.14.1_linux_x86_64/bin/salmon index -k 31 -i index -t sample_data/transcripts.fasta
Version Info: ### PLEASE UPGRADE SALMON ###
### A newer version of salmon with bug fixes is available. ####
###
The newest version, available at https://github.com/COMBINE-lab/salmon/releases
contains new features, improvements, and bug fixes; please upgrade at your
earliest convenience.
###
Sign up for the salmon mailing list to hear about new versions, features and updates at:
https://oceangenomics.com/subscribe
###
[2020-04-07 21:12:14.575] [jLog] [info] building index
[2020-04-07 21:12:14.580] [jointLog] [info] [Step 1 of 4] : counting k-mers
Elapsed time: 0.00677775s

[2020-04-07 21:12:14.596] [jointLog] [info] Replaced 0 non-ATCG nucleotides
[2020-04-07 21:12:14.596] [jointLog] [info] Clipped poly-A tails from 0 transcripts
[2020-04-07 21:12:14.599] [jointLog] [info] Building rank-select dictionary and saving to disk
[2020-04-07 21:12:14.599] [jointLog] [info] done
Elapsed time: 5.7764e-05s
[2020-04-07 21:12:14.606] [jointLog] [info] Writing sequence data to file . . . 
[2020-04-07 21:12:14.607] [jointLog] [info] done
Elapsed time: 0.000590993s
[2020-04-07 21:12:14.614] [jointLog] [info] Building 32-bit suffix array (length of generalized text is 28,577)
[2020-04-07 21:12:14.616] [jointLog] [info] Building suffix array . . . 
success
saving to disk . . . done
Elapsed time: 0.000716831s
done
Elapsed time: 0.0107059s
```
Specifically, please provide at least the following information:

  * Which version of salmon was used? 1.1.0, 1.0.0 and 0.14.1
  * How was salmon installed (compiled, downloaded executable, through bioconda)? GitHub binary
  * Which reference (e.g. transcriptome) was used? sample data from GitHub release
  * Which read files were used? none
  * Which which program options were used? -k 31 -i index -t sample_data/transcripts.fasta

**Expected behavior**
I expected salmon 1.1.0 to run without a core-dump and produce similar results to 0.14.1

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX] Ubuntu 18.04.4 LTS
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]
Linux firefly 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Using "bcbio-nextgen", with "salmon 1.1.0" installed by Anaconda: Removed this version because of core-dumps and installed the binary releases of "salmon" 1.1.0 then 0.41.1 from GitHub in /usr/local. Did stand-alone tests with sample data from the GitHub binary release.

**Comment by tony-travis** [comment]
Note: This is on a dual Six-Core AMD Opteron(tm) Processor 8435 system

**Comment by rob-p** [comment]
Hi @tony-travis,

  Thank you for the detailed bug report!  The fact the core dump follows an `Illegal instruction` suggests that the issue is that the binary is compiled with an instruction that is not supported on the target CPU architecture.  Now, the question is how best to isolate the illegal instruction causing the issue, and determine the feasibility of removing or replacing the appropriate compiler option.

**Comment by tony-travis** [comment]
Hi, Rob.
I've been trying to compile "salmon" 1.1.0 from source under Ubuntu 18.04 and managed to get a newer version of "cmake" from KitWare, but there are many other dependency problems...

**Comment by rob-p** [comment]
We shy away from using `native` arch anywhere, and instead try to be explicit about the instruction sets used.  My current best guess is that we assume SSE4 (at least [here](https://github.com/COMBINE-lab/pufferfish/blob/master/CMakeLists.txt#L77)).  I believe this processor does not fully support SSE4.0.  I can try and see if there are any other places we make this assumption, and then perhaps make a test pre-compiled binary without it.

**Comment by rob-p** [comment]
Hi @tony-travis,

  Can you please give [this](https://drive.google.com/file/d/12GFekbIELDxbSXlMq6i-g9iF9stHyn3P/view?usp=sharing) executable a try?  It's built from the latest develop, but without the `-msse4` flag.  Does this run on the Opterton machine?

--Rob

**Comment by tony-travis** [comment]
Yes, that works :-)

**Comment by rob-p** [comment]
Excellent!  Now we should do some internal testing to see if this has any negative performance impact on machines that _do_ have SSE4.  Then we can determine if we can just make this the default, or if it's worth cutting a release under 2 configurations.

**Comment by tony-travis** [comment]
OK, Rob.

Thanks for your quick response!

  Tony.

**Comment by rob-p** [comment]
I saw no performance regressions, so 1.2.0 is built without the offending flag.  Thanks for the heads up.

**Comment by tony-travis** [comment]
On 11/04/2020 01:04, Rob Patro wrote:
> I saw no performance regressions, so 1.2.0 is built without the 
> offending flag. Thanks for the heads up.

Hi, Rob.

Thanks fixing the problem so quickly!

   Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk
