### ISSUE TITLE
alevin: --writeUnmappedNames option doesn't work

### ISSUE THREAD

**Issue by DrHogart** [COMBINE-lab/salmon#501]
Hi,
it seems that --writeUnmappedNames option doesn't work for `salmon alevin` (both R1 and R2 reads were used), while `salmon quant` with the same dataset (only R2 reads were used since R1 contains barcodes) reports unmapped read names correctly. The `alevin` reports all the reads in the dataset as unmapped, while `quant` gets only the fraction of them (the size of that fraction the same as reported in log).

`salmon version: 1.1.0`

**Comment by rob-p** [comment]
Thanks for the bug report.  This has been fixed in develop and should work properly in the new release.

**Comment by rob-p** [comment]
This should be fixed in 1.2.0, let me know if you have any trouble.
