### ISSUE TITLE
Segmentation fault when indexing

### ISSUE THREAD

**Issue by nickhir** [COMBINE-lab/salmon#503]
**Describe the bug**
I followed every step of this tutorial to generate the index.
https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/
Instead of using the mouse genomic data, I used the human data (https://www.gencodegenes.org/human/release_33lift37.html).
I invoked the indexing with the following command: 
**salmon index -t gentrome.fa.gz -d decoys.txt -p 8 -i salmon_index --gencode**
In the beginning everything seems to run smoothly, but a couple minutes in different error messages appear:
**error: Cant write to a temporary file**
**error: Cant read the input file**
followed by **Segmentation fault** and then the algorithm exits. 
Nonetheless a directory with different files regarding the indexing is beeing created.
However when I run
**salmon quant -i salmon_index/ -l A -1 ../../patients/patient001/fastq/S0012_1.fastq.gz -2 ../../patients/patient001/fastq/S0012_2.fastq.gz --validateMappings -o transcripts_quant**

it tells me that **The index version file salmon_index/versionInfo.json doesn't seem to exist**

**To Reproduce**
I installed salmon via bioconda, version 1.1.0

**Desktop (please complete the following information):**
Its running on CentOS 7

**Comment by tamuanand** [comment]
@nickhir  Probably your machine does not have enough memory for creating the index - I think it needs >220 GB of virtual memory 

You could try using the pre-built index from  http://refgenomes.databio.org/

**Comment by rob-p** [comment]
The virtual memory should also be greatly reduced in 1.2.0 (which I am working on finalizing the release of at the moment).  There will be detailed release notes describing the improvements.  However, getting the pre-built index is probably worth it if it's the right organism and annotation.

**Comment by nickhir** [comment]
Thank you very for the quick reply, must likely the virtual memory is the issue!

**Comment by tamuanand** [comment]
@nickhir  https://github.com/COMBINE-lab/salmon/releases/tag/v1.2.0 is now released by @rob-p
