### ISSUE TITLE
Memory Allocation Issue for Sailfish

### ISSUE THREAD

**Issue by diegoalzatec86** [COMBINE-lab/salmon#508]
Hello

I'm trying to quantify the samples included with the Salmon tutorial, but is giving me a malloc error.  I'm using ANACONDA with salmon 1.1.0  on  MacOS Catalina.

First, I had to separately download sailfish because wasn't included with the salmon package. So the first error was:

_Processing sample DRR016125

-bash: sailfish: command not found_

I solved this by downloading sailfish from biobuilds, but then I'm getting this error:

Processing sample DRR016125

sailfish(23259,0x105f71dc0) malloc: *** malloc_zone_unregister() failed for 0x7fff90f4f000

How can I solve this issue. I'm totally new on RNA-seq analysis and don't know how to continue.

Thanks

**Comment by tamuanand** [comment]
I think you should be using salmon and not sailfish

@rob-p  @k3yavi  can comment - I believe the sailfish codebase is now incorporated in salmon

**Comment by tamuanand** [comment]
@diegoalzatec86 Also, you should probably upgrade to 1.2.0 as there have been many memory related issues that @rob-p and @k3yavi have incorporated in 1.2.0

**Comment by diegoalzatec86** [comment]
Thanks, Isn't Sailfish required to run Salmon?, because the first time I run salmon I got an error:

`bash: sailfish: command not found_`

I dowloaded sailfish and when got back to use salmon the malloc error appears.

**Comment by tamuanand** [comment]
@diegoalzatec86 Probably you can try with salmon 1.2.0 and post back here

**Comment by rob-p** [comment]
@diegoalzatec86,

  Sailfish is *not* required to run salmon.  Salmon is a completely different tool, and it has subsumed and largely obviated sailfish.  I would recommend using salmon rather than sailfish to do any RNA-seq quantification.  Can you show what command you were running when you got the error:

```
bash: sailfish: command not found_
```

?

**Comment by diegoalzatec86** [comment]
Hi @rob-p 
Yes, for now I'm just trying to run the getting started tutorial, I dowloaded and indexed the A. thaliana transcriptome, then I dowloaded the sequnecing data and run the quantification code:

`#!/bin/bash
for fn in data/DRR0161{25..40};
do
samp=`basename ${fn}`
echo "Processing sample ${samp}"
sailfish quant -i athal_index -l A \
         -1 ${fn}/${samp}_1.fastq.gz \
         -2 ${samp}_2.fastq.gz \
		 -p 8 -o quants/${samp}_quant
done `

`_Processing sample DRR016125

-bash: sailfish: command not found_`

**Comment by diegoalzatec86** [comment]
Hello again @rob-p 

I was calling using the wrong code for quantification and calling sailfish .
 The code that I just sent you is included in the tutorial and is saved as shell script 

`quant_tut_samples.sh`.

However this doesn't match with the code described immediately below in the tutorial. 
>#!/bin/bash
>for fn in data/DRR0161{25..40};
> do
> samp=`basename ${fn}`
> echo "Processing sample ${samp}"
> salmon quant -i athal_index -l A \
>          -1 ${fn}/${samp}_1.fastq.gz \
>          -2 ${fn}/${samp}_2.fastq.gz \
>          -p 8 --validateMappings -o quants/${samp}_quant
>done

This is something that should be corrected in the tutorial. Thank you so much. I apologize.

**Comment by tamuanand** [comment]
@diegoalzatec86 I think you are referring to this page - https://combine-lab.github.io/salmon/getting_started/

I myself have used that I did not encounter any errors or anything related to sailfish when I used the very same shell script you are alluding to..

I don't know which tutorial has the sailfish code that you state - https://github.com/COMBINE-lab/salmon/issues/508#issuecomment-614279802

Probably you landed on a wrong or outdated tutorial page 

As previously mentioned many times in this GH issue, most of sailfish code is within salmon 

Either way, I think you should use bioconda to upgrade to 1.2.0 and start using salmon as the quantification tool

**Comment by rob-p** [comment]
I've updated the linked shell script.  Thanks for pointing it ou!

**Comment by rob-p** [comment]
I think this issue is resolved for the time being, so I'm closing it.  If there are any followup problems, please open a new issue.
