### ISSUE TITLE
Linkout suggestions from salmon code page

### ISSUE THREAD

**Issue by tamuanand** [COMBINE-lab/salmon#509]
Hi @rob-p @k3yavi 

I think it is best to have the below stated somewhere within the 1st para of the README  at https://github.com/COMBINE-lab/salmon  **_This will avoid lots of confusion for most users_** - as seen here https://github.com/COMBINE-lab/salmon/issues/508#issuecomment-614298125 

3 possible ways in which salmon index can be created

- cDNA only index : salmon_index - https://combine-lab.github.io/salmon/getting_started/

- SA mashmap index: salmon_partial_sa_index  -  (regions of genome that have high sequence similarity to the transcriptome) - https://github.com/COMBINE-lab/SalmonTools/blob/master/README.md  and  using this script https://raw.githubusercontent.com/COMBINE-lab/SalmonTools/master/scripts/generateDecoyTranscriptome.sh

- SAF genome index: salmon_sa_index -  (the full genome is used as decoy) -  https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/

**Comment by rob-p** [comment]
Great suggestions!  I've added these near the top of the README.
