### ISSUE TITLE
QUESTION related to names in quant.sf

### ISSUE THREAD

**Issue by Lordlitong** [COMBINE-lab/salmon#513]
Hi.

Can someone please tell me how to get rid of the gene names and other weird names but only keep transcript names in `quant.sf`? Here is what my `quant.sf `looks like:

Name Length EffectiveLength TPM NumReads
ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript| 1657 1502.212 0.752165 16.577
ENST00000450305.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000002844.2|DDX11L1-201|DDX11L1|632|transcribed_unprocessed_pseudogene| 632 477.467 0.000000 0.000

Also I am wondering if this is the reason why the error occurs when I import the data and run `tximeta` in R.
It says Error in checkAssays2Txps(assays, txps) :
none of the transcripts in the quantification files are in the GTF

Thanks.

**Comment by rob-p** [comment]
Hi @Lordlitong,

  The name of a FASTA record is whatever appears up to the first white space character in its header line.  This is why you get these long names in the index as a sequence name.  If you pass the `—gencode` flag when building the salmon index, it will treat `|` as an additional separator, and your names will just be e.g. `ENST00000456328.2`.  That is the easiest way to avoid this issue going forward.

  If you don’t want to rebuild the index and re-process the data (if you’ve already processed a ton of samples), then you would have to write some code to strip the sequence names before loading them.

**Comment by Lordlitong** [comment]
Hi @rob-p,

It worked well. Thanks for your help!
