### ISSUE TITLE
Salmon -1.2.1 issue

### ISSUE THREAD

**Issue by maysonlin** [COMBINE-lab/salmon#517]
hi, I am running Salmon-1.2.1 on my MacBook with Sierra 10.13.6. I try to run Salmon binary with terminal, and I get this error. How'd do solve this problem? 

Last login: Sat May  2 23:14:08 on ttys007
/Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0\ 2/bin/salmon ; exit;
Maysons-MacBook-Air:~ maysonlin$ /Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0\ 2/bin/salmon ; exit;
dyld: Library not loaded: @rpath/libtbbmalloc.dylib
  Referenced from: /Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0 2/bin/salmon
  Reason: image not found
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by rob-p** [comment]
Can you try doing:

```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0 2/lib
```

before running salmon?  The problem is that the executable is looking for `libtbb` and `libtbb_proxy`, but they are not in the library path.

**Comment by maysonlin** [comment]
> Can you try doing:
> 
> ```
> export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0 2/lib
> ```
> 
> before running salmon? The problem is that the executable is looking for `libtbb` and `libtbb_proxy`, but they are not in the library path.

Hi, Rob, thank you for replying, do you mean type those code in "Terminal"? 
I tried it, and I got this message:

-bash: export: `2/lib': not a valid identifier

**Comment by rob-p** [comment]
It looks like it's having trouble parsing this folder name "salmon-1.2.1-h2072146_0 2/", what if you put it in quotes?

```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"/Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0 2/lib"
```

**Comment by maysonlin** [comment]
> It looks like it's having trouble parsing this folder name "salmon-1.2.1-h2072146_0 2/", what if you put it in quotes?
> 
> ```
> export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"/Users/maysonlin/Downloads/salmon-1.2.1-h2072146_0 2/lib"
> ```

Hi, Rob, I tried that, nothing happened

**Comment by rob-p** [comment]
Is there a reason for the strange folder name?  Can you move salmon to a folder name with no space and try adding that to the path?  If you `ls` the lib directory, do you see the libraries I mentioned?

**Comment by maysonlin** [comment]
I changed the folder name and moved to the desktop, so I tried putting this in terminal, nothing happened 
>export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"/Users/maysonlin/Desktop/salmon1.2.1/lib

Then I opened up in lib directory, I didn't see the one you mentioned in the quote, this is what it looks like 
![Screen Shot 2020-05-03 at 12 39 30 PM](https://user-images.githubusercontent.com/64718774/80920140-da1ad580-8d3b-11ea-8ca1-041103f707da.png)

**Comment by rob-p** [comment]
Hrmm; can you say a bit about where you got the executable from?  What's missing in that directory are the key shared library files `libtbbmalloc.dylib`, `libtbbmalloc_proxy.dylib` and `libtbb.dylib`.  These are included in precompiled linux excutable, and if you install via Conda for linux or OSX, they should be taken care of.  Also, if you build from source, they are installed into the install target `lib` subdirectory by the `make install` command.

**Comment by maysonlin** [comment]
I downloaded the package from here 
https://anaconda.org/bioconda/salmon/files
then I opened the package up with "The Unarchiver.app", so I downloaded linux one, and open up the package with "Unarchiver.app", I didn't see any library files -libtbbmalloc.dylib, libtbbmalloc_proxy.dylib and libtbb.dylib. 
![Screen Shot 2020-05-03 at 4 17 25 PM](https://user-images.githubusercontent.com/64718774/80924960-3ee52880-8d5a-11ea-8fbc-5cf4537f0129.png)
 
Then I just installed Conda, but I have no idea how to install the package, sorry, I have ground zero coding knowledge

**Comment by rob-p** [comment]
Ahh, that's not how the conda install works.  Take a look at the bioconda instructions here (http://combine-lab.github.io/salmon/getting_started/), and click the link therein to see how to install conda.

**Comment by maysonlin** [comment]
> Ahh, that's not how the conda install works. Take a look at the bioconda instructions here (http://combine-lab.github.io/salmon/getting_started/), and click the link therein to see how to install conda.

Hi, problem solved, I can finally install and activate Salmon now, thank you very much!

**Comment by rob-p** [comment]
Awesome!  Glad it works now :).
