### ISSUE TITLE
Feature request: long read error model

### ISSUE THREAD

**Issue by bsipos** [COMBINE-lab/salmon#519]
Dear `salmon` developers,

We are using salmon at ONT for quantifying transcripts from alignments of cDNA reads to transcriptomes on a regular basis and in [some](https://github.com/nanoporetech/pipeline-transcriptome-de) of our pipelines.
Transcriptomic aligments of long reads generate less multimapping reads than short reads (depeneding on the structure of the transcriptome), however we would prefer not to ignore them during quantification in order to make maximal use of the data.
However, since the error model was built for short reads, until now we have used the tool with the error model turned off (`--noErrorModel`), which is not optimal.

Would it be possible to add a simple error model suitable for long read alignments? We propose something like the following for calculating the likelihood of an alignment:

- The likelihood of the aligment would be calculated based on the empirical distributions (or a normal fit) of edit distances conditioned on the length of the alignment. We could provide you with this information if needed.
- The likelihood of left and right soft or hard clipped sequences would be calculated as a function of their length (such as (1/x)^z, where the parameter z can be tuned based on real datasets).

A more complicated model could be build taking into account the error profile of the long reads. It might be overkill though.

I had a look at the source code and it seems to me that it might not be hard to implement it, however I am lacking the intimate knowledge of the codebase to do it easily.
Let me know if you would be interested in adding this feature. If yes, we could evaluate the change in the quality of estimates on real datasets.

Best regards,
Botond Sipos

**Comment by bsipos** [comment]
Hey @rob-p , would you consider this feature? No worries if not, in that case I might carry on hacking together something similar based on [NanoCount](https://github.com/a-slide/NanoCount).

**Comment by hjbolus** [comment]
Was an error model ever implemented for this?
