### ISSUE TITLE
[Alevin] Segfault with unmated reads

### ISSUE THREAD

**Issue by TobiTekath** [COMBINE-lab/salmon#522]
Hi,

I just encountered an unexpected behaviour of alevin when unmated reads are provided. Are unmated reads supported by alevin at all? I did not find anything in the alevin documentation, but the parameter is there.

I tried to quantify some public Illumina SureCell data.

Apparently the number of threads is set to 0 (because there are no file pairs?), which is of course not a good idea. The behaviour consists if I specify the number of threads manually (e.g. -p 1).

Side note: There is a typo in the threads warning message (I think).

---
Salmon v1.2.1, installed from conda.

#### Error message:

```
## alevin (dscRNA-seq quantification) v1.2.1
### [ program ] => salmon 
### [ command ] => alevin 
### [ libType ] => { A }
### [ index ] => { ../salmon/index/ }
### [ unmatedReads ] => { ../samples/sc.fastq.gz }
### [ output ] => { sc/ }
### [ tgMap ] => { tx2gene.tsv }
### [ end ] => { 3 }
### [ umiLength ] => { 8 }
### [ barcodeLength ] => { 6 }


Can't make user of more parsing threads than file (pairs); setting # of parsing threads to 0

Segmentation fault (core dumped)
```
---

**To Reproduce**

The index is based on a gencode reference and works fine for bulk data (salmon quant).

Command:
```
salmon alevin -l A -i ../salmon/index/ --unmatedReads ../samples/sc.fastq.gz -o sc/ --tgMap tx2gene.tsv --end 3 --umiLength 8 --barcodeLength 6
```

**Comment by TobiTekath** [comment]
I just noticed there is something wrong with my input file, sorry for my mistake. 

The basic question stays the same: Are unmated reads supported by Alevin? Is there a single-cell protocol that produces 'single-end' files?

**Comment by k3yavi** [comment]
Hey @TobiTekath ,

Thanks for the very interesting question. You are right, the unmated reads are not supported yet, but the basic idea was to consume a file with cb and umi attached to the read name, however it's a wip and is not properly supported. 

re: any SE single-cell protocol - I am not aware of any.
