### ISSUE TITLE
RNA-velocity (Salmon-alevin and scVelo)

### ISSUE THREAD

**Issue by brejnev** [COMBINE-lab/salmon#526]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
yes
**Describe the bug**
I was going though the tutorial  https://combine-lab.github.io/alevin-tutorial/2020/alevin-velocity/
using Alevin and scVelo

The filtering with 
scv.pp.filter_genes(adata, min_shared_counts = 30)

gives the error bellow. Any advice?
**Error**
R[write to console]: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  : 
  unimplemented type 'char' in 'eval'

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: call dbDisconnect() when finished working with a connection 

---------------------------------------------------------------------------
RRuntimeError                             Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    168                     if reductor:
--> 169                         rv = reductor(4)
    170                     else:

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py in __getstate__(self)
    123                     self.__sexp__._cdata,
--> 124                     globalenv.__sexp__._cdata)
    125             )

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in serialize(cdata, cdata_env)
    412         if error_occured[0]:
--> 413             raise embedded.RRuntimeError(_geterrmessage())
    414         return res

RRuntimeError: Error in (function (object, connection, ascii = FALSE, xdr = TRUE, version = NULL,  : 
  unimplemented type 'char' in 'eval'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    140 
--> 141     d = id(x)
    142     y = memo.get(d, _nil)

SystemError: <built-in function id> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-23-f2e7708b5cf8> in <module>
----> 1 scv.pp.filter_genes(adata, min_shared_counts = 30)

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/scvelo/preprocessing/utils.py in filter_genes(data, min_counts, min_cells, max_counts, max_cells, min_counts_u, min_cells_u, max_counts_u, max_cells_u, min_shared_counts, min_shared_cells, copy)
    194             gene_subset &= filter(X, min_cells=_min_cells, max_cells=_max_cells)[0]
    195 
--> 196         adata._inplace_subset_var(gene_subset)
    197 
    198         s = np.sum(~gene_subset)

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/anndata/_core/anndata.py in _inplace_subset_var(self, index)
   1214         Same as `adata = adata[:, index]`, but inplace.
   1215         """
-> 1216         adata_subset = self[:, index].copy()
   1217         self._init_as_actual(adata_subset, dtype=self._X.dtype)
   1218 

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1048         """Returns a sliced view of the object."""
   1049         oidx, vidx = self._normalize_indices(index)
-> 1050         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1051 
   1052     def _remove_unused_categories(self, df_full, df_sub, uns):

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/anndata/_core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    280             if not isinstance(X, AnnData):
    281                 raise ValueError("`X` has to be an AnnData object.")
--> 282             self._init_as_view(X, oidx, vidx)
    283         else:
    284             self._init_as_actual(

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/site-packages/anndata/_core/anndata.py in _init_as_view(self, adata_ref, oidx, vidx)
    328         self._varp = adata_ref.varp._view(self, vidx)
    329         # hackish solution here, no copy should be necessary
--> 330         uns_new = deepcopy(self._adata_ref._uns)
    331         # need to do the slicing before setting the updated self._n_obs, self._n_vars
    332         self._n_obs = self._adata_ref.n_obs  # use the original n_obs here

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in _deepcopy_dict(x, memo, deepcopy)
    239     memo[id(x)] = y
    240     for key, value in x.items():
--> 241         y[deepcopy(key, memo)] = deepcopy(value, memo)
    242     return y
    243 d[dict] = _deepcopy_dict

/primary/projects/mnp/tools/anaconda3/envs/alevin_env/lib/python3.7/copy.py in deepcopy(x, memo, _nil)
    159             copier = getattr(x, "__deepcopy__", None)
    160             if copier:
--> 161                 y = copier(memo)
    162             else:
    163                 reductor = dispatch_table.get(cls)

SystemError: <built-in method __deepcopy__ of numpy.ndarray object at 0x2aab0b27cc60> returned a result with an error set

**Comment by k3yavi** [comment]
@brejnev 

```
280 if not isinstance(X, AnnData):
281 raise ValueError("X has to be an AnnData object.")
--> 282 self._init_as_view(X, oidx, vidx)
283 else:
284 self._init_as_actual(
```

This could be an informative error, is your adata objec an `AnnData` object ?

**Comment by k3yavi** [comment]
@brejnev it seem to be a bug with scvelo package, please follow the following issue for more detail.
https://github.com/theislab/scvelo/issues/204
