### ISSUE TITLE
Feature request: infer library type without needed to run all of salmon quant

### ISSUE THREAD

**Issue by millerh1** [COMBINE-lab/salmon#534]
Hello! 

I absolutely love Salmon and use it whenever I get the chance. I've also found that the automatic inference of library type is an extremely powerful feature for other contexts outside of salmon mapping -- but virtually no other tools offer this capability and certainly not with the same speed as salmon. Would it be possible to make a small function Salmon or a standalone package that can be used to infer library type independent of salmon mapping?

Thanks!
Henry

**Comment by millerh1** [comment]
Never mind -- it looks like the mapping step is required... My bad!

**Comment by rob-p** [comment]
@millerh1,

  Thanks for the kind words about salmon! Mapping is required.  However, please check out [this issue](https://github.com/COMBINE-lab/salmon/issues/138) for an idea of how you might infer the library type without having to process all of the data, or undergo the entire quantification procedure.

Best,
Rob

**Comment by millerh1** [comment]
Thank you so much @rob-p -- I will try just running the first 100,000 reads or so with --skipQuant to get the library type.

Best,
Henry
