### ISSUE TITLE
Alevin with full length scRNA data (smart-seq etc)

### ISSUE THREAD

**Issue by gouthamatla** [COMBINE-lab/salmon#539]
Hi All,

I am wondering if Alevin can be used with scRNA data sets that are generated through plate based methods like smart-seq. I tried to use salmon but the estimated counts/TPMs seems to highly inflated.

For example, for this transcript, the output from a single cell looks like this.

```
Name    Length  EffectiveLength TPM     NumReads
ENST00000344843.7       721     250     247.016 471.945
```

If you see the bam file of the same cell, there are only around 50 reads mapped to that gene/transcript

![salmon](https://user-images.githubusercontent.com/4629007/85198080-143d3800-b2e6-11ea-8042-742772cb06da.PNG)

I am wondering why the values are inflated ? Could be due to default scaling factor used as for bulk-rna where the total counts tend to be in millions.  @rob-p 

I would like to know if I can use Alevin for plate-based methods where I have one bam file per cell.

Thanks,
Goutham A

**Comment by roryk** [comment]
Heya, you can just use Salmon for full-length transcript libraries, it works well. The number of reads isn't an absolute number so it can be different than the absolute number of reads, the important thing you are interested in is not the absolute number but the relative expression compared to everything else.

**Comment by gouthamatla** [comment]
Thanks.

**Comment by rob-p** [comment]
The response by genomax [here](https://www.biostars.org/p/444853/) is spot on too.  There are many, independent, overlapping reads here.  If you have some other reason to believe this is wrong, we’d be happy to investigate further.  However, I’m going to close the issue for the time being. 

P.S. Yes, salmon is the right tool for full-length, plate-based protocols.  Alevin is for tagged end (mostly droplet-based) protocols.
