### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by jorvis** [COMBINE-lab/salmon#54]
I've switched to using precompiled binaries, version 0.6.0.  Now working on a new server running CentOS Linux release 7.1.1503.  I was able to successfully generate my index, then started running the quantification step.  Here is my command:

`$ /home/jorvis/salmon/bin/salmon quant -p 24 -i transcripts_index -l IU -1 R1.trimmed.PE.fastq -2 R2.trimmed.PE.fastq -o transcripts_quan`

This host has 48 cores and 128GB RAM.  

And here is the STDOUT

```
Version Info: This is the most recent version of Salmon.
# salmon (mapping-based) v0.6.0
# [ program ] => salmon
# [ command ] => quant
# [ threads ] => { 24 }
# [ index ] => { transcripts_index }
# [ libType ] => { IU }
# [ mates1 ] => { R1.trimmed.PE.fastq }
# [ mates2 ] => { R2.trimmed.PE.fastq }
# [ output ] => { transcripts_quan }
Logs will be written to transcripts_quan/logs
[2016-03-30 15:50:48.489] [jointLog] [info] parsing read library format
there is 1 lib
Loading 64-bit quasi index[2016-03-30 15:50:48.543] [jointLog] [info] Loading Quasi index
[2016-03-30 15:50:48.544] [stderrLog] [info] Loading Suffix Array
[2016-03-30 15:50:48.544] [stderrLog] [info] Loading Position Hash
[2016-03-30 15:50:58.359] [stderrLog] [info] Loading Transcript Info
[2016-03-30 15:50:59.932] [stderrLog] [info] Loading Rank-Select Bit Array
[2016-03-30 15:51:00.610] [stderrLog] [info] There were 2027284 set bits in the bit array
[2016-03-30 15:51:00.917] [stderrLog] [info] Computing transcript lengths
[2016-03-30 15:51:00.925] [stderrLog] [info] Waiting to finish loading hash
Index contained 2027284 targets
[2016-03-30 15:51:08.499] [jointLog] [info] done
[2016-03-30 15:51:08.499] [stderrLog] [info] Done loading index




Segmentation fault
```

The only log file I see is this one:  transcripts_quan/logs/salmon_quant.log

$ cat salmon_quant.log 
[2016-03-30 15:50:48.489] [jointLog] [info] parsing read library format
[2016-03-30 15:50:48.543] [jointLog] [info] Loading Quasi index
[2016-03-30 15:51:08.499] [jointLog] [info] done

**Comment by rob-p** [comment]
Hi Josh,

  My best guess is that something is awry with the 64-bit index.  That code-path is less well-tested (since I don't really have any transcriptomes in my collection that exceed the size of a 32-bit signed int).  If you're able to share the txome and / or the index itself, I'd be happy to try and reproduce and fix this.  Actually, I'd be really happy to squash any bugs in the 64-bit code path.

--Rob

**Comment by jorvis** [comment]
OK, could you send me a private e-mail address so I don't post links for
the data publicly?

**Comment by rob-p** [comment]
Sure; its rob.[lastname]@cs.stonybrook.edu.  Sorry for the trouble you're encountering with the 64-bit index, but thanks for helping me track it down to fix!

**Comment by rob-p** [comment]
Ok, I think I tracked it down!  I'd forgot to replace `int` with the generic `OffsetT` in one function.  This led to the `int64_t` being interpreted as an `int32_t` and hence ... overflow.  I'll fix this upstream and push a new salmon binary (by the end of the week).  Luckily, this only affects mapping and not index building, so you can use the index you already have.

**Comment by rob-p** [comment]
Rather than hang you up in any way waiting on a release that adds ancillary improvements, I'm just putting an updated binary right here that addresses this issue.  Please let me know if this allows you to run your dataset on the large index successfully.
[SalmonBeta-0.6.5-pre_CentOS5.tar.gz](https://github.com/COMBINE-lab/salmon/files/197982/SalmonBeta-0.6.5-pre_CentOS5.tar.gz)

**Comment by jorvis** [comment]
Hmm, something's up.  I just deleted my previous transcripts_quan directory, replaced salmon with this newer version, and ran the same command.  It finishes almost immediately with a return value of 1.

```
$ /home/jorvis/salmon/bin/salmon quant -p 24 -i transcripts_index -l IU -1 R1.trimmed.PE.fastq -2 R2.trimmed.PE.fastq -o transcripts_quan
Version Info: This is the most recent version of Salmon.
# salmon (mapping-based) v0.6.0
# [ program ] => salmon 
# [ command ] => quant 
# [ threads ] => { 24 }
# [ index ] => { transcripts_index }
# [ libType ] => { IU }
# [ mates1 ] => { R1.trimmed.PE.fastq }
# [ mates2 ] => { R2.trimmed.PE.fastq }
# [ output ] => { transcripts_quan }
Logs will be written to transcripts_quan/logs
there is [2016-03-31 12:30:21.714] [jointLog] [info] parsing read library format
1 lib
[jorvis@grid-1-3-4 salmon]$ echo $?
1
[jorvis@grid-1-3-4 salmon]$ ls transcripts_quan
logs
[jorvis@grid-1-3-4 salmon]$ ls transcripts_quan/logs/
salmon_quant.log
[jorvis@grid-1-3-4 salmon]$ cat transcripts_quan/logs/salmon_quant.log 
[2016-03-31 12:30:21.714] [jointLog] [info] parsing read library format
```

**Comment by rob-p** [comment]
That's very strange in that it doesn't even seem to be trying to load the index!  I obviously don't have the same set of reads you do, but here is what I get when using this pre-compiled binary on the 64-bit index (this is a small read set from single-cell data, which is why the total # of reads is so small).

```
rob@feynman:/mnt/scratch3/rob/JoshTest$ ~/SoftwareStaging/salmon/scripts/SalmonBeta-0.6.5-pre_CentOS5/bin/salmon quant -p 15 -i salmon_index -l IU -1 ../strange_peak/19232_1_1.fastq -2 ../strange_peak/19232_1_2.fastq -o quant_binary
Version Info: This is the most recent version of Salmon.
# salmon (mapping-based) v0.6.0
# [ program ] => salmon
# [ command ] => quant
# [ threads ] => { 15 }
# [ index ] => { salmon_index }
# [ libType ] => { IU }
# [ mates1 ] => { ../strange_peak/19232_1_1.fastq }
# [ mates2 ] => { ../strange_peak/19232_1_2.fastq }
# [ output ] => { quant_binary }
Logs will be written to quant_binary/logs
there is 1[2016-03-31 14:05:14.184] [jointLog] [info] parsing read library format
 lib
Loading 64-bit quasi index[2016-03-31 14:05:14.266] [stderrLog] [info] Loading Suffix Array
[2016-03-31 14:05:14.266] [jointLog] [info] Loading Quasi index

[2016-03-31 14:07:58.647] [stderrLog] [info] Loading Transcript Info
[2016-03-31 14:08:59.703] [stderrLog] [info] Loading Rank-Select Bit Array
[2016-03-31 14:09:06.744] [stderrLog] [info] There were 2027284 set bits in the bit array
[2016-03-31 14:09:08.123] [stderrLog] [info] Computing transcript lengths
[2016-03-31 14:09:08.240] [stderrLog] [info] Waiting to finish loading hash
Index contained 2027284 targets
[2016-03-31 14:09:15.789] [jointLog] [info] done
[2016-03-31 14:09:15.786] [stderrLog] [info] Successfully loaded position hash
[2016-03-31 14:09:15.789] [stderrLog] [info] Done loading index












[2016-03-31 14:09:36.623] [jointLog] [info] Computed 8083 rich equivalence classes for further processing
[2016-03-31 14:09:36.623] [jointLog] [info] Counted 159824 total reads in the equivalence classes

[2016-03-31 14:13:24.480] [jointLog] [warning] Only 159824 fragments were mapped, but the number of burn-in fragments was set to 5000000.
The effective lengths have been computed using the observed mappings.

[2016-03-31 14:13:24.480] [jointLog] [info] Mapping rate = 36.3942%

[2016-03-31 14:13:24.480] [jointLog] [info] finished quantifyLibrary()
[2016-03-31 14:13:24.480] [jointLog] [info] Starting optimizer
[2016-03-31 14:13:25.441] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2016-03-31 14:13:25.660] [jointLog] [info] iteration = 0 | max rel diff. = 13.7627
[2016-03-31 14:13:26.460] [jointLog] [info] iteration = 100 | max rel diff. = 0.100799
[2016-03-31 14:13:27.252] [jointLog] [info] iteration = 200 | max rel diff. = 0.0452885
[2016-03-31 14:13:28.046] [jointLog] [info] iteration = 300 | max rel diff. = 0.0323517
[2016-03-31 14:13:29.037] [jointLog] [info] iteration = 400 | max rel diff. = 0.0173087
[2016-03-31 14:13:29.842] [jointLog] [info] iteration = 500 | max rel diff. = 0.0173241
[2016-03-31 14:13:30.837] [jointLog] [info] iteration = 600 | max rel diff. = 0.0131171
[2016-03-31 14:13:31.633] [jointLog] [info] iteration = 700 | max rel diff. = 0.0117939
[2016-03-31 14:13:32.631] [jointLog] [info] iteration = 800 | max rel diff. = 0.0102536
[2016-03-31 14:13:32.724] [jointLog] [info] iteration = 813 | max rel diff. = 0.00845215
[2016-03-31 14:13:32.998] [jointLog] [info] Finished optimizer
[2016-03-31 14:13:32.998] [jointLog] [info] writing output

[2016-03-31 14:13:36.554] [jointLog] [warning] NOTE: Read Lib [( ../strange_peak/19232_1_1.fastq, ../strange_peak/19232_1_2.fastq )] :

Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: quant_binary/libFormatCounts.txt for details
```

of course, it takes a stupid amount of time to load the giant index the first time around, but it seems able to do this successfully on my end (using the data you shared).  Do you have any idea why it may have quit?  What if you try running it with `gdb`; e.g.?

```
$ gdb /home/jorvis/salmon/bin/salmon
(gbd) r quant -p 24 -i transcripts_index -l IU -1 R1.trimmed.PE.fastq -2 R2.trimmed.PE.fastq -o transcripts_quan
```

does that give any more info into why it's not even loading the index?

**Comment by jorvis** [comment]
I actually just deleted the index and recreated it with the same command (but newer tool) then re-ran the quant step and it's running now.  It's searching just under 800GB of reads though, so I'm not sure how long it will take.  I'll let you know when it has completed.

**Comment by rob-p** [comment]
Great.  I'm not sure why the old index was problematic, but I'm glad this one seems to load successfully etc.  Also, I'm glad the read set is rather large, because this is one of those cases where the index loading time might otherwise trump the time related to map the reads on a smaller dataset!  I have some work to do in speeding up the loading of large indices.

**Comment by jorvis** [comment]
Interesting.  It got past the index loading step for me in under 10 seconds at least.  I could time it more properly if you like after this run has completed.

**Comment by rob-p** [comment]
That is interesting!  It could just be that you have a much faster disk ;P.

**Comment by jorvis** [comment]
Still going:

```
processed 229000000 fragments
hits: 1768721166, hits per frag:  7.72432
```

I asked our IT guy, and the hardware supporting that volume is a 1.3PB disk array on Oracle ZFS4-4, mounted using NFS v4.

**Comment by rob-p** [comment]
Thanks for asking.  It could be that ZFS is substantially faster for this purpose than ext4 (which is what I'm using).  It's interesting that there is so much multi-mapping in this dataset (looks like Salmon's found over 1.7 billion alignments so far; almost 8 hits per read on average).  I guess this is *somewhat* less surprising given that the contigs were (presumably) assembled using these same reads.

**Comment by jorvis** [comment]
Yes, this is a set of transcripts assembled using a few different Trinity and Velvet/Oases protocols, merged together.  I'm testing reduction with different tools along with relative abundance estimation.

**Comment by rob-p** [comment]
Ahh; cool!  That also explains the size ;).  If you're interested in evaluating & potentially merging assemblies, I can also point you at [transrate](https://github.com/Blahah/transrate), which you may find useful (cc @Blahah).

**Comment by Blahah** [comment]
I'm going to be daydreaming about that 1.3PB disk array for a while.

**Comment by jorvis** [comment]
I'm definitely spoiled on space.  That is only our scratch volume.  The
longer-term project storage area is quite a bit larger.  It seems like no
matter what you have though, it gets used.

**Comment by mdshw5** [comment]
<img width="32" alt="screen shot 2016-03-31 at 8 34 59 pm" src="https://cloud.githubusercontent.com/assets/819554/14194783/1bc2d8e4-f780-11e5-87ed-76a1ff423de9.png">
👋🎤(mic drop)

**Comment by jorvis** [comment]
Ha!  Impressive either way, but I think I see some shared volumes there.  :+1:

**Comment by rob-p** [comment]
Btw @mdshw5, you can try the --perfectHash option with the binary linked above if you want ;).

**Comment by jorvis** [comment]
My run finished successfully a few hours ago, btw.  Thanks for all your help!  Giving transrate a look.

**Comment by mdshw5** [comment]
Yes, shared volumes :( - thanks @rob-p for the update - I'll give it a shot on our large index and hopefully feel the benefit!

**Comment by rob-p** [comment]
@jorvis — ok; good. I'd be very worried if it was still going all this time later :)!

**Comment by kbchoi-jax** [comment]
@rob-p I tried SalmonBeta-0.6.5-pre_CentOS5.tar.gz but for some reason, it still make 32-bit index on my x86_64 machine. What do you think I am doing wrong?

```
$ salmon index -t emase.pooled.transcripts.fa -i salmon
Version Info: This is the most recent version of Salmon.
[2016-05-19 16:06:55.048] [jLog] [info] building index
RapMap Indexer

[Step 1 of 4] : counting k-mers
counted k-mers for 920000 transcriptsElapsed time: 24.0224s

Replaced 12 non-ATCG nucleotides
Clipped poly-A tails from 4247 transcripts
Building rank-select dictionary and saving to disk done
Elapsed time: 0.0972664s
Writing sequence data to file . . . done
Elapsed time: 0.872786s
[info] Building 32-bit suffix array (length of generalized text is 1561273393)
Building suffix array . . . success
saving to disk . . . done
Elapsed time: 3.65916s
done
Elapsed time: 265.19s
processed 1561000000 positions
khash had 135536906 keys
saving hash to disk . . . done
Elapsed time: 11.27s
[2016-05-19 16:19:10.357] [jLog] [info] done building index
```

**Comment by rob-p** [comment]
Hi @kbchoi-jax — the index size (i.e. 32 or 64-bit) is dependent only on how long the reference is, not the width of the machine on which you're running Salmon.  That is, if the reference is < 2.1G, then a 32-bit index will always be used (even on a 64-bit machine).  The purpose of the "64-bit" index is that it uses 64-bit indices when building the suffix array, so that it can distinguish positions on much larger reference sequences (up to 9223372036854775808 characters . . . but you'd run out of memory long before that ;P).
