### ISSUE TITLE
Write non-error output to stdout

### ISSUE THREAD

**Issue by rob-p** [COMBINE-lab/salmon#55]
As suggested by Nick Schurch, we should be writing non-error output (including simple logging and informative messages) to stdout rather than stderr.

**Comment by mdshw5** [comment]
I might add that the progress display is pretty, but having an option to exclude it from the stderr logging, or even have no status updates, would be helpful for log file analysis.

**Comment by rob-p** [comment]
duly noted!

**Comment by rob-p** [comment]
One issue with this (realizing this now that I've mostly made this change) is that it may conflict with writing pseudobam output, which, presumably we'd want to go to stdout by default so that it could be streamed into a bam compressor etc.  Is there an easier way to handle this?

**Comment by mdshw5** [comment]
I think logging non-error output to stderr is OK.

**Comment by rob-p** [comment]
The current behavior, which I think is the most reasonable for now, is to keep logging messages to stderr, even if they are not errors.  This lets us use stdout for output which may need to be redirected to other programs (e.g. mapping results).

**Comment by scottkall** [comment]
The downside of this choice, @rob-p, as may have been noted elsewhere, is that the user has to do this kind of thing to get the long documentation into `less`:

`salmon quant --help-reads 2>&1 | less`

And this behavior is very unusual among command-line tools when invoking `--help`

**Comment by rob-p** [comment]
Good point, @scottkall.  I think the correct longer-term solution to this is to implement the functional to write directly to BAM (or compressed SAM), which _should_ make the necessity of allowing the writing of the SAM output to stdout considerably less important.
