### ISSUE TITLE
Salmon 1.3.0 becomes stuck during the index command

### ISSUE THREAD

**Issue by arrowandbead** [COMBINE-lab/salmon#554]
This bug occurs in salmon 1.3.0
I installed by downloading the precompiled Linux binary from github and running salmon from that directory.
The issue comes as I try to follow the indexing steps on this page : 
https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/

When I try to use salmon index it runs as normal but becomes stuck on : 

------------------------------
[2020-08-03 13:07:50.641] [puff::index::jointLog] [info] Replaced 78,088,277 non-ATCG nucleotides
[2020-08-03 13:07:50.641] [puff::index::jointLog] [info] Clipped poly-A tails from 753 transcripts
wrote 140775 cleaned references
[2020-08-03 13:07:54.854] [puff::index::jointLog] [info] Filter size not provided; estimating from number of distinct k-mers
[2020-08-03 13:08:34.650] [puff::index::jointLog] [info] ntHll estimated 2272527625 distinct k-mers, setting filter size to 2^36
Threads = 12
Vertex length = 31
Hash functions = 5
Filter size = 68719476736
Capacity = 2
Files: 
salmon_index/ref_k31_fixed.fa
--------------------------------------------------------------------------------
Round 0, 0:68719476736
Pass	Filling	Filtering

------------------------------

and never progresses past that point. I have to interrupt the program.

At first I tried to use my fasta sequences of interest, but after those didn't work I used the suggested sequences in the tutorial. Those also got stuck in the same place.

I expected the program to end and give me a message indicating success. The index file is generated but I suspect it is incomplete and I am hesitant to proceed without confirmation from the command line.

**Comment by rob-p** [comment]
Thanks for the report @arrowandbead,

  Can you say something about the machine that you're running the indexing command on, and the FASTA file you're trying to index?  We've seen poor behavior before specifically on cluster nodes with slow (networked) disk, but this should be largely mitigated in recent releases.

--Rob
