### ISSUE TITLE
Generating output with both FPKM and TPM unit

### ISSUE THREAD

**Issue by microjordan** [COMBINE-lab/salmon#566]
**Question: How to generate a Salmon output with both FPKM and TPM?**

Hello guys! I really enjoy using Salmon, but I recently encounter a problem regarding the output unit. 

I'm currently using Salmon version 1.2.0 for processing metagenomic data but I can only generate .sf file with 5 columns (Name, Length, EffectiveLength, TPM & NumReads).

From the information of the following website, Salmon seems to be capable to write the output as FPKM and TPM.
https://sailfish.readthedocs.io/en/master/salmon.html

I've tried to install the latest version of Salmon (1.3.0), but the output is still the same. So, does anyone know how to make such output?

Thanks!

**Comment by uros-sipetic** [comment]
Salmon doesn't produce FPKM values, but you can produce that yourself with a script easily. For example:

```
import argparse
import numpy as np
import pandas as pd

parser = argparse.ArgumentParser(
    description="Parses output quant.sf file form Salmon and converts TPM to "
                "FPKM based on formula FPKMi = 10^3 * TPMi / (sum_to_i(TPMi * effective_lengthi / 10^6))")
parser.add_argument("--quant_file", help="Salmon quant file with TPM values and effective lengths",
                    required=True)
parser.add_argument("--tpm_colname", help="Name of the coulmn in which TPM values are located",
                    required=True)
parser.add_argument("--eff_len_colname", help="Name of the coulmn in which effective length values are located",
                    required=True)
parser.add_argument("--extension", help="Extension of the input quantification file",
                    required=True)
args = parser.parse_args()

# Read input data
data = pd.read_csv(args.quant_file, sep='\t')

# Calculate FPKMs
l_bar = np.sum(data[args.tpm_colname]*data[args.eff_len_colname]/1000000)
data['FPKM'] = 1000/l_bar * data[args.tpm_colname]

# Change output name
file_name = args.quant_file.split('/')[-1].strip(args.extension)
new_name = file_name+'.with-FPKM'+args.extension

# Provide output 
data.to_csv(path_or_buf=new_name, sep='\t', index=False)
```

**Comment by ETaSky** [comment]
Hello,
I found there may be an error in the example code that posted by @uros-sipetic. I believe from my calculation, the correct equation for converting between FPKM and TPM should be: 
`FPKMi = 10^3 * TPMi / (sum_to_i(TPMi * effective_lengthi))`.

Thanks!
