### ISSUE TITLE
SALMON produce gigantic standard output?

### ISSUE THREAD

**Issue by yeodynasty** [COMBINE-lab/salmon#573]
Hi, 
just a quick check if it is normal for SALMON 1.3 to send > 100 Gb of output to the stdout, despite using the -quiet flag.

The quant mode appears to be running smoothly.
A sample of the output at the end of file:
<img width="960" alt="Screenshot 2020-10-15 14 23 42" src="https://user-images.githubusercontent.com/1333150/96084759-380a3680-0ef2-11eb-82ab-b5ea839c9113.png">

My command is as follow:
/gpfsdata/apps/salmon-latest_linux_x86_64/bin/salmon quant \
-i /gpfshome/hockchuan/SALMON/GCF_900626175.2_cs10_index \
-l ISR \
-1 /gpfsdata/JangiLab/hockchuan/170302/2.Trimmomatic_output/clean_HEADBANDSTEM_1.fastq.gz \
-2 /gpfsdata/JangiLab/hockchuan/170302/2.Trimmomatic_output/clean_HEADBANDSTEM_2.fastq.gz \
--seqBias \
--gcBias  \
--posBias \
--incompatPrior 0.0 \
--geneMap /gpfsdata/JangiLab/hockchuan/cs10_reference_genome/GCF_900626175.2_cs10_genomic.gtf \
--recoverOrphans \
--allowDovetail \
--threads $NSLOTS \
--dumpEq \
--minScoreFraction 0.65 \
--writeMappings /gpfshome/hockchuan/SALMON/MAP/HEADBANDSTEM \
--fldMean 250 \
--fldSD 25 \
--writeOrphanLinks \
--writeUnmappedNames \
--quiet \
-o /gpfshome/hockchuan/SALMON/HEADBANDSTEM_quant

**Comment by rob-p** [comment]
Hi @yeodynasty,

  This is because of the unfortunate conventions regarding the parsing of command line options in the presence of a flag that has an _implicit_ option.  Specifically, the `--writeMappings` flag has an implicit option.  Therefore, to provide an explicit option to the long-form argument flag, you must use the syntax `--writeMappings=<outputdir>`.  So, your command would look something like:


```
/gpfsdata/apps/salmon-latest_linux_x86_64/bin/salmon quant
-i /gpfshome/hockchuan/SALMON/GCF_900626175.2_cs10_index
-l ISR
-1 /gpfsdata/JangiLab/hockchuan/170302/2.Trimmomatic_output/clean_HEADBANDSTEM_1.fastq.gz
-2 /gpfsdata/JangiLab/hockchuan/170302/2.Trimmomatic_output/clean_HEADBANDSTEM_2.fastq.gz
--seqBias
--gcBias
--posBias
--incompatPrior 0.0
--geneMap /gpfsdata/JangiLab/hockchuan/cs10_reference_genome/GCF_900626175.2_cs10_genomic.gtf
--recoverOrphans
--allowDovetail
--threads $NSLOTS
--dumpEq
--minScoreFraction 0.65
--writeMappings=/gpfshome/hockchuan/SALMON/MAP/HEADBANDSTEM
--fldMean 250
--fldSD 25
--writeOrphanLinks
--writeUnmappedNames
--quiet
-o /gpfshome/hockchuan/SALMON/HEADBANDSTEM_quant
```

let me know if this resolves your issue.

Best,
Rob

**Comment by yeodynasty** [comment]
Thank you, will give a try.

**Comment by yeodynasty** [comment]
It works!

**Comment by rob-p** [comment]
Great!
