### ISSUE TITLE
Question about --noSingleFragProb

### ISSUE THREAD

**Issue by uros-sipetic** [COMBINE-lab/salmon#575]
Hey, what exactly does the parameter --noSingleFragProb do? 
Is Salmon now able to (somehow) model the fragment length distribution for Single End data as well? And this parameter turns that off then?
So, if I don't specify this option, do I not have to specify the mean and standard deviation for fragment distribution anymore, if working with single end data? 
Or am I misinterpreting this? :)

**Comment by rob-p** [comment]
Hi @uros-sipetic!

  Unfortunately, as you suggest, there really is no good way to infer the fragment length distribution from only single-end reads.  Rather, this flag determines how the conditional probability of single-end fragments near the beginning (if in the rc orientation) or end (if in the forward orientation) of the transcript are determined.  A single-end read does not have any known fragment length.  But we do know that e.g. fragments very close to the end or beginning of the transcript are rather unlikely.  In this case, we can integrate (sum) over all possibilities to assign a conditional probability.  This is what salmon does.  For a single-end read (assume forward orientation for simplicity) at position i on a transcript of length n, we consider the conditional fragment length probability to be given by F_n(n-i), where f_n is the conditional fragment length distribution conditioned on the transcript length (maximum observable length) being n and F_n is the cumulative distribution function of f_n.  Intuitively, this means that fragments very close to transcript ends will get a smaller conditional probability, while those farther from the end will get larger conditional probabilities.  The `--noSingleFragProb` flag simply turns off this conditional probability all together.  It is _not_ recommended to disable the single-end fragment length probability modeling.  We have evidence from testing that it improves quantification accuracy.  Thus, I would suggest _not_ setting the `--noSingleFragProb` flag.

Best,
Rob

**Comment by uros-sipetic** [comment]
Got it, thanks! So, keep not setting the --noSingleFragProb flag, and keep providing the fragment length distribution for single end reads. Thanks again @rob-p!
