### ISSUE TITLE
alevin tutorial setup ressources :: error

### ISSUE THREAD

**Issue by EricDeveaud** [COMBINE-lab/salmon#584]
Hello, 

while setting ressources for alevin test using: https://combine-lab.github.io/alevin-tutorial/2018/setting-up-resources/

generation of mapping file  txp2gene.tsv using given instruction is broken:

```
c6builder:salmon/1.3.0 > wget -q ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/gencode.v31.primary_assembly.annotation.gtf.gz
c6builder:salmon/1.3.0 > bioawk -c gff '$feature=="transcript" {print $group}' <(gunzip -c gencode.v31.primary_assembly.annotation.gtf.gz) | awk -F ' ' '{print substr($4,2,length($4)-3) "\t" substr($2,2,length($2)-3)}' - > txp2gene.tsv
/mount/gensoft2/exe/bioawk/1.0/bin/bioawk: illegal field $(), name "group"
 input record number 7, file /proc/self/fd/14
 source line number 1
```

https://github.com/COMBINE-lab/salmon/issues/336#issuecomment-496251814 point to bioawk modification that allows to generate `txp2gene.tsv`

please update docs !

regards

Eric

**Comment by k3yavi** [comment]
Sorry for the late reply, it has been fixed and merge today into the alevin-tutorial repo.
https://github.com/COMBINE-lab/alevin-tutorial/pull/15
