### ISSUE TITLE
Entry longer than 200000 nucleotides

### ISSUE THREAD

**Issue by guidohooiveld** [COMBINE-lab/salmon#591]
Hi,
When generating an index for the latest human gencode transcriptome (release 35) I noticed this message:
`[2020-11-25 09:42:04.534] [puff::index::jointLog] [warning] Entry with header [ENST00000674361.1|ENSG00000241743.4|OTTHUMG00000022220.5|OTTHUMT00000530527.1|XACT-203|XACT|347561|lncRNA|] was longer than 200000 nucleotides.  This is probably a chromosome instead of a transcript.`

Since I don't recall that I have seen this notification before when doing previous analyses, I had a look at this particular transcript. It turns out it indeed has been annotated as a (very long!), but apparently true transcript (a lncRNA):
`Transcript: XACT-203 ENST00000674361.1, Exons: 2, Coding exons: 0, Transcript length: 347,561 bps. Manual annotation (determined on a case-by-case basis) from the Havana project.`
See [here](http://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000241743;r=X:113616300-114059289;t=ENST00000674361).
 
I realize that this is not really a bug (you have to set such cutoff at some (likely arbitrary??) value), and it applies to only a single human transcript, but considering this case, would it also be OK to set the cutoff to e.g. 400k (instead of 200k)?

Thanks for addressing my curiosity!
Guido

**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
- salmon 1.3.0
**To Reproduce**
- I followed [this workflow](https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/) but using the latest human gencode files.
**Desktop (please complete the following information):**
 - OS: Linux Fedora

**Comment by rob-p** [comment]
Hi @guidohooiveld,

  Yes, the original cutoff was set to accomodate TITIN, which, at the time, was the longest human transcript.  Note, this warning doesn't prevent the transcript from being indexed, it just notifies the user its exceptionally long.  I think updating the warning threshold makes sense so that gencode indexes cleanly in this regard.  We'll update this.  Thanks for the report!

**Comment by rob-p** [comment]
This is fixed in https://github.com/COMBINE-lab/pufferfish/commit/e7fb924850e2a04793cdd2ace628afa8cf37885c, and should show up in the next (shortly coming) release.

**Comment by guidohooiveld** [comment]
Thanks a lot for your quick reply and 'fix'; much appreciated!

**Comment by rob-p** [comment]
Should be fixed now in 1.4.0.
