### ISSUE TITLE
How can I install salmon latest version via Conda?

### ISSUE THREAD

**Issue by lizhaozhi** [COMBINE-lab/salmon#592]
I tried to install salmon via conda:
conda install -c bioconda/label/main salmon 

but it seems not the latest version:
The following packages will be UPDATED:
  salmon                 bioconda::salmon-0.14.1-heb0d2e1_1 --> bioconda/label/main::salmon-0.14.2-ha956f45_0

https://anaconda.org/bioconda/salmon/labels

Thanks

**Comment by lizhaozhi** [comment]
If I install Salmon Binary:
[100%] Building CXX object src/CMakeFiles/salmon.dir/BAMUtils.cpp.o
[100%] Linking CXX executable salmon
/usr/bin/ld: ../../external/install/lib/libstaden-read.a(libstaden_read_la-open_trace_file.o): in function `find_file_url':
open_trace_file.c:(.text+0xf4e): warning: the use of `tempnam' is dangerous, better use `mkstemp'
during IPA pass: icf
lto1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/salmon.dir/build.make:421: src/salmon] Error 1
make[1]: *** [CMakeFiles/Makefile2:659: src/CMakeFiles/salmon.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by rob-p** [comment]
There is a (known) compiler error.  To compile from source, you should pass `-DNO_IPO=TRUE` to the `cmake` step.  That should fix your compile.

**Comment by ACastanza** [comment]
@lizhaozhi Do you have R 4.0.3 in your conda enviornment? 0.14 is the version of Salmon that conda tries to downgrade me to when I try to update from R 4.0.2 to R 4.0.3 see: https://github.com/COMBINE-lab/salmon/issues/594
