### ISSUE TITLE
Read quants_tier_mat.gz file

### ISSUE THREAD

**Issue by kikegoni** [COMBINE-lab/salmon#596]
Hey, 

First, thanks a lot for implementing Alevin for the analysis of scRNA-seq, it is super useful.

I would like to open the file ```alevin/quants_tier_mat.gz``` but I am not being able to do it. 

When I try to follow the parser instructions [here](https://github.com/k3yavi/vpolo/blob/242b519ea47eae1cce14bb3bafb736a1f3ad7d40/vpolo/alevin/parser.py) I am facing this error when importing sce:
```
ImportError: cannot import name 'sce' from partially initialized module 'sce' (most likely due to a circular import) (/home/egonie/.local/lib/python3.8/site-packages/sce/__init__.py)
```

I have already imported```vpolo``` which I have installed with: 
```
pip3 install vpolo
```

Also I have tested the R library ```fishpond```with the function
```
fishpond::readEDS(numOfGenes = num.genes, numOfOriginalCells = num.cells, countMatFilename = tier.file, tierImport = T)
```
Which outputs this message:
```
Error in validObject(x) : 
  invalid class "dgCMatrix" object: all row indices must be between 0 and nrow-1
```

Any insight that helps in reading Alevin tiers file would be much appreciated.

Thanks in advance and sorry for the inconveniences.

Best,

Kike

**Comment by k3yavi** [comment]
Hi @kikegoni ,

Thanks for reaching out, may I ask what version of salmon you are using ?

**Comment by kikegoni** [comment]
Hey @k3yavi ,

salmon 0.12.0

**Comment by k3yavi** [comment]
hey @kikegoni ,

I'd strongly advise updating to latest salmon. 0.12.0 is a bit old (released 16 cycles back) there were some bugs which we fixed over time. It'd be great if you can verify the issue persists with the latest release ?

**Comment by kikegoni** [comment]
Hey @k3yavi ,

Thank you for your suggestions. I Can confirm it works now. 

Best,

Kike
