### ISSUE TITLE
Can't use the salmon index

### ISSUE THREAD

**Issue by loverlyday** [COMBINE-lab/salmon#599]
![image](https://user-images.githubusercontent.com/33716378/100950925-6bf3f680-3548-11eb-9c5b-bdc1a5d6ce7f.png)
i get this information when i use the command : salmon index 
can anybody have the same problem,how should i do with these error
thanks!

**Comment by k3yavi** [comment]
hey @loverlyday ,

check the following page for the indexing tutorial

https://salmon.readthedocs.io/en/develop/salmon.html#preparing-transcriptome-indices-mapping-based-mode

**Comment by rob-p** [comment]
You can also pass `-h` to the salmon index command to get the usage information as `salmon index -h`.

**Comment by loverlyday** [comment]
> You can also pass `-h` to the salmon index command to get the usage information as `salmon in
thank you very much ,it works fine now
