### ISSUE TITLE
Significant performance regression in version 0.4.0

### ISSUE THREAD

**Issue by vals** [COMBINE-lab/salmon#6]
I tend to benchmark new versions of software mostly to check how much better things get over time at solving our problems. My strategy for benchmarking is to look at correlation between spike-ins at known abundances and estimated expression by software.

The latest version of Salmon (0.4.0) performs markedly worse than all the previous versions of Salmon on the same data.

![salmong-performance](https://cloud.githubusercontent.com/assets/668803/8134113/8ff1a4ae-1124-11e5-80d5-10022530ba99.png)

For running parameters, here is the top part of one of the `quant.sf` files

```
# salmon (smem-based) v0.4.0
# [ program ] => salmon 
# [ command ] => quant 
# [ index ] => { /nfs/research2/teichmann/reference/homo-sapiens/salmon/Homo_sapiens.GRCh38.78.cdna_ERCC }
# [ libType ] => { IU }
# [ threads ] => { 4 }
# [ mates1 ] => { /nfs/research2/teichmann/valentine/detection-comparison/salmon-comparison/human/SRP030617_HCT116_86_1.fastq }
# [ mates2 ] => { /nfs/research2/teichmann/valentine/detection-comparison/salmon-comparison/human/SRP030617_HCT116_86_2.fastq }
# [ output ] => { /tmp/SRP030617_HCT116_86_salmon_out }
# [ geneMap ] => { /nfs/research2/teichmann/reference/homo-sapiens/Homo_sapiens.GRCh38.78.cdna_ERCC.gene_map.txt }
# [ useVBOpt ] => { }
# [ mapping rate ] => { 48.8199% }
```

**Comment by rob-p** [comment]
Hi @vals,

  This is very interesting, as we've been doing quite a bit of testing and (to the contrary) have found v0.4.0 to perform substantially *better* than v0.3.x.  Out of curiosity, could you check how v0.4.0 performs *without* `--useVBOpt`?  Obviously, if you continue to see this regression, I'll be happy to try and dig down deeper, but I might need you to provide some testing data.

--Rob

**Comment by vals** [comment]
Indeed, there seem to be an issue with the VB!

![em-vs-vb](https://cloud.githubusercontent.com/assets/668803/8139050/66a879be-1148-11e5-93fb-02827f2185a1.png)

Not using VB gives exactly the same quantification as 0.3.2.

**Comment by rob-p** [comment]
Thanks for reporting back (with the nice plots!).  This is interesting, because, at least in our other testing, the VB seems to be performing slightly *better* than the EM.  One guess I have is that the VB Opt tends to produce slightly sparser solutions than the EM opt.  Usually, this is a "good thing".  However, if you're dealing with such small datasets (n ~50), then dropping a few points could make a significant difference.  Since you can reproduce the previous behavior when dropping the VB option, there's no rush.  However, if you are able to share some of the data at some point, I'd be interested in digging in and figuring out exactly what's happening here.

--Rob

**Comment by vals** [comment]
Could the "sparser solution" bit mean that more reads are required before convergence? All these data sets have pretty shallow sequencing depth. 

The data is public :), though two of the batches is behind an EGA wall. The other three batches are from [SRP030617](http://www.ebi.ac.uk/ena/data/view/SRP030617) and [SRP041736](http://www.ebi.ac.uk/ena/data/view/SRP041736).

In SRP030617 the samples with "Single Cell SMARTer" in the Experiment title field have ERCC spike-ins. And in SRP041736 the K562 cells have ERCC spike-ins (with the same library sequenced on HiSeq and MiSeq).

**Comment by dcjones** [comment]
I have a pretty wide array of benchmarks and I haven't seen any regression with the VB option on 0.4.1, including ERCC spike-ins on the SEQC data, where it does very well. But I haven't tested 0.4.0.

@vals your data looks really compelling, I wonder if you'd humor me and try something, if it's not too much trouble: Could you try recomputing these correlations excluding ERCC-00074 and ERCC-00130? I've seen some data suggesting these might be misannotated by the vendor, which can cause these two to have a large effect on something like Pearson correlation, especially with methods like salmon and cufflinks that do bias correction. In benchmarks I've done, excluding them leads to more reliable results.  I'm really curious if doing the same in your data changes anything.

**Comment by rob-p** [comment]
@vals, it shouldn't be a coverage issue, at least as compared to previous versions of Salmon.  Hopefully we'll have a chance to look at this soon and see if we can figure out what might be causing the performance "regression" when `--useVBOpt` is enabled.  As @dcjones suggests, we haven't really seen any performance degradation with the VB option in our other testing, so I suspect something characteristic of this dataset.

@dcjones; it's great to see you drop by!  I'm actually looking for a reasonable collection of datasets to do (automated) regression testing on new releases of salmon --- something to replace my fairly simple and manual existing regression tests.  I'd greatly appreciate any suggestions or advice you may have about this!  Such tests will become even more useful as we're experimenting with a few inference approaches and it would be great to have a reasonable spread of data to see the effects of different strategies.

**Comment by dcjones** [comment]
Happy to compare notes! For benchmarking accuracy I'm mostly using data from SEQC. There are four reference samples, each sequenced quite deeply at several different labs. I took 20 lanes from BGI, which is about 100 million reads, which I compare it to TaqMan (~800 genes), PrimePCR on (~18000 genes), and ERCC spike-ins. 

On top of that, to get more directly at isoform-level accuracy, I'm simulating data using rlsim, which I've found to be the least awful RNA-Seq simulator. Unlike most simulators, it models some technical effects/bias. I think it underestimates these, but still a lot better than most that assume perfect uniform random sampling, etc.

I also have a set of benchmarks designed to get at the question of consistency or stability of estimates, which is one of the main thrusts of the paper I'm working on.

The other aspect I've been fretting about a lot the last month has been just what metric to use. You should check out this paper if you haven't seen it, which is pretty eye-opening as to the problems with using correlation on compositional gene expression data.
> Lovell, D., Pawlowsky-Glahn, V., Egozcue, J. J., Marguerat, S., & Bähler, J. (2015). Proportionality: a valid alternative to correlation for relative data. PLoS Computational Biology, 11(3), e1004075. http://doi.org/10.1371/journal.pcbi.1004075

Those problems aren't unique to correlation. E.g. the "median relative difference" approach taken by the Kallisto paper is very much affected by this, I think even more so than correlation. The method I've adopted is to use the "proportionality correlation" they propose on page 9, and add 0.1 TPM to expression values to account for zeros and tiny values. It's not terribly sensitive to the additive constant and gives pretty reliable results in my experience.

I have a somewhat horrifying labyrinth of makefiles and julia code that runs all this which I'll probably make public on github in the next few weeks, which may or may not be helpful.

**Comment by ehiggs** [comment]
@vals your profiling work is pretty useful. It would be better if it were automated so you didn't have to do the work manually. Have you considered putting in a PR to get salmon and friends working with [asv](https://github.com/spacetelescope/asv)?
