### ISSUE TITLE
Transcriptome versions used at refgenomes.databio.org

### ISSUE THREAD

**Issue by kvittingseerup** [COMBINE-lab/salmon#614]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
Salmon

**Describe the bug**
I love how you provide pre-build indexes at http://refgenomes.databio.org/. Would it be possible to also annotate which version of the annotation you used?

Cheers
Kristoffer

**Comment by stolarczyk** [comment]
hey @kvittingseerup, glad to hear you find refgenie useful. 

Currently, there is no way to view the recipe inputs using the web interface or server API. That said, it is possible to track this information down... For example, for [`hg38/salmon_sa_index`](http://refgenomes.databio.org/v2/asset/hg38/salmon_sa_index/splash?tag=default) asset look at the "asset_parents" section to find out what assets were used to create the salmon index. Then, by looking at [this file](https://github.com/refgenie/refgenomes.databio.org/blob/master/asset_pep/recipe_inputs.csv) you can find out what are the sources of the files we used to create the parent `fasta*` assets in question. 

As an aside, we're working on a [new recipe system](https://github.com/refgenie/refgenie/issues/198) that will enable serving this kind of data on http://refgenomes.databio.org/.

**Comment by k3yavi** [comment]
Thanks @stolarczyk  for clarifying and @kvittingseerup  for raising the issue.
Please feel free to reopen the issue https://github.com/refgenie/refgenieserver/issues/102 if you have more questions.
