### ISSUE TITLE
salmon was only able to assign 0 fragments to transcripts in the index

### ISSUE THREAD

**Issue by gianfilippo** [COMBINE-lab/salmon#616]
Hi,

I have been running salmon  v1.4.0 on 324 samples. In 8 samples I did not get any quantification and the process ended with a warning like ".....salmon was only able to assign 0 fragments to transcripts in the index...."

The command line I used is as follow (I simplified the paths and file names):
salmon quant -p 20 -i Salmon_Index -l A --seqBias --gcBias --biasSpeedSamp -1 $FASTQ1.R1.fastq.gz -2 $FASTQ2.R2.fastq.gz -o $outDIR --validateMappings

These same 8 samples were processed with HISAT2 and the overall alignment rate was above 80%.

I attached the log file for one of the 8 runs
[logFile.txt](https://github.com/COMBINE-lab/salmon/files/5846381/logFile.txt)

Do you have any suggestions ? do you need more info ?

Thanks

**Comment by rob-p** [comment]
Hi @gianfilippo,

  Thank you for the report and for including the log File.  Can you share one of the problematic samples and the reference against which you are aligning?  One big difference is that the alignment rate reported by HISAT2 is to the genome, while for salmon it is with respect to the genome.  For certain samples (e.g. if you get a bad sample with poor rRNA depletion etc.) you can have many reads align to the genome, but none of them align to the annotated transcriptome.

--Rob

**Comment by gianfilippo** [comment]
Hi,

thanks for the prompt reply.

you are right, I went back to the FASTQ qc and noticed that this set of
samples all have a very low total number of reads and I would discard them.
I guess, it makes sense that the salmon did not assign fragments to any
transcripts.

I should have caught it. Sorry

Thanks for your help

**Comment by rob-p** [comment]
No worries; thanks for getting back!
