### ISSUE TITLE
Question: salmon index using spike in sequences

### ISSUE THREAD

**Issue by ConYel** [COMBINE-lab/salmon#621]
Dear Avi,
firstly, I would like to thank you for this remarkable tool, as it had helped me to create a strategy for the analysis of piRNAs in small RNAseq data!
I am using salmon for the quantification of small RNA sequences and spike-ins in samples from human tissue and cell lines.
For some reason, (still searching for possibly? mistyped command or something else) I wasn't able to have results on the spike in sequences.
Although in the past, I was able to do it, this time doesn't seem to work.
The commands I used can be found here: [wind](https://github.com/ConYel/wind/blob/main/GRCh38_STEP_1_annotation_forging.Rmd)
following the 819, 858+ line code.
I followed the instructions for decoy file from [here](https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/).
Is it possible to suggest potential solutions?

Thank you for your time!

> EDIT: adding the complete first email.

**Comment by k3yavi** [comment]
@ConYel is it possible to paste the email exchange here ? Let us know if the solution helped.

Thanks !

**Comment by ConYel** [comment]
@k3yavi 

> Dear Konstantinos,
> 
> Thanks for your kind words and reaching out with the issue.
> Unfortunately, I might need more information regarding the motivation of what you are trying to do. For example:
> 
> 1) Do you want to use spike sequence as the decoy sequence ? 
> A small background on decoys, in the paper we proposed to use the genome  as decoys, reason being
> salmon is a transcriptome aligner and we filter out reads which are mapping better to genomic region
> than transcriptomic regions to improve overall accuracy of the alignment methods. Similarly, in your
> Case if you use spike sequence as decoys, you are filtering out reads if they are mapping to
> Spike sequence. If you don’t want to do that then I’d suggest concatenating the two reference
> Sequence together and reindexing, instead of providing spike sequecnce as the decoy sequence.
> 
> 2) If you indeed are planning to use spike sequences as the decoy sequence then I am not
> Sure why you expect the results, by results I am assuming you mean the fasta id of the 
> Spike sequence are in the quants.sf file, which is an expected behavior.
> 
> Lastly, I’d like to request you to please raise the issue on the GitHub , mainly because of two
> Reasons - it will help others as well as us in case other have same question.
> 
> Hope this helps.
> Best,
> Avi


@ConYel 
 Dear Avi,
thank you for your prompt response,
indeed I didn't want to have the spike-in sequences in the decoys.
The issue was that I have created a concatenated fasta of the genome and the spike-ins
in order to make an index for STAR first, thus then just following
the instructions for the decoys file I also included them...

I am remaking the index now!

**Comment by ConYel** [comment]
Dear Avi,
everything works well know!

Thank you again for your assistance!

**Comment by k3yavi** [comment]
Glad to hear that.
