### ISSUE TITLE
Alevin DropSeq ~80% of Reads Thrown Away

### ISSUE THREAD

**Issue by ACastanza** [COMBINE-lab/salmon#625]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
Alevin
**Describe the bug**
Reanalyzing published Drop-Seq data the alevin analysis results in drastically fewer barcodes accepted than the published dataset. Published dataset contains 3000 CBs for the specific sample (authors report that 70% of [these] putative cells from WT mice met QC criteria), alevin result contains 459 CBs.
A similar highly abbreviated CB result was obtained with reanalysis of SRR8889412.

**To Reproduce**
Steps and data to reproduce the behavior:

Data used from Sample: https://www.ebi.ac.uk/ena/browser/view/SRR8889411
Publication: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6925218/#
Specific Sample: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3720936

Alevin was run using no special parameters with the --dropseq flags. The only significant protocol deviation was in index construction (see below)

Specifically, please provide at least the following information:

  * Which version of salmon was used?
   v1.4.0
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
    Salmon was run in stock docker container
  * Which reference (e.g. transcriptome) was used?
  Full decoy Index generated on Gencode M25 per Alevin Velocity tutorial with a k=17 (dataset has 50bp R2 Reads)
 Introns were extracted with 49bp flanking sequence. 
  ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz

  * Which read files were used?
   Data used from Sample: https://www.ebi.ac.uk/ena/browser/view/SRR8889411
  * Which which program options were used?
   --dropseq -l ISR

**Expected behavior**
Cell calls should be ballpark similar to published result (3000 original vs. 459 alevin)

**Tar of Alevin Output directory**
[WT01_P7_WT_Cerebellum_alevin.output.tar.gz](https://github.com/COMBINE-lab/salmon/files/5953855/WT01_P7_WT_Cerebellum_alevin.output.tar.gz)

**Comment by k3yavi** [comment]
Hi @ACastanza ,

Thanks for reaching out, please check if the following discussion helps answer some of the issues ?
https://github.com/COMBINE-lab/salmon/discussions/506

**Comment by ACastanza** [comment]
Hi @k3yavi,

I saw that post, however, the issue here is much more severe than the previously reported issue (they were seeing 15-40% reads thrown away because of noisy Cellular barcodes, this is closer to 80%, additionally, this experiment was previously published and saw nowhere near this looseness.

**Comment by k3yavi** [comment]
Yea, so Drop-seq data tends to be a bit more noisier than 10x, at least in my experience. 
I had a quick look at the logs and it seems the "knee" method is under estimating a bit. I highly recommend playing with the alevin flags from the discussion I forwarded, I think it should work fine with `--expectCells 3000` or `--forceCells 3000`. You can check and process the featureDump file from the alevin if you use `--dumpFeatures` flag to choose the number of barcodes to provide in the expectCells or forceCells command.

**Comment by ACastanza** [comment]
Ok, I'll give it a try with that flag. I'm working on implementing Salmon and Alevin (along with support for full and partial decoy indexing and preprocessing to add intron flanking sequences for velocity) in GenePattern so I needed to test that flag anyway.

**Comment by ACastanza** [comment]
--expectCells 3000 was an improvement, but still *very* low 

[2021-02-09 13:13:14.499] [alevinLog] [info] Done barcode density calculation.
[2021-02-09 13:13:14.499] [alevinLog] [info] # Barcodes Used: 210762147 / 210762147.
[2021-02-09 13:13:15.235] [alevinLog] [info] Total 1697(has 565 low confidence) barcodes
[2021-02-09 13:13:16.016] [alevinLog] [info] Done True Barcode Sampling
[2021-02-09 13:13:16.304] [alevinLog] [warning] Total 60.1025% reads will be thrown away because of noisy Cellular barcodes.
[2021-02-09 13:13:16.399] [alevinLog] [info] Done populating Z matrix
[2021-02-09 13:13:16.416] [alevinLog] [info] Total 60244 CB got sequence corrected
[2021-02-09 13:13:16.423] [alevinLog] [info] Done indexing Barcodes
[2021-02-09 13:13:16.423] [alevinLog] [info] Total Unique barcodes found: 2354754
[2021-02-09 13:13:16.423] [alevinLog] [info] Used Barcodes except Whitelist: 59119
[2021-02-09 13:13:16.471] [alevinLog] [info] Done with Barcode Processing; Moving to Quantify

**Comment by ACastanza** [comment]
Hey @k3yavi,

Most of the samples ran fine with --expectCells 3000, one did not, it gave an error:
[2021-02-10 18:43:12.296] [alevinLog] [info] Done barcode density calculation.
[2021-02-10 18:43:12.296] [alevinLog] [info] # Barcodes Used: [32m135909784[0m / [31m135909784[0m.
[2021-02-10 18:43:13.337] [alevinLog] [error] Can't find right Boundary.
Please Report this issue on github.

Rerunning it with --forceCells 3000 "worked"  (output was generated). I'm attaching the alevinQC report (renamed to .txt)
[MB15_alevinReport.html.txt](https://github.com/COMBINE-lab/salmon/files/5961312/MB15_alevinReport.html.txt)
 To see if you have any thoughts on what may be going on with this sample.
