### ISSUE TITLE
Alevin with bootstrap returns no output

### ISSUE THREAD

**Issue by AnnaAMonaco** [COMBINE-lab/salmon#636]
Hello,

I have a 10x scRNA-seq dataset I would like to run Alevin on, with bootstrapping. I am working on a cluster and submitting my script (I'll paste it below) with a Slurm scheduler.

My issue is that the job runs for a couple of seconds, then gives me this massive “core” output - that is encrypted someway and I can’t read - and then an empty log and an empty alevin.log, so I don’t even have anything to use for troubleshooting.

```
(salmon) [amonaco_m@med0113 1_bootstrappedAlevin]$ ls -al
total 47106
drwxrwxr-x 3 amonaco_m hpc-ag-zinzen     4096 Mar  3 11:00 .
drwxrwxr-x 4 amonaco_m hpc-ag-zinzen     4096 Mar  2 11:47 ..
drwxrwxr-x 2 amonaco_m hpc-ag-zinzen     4096 Mar  3 11:00 alevin
-rw------- 1 amonaco_m hpc-ag-zinzen 36540416 Mar  3 11:00 core.39485
-rw-rw-r-- 1 amonaco_m hpc-ag-zinzen        0 Mar  3 11:00 logs
(salmon) [amonaco_m@med0113 1_bootstrappedAlevin]$ ls -al alevin
total 1
drwxrwxr-x 2 amonaco_m hpc-ag-zinzen 4096 Mar  3 11:00 .
drwxrwxr-x 3 amonaco_m hpc-ag-zinzen 4096 Mar  3 11:00 ..
-rw-rw-r-- 1 amonaco_m hpc-ag-zinzen    0 Mar  3 11:00 alevin.log
```

I have used Salmon Alevin before on this dataset - without the bootstrap option - while providing the Cell Ranger whitelisted barcodes, and everything has gone smoothly (same script as below, commented out line). I have tried increasing the allotted memory and thread number as well, but with no change in outcome. Have you ever encountered something like this or could address me to where the issue may be (I'm assuming something to do with the bootstrap)?

*****Script I submit:*****
```
#!/bin/bash
# expected run time  
#SBATCH --time=24:00:00 
# Combine stderr and stdout log files into the stdout log file.
#SBATCH -o without -e
# Keep current environment variables.
#SBATCH --export=variables
# number of cores
#SBATCH -n 30
# expected memory to be used
#SBATCH —mem=50000
# Specify queue via expected length of job. 
#SBATCH --partition=medium
# Set the log directory.
#SBATCH -o logs

####declarations
conda activate salmon

Read1=$1 # fastq file - CB+UMI
Read2=$2 # fastq file - insert read
index=$3 # directory from salmon index
outDir=$4 # output directory
tsv=$5 # tsv containing txp-gene-id pairs
whitelist=$6 # cell ranger output barcodes

salmon alevin -lISR -1 $Read1 -2 $Read2 --chromiumV3 -i $index -p 8 -o $outDir --tgMap $tsv --whitelist $whitelist --numCellBootstraps 20 --dumpFeatures

#salmon alevin -lISR -1 $Read1 -2 $Read2 --chromiumV3 -i $index -p 8 -o $outDir --tgMap $tsv --whitelist $whitelist

```

Thank you in advance!
Anna

-------------------------
Additional FYI:
```
(salmon) [amonaco_m@med0113 1_bootstrappedAlevin]$ salmon version
Version Info: This is the most recent version of salmon.
salmon v1.4.0

Usage:  salmon -h|--help or 
        salmon -v|--version or 
        salmon -c|--cite or 
        salmon [--no-version-check] <COMMAND> [-h | options]

Commands:
     index      : create a salmon index
     quant      : quantify a sample
     alevin     : single cell analysis
     swim       : perform super-secret operation
     quantmerge : merge multiple quantifications into a single file
```

**Comment by k3yavi** [comment]
Hi @AnnaAMonaco ,

Is it possible to check if you can replicate the issue on a local environment as well ? I've not seen such issue, it could be some HPC related restrictions.

**Comment by AnnaAMonaco** [comment]
Hi @k3yavi ,

Thank you for your reply, it ended up actually being an issue with the cluster as you anticipated. Everything works fine otherwise!

Cheers,
Anna
