### ISSUE TITLE
Problem with "[error] In FixFasta, two references with the same name but different sequences: lcl. We require that all input records have a unique name up to the first whitespace (or user-provided separator) character." Error

### ISSUE THREAD

**Issue by TorkelE** [COMBINE-lab/salmon#642]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
It occurs when I run Salmon

**Describe the bug**
When I try to index I get an error
```
[2021-03-30 14:29:34.670] [puff::index::jointLog] [error] In FixFasta, two references with the same name but different sequences: lcl. We require that all input records have a unique name up to the first whitespace (or user-provided separator) character.
```
I asked for advice, and it was suggested that two entries in the fasta file had the same name. I tried loading all of the entry names into a computing language, and check that the number of unique names was identical to the total number (suggesting that this wasn't the case).

**To Reproduce**
I required to re-run some RNA seq mapping from someone who left the lab, and gave me this script (I've asked them, they did not really know what got wrong).

```
conda create --name rnaseq -c bioconda salmon
conda activate rnaseq
conda install -c conda-forge -c bioconda salmon=1.4.0
mkdir -p reference 


# reference genome
wget -O reference/genome.fa.gz https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/497/485/GCA_000497485.1_ASM49748v1/GCA_000497485.1_ASM49748v1_genomic.fna.gz

# reference Transcriptome
wget -O reference/transcripts.fa.gz https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/497/485/GCA_000497485.1_ASM49748v1/GCA_000497485.1_ASM49748v1_cds_from_genomic.fna.gz

# prepare file with "decoy" sequences
zcat reference/genome.fa.gz | grep "^>" | cut -d " " -f 1 | sed -e 's/>//g' > reference/decoys.txt


# concatenate the two
cat reference/transcripts.fa.gz reference/genome.fa.gz > reference/gentrome.fa.gz

# Try to create index, this gives problems
salmon index -t reference/gentrome.fa.gz -d reference/decoys.txt -p 12 -i salmon_index --gencode -k 31
```

The last one gives an error:
```
Version Info: This is the most recent version of salmon.
[2021-03-30 14:29:34.652] [jLog] [info] building index
out : salmon_index
[2021-03-30 14:29:34.653] [puff::index::jointLog] [info] Running fixFasta

[Step 1 of 4] : counting k-mers
[2021-03-30 14:29:34.670] [puff::index::jointLog] [error] In FixFasta, two references with the same name but different sequences: lcl. We require that all input records have a unique name up to the first whitespace (or user-provided separator) character.
```

**Desktop (please complete the following information):**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by jrm5100** [comment]
I ran into this issue when creating an index as well.  I was using the Mouse Gencode reference concatenated with a bacterial reference.  I removed the `--gencode` option to resolve it.  

I'm guessing the names of bacterial transcripts in mine became identical after being altered due to this option.  You're likely having a similar issue since you aren't using a Gencode reference.

**Comment by TorkelE** [comment]
Yes, something like that is probably what happened. Thanks for the note!
