### ISSUE TITLE
Using custom cell barcodes in alevin

### ISSUE THREAD

**Issue by curtisd0886** [COMBINE-lab/salmon#654]
Is it possible to use alevin with cell barcodes that have constant regions within them (see example below)?

bbbbbbccccccccccccbbbbbbcccccccccccc bbbbbb

**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

**Describe the bug**

**To Reproduce**
Steps and data to reproduce the behavior:

Specifically, please provide at least the following information:

  * Which version of salmon was used?
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
  * Which reference (e.g. transcriptome) was used?
  * Which read files were used?
  * Which which program options were used?

**Expected behavior**

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by k3yavi** [comment]
Hey @curtisd0886 ,

Thanks for reaching out. Please check the following discussion for the details about how you can specify the specific geometry. 
https://github.com/COMBINE-lab/salmon/issues/445#issuecomment-777884823
