### ISSUE TITLE
salmon-sa-index on refgenie

### ISSUE THREAD

**Issue by JennyFrodoBrynnNick** [COMBINE-lab/salmon#658]
Hi,
for a previous human deep mRNA-seq project I had downloaded the full decoy-aware hg38 salmon index from refgenie. I am now working on a new project and I see that the full index is no longer available on refgenie. Is this index available somewhere or do I need to construct it?
Thanks, Ina

**Comment by k3yavi** [comment]
I have raised the issue on refgenie repo, please check the above issue. Unfortunately we haven't maintained the salmon index anywhere else and you might have to create one.
