### ISSUE TITLE
Alevin cannot match the barcode ID in the whitlist.

### ISSUE THREAD

**Issue by JunweiLiu0208** [COMBINE-lab/salmon#672]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
alevin
**Describe the bug**
Alevin cannot map the reads with provided cell barcode in the whitelist.

The running code is :
salmon alevin -l ISR -1 ./YF_008/YF008_Sample_R1.fastq.gz -2 ./YF_008/YF008_Sample_R2.fastq.gz -i /Disk1/Zeng_Align/index -o ./Alevin_0615 -p 20 --end 5 --umiLength 16 --barcodeLength 16 --whitelist ./WhiteListTmp.txt --tgMap /Disk1/Zeng_Align/txp2gene.tsv --freqThreshold 0 --dumpFeatures --noQuant 

The cell barcode in the whitelist is confirmed within the top-16 bases of reads in the R1 file.

Cell barcode in the white list
GGATATGGATACGCGT

Reads:
@A00265:667:H7H75DSX2:4:1101:16667:11099 1:N:0:CAGTACTG
GGATATGGATACGCGTTAACCCGAACCAACACTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTATGTGTTAGTTGTATTTTTTTATATATATATTTTTTTTTTTCCCCCATTTTTTACCTCA
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFF:FFF:F::F:::FFFF,,,:,F,,,,:,F,:,F,FF,,:,,,,,,,:,F,,,,,F,:,,F,,F,,:,F,,,:,F,

Alevin output:
"[2021-06-16 03:54:34.292] [alevinLog] [info] Done importing white-list Barcodes
[2021-06-16 03:54:34.292] [alevinLog] [warning] Skipping 1 Barcodes as no read was mapped
[2021-06-16 03:54:34.292] [alevinLog] [info] Total 0 white-listed Barcodes
[2021-06-16 03:54:34.292] [alevinLog] [info] Sorting and dumping raw barcodes
[2021-06-16 03:54:34.296] [alevinLog] [warning] Total 100% reads will be thrown away because of noisy Cellular barcodes.
[2021-06-16 03:54:34.296] [alevinLog] [info] Done populating Z matrix
[2021-06-16 03:54:34.296] [alevinLog] [warning] 0 Whitelisted Barcodes with 0 frequency"

The sample fastq files and the whitelist file are attached.

[YF008_Sample_R1.fastq.gz](https://github.com/COMBINE-lab/salmon/files/6655505/YF008_Sample_R1.fastq.gz)
[YF008_Sample_R2.fastq.gz](https://github.com/COMBINE-lab/salmon/files/6655507/YF008_Sample_R2.fastq.gz)
[WhiteListTmp.txt](https://github.com/COMBINE-lab/salmon/files/6655508/WhiteListTmp.txt)

Thank you very much, and looking forward to your responses!

**Comment by k3yavi** [comment]
Hi @JunweiLiu0208 ,

Thanks for reaching out, seemingly the fastq file you shared `YF008_Sample_R1.fastq.gz` doesn't have the reads with `GGATATGGATACGCGT` as the Cellular barcodes, that's why alevin is complaining. 
![image](https://user-images.githubusercontent.com/8772521/122650560-ad717b00-d101-11eb-8f5d-6a2054822c79.png)

**Comment by JunweiLiu0208** [comment]
Thank you, I will try the different setting of the flag --freqThreshold
