### ISSUE TITLE
Salmon: Mixed Paired-end, single-end inputs for the same sample/library

### ISSUE THREAD

**Issue by ETaSky** [COMBINE-lab/salmon#675]
Hi Salmon developers,

I wonder if Salmon can handle both paired-end reads, and single-end orphan reads from the same library as inputs. These inputs reads are from trimmomatic outputs, which would generate 4 files: Paired-end reads both pass QC, and 2 of the orphan forward or reverse reads that also passed QC. 

In my project, I found that for all of my 49 samples (~25M PE reads/sample), I had about ~70% of reads from each sample are Paired-end both pass QC, and another ~25% are orphan reads (expectedly majority are forwarded reads). 25% seems to be too big for me, so I was thinking to utilize those orphan reads. 

Since I wasn't sure if Salmon can handle these inputs in the same run, I initiated 2 runs of salmon, one for PE, one for SE, as follows:
```
# Mapped PE pass QC
parallel -a data/raw_filenames.txt -j 3 --results logs/salmon_map_PE/ --joblog logs/salmon_map_PE.log \
    salmon quant -i data/reference/MmvM27_salmon_ind -l IU \
        -1 data/qc/{}_O1_paired.fastq.gz \
        -2 data/qc/{}_O2_paired.fastq.gz \
        -p 8 \
        --validateMappings \
        --recoverOrphans \
        --allowDovetail \
        --useVBOpt \
        --seqBias \
        -o data/mapped_salmon/{}_quant &

# Mapped SE pass QC
# --fldMean and --fldSD is set based on the PE run results
parallel -a data/raw_filenames.txt -j 3 --results logs/salmon_map_SE/ --joblog logs/salmon_map_SE.log \
    salmon quant -i data/reference/MmvM27_salmon_ind -l U \
        -r data/qc/{}_O1_unpaired.fastq.gz data/qc/{}_O2_unpaired.fastq.gz \
        -p 8 \
        --validateMappings \
        --fldMean 265 \
        --fldSD 105 \
        --useVBOpt \
        --seqBias \
        -o data/mapped_salmon/SE/{}_quant &
```
But I wasn't sure if the outputs can be directly combined by addition. From TPM definition, I don't think it can be added together for the same transcript of in the same sample. But can I use the NumReads column from the 2 runs, and add them together and then re-generate the combined TPM?

Thank you very much!

Jincheng

**Comment by rob-p** [comment]
I would certainly not quantify them separately.  If you really want to include the single-end reads, the best thing you might do is to pair them in the input with decoy/fake/random mates, and ensure that you have enabled orphan mapping.  In this case, salmon will map one read of the pair even if the other doesn't map anywhere.
