### ISSUE TITLE
Duplicates error

### ISSUE THREAD

**Issue by rudondamba** [COMBINE-lab/salmon#683]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

**Describe the bug**
I am getting this error : Two references with the same name but different sequences: XR_001465382.2_LOC4
21118_-. We require that all input records have a unique name up to the first whitespace character. But when I try to create a histogram of that reference it only shows 1 sequence with that name: 
 grep 'XR_001465383.2_LOC421108' galGal6.gene+cluster+repBase+tRNA.fa.nodup | sort | uniq -c | awk '{printf("%s\t%s\n", $1, $2)}'
1       >XR_001465383.2_LOC421108_-

**To Reproduce**
This is the code I used 
salmon index -t galGal6.gene+cluster+repBase+tRNA.fa.nodup -i SalmonIndexNodup  -k 31

Specifically, please provide at least the following information:

  * Which version of salmon was used?
  I used v1.5.1
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
  Yes
  * Which reference (e.g. transcriptome) was used?
  Mouse (mm10)
  * Which read files were used?
  * Which which program options were used?

**Expected behavior**

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by rob-p** [comment]
Hi @rudondamba,

  We'd be happy to look into this.  Can you share the specific reference fasta file you are attempting to index (`galGal6.gene+cluster+repBase+tRNA.fa.nodup`)?
  
Thanks,
Rob

**Comment by rudondamba** [comment]
Thank you @rob-p . It's a pretty big file to copy and paste. I am still new to the platform, how best can I share it with you?

**Comment by rob-p** [comment]
Hi @rudondamba,

  There are a few options.  If it's less than ~10MB, then you can just drop the file into the text box in the GitHub web interface here, and it will upload it and provide a link.  If it's a few hundred MB or so, as is typical of many transcriptomes, the best thing to do might be to put it up on Google Drive or Box or Dropbox (whatever you have access to) and share a link.

--Rob

**Comment by rudondamba** [comment]
Okay, here is a dropbox link:https://www.dropbox.com/s/mxv071uwyqvevs1/galGal6.gene%2Bcluster%2BrepBase%2BtRNA.fa.nodup?dl=0

**Comment by rob-p** [comment]
Hi @rudondamba,

  The problem is that the sequence on line `30403` is parsed as "empty", since there is a space after the initial `>` and before the sequence name.  This messes up the state of the underlying parser leading to the (in this case, uninformative) error message you are observing.  If you fix the name online `30403`, then you should be able to index the transcriptome as expected.  Let me know if this works for you.

--Rob

**Comment by rudondamba** [comment]
Thank you very much! Do you know the reference name?

**Comment by rob-p** [comment]
It is `NM_001318772.1_Unfound_-`.

--Rob

**Comment by rudondamba** [comment]
Okay I found it thank you! Could you please tell me how you found that line with the problem(I am assuming you didnt manually go through the file)? I am using linux and would like to know how to trouble shoot in the future

**Comment by rob-p** [comment]
Sure!  So, I had a hunch that the problem might be the fasta file. I don't have a formal mechanism for hunches; just experience seeing a lot of weird edge cases.  But then I used this [fantastic pedantic fasta parser](https://github.com/kloetzl/pfasta) to actually check that hunch and report the location of the first non-conformant record.  In this case, there was only one non-conformant record.

Best,
Rob
