### ISSUE TITLE
Allow for comma-separate list of files as input

### ISSUE THREAD

**Issue by jorvis** [COMBINE-lab/salmon#69]
When we want to use Salmon to align the output from multiple sequencing libraries, we have to cat all the R1 files together first into one file, then all the R2 ones into another FASTQ file so we can pass these to the -1 and -2 arguments.  It would be great if these arguments supported comma-separated lists of files rather than just the raw file.  This would save both the time of merging the files as well as disk space required to copy them all.

**Comment by rob-p** [comment]
Hi Josh,

  Salmon already supports lists of files, though it uses space as a separator (there are various reasons a comma might be a better separator, and I'll definitely consider this in the future).  For example, it's currently possible to pass a list of files to `-1` and `-2` as a space separated list.  For example, consider `lib_1_1.fq`, `lib_1_2.fq`, `lib_2_1.fq` and `lib2_2.fq` as the first and second pairs from two separate libraries (`lib_1` and `lib_2`).  You can run something like:

```
> salmon quant -i index -l IU -1 lib_1_1.fq lib_2_1.fq -2 lib_1_2.fq lib2_2.fq -p 8 -o quant
```

and Salmon will read from `lib_1_1.fq`, `lib_1_2.fq` in sync and then from `lib_2_1.fq` and `lib2_2.fq`.  It will read these back to back as if they were one library.  If the files are gzipped, it's a little bit tricker (not in the upcoming v0.7.0 which supports gzipped input directly), but you could use:

```
> salmon quant -i index -l IU -1 <(gunzip -c lib_1_1.fq.gz lib_2_1.fq.gz) -2 <(gunzip -c lib_1_2.fq.gz lib2_2.fq.gz) -p 8 -o quant
```

and this will decompress the reads and stream them into salmon the the right order.  I'll note that the process substitution syntax can also be used even without zipped files.  For example, the following command is practically equivalent to the first command I showed:

```
> salmon quant -i index -l IU -1 <(cat lib_1_1.fq.gz lib_2_1.fq.gz) -2 <(cat lib_1_2.fq.gz lib2_2.fq.gz) -p 8 -o quant
```

The point is, even with the v0.6.0 and earlier parser, you should never have to physically create one file from which to read the sequences.

**Comment by jorvis** [comment]
Very good to know.  I didn't see anything about the space separation in the documentation, but perhaps I missed it.  This was great information, thank you.

**Comment by rob-p** [comment]
I think you're right that a good description of this is missing from the docs; I'll add it.

Thanks!
Rob

**Comment by knokknok** [comment]
I was wondering...
When using options --seqBias, --gcBias, and/or --posBias with several fastq files generated from different flowcells (but same sample and library), is it better to process the fastq files independently or is it ok to use the space-separated "trick"?
