### ISSUE TITLE
Issue Using Precomputed Indecies with Salmon

### ISSUE THREAD

**Issue by saipra003** [COMBINE-lab/salmon#690]
Hi, 
This is my first time posting here. I have been trying to get Salmon to work for the past few days but kept running into the same issue (shown below). Any help or tips would be greatly appreciated!

**This bug/issue is primarily related to salmon in bulk mode.**

**Bug/issue Description**
I'm trying to use Salmon with precomputed indecies that I downloaded from the refgenie website (located [here](http://refgenomes.databio.org/v3/genomes/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4)), but when I pass in the index and my `.fastq.gz` files into Salmon I am encountering an error (shown below). 

**To Reproduce**

- Used Salmon version 1.2.1
- Downloaded the index (aka the reference transcriptome from refgenie website (located [here](http://refgenomes.databio.org/v3/genomes/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4)).
- Attempted to pass in trimmed .fastq.gz files (the files were trimmed using the FASTQC quality control pipeline) using the following command

> `salmon quant -i default -l A -1 <(gunzip -c <path to .fastq.gz file>) -2 <(gunzip -c <path to .fastq.gz file>) --validateMappings -o salmon_output`

- Received error shown below.

![image](https://user-images.githubusercontent.com/67990244/126880016-0c556d6f-a4f6-4a4b-9906-29d9fc06e00d.png)

**Expected behavior**
I expected this program to run normally and generate the quantification output files. 

**Desktop (please complete the following information):**
- OS: RedHat Linux Enterprise
- More information in screenshot below
![image](https://user-images.githubusercontent.com/67990244/126880058-d03a8247-7eea-4108-b2c2-0566ff2c975f.png)

**Comment by saipra003** [comment]
Hi, 
I solved this problem by upgrading to Salmon version 1.5.2

**Comment by rob-p** [comment]
Hi @saipra003,

  Thank you for posting the issue, and also following up with the resolution.  It’s not immediately clear why there would have been an issue with 1.2.1, but we’ll be sure to make not of this for anyone else who runs into such an issue with older releases.

Best,
Rob
