### ISSUE TITLE
Extra `:` inside quotes of salmon_version in cmd_info.json file for salmon v1.5.2

### ISSUE THREAD

**Issue by allyhawkins** [COMBINE-lab/salmon#691]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
Alevin-fry

**Describe the bug**
The new updates to the `cmd_info.json` file result in an extra `:` at the end of `"salmon_version:"` inside the quotes. This results in the json file being read in with the header of that entry being `salmon_version:` when it should be `salmon_version`. 

Note that this was found when running `salmon alevin` in the `--rad` or `--justAlign` mode and we have not tested if this is also the case when running only `salmon alevin`. 

**To Reproduce**
Steps and data to reproduce the behavior:
We ran alevin-fry v0.4.1 starting with `salmon alevin` using `--rad` on single-cell data in the salmon biocontainer and that led to the `cmd_info.json` file being output with the extra `:` on salmon_version. 

The biocontainer that we used was: quay.io/biocontainers/salmon:1.5.2--h84f40af_0 

Specifically, please provide at least the following information:

  * Which version of salmon was used?
1.5.2
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
  used the biocontainer 
  * Which reference (e.g. transcriptome) was used?
  used the splici index following the alevin-fry tutorial 
  * Which read files were used?
  * Which which program options were used?
  ```
salmon alevin -l ISR --chromiumV3 --dumpFeatures --rad
```

**Expected behavior**
We would expect that the extra `:` would not be included to be consistent with previous versions of salmon. 
<img width="325" alt="Screen Shot 2021-07-29 at 12 35 38 PM" src="https://user-images.githubusercontent.com/54039191/127538599-206d5e71-cb7a-4a82-8064-4e92e12ee892.png">

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by rob-p** [comment]
Thanks for the super-detailed report, @allyhawkins.  We'll fix this in the next point release.

**Comment by rob-p** [comment]
Hi @allyhawkins; this is now fixed in 1.6.0.  Thanks again for the report!
