### ISSUE TITLE
salmon index was invoked improperly

### ISSUE THREAD

**Issue by rudondamba** [COMBINE-lab/salmon#694]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

**Describe the bug**
I am getting this error when I try to update my index using salmon v1.4.0 or 1.5.1
Version Server Response: Not Found
Exception : [Error: RapMap-based indexing is not supported in this version of salmon.]
salmon index was invoked improperly.
For usage information, try salmon index --help
Exiting.
However the index is working with salmon version 0.8.2 

**To Reproduce**
This is how I ran it:
salmon index -t galGal6.gene+cluster+repBase+tRNA.fa -i SalmonIndex --type quasi -k 31
 
This is the dropbox link to the galGal6.gene+cluster+repBase+tRNA.fa https://www.dropbox.com/s/nb39rpydanlxr3p/galGal6.gene%2Bcluster%2BrepBase%2BtRNA.fa?dl=0 file

**Comment by rob-p** [comment]
Hi @rudondamba,

  Thanks for the report.  At salmon v1.0.0, there was a breaking change in the index used in salmon.  We moved from using the RapMap index to using a [pufferfish based index](https://github.com/COMBINE-lab/pufferfish).  This means that, you'll want to rebuild your index using a recent version of salmon.

  Further, the move to the pufferfish index drops support for the FMD-like index, so you can remove the `--type` argument.  With a new version of salmon you should be able to do:

```{bash}
salmon index -t galGal6.gene+cluster+repBase+tRNA.fa -i SalmonIndex -k 31 -p 8
```

the `-p` is optional and tells salmon to use 8 threads during indexing.  Also, the default `k` is 31, so you don't need to pass that explicitly if don't want.

Best,
Rob
