### ISSUE TITLE
Minimum return cod e for left and right read was (-2). Make sure the file is valid.

### ISSUE THREAD

**Issue by theOlligist** [COMBINE-lab/salmon#700]
This 'bug' is related to the funcionality. When attempting to quantify reads using the form, salmon quant -i contig_index -l A -1 R1.fastq -2 R2.fastq -o SalmQuant_out, I get the error from the title of this post (screenshot below).

  * Salmon v 1.5.1 (downloaded executable) used to quantify transcriptome from two fastq files, R1 and R2, containing the same number of sequences. Executed as follows:
  * salmon quant -i contig_index -l A -1 R1.fastq -2 R2.fastq -o SalmQuant_out

**Expected behavior**
I expected a quant.sf file. Instead I
![Screen Shot 2021-09-07 at 3 25 26 PM](https://user-images.githubusercontent.com/50889111/132418472-1bca6641-008e-4a9e-aae5-e0b61f771fd4.png)
 got the error in the title, and in the salmon_quant.log file.

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version: 18.04.1 

Any insight and help getting that quantification file is greatly appreciated.

**Comment by k3yavi** [comment]
Please check [this](https://www.biostars.org/p/342945/) issue. I think something is wrong in the fastq, I'd recommend checking the format of your input fastqs.
