### ISSUE TITLE
Minimum return code for left and right read was (-2). Please help.

### ISSUE THREAD

**Issue by theOlligist** [COMBINE-lab/salmon#709]
salmon version 1.5.1
Running with the following keystrokes:
salmon quant -i contig_index -l A -1 R1.fastq -2 R2.fastq -o salmonoutput (screenshot attached as "command")

It keeps throwing the attached error message (as log).
Ive verified the R1 and R2 have the same number of entries using grep to count the number of "@" symbols. These match. The lines of each file are the same as well. (screenshot also attached as "size")
![Command](https://user-images.githubusercontent.com/50889111/134416661-77de22d1-5fc4-4b89-a21d-940948fdc4b8.png)
![Size](https://user-images.githubusercontent.com/50889111/134416664-21c6373f-57be-4c8d-b917-68aa16262f57.png)
<img width="1314" alt="Log" src="https://user-images.githubusercontent.com/50889111/134416666-5dcf3843-ef06-45b1-bb77-6c2dbae9e6e4.png">

I'm not sure what to do from here; Please help.

**Comment by rob-p** [comment]
The error code comes from the underlying `kseq` parser.  It means some read had an underlying quality string that was truncated (shorter than the corresponding read).  See [this](https://www.biostars.org/p/342945/#405026) biostars post.
