### ISSUE TITLE
Error with index build while mapping reads

### ISSUE THREAD

**Issue by oligomyeggo** [COMBINE-lab/salmon#713]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**

The bug is primarily related to salmon, but I am using salmon to build an index for use with alevin-fry per the [alevin-fry tutorial](https://combine-lab.github.io/alevin-fry-tutorials/2021/improving-txome-specificity/). 

**Describe the bug**

I have previously followed the steps outlined in the alevin-fry tutorial for a single sample and everything worked as expected. Now I am following the same steps but wrapped in a snakemake pipeline to process several samples and am running into issues building the index. Specifically, I am receiving the following error when my pipeline moves on the mapping reads step:

```
Exception : [Error: The index version file /beevol/home/winklerc/projects/scifi_pipeline/scifi/ref/idx/complete_ref_lens.bin/versionInfo.json doesn't seem to exist.  Please try re-building the salmon index.]
 alevin (sc-align) was invoked improperly.
```

I have tried re-building the index, and have also tried reusing the index that I had previously built for the single sample run that previously worked. However, neither of those approaches fixed the above error. When I build the index I am able to generate all of the expected files and the file sizes match those of my previous (successful) index build, so I am not sure why I am getting an error that the `versionInfo.json` file is missing.

**To Reproduce**
Steps and data to reproduce the behavior:

I followed the alevin-fry tutorial to generate a splici transcriptome, using the same [Human reference (GRCh38) dataset](https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz) provided by the tutorial. My snakemake rule to build the index uses the same commands outlined in the alevin-fry tutorial, and looks like this:

```
rule build_idx: 
# build a splici (spliced + intron) index for alevin-fry
    input:
        fasta = "{out_data}/ref/transcriptome/transcriptome_splici_fl86.fa"
    output:
        "{out_data}/ref/idx/complete_ref_lens.bin",
        "{out_data}/ref/idx/ctable.bin",
        "{out_data}/ref/idx/ctg_offsets.bin",
        "{out_data}/ref/idx/duplicate_clusters.tsv",
        "{out_data}/ref/idx/info.json",
        "{out_data}/ref/idx/mphf.bin",
        "{out_data}/ref/idx/pos.bin",
        "{out_data}/ref/idx/pre_indexing.log",
        "{out_data}/ref/idx/rank.bin",
        "{out_data}/ref/idx/refAccumLengths.bin",
        "{out_data}/ref/idx/ref_indexing.log",
        "{out_data}/ref/idx/reflengths.bin",
        "{out_data}/ref/idx/refseq.bin",
        "{out_data}/ref/idx/seq.bin",
        "{out_data}/ref/idx/versionInfo.json"
    params:
        job_name = "build_idx",
        memory = "select[mem>64] rusage[mem=64]",
        out_dir = "{out_data}/ref/idx"
    log:
        "logs/build_idx.out"
    threads:
        16
    shell:
        """
        salmon index \
            -t {input.fasta} \
            -i {params.out_dir} \
            -p {threads}
        """
```

Running this rule does generate all the expected output files, including `versionInfo.json`. My pipeline crashes during the next step, where I am attempting to map reads. Again, I followed the code as outlined by the alevin-fry tutorial (tweaked slightly) and my snakemake rule is as follows (apologies that I am still using the deprecated --end, --barcodeLength and --umiLength options; my intention was to update those once I had my pipeline working, but I've gotten stuck on the index build):

```
rule map_reads: 
# map reads and generate a RAD (Reduced Alignment Data) file
    input:
        R1 = "{out_data}/preprocessed_fastqs/{sample}_R1.fastq.gz",
        R2 = "{out_data}/preprocessed_fastqs/{sample}_R2.fastq.gz",
        idx = rules.build_idx.output,
        tgmap = "{out_data}/ref/transcriptome/transcriptome_splici_fl86_t2g.tsv"
    output:
        "{out_data}/{sample}/map/alevin/alevin.log",
        "{out_data}/{sample}/map/aux_info/meta_info.json",
        "{out_data}/{sample}/map/cmd_info.json",
        "{out_data}/{sample}/map/libParams",
        "{out_data}/{sample}/map/logs/salmon_quant.log",
        "{out_data}/{sample}/map/map.rad",
        "{out_data}/{sample}/map/unmapped_bc_count.bin",
    params:
        job_name = "map_reads",
        memory = "select[mem>64] rusage[mem=64]",
        library_type = "ISR",
        end = 5,
        barcodeLength = 16,
        umiLength = 8,
        out_dir = "{out_data}/{sample}/map"
    log:
        "logs/map_reads/{sample}.out"
    threads:
        16
    shell:
        """
        salmon alevin \
            -l {params.library_type} \
            -1 {input.R1} \
            -2 {input.R2} \
            -i {input.idx} \
            -p {threads} \
            -o {params.out_dir} \
            --tgMap {input.tgmap} \
            --end {params.end} \
            --barcodeLength {params.barcodeLength} \
            --umiLength {params.umiLength} \
            --keepCBFraction 1 \
            --sketch
        """
```

Specifically, please provide at least the following information:

  * Which version of salmon was used? v1.5.2
  * How was salmon installed (compiled, downloaded executable, through bioconda)? Downloaded [this](https://github.com/COMBINE-lab/salmon/releases/tag/v1.5.2) binary
  * Which reference (e.g. transcriptome) was used? Human reference (GRCh38) (from the alevin-fry tutorial [here](https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz))
  * Which read files were used? See attached subsampled sub_R1.fastq.gz and sub_R2.fastq.gz from one sample as representative reads.
  * Which which program options were used? See above snakemake rule code for program options, which closely follow the options used in the alevin-fry tutorial.

**Expected behavior**

I expected my reads to be mapped and a RAD file to be generated.

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX] Linux (university cluster)
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]
 
Output of `uname -a`:
 ```
Linux amc-bodhi 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Output of `lsb_release -a`:
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core
```

**Additional context**

I have attached subsampled fastq files for one of my samples as an example:
[sub_R1.fastq.gz](https://github.com/COMBINE-lab/salmon/files/7331798/sub_R1.fastq.gz)
[sub_R2.fastq.gz](https://github.com/COMBINE-lab/salmon/files/7331799/sub_R2.fastq.gz)

This is the error log after attempting to run the map reads step, which indicates an issue with the index build:
[B13_MeOH_cells_Jurkat_Cas9_EGR1_1_stimulated.out.err.txt](https://github.com/COMBINE-lab/salmon/files/7331816/B13_MeOH_cells_Jurkat_Cas9_EGR1_1_stimulated.out.err.txt)

This is the error log after building the index, which seems to have run successfully (though maybe I am missing something):
[build_idx.out.err.txt](https://github.com/COMBINE-lab/salmon/files/7331817/build_idx.out.err.txt)

This is the versionInfo.json file that is successfully generated after building the index, but that can't be found when mapping reads:
[versionInfo.txt](https://github.com/COMBINE-lab/salmon/files/7331818/versionInfo.txt)

Thank you so much for any help/insight you might have! I appreciate it.

**Comment by oligomyeggo** [comment]
Ah, I see what went wrong! When I initially looked at the `B13_MeOH_cells_Jurkat_Cas9_EGR1_1_simulated.out.err` I saw all the index files listed and thought that that meant the pipeline found all of them, but I see that it was just grabbing that first file and trying to use it as the entire index directory. I have adjusted my snakemake rule per your suggestion and it is now working. Thank you so much @rob-p! I appreciate it, and sorry for the oversight on my part!

**Comment by rob-p** [comment]
No need to apologize @oligomyeggo!  Thanks to your excellent reporting and otherwise precise following of the tutorial, it was relatively straightforward to diagnose the problem.

I'm glad to hear it's working now.  Please let us know if you run into any other issues or have other questions.
