### ISSUE TITLE
Salmon Index [unrecognised option '-d']

### ISSUE THREAD

**Issue by BenSamy2020** [COMBINE-lab/salmon#714]
Greetings,

I would like to thank you for providing this as an open-source tool. Currently, I am performing Salmon Indexing using human Gencode V35. I am following the instruction from: https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/

But when I try running the command of "**salmon index -t gentrome.fa.gz -d decoys.txt -p 12 -i salmon_index --gencode**", I hit the error of "exception : [unrecognised option '-d']. Exiting."

In the --help section the argument of "-d" is not present. Please do advise me on how I should proceed with indexing?

Regards,
Ben

![image](https://user-images.githubusercontent.com/69944967/137584568-a0378455-a751-4d1f-885b-a66addf07160.png)

![image](https://user-images.githubusercontent.com/69944967/137584591-c61a3777-aff5-416f-beee-a33ad81ea5dd.png)

**Comment by rob-p** [comment]
Hi @BenSamy2020,

  Judging from the options available to the indexing command, it seems you're running quite an old version of salmon (before the `-d` flag was even introduced).  Specifically, it seems to be a version prior to 1.0 (when the new index was introduced).  I'd recommend updating to the latest version of salmon, then you should be able to properly provide the decoys file.

Best,
Rob
