### ISSUE TITLE
Installing Salmon

### ISSUE THREAD

**Issue by paulitikka** [COMBINE-lab/salmon#716]
Could you please provide the newest salmon 
version for installation via e.g. 'sudo apt install salmon' (rather than the cmake source code approach)?
Thanks!

**Comment by rob-p** [comment]
Hi @paulitikka,

  This isn't something that I have control over (in terms of the official package repositories), and we don't have the resources to independently package salmon for the huge variety of different linux distributions.

  However, there are already ways to install the salmon binary directly across linux and OSX.  Specifically, there is a pre-compiled binary [here](https://github.com/COMBINE-lab/salmon/releases/download/v1.5.2/salmon-1.5.2_linux_x86_64.tar.gz) --- tagged on the release page.  Additionally, you can install salmon directly on linux or osx using bioconda — as outlined [here](https://anaconda.org/bioconda/salmon).

Best,
Rob
