### ISSUE TITLE
Indexing failed

### ISSUE THREAD

**Issue by Lucas-Servi** [COMBINE-lab/salmon#720]
First time trying to use SALMON 1.5.2 (not bioconda) index with decoy.txt on Arabidopsis thaliana.

I'm using AtRTD3 Transcriptome "atRTD3_07082020.fasta" (https://ics.hutton.ac.uk/atRTD/RTD3/ - username atrtd; password atrtd3-06092021) and the genome "GWHBDNP00000000.1" from https://ngdc.cncb.ac.cn/gwh/Assembly/21820/show

I followed the steps from (https://gist.github.com/k3yavi/a486647c35158a8296cec543ed9b526f) using this two files as follow:
```
grep "^>" <(zcat GWHBDNP00000000.1.genome.fasta.gz) | cut -d " " -f 1 > decoys.txt
sed -i -e 's/>//g' decoys.txt
cat atRTD3_07082020.fasta GWHBDNP00000000.1.genome.fasta.gz > gentrome.fa.gz
salmon index -t gentrome.fa.gz -d decoys.txt -p 12 -i salmon_index --gencode
```

The index generation failed, creating a folder with only two files "pre_indexing.log" and "ref_indexing.log"([pre_indexing.log](https://github.com/COMBINE-lab/salmon/files/7515704/pre_indexing.log) and [ref_indexing.log](https://github.com/COMBINE-lab/salmon/files/7515701/ref_indexing.log)) 

I recieved this error from the terminal:
![Screenshot from 2021-11-10 17-24-24](https://user-images.githubusercontent.com/71443183/141187955-4601923f-001f-424a-969a-8ad346f2cf36.png)

 - OS: Ubuntu Linux
 - Version 21.10

Thanks for this great software!!!

**Comment by mdshw5** [comment]
@Lucas-Servi it looks like your genome assembly contains tab characters in the sequence identifiers:
**
<img width="403" alt="image" src="https://user-images.githubusercontent.com/819554/141483689-2273ce79-2028-4a56-b7b3-de8017c3c7ec.png">
**
FASTA is such an ill-defined format, but I believe that the only whitespace that's expected is the ASCII "space" character.

**Comment by rob-p** [comment]
I'm going to assume this resolved the issue.  If not, please feel free to re-open.
