### ISSUE TITLE
I can't find the salmon package in the Conda channels. I'm using an m1 chip. 

### ISSUE THREAD

**Issue by vbontempi96** [COMBINE-lab/salmon#724]
this is the error I am getting. 

```
The package "salmon" has no matches.
There are these packages and versions available:

NULL

Error in install_CondaTools(tools = "salmon", env = "RNAseq_analysis", :
The package and/or version are not available in conda. Check above for details.
In addition: Warning message:
In system(paste(pathToConda, "search --quiet --json", package_input, :
running command '/Users/vittoriobontempi/Library/r-miniconda/bin/conda search --quiet --json "salmon" -c bioconda -c defaults -c conda-forge 2>/dev/null' had status 1
```

any help will be greatly appreciated. thank you!

**Comment by rob-p** [comment]
Hi @vbontempi96 — I don't know how bioconda is actually handling building for the new Mac archs.  I'll ping @dpryan79 who would know what's currently being done and what the plan is.

**Comment by rob-p** [comment]
@vbontempi96,

  Thanks to @genomax, working from an M1, it seems likely that the issue is your order of Conda channels.  Given an empty channel list, try the following:

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

This should allow you to get the latest salmon (currently 1.6.0) on an M1 from bioconda.  Please feel free to re-open if this doesn't work for you.

**Comment by charlotte-west** [comment]
I'm having a similar problem, also using an M1 mac. I've tried your solution @rob-p, as well as updating conda, creating a new environment specifically for salmon, it still doesn't work. I get the following error:

```
$ conda install -c bioconda salmon                               3s Py salmon
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - salmon

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by vbontempi96** [comment]
I tried re-installing salmon today after seeing your message. A simple `conda install salmon` worked for me this time. I don't know why it was giving me an error back then and not one now though....

**Comment by rob-p** [comment]
> Hmm strange! But `conda install salmon` still gives the same error for me.

Hi @charlotte-west,

  Can you please try the following?

```
CONDA_SUBDIR=osx-64 conda create -n rosetta   # create a new environment
conda activate rosetta
conda env config vars set CONDA_SUBDIR=osx-64  # subsequent commands use intel packages
conda install salmon
```

These instructions came from (here)[https://github.com/Haydnspass/miniforge#rosetta-on-mac-with-apple-silicon-hardware] and have worked for me on my M1 laptop. My understanding is that conda / bioconda are still working on having worker nodes that can pre-compile native M1 executables.  So, until that work is complete, it may be necessary to run certain native packages in a Rosetta environment.  Let me know if this works for you.

Best,
Rob

**Comment by rob-p** [comment]
Awesome!  Thanks for looping back around.  I'll update the discussion Q&A on GitHub about this and update that when bioconda has native M1 support.

**Comment by BenjaminDEMAILLE** [comment]
I trey but it's destroy my conda after "HTTPerror".

**Comment by rob-p** [comment]
Can you please show the commands you are using and also your conda channel list.  The backup solution is always to just use a Docker kr Singularity inage.

**Comment by rob-p** [comment]
One thing is that bioconda is not in your channels list, only conda forge. Though I don't think that's the ultimate source of this error.

**Comment by erzakiev** [comment]
> > Hmm strange! But `conda install salmon` still gives the same error for me.
> 
> Hi @charlotte-west,
> 
> Can you please try the following?
> 
> ```
> CONDA_SUBDIR=osx-64 conda create -n rosetta   # create a new environment
> conda activate rosetta
> conda env config vars set CONDA_SUBDIR=osx-64  # subsequent commands use intel packages
> conda install salmon
> ```
> 
> These instructions came from (here)[https://github.com/Haydnspass/miniforge#rosetta-on-mac-with-apple-silicon-hardware] and have worked for me on my M1 laptop. My understanding is that conda / bioconda are still working on having worker nodes that can pre-compile native M1 executables. So, until that work is complete, it may be necessary to run certain native packages in a Rosetta environment. Let me know if this works for you.
> 
> Best, Rob

it worked for me but i had to remove the comments starting with the `#`
