### ISSUE TITLE
Alevin format bfh.txt file (--dumpBfh)

### ISSUE THREAD

**Issue by tmms1** [COMBINE-lab/salmon#728]
Hello

I ran Alevin with the `--dumpBfh` flag. This resulted in ``bfh.txt`` present in the output. 
At first sight, this file shares similarities with the ``eq_classes.txt`` you obtain when running salmon with the ``--dumpEq`` flag. Could you explain the format of the file in more detail? I couldn't find in the documentation of Alevin.

At the moment, I think that: 

- The first line is the number of transcripts.
- The second line is the number of valid barcodes, i.e. the number of detected cells. 
- The third line is the number of equivalence classes
- The next lines, starting with ENSMUST in my case, are the transcripts. 
- The next lines, starting with ACGT and in my case 12 characters long, are the retrieved cellular barcodes. 
- ... (Here I don't know what I am looking at)

Thanks in advance.

**Comment by k3yavi** [comment]
Hi @tmms1 ,

sorry for the late reply. the function [here](https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L374-L444) should give the schema of the bfh file generated by alevin. It's an internal format that's why there is not much info but happy to discuss if it's relevant for your use case.

**Comment by tmms1** [comment]
Hi @k3yavi 

Thank you very much for the answer. 

I am interested in the equivalence class counts (ECC) per cell and the transcripts that belong to each equivalence class. I think bfh.txt is file that contains that information, but I couldn't figure out how the file is structured. I looked at the function you linked to, but the schema hasn't become totally clear. Could you provide some more information? 

Thanks in advance.

**Comment by tmms1** [comment]
Hi @k3yavi 

Thank you for linking me to your script to parse the bfh file from alevin. I think I could figure out the structure of the bfh file. I will write it down underneath with the help of an example. Could you confirm it is correct? 

Everything up and until the listing of the barcodes is clear. I will start with a line from after the barcodes.     
"7	90480	90486	107507	107990	108641	109149	112915	1	1	105	1	TGGGATTT	1"

I think that each such line corresponds to an equivalence class (EC). The first entry on each row is the number of transcripts in the EC. This is followed by the transcripts (more correctly, indices you can use to obtain the transcripts). Then you have the number of reads with in the EC, followed by the number of barcodes (~cells). For each barcode, you have an index that can be used to retrieve the identity of the barcode, followed by the number of UMIs within that barcode, the sequence of the UMI and lastly the number of reads associated with that UMI. 

My goal is create a expression matrix where the ECs are the rows and the columns are the cells. If I want the UMI counts, do I need to count the number of reads associated with each UMI or just the number of UMIs per cell? 

Thanks in advance.

**Comment by k3yavi** [comment]
Hi @tmms1 ,

> I think that each such line corresponds to an equivalence class (EC). The first entry on each row is the number of transcripts in the EC. This is followed by the transcripts (more correctly, indices you can use to obtain the transcripts). Then you have the number of reads with in the EC, followed by the number of barcodes (~cells). For each barcode, you have an index that can be used to retrieve the identity of the barcode, followed by the number of UMIs within that barcode, the sequence of the UMI and lastly the number of reads associated with that UMI.

This is correct !


Unfortunately you goal is not very clear to me and the output matrix depends on that. I understand that you wan't a matrix of dimension |eq_class X cells| but if you wan't the values in the matrix to be read count then you have to add the counts of all the UMIs in class across the cells; and if you wan't the values in the matrix to be the frequency of the unique UMIs then just count the UMIs you wan't instead of reads.

**Comment by tmms1** [comment]
Hi @k3yavi 

Thank you for confirming I got the structure of the bfh file right. I couldn't have figured it out without your parsing script.

I want to obtain a matrix like salmon alevin generates by default, but instead of using genes or transcripts as features, I want to use the equivalence classes. Similar as described [in this paper](https://f1000research.com/articles/8-265) (Figure 1), but then for single cell data. I think this should be possible? 

Thanks in advance.
