### ISSUE TITLE
"salmon" with no options should print help

### ISSUE THREAD

**Issue by tseemann** [COMBINE-lab/salmon#73]
I think `salmon` invoked with no parameters should invoke the help.

It takes `salmon`, then `salmon --help` then `salmon index -h` before you can even begin to figure out how to run it.

**Comment by rob-p** [comment]
Well, to be fair, you could [read the docs](http://salmon.readthedocs.io/en/develop/salmon.html) ;P.

**Comment by tseemann** [comment]
You just cut your potential audience by 90% :)

**Comment by rob-p** [comment]
This is fixed in c5d4a23
