### ISSUE TITLE
Salmon does not recognize the second mate of each pair

### ISSUE THREAD

**Issue by amitpande74** [COMBINE-lab/salmon#737]
HI,
I using Salmon version1.2.1_l.
I have mate pairs for transcriptome mapping. 
`./bin/salmon quant -i /media/amit/Amit/Usr/new_salmon_index/ -l IU -1 /media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_1.fq V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq -2 /media/amit/Amit/Usr/DNA12/fastq/V300012057_L4_HK500HUMpybEAAKRAAPEI-530_1.fq V300012057_L4_HK500HUMpybEAAKRAAPEI-530_2.fq -p 8 --validateMappings -o /media/amit/Amit/Usr/DNA12/fastq/DNA12.quant`

But salmon gives an error:
```
The following errors were detected with the read files
======================================================
ERROR: file [V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq] does not appear to exist!

```
Kindly help. I have followed all the instructions noted here:
https://github.com/COMBINE-lab/salmon/issues/69

Regards.

**Comment by k3yavi** [comment]
Hi @amitpande74 ,

Please check the path of the files like `V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq` since you provided the full path of other files like `/media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_1.fq`.

**Comment by rob-p** [comment]
Great catch @k3yavi!  Also, it seems that the way that the files are passed may be different from what's expected.  The paths passed to `-1` are 

```
/media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_1.fq V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq
```

and those passed to `-2` are

```
/media/amit/Amit/Usr/DNA12/fastq/V300012057_L4_HK500HUMpybEAAKRAAPEI-530_1.fq V300012057_L4_HK500HUMpybEAAKRAAPEI-530_2.fq
```

But you should not be passing the reads to `-1`  the form `L3_R1 L3_R2` and `-2` in the form `L4_R1 L4_R2`; rather it should be like `-1 L3_R1 L4_R1` and `-2 L3_R2 L4_R2`.  That is, *all* read 1 files get passed to `-1` and all read 2 files (in the same order) get passed to `-2`.

**Comment by amitpande74** [comment]
> Hi @amitpande74 ,
> 
> Please check the path of the files like `V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq` since you provided the full path of other files like `/media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_1.fq`.

@k3yavi it should be like this ?

`./bin/salmon quant -i /media/amit/Amit/Usr/new_salmon_index/ -l IU -1 /media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_1.fq  /media/amit/Amit/Usr/DNA12/fastq V300012057_L4_HK500HUMpybEAAKRAAPEI-530_1.fq -2 /media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq  /media/amit/Amit/Usr/DNA12/fastq /V300012057_L4_HK500HUMpybEAAKRAAPEI-530_2.fq -p 8 --validateMappings -o /media/amit/Amit/Usr/DNA12/fastq/DNA12.quant`

Regards.

**Comment by rob-p** [comment]
Hi @amitpande74,

  Almost, but I think you are missing a `/` or so.  Assuming uniform paths for the input, I think the command should look like:

```
./bin/salmon quant -i /media/amit/Amit/Usr/new_salmon_index/ -l IU -1 /media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_1.fq /media/amit/Amit/Usr/DNA12/fastq/V300012057_L4_HK500HUMpybEAAKRAAPEI-530_1.fq -2 /media/amit/Amit/Usr/DNA12/fastq/V300012057_L3_HK500HUMpybEAAKRAAPEI-530_2.fq /media/amit/Amit/Usr/DNA12/fastq/V300012057_L4_HK500HUMpybEAAKRAAPEI-530_2.fq -p 8 --validateMappings -o /media/amit/Amit/Usr/DNA12/fastq/DNA12.quant
```

**Comment by amitpande74** [comment]
Thanks a lot @rob-p and @k3yavi .
I wanted your advise on something more intricate. Asking since you people are the pioneers in this aspect of problem solving.
I have to determine the expression of GFP and Transposon sequence in the transcriptome.
I read the material posted on the link https://salmon.readthedocs.io/en/latest/salmon.html.
It instructs this to be done in 2 different ways-
There are two options for generating a decoy-aware transcriptome:

    The first is to compute a set of decoy sequences by mapping the annotated transcripts you wish to index against a hard-masked version of the organism’s genome. This can be done with e.g. MashMap2, and we provide some simple scripts to greatly simplify this whole process. Specifically, you can use the generateDecoyTranscriptome.sh script, whose instructions you can find in this README.

    The second is to use the entire genome of the organism as the decoy sequence. This can be done by concatenating the genome to the end of the transcriptome you want to index and populating the decoys.txt file with the chromosome names. Detailed instructions on how to prepare this type of decoy sequence is available here. This scheme provides a more comprehensive set of decoys, but, obviously, requires considerably more memory to build the index.

I tried the 2nd approach. Combined the GFP,Transposon and the genome FASTA files, indexed it , constructed the decoy according to the given instructions given here https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/.
When I ran Salmon (version 1.2.1_linux_x86_64) it did not report anything in the quant files (I know that these samples have high GFP and Transposon expression in these samples).

The 1st approach is giving me problems to the construction of the GTF file and then memory usage. The instructions say - generateDecoyTranscriptome.sh — Located in the scripts/ directory, this is a preprocessing script for creating augmented hybrid fasta file for salmon index. It consumes genome fasta (one file given through -g), transcriptome fasta (-t) and the annotation (GTF file given through -a) to create a new hybrid fasta file which contains the decoy sequences from the genome, concatenated with the transcriptome (gentrome.fa). 
Kindly advise.

**Comment by k3yavi** [comment]
Hi @amitpande74 ,

May be you are already aware of this but just to make it clear, the idea behind decoy indexing is to "exclude" those sequences from the transcriptome quantification and that's why you don't see the indexed transposon sequence in the salmon output. The motivation behind such indexing is to remove false mapping reads i.e. exclude RNA-seq reads from the quantification pipelines which maps better to the decoy sequences compared to the provided transcriptome. 

I hope that clarifies your doubt and if you wan't to quantify GFP sequences then you have to concatenate them with the transcriptome sequence "not" the decoy sequence, although I just wanted to give you heads up that this analysis goes into an unexplored territory as we personally have not explored such use cases. Unless Rob have more thoughts on it.

**Comment by colinmccornack** [comment]
I am having a similar issue when trying to loop `salmon quant` over reads on multiple lanes.
```shell
for i in \`ls *.fastq | cut -d "_" -f 1 | uniq` ;
    do 
        read1=$(ls *.fastq | grep ${i} | grep "R1" | tr '\n' ' '| sed 's/.$//')
        read2=$(ls *.fastq | grep ${i} | grep "R2" | tr '\n' ' '| sed 's/.$//')

        salmon quant \
            -i GRCm39_index \
            -l IU \
            -1 "${read1}" \
            -2 "${read2}" \
            -p 8 \
            --validateMappings \
            -o ./results/salmon/"$i"_quant

    done
``` 
The error given is 
```shell 
The following errors were detected with the read files
======================================================
ERROR: file [LIB020923_22H27NLT3_S311_L001_R1_001.fastq LIB020923_22H27NLT3_S311_L002_R1_001.fastq] does not appear to exist!
```
I can open an interactive session and copy/paste this directly into the `-1` for `salmon quant` and it will not throw the same error, so while I'm pretty sure it has to be something in my script that is throwing `salmon` off, I'm not sure of what. I've tried the following:

- Absolute filepaths through `realpath`
- Removing the `sed` command to remove the last character
- Confirmed that the files exist through `ls` 
- Changed file permissions in case there was an issue with that
