### ISSUE TITLE
"Normal" mapping for Drop-Seq data

### ISSUE THREAD

**Issue by tmms1** [COMBINE-lab/salmon#738]
Hello

I am analyzing Drop-Seq data with salmon alevin. I applied the tips given in this discussion (#506). 
However, to me the mapping rates (found in "salmon_quant.log") are rather low. On average, the mapping rate is only 23 % with a standard deviation of 9 % when running salmon alevin with default parameters. 
When setting ```--expectCells``` or ```--forceCells```, these numbers change to 23 % (sd: 5%) and 26 % (sd: 6%).

Are these mapping rates what you expect for Drop-Seq data? It is my first time analyzing Drop-Seq data, so I have no reference. 
Is this low mapping rate problematic? 

Thanks in advance

**Comment by k3yavi** [comment]
Hi @tmms1 ,

I think it's generally in the same ballpark I've seen for the Drop-Seq data.

**Comment by rob-p** [comment]
@k3yavi — might it be worthwhile exploring the effect of changing the min score fraction here, or enabling softclipping? I do recall that this seems in the ballpark of drop-seq data mapping to the annotated (spliced) transcriptome, but is it clear _why_ the mapping rates for this technology are so low?

**Comment by tmms1** [comment]
Hi @k3yavi

Thank you very much for the swift answer. 

Maybe a relevant thing I forgot to mention, the reads originate from mouse.

**Comment by k3yavi** [comment]
Unfortunately I don't have much thoughts about the low mapping rates of Drop-seq technology. 
Although, it doesn't necessarily have to be associated with the mapping rate, from what I remember a lot CB are more than one-edit distance away from the high quality barcodes which are excluded from the mapping phase of the pipeline.

**Comment by tmms1** [comment]
I ran salmon alevin with the additional ``--softclip`` flag as @rob-p suggested. The mapping rate was almost identical compared to results without that flag. 

As I didn't include the ``--validateMappings`` flag, changing the ```--minScoreFraction`` wouldn't matter (if I understand the manual correctly). 

If these mapping rates are what you have seen for similar data, that is fine for me.

**Comment by rob-p** [comment]
I would recommend trying to process this data with `alevin-fry` using the `--sketch` option.  Feel free to open a new issue if you believe the mapping rate is still unreasonably low.
