### ISSUE TITLE
Salmon Alevin ```--forceCells``` returns unexpected number of cells

### ISSUE THREAD

**Issue by tmms1** [COMBINE-lab/salmon#739]
Hello

I am analyzing Drop-Seq data with salmon alevin. I applied the tips given in this discussion (#506). 
When adding the ```--forceCells``` flag and setting it to 1000, the number of detected cells is 1499 or 1500 in all samples. 
I don't think this is normal behaviour, but I have no idea what is causing this. 

Thanks in advance

**Comment by k3yavi** [comment]
Can you share the full log @tmms1  ?

**Comment by k3yavi** [comment]
Ah so what's happening is alevin is keeping around 500 low confidence CB for performing downstream whitelisting.
`[2021-12-10 15:28:09.434] [alevinLog] [info] Total 1501(has 500 low confidence) barcodes`

**Comment by tmms1** [comment]
Thank you for the answer. If I understand it correctly, whitelisting is the process in which alevin tries to figure out which are good barcodes? 
Should these 500 low confidence CB be removed in subsequent steps?

**Comment by k3yavi** [comment]
Right, so at the end of the quantification pipeline you should have the file `whitelist.txt` which you can use as a high confidence barcodes and filter the full matrix file.
