### ISSUE TITLE
Inconsistent return codes with command help

### ISSUE THREAD

**Issue by tseemann** [COMBINE-lab/salmon#74]
* `salmon --help` returns 0
* `salmon index -h` returns 1
* `salmon quant -h` returns 0
* `salmon swim -h` returns 0

**Comment by rob-p** [comment]
So, you propose return `1` for all of these?

**Comment by rob-p** [comment]
Actually, I think the suggestion is that :

```
salmon
```

returns 1, and all other variants e.g.

```
salmon --help
salmon index -h 
salmon quant -h 
salmon swim -h 
```

return 0.

**Comment by tseemann** [comment]
Yep that's correct - the command returns `0` when it did what was asked, and non-`0` otherwise.

Thank you :)
