### ISSUE TITLE
how to use create index for genome instead of transcriptome

### ISSUE THREAD

**Issue by bzmby** [COMBINE-lab/salmon#741]
I am trying to create index using salmon for human Genome (not transcriptome). The version of salmon I am using is : salmon `v0.13.1` .
The command I used is :

    salmon index \
      -t /hg38_genome/GRCh38.p13.genome.fa \
      -i index

The main error I am getting is:

    Command error:
      [2022-01-26 12:20:19.647] [jointLog] [warning] Entry with header [KI270896.1] was longer than 200000 nucleotides.  Are you certain that we are indexing a transcriptome and not a genome?

If I use transcriptome file instead of genome, it works perfectly and returns the index files. I got both `transcriptome` and `genome` from the `gencode`.

For my analysis I need to use genome. do you know how I can use genome?

**Comment by k3yavi** [comment]
Hi @bzmby ,

I am sure you are aware of this but just wanted to clear that salmon is primarily designed for transcriptome quantification.
Ideally, there should not be a problem with indexing genome, also from the log you shared it looks like a warning. 
Having said that if you will index the genome then at the end of the day you will get quantification of the chromosomes, is that what you wan't ?
