### ISSUE TITLE
Will a smaller k-mer length reduce alignment accuracy?

### ISSUE THREAD

**Issue by diyang1354** [COMBINE-lab/salmon#754]
Hi,
When I use the default k-mer length of 31 to generate index, it throws warnings like 'ENSTxxxxx had length less than equal to the k-mer length of 31'. I checked these transcripts, and most of them are immunoglobulin and T cell receptor genes. 
My question is:
1. Transcripts with a length below specified k-mer length will be discarded during alignment, right? 
2. If I reduced the k-mer length to a smaller odd value, say 15, will this affect accuracy? My read length is 150.  
Thanks

**Comment by rob-p** [comment]
Hi @diyang1354,

  To answer your questions as directly as possible:

1.) Yes, you cannot align to a transcript of less than the k-mer length.
2.) If you are processing bulk RNA-seq data, and therefore using `selective-alignment`, using a smaller `k` is unlikely to reduce your alignment accuracy, but it *can* increase the runtime of mapping if you make it too small.  If you are processing single-cell RNA-seq data and using `--sketch` mode, then a reduction in the value of `k` can negatively impact accuracy.

Finally, I'll mention that RNA-seq, in general, isn't a great assay for measuring very small molecules, so you probably want to be somewhat suspicious of the quantification results for *very short* transcripts anyway.

Best,
Rob
