### ISSUE TITLE
the installation of salmon index cannot be completed

### ISSUE THREAD

**Issue by dhy2002** [COMBINE-lab/salmon#755]
Hi,
i met a problem when installing the index for salmon. The feedback suggests that "server did not respond before timeout". This problem is shown in the following picture.
I've already given it enough space for running, while it seems that it was stuck in the first step. And the index file only contains "pre_indexing.log  ref_indexing.log"
So could you please help me to solve this problem?
Thanks
![image](https://user-images.githubusercontent.com/100278952/155299114-10a7e3b7-bf08-49aa-824d-48dcbaa1fd71.png)

**Comment by rob-p** [comment]
Hi @dhy2002,

  The message at the beginning is just a result of salmon not being able to complete the version check — that is not related to any issues building the index.  What is at the end of the log file?

  Also, I'll note that we've seen before some issues related to building the index directly on a network file system mounted partition — the tool we use for compacted de Bruijn graph construction, TwoPaCo, can create many small intermediate files that causes issues for NFS.  If this is the problem, I might suggest building the index on the local scratch disk of a node, and then copying over the completed index when it's finished.

Best,
Rob
