### ISSUE TITLE
Read matrix from Alevin

### ISSUE THREAD

**Issue by knokknok** [COMBINE-lab/salmon#757]
Hello,
Is there a way to generate the read matrix from alevin (before collapsing the UMIs)?
I'd like to plot the nUMIs vs nReads for each gene of each cell.
Thanks!

**Comment by rob-p** [comment]
Hi @knokknok,

  You can directly use [`alevinQC`](https://github.com/csoneson/alevinQC) to get such plots.

Best,
Rob

**Comment by knokknok** [comment]
Aren't those aggregated at the cell level?
I would like the information for each gene of each cell.

**Comment by rob-p** [comment]
Hi @knokknok,

  That's a good point.  I don't know if there's a way to get at this easily.  I'll ping @k3yavi here for his input.

--Rob

**Comment by rob-p** [comment]
Pinging @k3yavi  here again and moving this over to a discussion where convo might better take place.
