### ISSUE TITLE
Binaries for v1.8.0 forgotten?

### ISSUE THREAD

**Issue by HenrikBengtsson** [COMBINE-lab/salmon#760]
Hi, thanks for a great tool.  I just noticed that contrary to previous releases, v1.8.0 does _not_ have a binary asset, cf. https://github.com/COMBINE-lab/salmon/releases.  Was this forgotten, or a switch to releasing only source tarballs?

**Comment by rob-p** [comment]
Alas, I'd just forgotten to do it :).  That part of the release process is manual, and requires me grabbing files from the CI, changing the folder name to reflect the release, and uploading them to GitHub.  One of these days I'll automate that, but for now it's a manual process.  Just added the 1.8.0 binary tarball.  Thanks for the reminder.

**Comment by HenrikBengtsson** [comment]
Thxs
