### ISSUE TITLE
salmon 1.8.0: binary release does not come with proper file permissions

### ISSUE THREAD

**Issue by HenrikBengtsson** [COMBINE-lab/salmon#761]
Contrary to earlier versions, e.g.

```sh
$ curl -L -O https://github.com/COMBINE-lab/salmon/releases/download/v1.7.0/salmon-1.7.0_linux_x86_64.tar.gz
$ tar zxf salmon-1.7.0_linux_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   669  100   669    0     0   2676      0 --:--:-- --:--:-- --:--:--  2676
100 52.5M  100 52.5M    0     0  26.0M      0  0:00:02  0:00:02 --:--:-- 33.2M
20220314-W11-1 (d073) 12:51:34 hb-x1:~/tmp/salmon
○ $ ls -la salmon-1.7.0_linux_x86_64/
total 1184
drwxr-xr-x 4 hb hb    4096 Feb 16 10:01 .
drwxrwxr-x 4 hb hb    4096 Mar 14 12:51 ..
drwxr-xr-x 2 hb hb    4096 Feb 15 21:05 bin    # <===
drwxr-xr-x 2 hb hb    4096 Feb 15 21:05 lib    # <===
-rw-r--r-- 1 hb hb 1193382 Feb 15 21:05 sample_data.tgz
```

the binaries for the recent salmon 1.8.0 release does not share any of the files or subfolders with "group" and "other";

```sh
$ curl -L -O https://github.com/COMBINE-lab/salmon/releases/download/v1.8.0/salmon-1.8.0_linux_x86_64.tar.gz
tar zxf salmon-1.8.0_linux_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   669  100   669    0     0   7689      0 --:--:-- --:--:-- --:--:--  7689
100 91.9M  100 91.9M    0     0  33.4M      0  0:00:02  0:00:02 --:--:-- 35.9M
20220314-W11-1 (d073) 12:51:14 hb-x1:~/tmp/salmon
○ $ ls -la salmon-1.8.0_linux_x86_64/
total 1184
drwx------ 4 hb hb    4096 Mar 10 09:57 .
drwxrwxr-x 3 hb hb    4096 Mar 14 12:51 ..
drwx------ 2 hb hb    4096 Mar 14 12:51 bin    # <===
drwx------ 2 hb hb    4096 Mar  8 06:57 lib    # <===
-rw------- 1 hb hb 1193382 Mar  8 06:57 sample_data.tgz    # <===

$ ls -la salmon-1.8.0_linux_x86_64/bin
total 442304
drwx------ 2 hb hb      4096 Mar 14 12:51 .
drwx------ 4 hb hb      4096 Mar 10 09:57 ..
-rw------- 1 hb hb 452905776 Mar  8 06:57 salmon    # <===
```

**Comment by HenrikBengtsson** [comment]
Oh, I also missed that `$prefix/bin/salmon` is marked executable, even for the use who install it.

**Comment by rob-p** [comment]
@HenrikBengtsson,

  Good catch.  We had to update the continuous integration image used because we bumped some libraries (and the compiler version).  Apparently the permissions are not set up in the same way by default.  Can you share what you think the permissions should be for the relevant files / folders?

Thanks,
Rob

**Comment by HenrikBengtsson** [comment]
This was caught by an end-user, reporting that `salmon` was not found.  I just [patched our installation script](https://github.com/HenrikBengtsson/CBI-software/blob/c0ed7c62446b8b26559bb71ff5f55c7d8e751296/CBI/salmon/Makefile#L24-L29) to do:

```sh
chmod -R go+r $(PREFIX)
chmod   ugo+x $(PREFIX)/{bin,lib,bin/salmon}
```

which I decided on looking at what salmon 1.7.0 had, except I skipped setting executable on the `lib/*.so` files (which 1.7.0 has for some of them).

**Comment by rob-p** [comment]
Hi @HenrikBengtsson,

  I've updated the script that builds the tarball of the CI server to apply the above permissions explicitly.  It seems to be working (and I've uploaded the modified tarball under the release page).  Thanks again for the issue!

--Rob
