### ISSUE TITLE
A simple question about strand bias

### ISSUE THREAD

**Issue by NJU-Bio-Info** [COMBINE-lab/salmon#762]
Hi, such a beautiful RNA-seq analysis tool!!!

So when I used it I have a question: does the relatively high(0.9~) or low(0.1~) strand bias mean that the library is stranded? I can't well understand the exact meaning of this value. Could you give me some guidance? Great gratitude for you~~~

**Comment by rob-p** [comment]
Hi @NJU-Bio-Info,

  Yes — the bias means that reads preferentially map in one orientation compared to the other.  An unbiased value (close to 0.5) is what you would expect from an unstranded library.  Values very far from 0 suggest a stranded library, with the type of bias (close to 0 versus close to 1) indicating the strand generating the reads.

Best,
Rob

**Comment by juliayork** [comment]
Good morning! This was helpful. I believe my data is unstranded with a value close to 0.5, but the lib type .json file looks like this:     
"expected_format": "IU",
    "compatible_fragment_ratio": 1.0,
    "num_compatible_fragments": 20834392,
    "num_assigned_fragments": 20834392,
    "num_frags_with_concordant_consistent_mappings": 33966029,
    "num_frags_with_inconsistent_or_orphan_mappings": 189540,
    "strand_mapping_bias": 0.47332512729115319,
    "MSF": 0,
    "OSF": 0,
    "ISF": 17889054,
    "MSR": 0,
    "OSR": 0,
    "ISR": 16076975,
    "SF": 96618,
    "SR": 92922,
    "MU": 0,
    "OU": 0,
    "IU": 0,
    "U": 0
}

I find this a little confusing... if all the reads fall under ISF/SF or ISR/SR, then is it stranded?? Please help.

**Comment by rob-p** [comment]
No, it is unstranded in this case. A specific read alwasys has a stranded orientation (it maps to one strand or the other). The strandedness of the library is a property of the collection of all reads.  Here, approximately half map in each orientation, so the library is unstranded,  since there is not a string, systematic bias for one orientation over the other. 

Best,
Rob

**Comment by juliayork** [comment]
Thank you so much, that makes sense.
