### ISSUE TITLE
"salmon index was invoked improperly. " Error 

### ISSUE THREAD

**Issue by benadikt** [COMBINE-lab/salmon#767]
**Is the bug primarily related to salmon (bulk mode) or alevin (single-cell mode)?**
salmon (bulk mode)

**Describe the bug**
after following tutorial step by step from the following website:
https://combine-lab.github.io/alevin-tutorial/2019/selective-alignment/

with the following files 
GRCm39.primary_assembly.genome.fa.gz
gencode.vM28.transcripts.fa.gz

I get the following error 

Exception : [Device or resource busy: 'salmon_index/twopaco_tmp']
salmon index was invoked improperly.
For usage information, try salmon index --help
Exiting.

**To Reproduce**
Steps and data to reproduce the behavior:
create the files:
decoys.txt
gentrome.fa.gz

and put them in salmonDecoy directory 
and run:
salmon index -t salmonDecoy/gentrome.fa.gz -d salmonDecoy/decoys.txt -p 12 -i salmon_index --gencode

Specifically, please provide at least the following information:
  * Which version of salmon was used?
  * How was salmon installed (compiled, downloaded executable, through bioconda)?
  * Which reference (e.g. transcriptome) was used?
  * Which read files were used?
  * Which which program options were used?
I used a linux machine with conda salmon env 
salmon version:  salmon 1.8.0

**Expected behavior**
create index for salmon 

**Screenshots**
If applicable, add screenshots or terminal output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, OSX]
 - Version [ If you are on OSX, the output of `sw_vers`. If you are on linux the output of `uname -a` and `lsb_release -a`]

**Additional context**

**Comment by rob-p** [comment]
Hi @benadikt,

  This indicates a system level problem with the underlying filesystem during the period that salmon calls out to TwoPaCo to create the compacted de Bruijn graph (or when attempting to clean up the intermediate files it makes after execution).  Please make sure that the filesystem has sufficient free space, and that you have sufficient permissions for the salmon output directory. Finally, there have been intermittent issues in the past with the behavior of Twopaco on NFS mounted filesystems. If you are on a networkes filesystem, you should try building the index on a loc scratch partition, and then copying it over to a shared location if you need shared access to it.

Best,
Rob
