### ISSUE TITLE
Add 'quantmerge' subcommand to combine runs

### ISSUE THREAD

**Issue by tseemann** [COMBINE-lab/salmon#77]
It would be amazing to have a subtool in salmon to combine the multiple output files into a single TSV file to pass to R or Degust for example.

It should take as parameters N salmon output folders, and combine them into a N+1 column file where column 1 is the transcript ID and the other N are the XXXX column from each quant file.

**Comment by roryk** [comment]
You might like to have a look at `tximport`, which does that for R at least: https://github.com/mikelove/tximport

**Comment by vals** [comment]
And I made one in Python :) https://github.com/Teichlab/readquant , you can pip install it. It also reads QC metrics from the directories.

It's not updated for 0.7.0 yet though.

**Comment by tseemann** [comment]
@roryk I don't think an R package is the right answer :)  

My real motivation is to load into Degust: http://www.vicbioinformatics.com/degust/

 It can be done with simple Unix cut/paste or with a python script too. But I don't want to depend on R for the pipeline, or even littler.

@vals I'll take a look at your script, but still be better if part of Salmon.

**Comment by mdshw5** [comment]
@tseemann You know degust is based on R packages, right? 😉

**Comment by tseemann** [comment]
@mdshw5 The backend is, but not the front-end.  

Let me know if you are able to manage to get the backend built and running. It's currently written in Haskell :-)

**Comment by rob-p** [comment]
@tseemann --- Is there still interest in this?  I'm trying to decide if the existing R / Python solutions are adequate, or if it would be of significant utility to have a builtin quantmerge command.

**Comment by tseemann** [comment]
Yes there is still interest from me.   This is stopping us using `salmon` in the Genomics Virtual Laboratory and our national training materials at http://sepsis-omics.github.io/tutorials/

**Comment by rob-p** [comment]
I don't understand how there's a kallisto tutorial then, though (http://sepsis-omics.github.io/tutorials/modules/kallisto/) --- it doesn't have a similar "merge" command.

**Comment by rob-p** [comment]
That's not to say I don't see the utility of having this built in.  I'll try and add this command to the next release ;).

**Comment by tseemann** [comment]
@rob-p that was written before we could get Salmon incorporated. We don't want kallisto due to the weird licence. We will replace it all with Salmon eventually.  But I understand why you may not want to spend time on it.

**Comment by rob-p** [comment]
@tseemann : Ahh ... makes sense.  As I said above, I have no aversion to implementing this and see why it could be useful.  It shouldn't be too difficult to do, so I'll give it a go when I have a free block of time.

**Comment by macmanes** [comment]
What is the usage for `quantmerge`? I just installed from the develop branch..

**Comment by rob-p** [comment]
The purpose is to have a builtin command to create a sample table for quant results.  The way it works now is that yoi feed a list of quant directories abd sample names (in the same order), and the field you want in the output (e.g., tpm or numreads etc.) And it will generate a num-txp by num-sample tsv file for the chosen attribute.

**Comment by rob-p** [comment]
This command is implemented in develop and will be in the next release.
