### ISSUE TITLE
CITE-seq like data with different barcode geometry

### ISSUE THREAD

**Issue by Simon-Coetzee** [COMBINE-lab/salmon#770]
This is concerned with alevin, using a cite-seq like method with a different UMI barcode length.

I believe this is similar to #531

running the command like this:

```
salmon alevin \
    -l ISR \
    -i ${PROJECT}/adt_index \
    -1 $R1_ADT \
    -2 $R2_ADT \
    --end 5 \
    --umiLength 10 \
    --barcodeLength 16 \
    -o $PROJECT/alevin_adt \
    -p 24 \
    --featureStart 1 --featureLength 15 \
    --naiveEqclass \
    --citeseq
```
Produces the error `ERROR: Please specify one and only one scRNA protocol;`

whereas removing the `--citeseq` argument like this:
```
salmon alevin \
    -l ISR \
    -i ${PROJECT}/adt_index \
    -1 $R1_ADT \
    -2 $R2_ADT \
    --end 5 \
    --umiLength 10 \
    --barcodeLength 16 \
    -o $PROJECT/alevin_adt \
    -p 24 \
    --featureStart 1 --featureLength 15 \
    --naiveEqclass
```
Produces the error `[alevinLog] [critical] Transcript to Gene Map File not provided. Exiting Now.`

This is based on salmon 1.8.0 installed via bioconda on ubuntu 18.04

**Comment by k3yavi** [comment]
Hi @Simon-Coetzee , please check the geometry commands from the new version of the tool. The full tutorial can be found [here](https://combine-lab.github.io/alevin-fry-tutorials/2021/af-feature-bc/) .
