### ISSUE TITLE
Problem Installing Salmon

### ISSUE THREAD

**Issue by Jensen416** [COMBINE-lab/salmon#778]
I cloned salmon v1.8.0 and tried to install it on my server. However, when I run make I receive an error at the final step "Linking CXX executable salmon". The error

`[100%] Linking CXX executable salmon
/usr/bin/ld: ../../external/install/lib/libstaden-read.a(libstaden_read_la-open_trace_file.o): in function `find_file_url':
open_trace_file.c:(.text+0xf4e): warning: the use of `tempnam' is dangerous, better use `mkstemp'
during IPA pass: icf
lto1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/salmon.dir/build.make:454: src/salmon] Error 1
make[1]: *** [CMakeFiles/Makefile2:663: src/CMakeFiles/salmon.dir/all] Error 2
make: *** [Makefile:163: all] Error 2`

Prior to this step, I ran cmake as follows:

`cmake -DFETCH_BOOST=TRUE -DTBB_INSTALL_DIR= ~/anaconda3/pkgs/tbb-2021.5.0-hd09550d_0/ -DCMAKE_INSTALL_PREFIX= ~/salmon/`

OS: Ubuntu Linux 20.04

**Comment by rob-p** [comment]
Hi @Jensen416,

  Thank you for reporting this.  Certain versions of the GCC compiler are not capable of performing full program link time optimization (`lto`) for this codebase.  This is a known issue — and there are other programs that exhibit this same behavior.  This is something that GCC must fix upstream — an internal compiler error is something that really shouldn't happen.

  Luckily, the solution is simple; just don't use whole program inter procedural optimization.  Try using this `cmake` invocation (after clearing out your build directory):


```
cmake -DNO_IPO=TRUE -DFETCH_BOOST=TRUE -DTBB_INSTALL_DIR= ~/anaconda3/pkgs/tbb-2021.5.0-hd09550d_0/ -DCMAKE_INSTALL_PREFIX= ~/salmon/
```

The `-DNO_IPO` tells `cmake` to invoke the compiler without inter procedural optimization (i.e. `lto`).  Let me know if this works for you.

Best,
Rob
