### ISSUE TITLE
salmon 0.7.0 crashes in alignment mode

### ISSUE THREAD

**Issue by zhangchipku** [COMBINE-lab/salmon#78]
Hi!
Thank you for making salmon. Great work!

my command line is 
salmon quant -t /hpc/grid/shared/ngsdb/fasta/gencode.v24.transcripts.no_annotation.fa -l ISR -a RC-140808-00004.tx.bam -p 8 -o salmon_aln --useVBOpt  --incompatPrior 0

The end of log file looks like:

1008 Completed first pass through the alignment file.
1009 Total # of mapped reads : 53203073
1010 # of uniquely mapped reads : 14377795
1011 # ambiguously mapped reads : 38825278
1012
1013
1014
1015 [2016-08-19 14:45:45.648] [fileLog] [info] quantification processed 53203073 fragments so far
1016
1017 [2016-08-19 14:45:45.982] [jointLog] [info] Computed 292761 rich equivalence classes for further processing
1018 [2016-08-19 14:45:45.982] [jointLog] [info] Counted 53203073 total reads in the equivalence classes
1019 [2016-08-19 14:45:45.983] [jointLog] [info] starting optimizer
1020 [2016-08-19 14:45:48.932] [jointLog] [info] Marked 1 weighted equivalence classes as degenerate

I tried dropping the --useVBOpt and it only outputs "nan".

I also tried --useVBOpt in quasi-mapping base mode.
salmon quant -i /hpc/grid/shared/ngsdb/annotation/gencode/salmon_0.6.1_v24/ -l ISR -1 /hpc/grid/ngsws/btx_clinical/zhanc120/test/longitudinal/fastq/RC-140808-00004_1.fq.gz -2 /hpc/grid/ngsws/btx_clinical/zhanc120/test/longitudinal/fastq/RC-140808-00004_2.fq.gz -p 8 -o salmon --useVBOpt  --incompatPrior 0
That worked fine.

More on the bam file:
it was generated by STAR with write alignments to transcriptome option

STAR --genomeDir /hpc/grid/shared/ngsdb/STAR/GRCh38_gencode24_100 --readFilesIn /hpc/grid/ngsws/ptx_clinical/zhanc120/test/longitudinal/fastq/RC-140808-00004_1.fq.gz /hpc/grid/ngsws/ptx_clinical/zhanc120/test/longitudinal/fastq/RC-140808-00004_2.fq.gz --readFilesCommand zcat             --runThreadN 8 --alignSJDBoverhangMin 1 --outFilterScoreMinOverLread 0.90 --outFilterMatchNminOverLread 0.90        --outFilterMis    matchNoverLmax 0.05  --quantMode TranscriptomeSAM --alignEndsType EndToEnd         --alignIntronMax 1000000 --outSAMtype BAM SortedByCoordinate;

The bam file worked with salmon 0.6.1 in alignment mode without --incompatPrior 0, (--useVBOpt was not an option in alignment based mode)

**Comment by rob-p** [comment]
*Note:* This behavior is exhibited in salmon v0.7.0 in alignment mode when using `--useVBOpt` in conjunction with `--incompatPrior 0`.  The key here will be determining why `--incompatPrior 0` triggers this behavior.

**Comment by rob-p** [comment]
Hi @zhangchipku,

  The referenced commit should fix this issue.  I've tested `--incompatPrior 0` in alignment and read-based mode with and without VB.  The bug was the result of a double-precision floating point comparison close to machine precision returning an unexpected result.  The behavior has been fixed (and modified).  I'm still planning to do more testing, but feel free to test this out if you can build from source (on the develop branch).

--Rob

**Comment by rob-p** [comment]
@zhangchipku — here's a pre-compiled binary to test, in case you're unable to build a binary from develop on the target machine.

[SalmonBeta-0.7.1-pre-aug20_linux_x86_64.tar.gz](https://github.com/COMBINE-lab/salmon/files/428673/SalmonBeta-0.7.1-pre-aug20_linux_x86_64.tar.gz)

**Comment by rob-p** [comment]
Confirmed that this is resolved in 0.7.1.
