### ISSUE TITLE
pseudoalign in nf-core using salmon?

### ISSUE THREAD

**Issue by marwa38** [COMBINE-lab/salmon#784]
Hi guys 
Do you recommend pseudoalign in nf-core using salmon? Could you please share you opinion?
Cheers
M

**Comment by rob-p** [comment]
Could you please expand upon the question a bit?  Are you asking if I would recommend the [nf-core RNA-seq pipeline](https://nf-co.re/rnaseq/usage) using `salmon` as the quantifier? In general, I think it is a nice pipeline that provides a good deal of information and a nice report. If you're looking for an off-the-shelf workflow for sample quantification for gene-level differential expression, I think that nf-core's RNA-seq workflow is a good option for quality-control and quantification.  If you want to do transcript-level differential analysis, you may want to consider [swish](https://academic.oup.com/nar/article/47/18/e105/5542870), in which case you need to make sure that salmon is run with parameters to generate inferential replicates (either `--numBootstraps X` or `--numGibbsSamples X`).  You can ask over in the nf-core GitHub repo or Slack channel how best to pass those extra options.

Best,
Rob
