### ISSUE TITLE
Installing on macOS

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [COMBINE-lab/salmon#787]
Hi @rob-p ! I try to install Salmon on macOS M1 Max with hombrew (brewsci) 
but I guess the formula is the UNIX one on it. I got :

```
Benjamin@macbook-pro ~ % brew install salmon   
==> Downloading https://github.com/COMBINE-lab/salmon/archive/v1.3.0.tar.gz
Already downloaded: /Users/Benjamin/Library/Caches/Homebrew/downloads/b27a343a5c5128c674be4986b6c0bb348bc77d521662866976898bd4768fd8bb--salmon-1.3.0.tar.gz
==> Installing salmon from brewsci/bio
==> cmake .
Last 15 lines from /Users/Benjamin/Library/Logs/Homebrew/salmon/01.cmake:
Build system will fetch and use JEMalloc
==================================================================
CPACK_SOURCE_IGNORE_FILES = /src/PCA.cpp;/src/PCAUtils.cpp;/build/;/scripts/AggregateToGeneLevel.py;/scripts/ExpressionTools.py;/scripts/GenerateExpressionFiles.sh;/scripts/ParseSoftFile.py;/scripts/PlotCorrelation.py;/scripts/junk;/scripts/sfstrace.log;/scripts/SFPipeline.py;/bin/;/lib/;/sample_data/;PublishREADMEToWebsite.sh;/external/;/src/obsolete/;/include/obsolete/;WebsiteHeader.txt;/experimental_configs/;.git/
CC: /opt/homebrew/Library/Homebrew/shims/mac/super/clang
CC version: 
version: 1.0.0
Building basic pufferfish components for salmon
setting -DHAVE_NUMERIC_LIMITS128
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find Jemalloc (missing: JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR) 
NO_IPO = FALSE
TBB_LIBRARIES = /tmp/salmon-20220630-57321-j1f2iv/salmon-1.3.0/external/install/lib/libtbb.dylib;/tmp/salmon-20220630-57321-j1f2iv/salmon-1.3.0/external/install/lib/libtbbmalloc.dylib
-- Configuring incomplete, errors occurred!
See also "/tmp/salmon-20220630-57321-j1f2iv/salmon-1.3.0/CMakeFiles/CMakeOutput.log".
See also "/tmp/salmon-20220630-57321-j1f2iv/salmon-1.3.0/CMakeFiles/CMakeError.log".

Do not report this issue to Homebrew/brew or Homebrew/core!

Benjamin@macbook-pro ~ % salmon              
zsh: exec format error: salmon
Benjamin@macbook-pro ~ % 
```
I try via bioconda but I got a HTTPerror 

and by building from source and I don't understand how to do it from the website 

How can I do it on macOS Monterey M1 Max chip ? 

thanks a lot for you help in advance 

Since it's the v 1.3.0 is it possible to update the brew formula to 1.9.0 ?

**Comment by rob-p** [comment]
Hi @BenjaminDEMAILLE,

  I think brew is a bit behind bioconda on this front, and, indeed, the M1 being a completely new architecture complicates things. I have an M1 Max and so there are plans to get a native compile going soon.

  For the time being, the recommended way to get `salmon` on an M1 (or M2) Mac is as suggested [here](https://github.com/COMBINE-lab/salmon/issues/724#issuecomment-1137183671).  Basically, you create an x86 conda environment (running under rosetta2) and install the latest version of salmon there. Rosetta2 is pretty amazing, and everything seems to run without a hitch, with nary a performance hit for the x86 -> ARM translation.

Best,
Rob

**Comment by BenjaminDEMAILLE** [comment]
Thanks ! 
When you release the apple silocon version. Is it possible to upload to brew ? Do you want to take in account the gpu with metal or the neural engine ?
