### ISSUE TITLE
Unmatched reads in paired end mode

### ISSUE THREAD

**Issue by kdorman** [COMBINE-lab/salmon#793]
Does Salmon currently handle unpaired reads in forward and reverse FASTQ files? We unintentionally created such files by applying one preprocessing filter separately to the two FASTQ files. Salmon did not complain and alignment rates look reasonable, but various sites around the web suggest that it should not work. Thanks for the clarity!

**Comment by rob-p** [comment]
In this case, it is likely treating the left and right reads as orphans when mapping.  Therefore, you're losing basically all of the benefit of having paired-end reads (which can be considerable) and also increasing the probability of spurious mapping (orphans generally map much more ambiguously than properly paired reads).

Since you have the paired-end files, you should try to repair them (using something like BBMap's [re-pair tool](https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/repair-guide/)) to get back properly-paired FASTQ files for analysis.

Best,
Rob

**Comment by kdorman** [comment]
It really doesn't seem like Salmon is treating them all as orphans. As an example, our forward file has 17385254 reads, reverse 17361911. Salmon says:

At end of round 0
==================
Observed 17361911 total fragments (17361911 in most recent round)

[2022-04-11 23:11:53.713] [jointLog] [info] Computed 2,763,922 rich equivalence classes for further processing
[2022-04-11 23:11:53.731] [jointLog] [info] Counted 16,393,065 total reads in the equivalence classes 
...

[2022-04-11 23:11:53.743] [jointLog] [info] Number of mappings discarded because of alignment score : 680,083
[2022-04-11 23:11:53.743] [jointLog] [info] Number of fragments entirely discarded because of alignment score : 263,662
[2022-04-11 23:11:53.743] [jointLog] [info] Number of fragments discarded because they are best-mapped to decoys : 0
[2022-04-11 23:11:53.743] [jointLog] [info] Number of fragments discarded because they have only dovetail (discordant) mappings to valid targets : 2,335
[2022-04-11 23:11:53.744] [jointLog] [info] Mapping rate = 94.4197%

Also, library is auto-detected as IU and mean fragment length is computed as 417.8. This looks to me like most of the reads are recognized as paired, which in fact they are.

**Comment by rob-p** [comment]
Hi @kdorman,

  Ok, let me refine my response a little bit.  When you said that the files were "unpaired" I was under the assumption that the synchronization between the left and right files was broken; that is that the read names in the left file are in a different order than the right file.  In this case, `salmon` doesn't check explicitly, and it doesn't store reads internally and wait for the mate in the other file.  Every time it reads a record from the left and right file together, it assumes they constitute a pair during sequencing.  If the files become desynchronized, you will likely observe the behavior I mentioned in my initial response.
  
  However, if the reads remain properly paired, then they will be mapped as such.  Judging from the total number of reported fragments in the output above, it looks as though it's attempted to map the first `17361911` reads from both files, treating them as paired-end reads (ignoring the extra records in file 1 that have no mate in file 2).  You could check if it's the case that these reads are properly paired, and that file 1 just contains some extra reads that were unpaired after filtering.
