### ISSUE TITLE
Salmon Quant Alignment --help

### ISSUE THREAD

**Issue by uros-sipetic** [COMBINE-lab/salmon#80]
Hey, just a quick note, when using Salmon Quant Alignment --help option, the parameter
--noBiasLengthThreshold is listed twice, one is I suppose the new description and one is from the old version. Correct me please if I got something wrong. 

Also, the parameter  --fldMax lists its default value at 800, but in the new version, the same parameter for Salmon Quant Reads lists the default value at 1000. Intentional or...?

**Comment by rob-p** [comment]
Hi @uros-sipetic,

  Indeed, you're right on both fronts.  I've just pushed commit 423b622, which addresses these.  It removes one of the duplicate flags --- keeping the one with the same description as in the mapping-based mode, and it updates the default `--fldMax` in alignment-based mode to be 1000 for consistency with mapping-based mode.  Thanks for pointing these out!
