### ISSUE TITLE
Missing transcripts in Salmon quant.sf file

### ISSUE THREAD

**Issue by Gayathri142** [COMBINE-lab/salmon#800]
Hello,

I was using Salmon 1.10 for quantifying some of my RNA-seq datasets, against a custom transcriptome. The transcriptome has 89109 transcripts, but the final quant.sf file has 88119. I am wondering how some of the transcripts(990) are missing from the quant.sf. Does this mean that, they are not fully mapping against the transcriptome? In that case, shouldn't they be reported with a zero TPM?
Do you recommend I upgrade the version?

Thank you in advance.
Gayathri

**Comment by rob-p** [comment]
Hi @Gayathri142,

  Salmon removes (by default) transcripts that are exact sequence duplicates of other transcripts in the input file. This means that the first of the duplicate transcripts is retained, but the others are not indexed (and hence don't appear in the output).  If you look in the directory where you created the index, you'll see a file called `duplicate_clusters.tsv`, which lists each removed (duplicate) transcript, along with the retained transcript to which it was identical.  Additionally, if you pass the `--keep-duplicates` option to salmon when indexing, it will no discard these duplicate transcripts (though note they cannot be differentiated between during inference, so there is little purpose to retaining identical transcripts in the index).  As to your second question, I'd always recommend upgrading to the latest version of salmon if you can do so.

Best,
Rob
