### ISSUE TITLE
Ensembl 107 - Different number of genes quantified

### ISSUE THREAD

**Issue by SFonsecaCosta** [COMBINE-lab/salmon#803]
Hello @rob-p @k3yavi 

I'm contacting you because I'm getting different number of genes quantified based on the tool that I'm using to quantify my RNA-Seq samples. I'm running it using nf-core/rnaseq 3.8.1 version.
The point is if I use STAR/SALMON I get 61860 genes quantified, same number as unique genes IDs in GTF file,  if I run in pseudo-mapping mode SALMON I get 61466 genes quantified.

## This is the way that I'm generating the index:
`
### Get files from ensembl
wget http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gunzip Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
wget http://ftp.ensembl.org/pub/release-107/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
gunzip Homo_sapiens.GRCh38.cdna.all.fa.gz
wget http://ftp.ensembl.org/pub/release-107/gtf/homo_sapiens/Homo_sapiens.GRCh38.107.gtf.gz
gunzip Homo_sapiens.GRCh38.107.gtf.gz
 
### Get files from ERCC92 (Spike-in)
wget https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip
unzip ERCC92.zip
rm -rf ERCC92.zip
 
### Add ERCC92 to FASTA file and to GTF file
cat ERCC92.fa Homo_sapiens.GRCh38.dna.primary_assembly.fa > Homo_sapiens.GRCh38.dna.primary_assembly_ERCC92.fa
cat ERCC92.gtf Homo_sapiens.GRCh38.107.gtf > Homo_sapiens.GRCh38.107_ERCC92.gtf
 
### Regenerate a new transcript fasta
gffread -w regenerate_transcriptome.fa -g Homo_sapiens.GRCh38.dna.primary_assembly_ERCC92.fa Homo_sapiens.GRCh38.107_ERCC92.gtf
 
### Create the decoys
grep "^>" Homo_sapiens.GRCh38.dna.primary_assembly_ERCC92.fa | cut -d " " -f 1 > decoys.txt
sed -i.bak -e 's/>//g' decoys.txt
 
IMPORTANT: remove spike-in from decoy (otherwise we don't have count on that)
 
### Generate gentrome
cat regenerate_transcriptome.fa Homo_sapiens.GRCh38.dna.primary_assembly_ERCC92.fa > gentrome.fa
 
### Create salmon index
salmon index -t gentrome.fa -d decoys.txt -p 12 -i salmon_index
 `

## Parameters pass to nf-core

`
STAR nf-params.json
{
    "input": "/localdata/samples_to_test/samplesheet_test_samples.csv",
    "outdir": "/localdata/samples_to_test/teste_star/",
    "multiqc_title": "MultiQC",
    "skip_umi_extract": true,
    "fasta": "/indexes/Homo_sapiens.GRCh38.dna.primary_assembly_ERCC92.fa",
    "gtf": "/indexes/Homo_sapiens.GRCh38.107_ERCC92.gtf",
    "transcript_fasta": "/indexes/gentrome.fa",
    "skip_markduplicates": true,
    "rseqc_modules": "bam_stat,infer_experiment",
    "deseq2_vst": true,
    "skip_bigwig": true,
    "skip_stringtie": true,
    "skip_preseq": true,
    "skip_dupradar": true,
    "skip_qualimap": true,
    "skip_rseqc": true,
    "skip_biotype_qc": true,
    "skip_deseq2_qc": true
}
 
Salmon nf-params.json
{
    "input": "/localdata/samples_to_test/samplesheet_test_samples.csv",
    "outdir": "/localdata/samples_to_test/teste_salmon/",
    "multiqc_title": "MultiQC",
    "skip_umi_extract": true,
    "fasta": "/indexes/Homo_sapiens.GRCh38.dna.primary_assembly_ERCC92.fa",
    "gtf": "/indexes/Homo_sapiens.GRCh38.107_ERCC92.gtf",
    "transcript_fasta": "/indexes/gentrome.fa",
    "salmon_index": "/indexes/salmon_index/",
    "pseudo_aligner": "salmon",
    "skip_markduplicates": true,
    "skip_alignment": true,
    "rseqc_modules": "infer_experiment,read_distribution",
    "deseq2_vst": true,
    "skip_bigwig": true,
    "skip_stringtie": true,
    "skip_preseq": true,
    "skip_dupradar": true,
    "skip_qualimap": true,
    "skip_rseqc": true,
    "skip_biotype_qc": true,
    "skip_deseq2_qc": true
}
 
`

**Comment by k3yavi** [comment]
Hi @SFonsecaCosta , 

Some variability is expected since the read alignment methods are different. It's worth checking and generating summary stats for the unquantified genes, for example, their expression across cells, or if all the unquantified genes are mitochondrial/ribosomal of some sort.

**Comment by SFonsecaCosta** [comment]
Hi @k3yavi ,

Thanks a lot for you reply. 
Yes I agree that variability is expected, but my point is why these ~ 400 genes did not appear/exported in the quant.genes.sf file? some reason in special? Because they should be reported as well no?

**Comment by SFonsecaCosta** [comment]
I can confirm to you @k3yavi that from the exactly 394 genes that are not showing up in the final quant.genes.sf output file from salmon, 36 are for example protein coding genes.

> table(unlist(strsplit(tolower(filter_genes$GENEBIOTYPE), " ")))

>                        
                         ig_d_gene                          ig_v_gene                    ig_v_pseudogene                             lncrna 
                                 7                                  1                                  3                                 34 
                             mirna                           misc_rna               processed_pseudogene                     protein_coding 
                                51                                 59                                 26                                 36 
                        pseudogene                               rrna                    rrna_pseudogene                             scarna 
                                 1                                 25                                 10                                  1 
                            snorna                              snrna                                tec                          tr_j_gene 
                                18                                 71                                 10                                  1 
                   transcribed_processed_pseudogene transcribed_unprocessed_pseudogene             unprocessed_pseudogene 
                                 2                                  2                                 36
                                 
  The median TPM counts for this protein coding genes are zero across the 4 libraries (by taking in consideration the STAR results). 
But again my point is, I think all the gene IDs should be reported in the quant.genes.sf file and I still don't understand why they are missing after running Salmon and they are present after running  STAR/Quantification_with_Salmon then.

**Comment by k3yavi** [comment]
can you check if the transcript of these genes is marked duplicate by salmon indexing? I think there should be a file called "duplicate.tsv" (or similar) in the salmon index folder.

**Comment by rob-p** [comment]
@SFonsecaCosta,

  Yes, the file is called `duplicate_clusters.tsv` and it is in the directory where the salmon *index* resides.  The reason this is created is that when transcripts are sequence identical to each other, they cannot be independently quantified — that is, they are inferentially indistinguishable.  So, the default strategy is to keep one representative from each indistinguishable cluster and to record the rest in the `duplicate_clusters` file.

  If you want to force salmon to quantify the duplicates (they should all just get equal abundance of 1 / D where D is the number of duplicates), you can pass `--keepDuplicates` when building the salmon index.  When you quantify with alignments performed by STAR, no such duplicate removal is done by STAR upstream, and so all of the sequence identical transcripts are retained.

**Comment by SFonsecaCosta** [comment]
Thanks a lot @k3yavi @rob-p 
Completely clarified.
