### ISSUE TITLE
salmon quant (quasi-alignment)

### ISSUE THREAD

**Issue by Sanaya30** [COMBINE-lab/salmon#804]
I am using salmon v1.0.0 that was compiled using bioconda. I downloaded fastq files from GEO, built an index using salmon index, but am getting 0 mappings. 

#Downloading data
wget -o test.fastq.gz s3://sra-pub-src-5/SRR*******/test.fastq.gz

#building the salmon index from gencode [using vM22 for consistency]
salmon index -t gencode.vM22.transcripts.fa.gz -i gencode.vM22.transcripts --gencode

#running salmon quant
salmon quant -l A -i gencode.vM22.transcripts -r test.fastq.gz -o ~/Test1/ --gcBias --validateMappings --numGibbsSamples 20

The output .sf files have 0 TPMs and 0 fragment reads for all outputs and I am attaching a screenshot of the log file. 

The reference genome and sequencing file is from the same organism.  

![Screen Shot 2022-10-06 at 3 53 32 PM](https://user-images.githubusercontent.com/108241225/194406132-61d5a5ce-a429-4b04-9fab-e4586dea9020.png)

**Comment by Sanaya30** [comment]
Ahh my wget command messed up the file format. I refetched the file using fasterq-dump and it's working now. Sorry for the bother!

**Comment by rob-p** [comment]
No worries; thanks for looping back around.  As a side-note, v1.0.0 is quite a few releases old and it’s probably worth updating to the latest (v1.9.0) if that’s not too difficult on your end.

**Comment by Sanaya30** [comment]
Yes, will update it too. Thank you :)
