### ISSUE TITLE
k-mers for TCGA studies

### ISSUE THREAD

**Issue by ryanpe13002** [COMBINE-lab/salmon#807]
I'm using Salmon to quantify isoforms in TCGA short-read data, which have fairly short reads (48-50 bp, generally). I noted on the documentation that a k-mer size of 31 while building the index is good for 75 bp and up, but shortening that length might be better for smaller reads. How short of an index should I use for TCGA, and how should I go about thinking about which number is optimal? I'm not sure what the tradeoffs are, and don't want to randomly pick a number smaller than 31 that may not be best.

Thanks so much for any help or guidance you can provide! I've used STAR+RSEM, Kallisto, and have now settled on Salmon for my project, and I am really, really happy with its versatility, speed, and accuracy. Excellent work on this tool!

Kindest regards,
Ryan Englander

MD/PhD Candidate, GS3
Jackson Laboratory for Genomic Medicine

**Comment by rob-p** [comment]
Hi Ryan,

  Thanks for your kind words regarding salmon! First, I'll point out that *if it is desired*, you can also use STAR+Salmon in much the same way you've used STAR+RSEM (though STAR+salmon will be faster).

  To your question, if you want to use salmon's built-in selective-alignment, while choosing a k-mer length for this data, then the general rule of thumb is that the k-mer length should not be much longer than about half of the read length.  In general, the alignment procedure and ultimate quantification are pretty robust to the specific choice of k, but you may want to try out a few values for one or two samples.  Given these read lengths, I'd probably choose a value in {21, 23, 25}.  If you have any follow-up questions after looking at those results, I'd be happy to discuss further!

Best,
Rob

**Comment by ryanpe13002** [comment]
Hi Rob,

Thanks so much! I will try with -k 21 and see how that goes! :) Thanks again for making Salmon!

Kindest regards,
Ryan
