### ISSUE TITLE
Documentation --help typos

### ISSUE THREAD

**Issue by uros-sipetic** [COMBINE-lab/salmon#81]
Hey, I ran into couple of more typos in the --help documentation.
In Salmon Quant Reads mode, the option --writeUnmappedNames says the the file created is named unmapped.txt, while it is actually named unmapped_names.txt
In Salmon Quant Alignment mode, the option --sampleUnaligned says the un-aligned reads are also written to the file "posSample.bam", I suppose a 't' is missing there?
Also, when I ran Salmon Quant with Alignment mode, the output auxiliary directory was still named just 'aux' instead of 'aux_info' per the newest change log. 
Sorry if I'm bothering with these pesky details, I though it might help when clearing the documentation a bit.

**Comment by rob-p** [comment]
Hi @uros-sipetic,

  No bother at all; it's very helpful.  Keeping the documentation correct and consistent during development (and between different code paths) is always a bit challenging, so I appreciate your notifying me of discrepancies!

--Rob

**Comment by rob-p** [comment]
Fixed in fd4a3c6.
