### ISSUE TITLE
Salmon indexing hangs or throws segmentation fault

### ISSUE THREAD

**Issue by zaherlab** [COMBINE-lab/salmon#829]
Trying to generate salmon indexes in WSL with Ubuntu 22.04.01 LTS either hangs after the contig count for validation step or throws a segmentation fault. 

Using Salmon 1.9 installed through bioconda
Custom annotation of S. cerevisiae R64-3-1 downloaded from SGD. The whole genome was appended as a decoy

**Comment by zaherlab** [comment]
Hi @rob-p, thanks for the quick response! I ran with the precompiled binary and it ran successfully.

**Comment by rob-p** [comment]
Hi @zaherlab,

  Thanks again for reporting this. Now, also, if you pull the latest version from bioconda, everything should work.

Thanks,
Rob
