### ISSUE TITLE
Missing documentation for Salmon metagenomics mode (--meta)

### ISSUE THREAD

**Issue by JSSaini** [COMBINE-lab/salmon#834]
Hi, please provide some documents on Salmon metagenomics mode. 
Thank you.

**Comment by rob-p** [comment]
Thanks for the suggestion. A description of the flag's effects has been added [here](https://salmon.readthedocs.io/en/develop/salmon.html#meta).

**Comment by JSSaini** [comment]
@rob-p Thank you for your suggestion. Just a little clarification, does the metagenomics flag expect the input of DNA libraries? Can this be used to estimate the gene abundance (DNA sequences) in metagenomics (DNA) libraries? If yes, what would be the quantification unit? Gene per million reads for R1 and R2 input.  Thank you for your assistance.

**Comment by rob-p** [comment]
Hi @JSSaini,

  The most common use case would be taxonomic abundance estimation in a DNA-seq library where the references are whole genomes of the potential taxa. The references indexed would be the gnomes (and / or contigs) of the potential organisms in the sample, and the output would be the estimated number of fragments arising from each contig / genome.  If a given organism is split across multiple contigs, one would aggregate them post quantification in the same way one aggregates transcript abundance estimates to the gene level (i.e. the natural way to do this would be to create a contig to organism mapping and to load up the quantification results using tximport).

Best,
Rob

**Comment by JSSaini** [comment]
Thank you for clarifying that.
