### ISSUE TITLE
Effective length greater than transcript length

### ISSUE THREAD

**Issue by davismcc** [COMBINE-lab/salmon#85]
Hi Rob

I'm using Salmon v0.7.2 to quantify expression from single-cell RNA-seq data, using a command like the following:
```
salmon quant -i <salmon_index> -l A -1 sample_1.fastq -2 sample_2.fastq --seqBias --gcBias --threads 1 --useVBOpt -o sample
```

The index was built with Salmon v0.7.1 (could this be a problem?), from a fasta file with Ensembl v75 transcripts and ERCC spike-in transcripts.

Having a quick skim of the quant.sf output I noticed that some transcripts have an effective transcript length greater than the actual base-pair length of the transcript (see below/attached; not restricted to ERCC transcripts, most often seen where estimated expression is zero, but not only).

Is this at all expected? It was surprising to me, but I'll certainly admit to not being completely across the details of how Salmon calculates effective tx length. How is one to interpret such cases where effective length is greater than transcript length?

Best
Davis

<img width="344" alt="1___screen_3__davis_hh-yoda-03-08__hps_nobackup_stegle_users_davis_hipsci-singlecell____ssh_" src="https://cloud.githubusercontent.com/assets/1668634/18202875/f9ed5294-710a-11e6-9c5e-d3bb293ca1a0.png">

**Comment by vals** [comment]
Hey Davis, the effective lengths are "corrected" to include factors due to sequence-specific and GC biases. After this TPM is normalised by these bias corrected lengths. 

The longer effective length means you are more likely to generate fragments from these transcripts than other of same physical length. (If I'm not misunderstanding something)

The new manuscript is a pretty nice read :) http://www.biorxiv.org/content/biorxiv/early/2016/08/30/021592.full.pdf  , the "Incorporating the bias models" explains the effective lengths.

**Comment by davismcc** [comment]
Thanks for the explanation, Valentine. That makes sense.

The new manuscript is indeed fantastic, but I admit to having skipped straight to the results and have not yet digested the details!

**Comment by rob-p** [comment]
Exactly what he (@vals) said :).  The interpretation would be that in this case, given the sequence composition of these transcripts (including both the sequence-specific and fragment GC biases), you'd expect *a priori* to sample more reads from them — thus they have a longer estimated effective length.  Thanks both for the kind comments on the latest manuscript!

**Comment by vals** [comment]
@davismcc Out of curiosity, do you see something along the lines of ERCCs having systematically longer effective than physical lengths, compared to mRNA transcripts?
