### ISSUE TITLE
Version Server Response: Not Found when attempting a mapping based quantification

### ISSUE THREAD

**Issue by KAffoh** [COMBINE-lab/salmon#851]
Hello,

Thanks for creating this efficient and rapid tool. I have earlier used Salmon in alignment based-mode and now trying the mapping based mode

I get a "Version Server Response:Not found" message on quantification of fast read. I suspect the problem is with my index but I am not entirely sure what exactly.

I installed salmon version 1.10.1 from Bioconda, and built the index, which appeared to have executed successfully.

Below is the trail of commands:

(salmonenv) nanaaffoh@kenneths-mbp-2 salmon % conda install -c bioconda salmon

Building decoy aware index
(salmonenv) nanaaffoh@kenneths-mbp-2 salmon % grep "^>" ../rna_seq_trial/GRCh38.primary_assembly.genome.fa | cut -d " " -f -1 > decoys.txt
(salmonenv) nanaaffoh@kenneths-mbp-2 salmon % less decoys.txt
(salmonenv) nanaaffoh@kenneths-mbp-2 salmon % sed -i.bak -e 's/>//g' decoys.txt
(salmonenv) nanaaffoh@kenneths-mbp-2 salmon % cat ../rna_seq_trial/gencode.v43.transcripts.fa ../rna_seq_trial/GRCh38.primary_assembly.genome.fa > gentrome.fa
(salmonenv) nanaaffoh@kenneths-mbp-2 salmon % salmon index -t gentrome.fa -d decoys.txt -p 12 -i salmon_index --gencode

This results in successful building of the index

Then when I attempt a mapping based quantification for a paired end reads FW and RV, as below, I get therefor mentioned.

salmon -i salmon_index -l A -1 $FW -2 $RV --validateMappings -o /Volumes/Ultra_Touch/malaria/Salmon/$FILEBASE/

The info.json file from the index folder has these contents:

{
"index_version": 4,
"reference_gfa": [
"salmon_index"
],
"sampling_type": "dense",
"k": 31,
"num_kmers": 2662886061,
"num_contigs": 37302977,
"seq_length": 3781975371,
"have_ref_seq": true,
"have_edge_vec": false,
"SeqHash": "39d9ea9f308ee7e18cdb034c1d064c3a9722df115147533a2ec237fb7cecfca9",
"NameHash": "29a75bc06784c090e5e015d4a5a7e895b7b3d91c9855a10528ee0130377edf3d",
"SeqHash512": "4e84aa54ec0cb1dad420c66197d8a9485e913b0a60805f2d7e44ce71ad0521b8103cf94dad72e1530b05dc0d08f39e5d4b9225345d8e7ffc60cb5cf02fecadbd",
"NameHash512": "24684d713ef7ab8e5f3bb7b16203900f9695e938760961daa2fe3733d5385554d4c60d7edfbac88831d9c645154847ec77c11d4125d38fd76137706af399d481",
"DecoySeqHash": "b87b7a94564c31d78da407e60a0aeb310b2dbdb398e0ddb39392286aaf2fe88c",
"DecoyNameHash": "5fc84a462ccf4735efdc48604a520ee47e1319156c2a5c252f5daba1e99bb401",
"num_decoys": 194,
"first_decoy_index": 252004,
"keep_duplicates": false
}

**Comment by rob-p** [comment]
Hi @KAffoh,

  Please let me know if this is resolved.  If not, you can try running:

```
salmon --no-version-check quant -i salmon_index -l A -1 $FW -2 $RV --validateMappings -o /Volumes/Ultra_Touch/malaria/Salmon/$FILEBASE/
```

Best,
Rob

**Comment by rob-p** [comment]
Great; thanks for the follow up, Kenneth.  As this is fixed, I'll close the issue.

Best,
Rob
