### ISSUE TITLE
Error in library(edgeR) - there is no package called 'edgeR'

### ISSUE THREAD

**Issue by ulin27** [COMBINE-lab/salmon#855]
Hello, 
Could someone tell me what this error message means and if there is a way to fix the issue? I'm trying to use salmon for my Master's project data (I break down salmon into two parts to make it easier for myself) but keep getting the error message below during the matrix combination step. I have downloaded edgeR to my home directory on my school's supercomputer, in addition to many other unsuccessful attempts at solving the issue. My main issue is that I've used the same code before without this issue, so I don't know exactly what is wrong now. I'm fairly new to bioinformatics and find it confusing, so any help is appreciated!

Here is my job script:

#!/bin/bash
#SBATCH --partition=debug
#SBATCH --account=PAS1725
#SBATCH --job-name=salmon_part2_cd-hit
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48

module load python
module load trinityrnaseq/2.15.1
module load samtools
module load salmon/1.4.0
module load R/4.1.0-gnu9.1
R

/apps/trinityrnaseq/2.15.1/util/abundance_estimates_to_matrix.pl --est_method salmon --gene_trans_map /fs/scratch/PAS1725/transcriptomics/trinity_cd-hit_fasta.gene_trans_map --name_sample_by_basedir --out_prefix transcript_counts /fs/scratch/PAS1725/transcriptomics/salmon_part1_cd-hit_output_files/A1/quant.sf ... [other files omitted for space]

Here is my error message:

/apps/trinityrnaseq/2.15.1/util/support_scripts/run_TMM_scale_matrix.pl --matrix transcript_counts.isoform.TPM.not_cross_norm > transcript_counts.isoform.TMM.EXPR.matrixCMD: R --no-save --no-restore --no-site-file --no-init-file -q < transcript_counts.isoform.TPM.not_cross_norm.runTMM.R 1>&2 
> library(edgeR)
Error in library(edgeR) : there is no package called ‘edgeR’
Execution halted
Error, cmd: R --no-save --no-restore --no-site-file --no-init-file -q < transcript_counts.isoform.TPM.not_cross_norm.runTMM.R 1>&2  died with ret (256)  at /apps/trinityrnaseq/2.15.1/util/support_scripts/run_TMM_scale_matrix.pl line 105.
Error, CMD: /apps/trinityrnaseq/2.15.1/util/support_scripts/run_TMM_scale_matrix.pl --matrix transcript_counts.isoform.TPM.not_cross_norm > transcript_counts.isoform.TMM.EXPR.matrix died with ret 6400 at /apps/trinityrnaseq/2.15.1/util/abundance_estimates_to_matrix.pl line 386.

**Comment by rob-p** [comment]
Hi @ulin27,

  This isn't a `salmon`-related issue.  The script is trying to run an instance of R, and within R to load the `edgeR` package to perform some normalization.  It looks like the location you are running this doesn't have `edgeR` installed.  I would check in with the people who installed `trinity` on your computer or, if that was you, ask upstream in the `trinity` user group.

Best,
Rob

**Comment by ulin27** [comment]
Thank you for your help, @rob-p! I'll look into it! Much appreciated!
