### ISSUE TITLE
--biasCorrect not recognised

### ISSUE THREAD

**Issue by hector3500** [COMBINE-lab/salmon#873]
I am running salmon as part of a pipeline and this error message is being displayed:

 running salmon quant...
Version Server Response: Not Found
exception : [unrecognised option '--biasCorrect']. Exiting.
pipeline failed at expression quantification!

Here are the options which the script uses: 
salmon quant -t ${transcript_fa} ${ltype} -a ${rna_bam} -o ${sm_odir} -p $nproc --biasCorrect
    check_file ${sm_out} "pipeline failed at expression quantification!"

I have the latest version of salmon installed.

**Comment by rob-p** [comment]
Hi @hector3500, 

 `--biasCorrect` is not a salmon flag. Instead, it provides the `--seqBias` and `--gcBias` flags.

--Rob
