### ISSUE TITLE
-seqbias | is it specific to random hexameric primers ? 

### ISSUE THREAD

**Issue by SHITIJ9810** [COMBINE-lab/salmon#880]
Hey,
I have a question regarding the  --seqBias flag, your documentation suggests it is specifically applied to random hexameric primers. But on the contrary it is based on Variable length Markov Model, is it feasible to use this flag for analysing the libraries made with random nonameric primers ?
Thank you

**Comment by rob-p** [comment]
The sequence bias model is generic.  That is, it does not start out with any assumption about the prevalence or use of specific hexamers.  Rather, it trains a VLMM to assess bias in the context surrounding (upstream and downstream) read start positions.  It makes sense to use this flag to model types of sequence-specific non-uniformity in read start positions even beyond those caused by non-random hexamer priming.

**Comment by reislab** [comment]
Hey Rob, not sure if I understood your answer. 
During cDNA synthesis, we use random 9-mer (not 6-mer). My impression from the documentation is that -seqbias can only be used if cDNA synthesis was done using 6-mer. This point is not clear in your answer for me. 
Could you please clarify?
Many thanks

**Comment by rob-p** [comment]
Certainly.  Let me be more specific.  The model itself is general, though we train it on a context that is of length 8.  Specifically, the model that is used (the context) is defined here

https://github.com/COMBINE-lab/salmon/blob/1c3f6c014ce77ec593d5b37ee2bb0cf9feddf123/src/SBModel.cpp#L7

If you look further up in that file, you can see that it's reasonably easy to consider different contexts — it's just a matter of how the model is initialized.  However, this isn't something that we currently expose as a runtime parameter.  However, if you have a reason to believe that a different model topology would work better in your context, we'd be happy to help you try it out (and enable such a feature in a future release).

Best,
Rob

**Comment by reislab** [comment]
Excellent, thank you. This should work fine for our purpose then.
Many thanks, Rodrigo
