### ISSUE TITLE
bioconda package

### ISSUE THREAD

**Issue by roryk** [COMBINE-lab/salmon#89]
Hi Rob,

I've been trying to update the bioconda package, but I can't get it to build. The bioconda package pulls in gperftools so Salmon gets built with tcmalloc, to fix some problems over NFS on CentOS < 6: https://github.com/chapmanb/bcbio-nextgen/issues/1376 I can get that to work by pulling in libunwind, but I end up with a bunch of linking errors I don't know how to fix.

I could use a hand debugging it. Alternatively, and maybe easier, we could use the Linux binary if it was built with tcmalloc. Is there any chance the Linux binary could get built with tcmalloc?

**Comment by rob-p** [comment]
Hi Rory,

  I'd be happy to help out.  However, can you first ensure that this NSF issue still persists with the "default" jemalloc allocator?  It's true that a variant of Salmon 0.6.0 manifested a segfault during program shutdown that seemed to be the result of using jemalloc (in combination with input/output files being read / written over NSF), however I subsequently restructured some of the memory allocations, and replaced a few "manual" `new`s and `delete`s with `std::unique_ptr`s, and this seems to have resolved the issue as far as I can tell.  The recent builds should be OK, even with jemalloc.

--Rob

**Comment by roryk** [comment]
Thanks! I don't have a CentOS 5 setup anywhere where I could test, but if it should be fixed then I'll go ahead and update the formula and bug you about it if anyone runs into problems.

**Comment by roryk** [comment]
Is there some way I can pass a custom CFLAGS to the libbwa build? The Makefile there assumes a system-wide installed zlib, which bioconda doesn't have on its docker image, so the bwa build needs to get the -I and -L flags to point to the correct place.

**Comment by rob-p** [comment]
Hrmm --- [this](https://github.com/COMBINE-lab/salmon/blob/master/CMakeLists.txt#L366) is the relevant part of the CMakeFile that builds this.  It uses the `CC` and `CXX` variables, but doesn't explicitly pass along any others.  The first thing to check is what variables the bwa makefile respects, and then to propagate these along via CMake.

**Comment by roryk** [comment]
Got this working, I had to make some edits to CMakeLists.txt:

```
    sed -i 's/.\/autogen.sh/CFLAGS=-fPIC CPPFLAGS=-fPIC .\/autogen.sh/' CMakeLists.txt
    sed -i 's/CFLAGS+=${STADEN_LIB}/CFLAGS+=${STADEN_LIB} CFLAGS+=-lz/' CMakeLists.txt
```

jemalloc wasn't getting passed the -fPIC flag properly so was causing some problems and libstaden was having some troubles finding the non-systemwide installed zlib.

**Comment by rob-p** [comment]
Great!  I'm glad you were able to get this compiling.  Is there a generic way to apply your changes to the CMakeLists.txt so they are *optional* (e.g. Could be triggered with a `-DCONDA_BUILD=TRUE` flag to cmake or some such?
