### ISSUE TITLE
anaconda version of salmon outdated, missing decoys option

### ISSUE THREAD

**Issue by adamfreedman** [COMBINE-lab/salmon#895]
surprisingly, after building a salmon conda env, when building an index I got the following error:

`exception : [unrecognised option '--decoys']. Exiting.`

I then ran salmon index --help , and there was no -d/--decoys option.

and
`salmon -v ` returned 
salmon 0.13.1

the tag on https://anaconda.org/bioconda/salmon , last uploaded a few months ago suggests it is for 1.10.2 , which is clearly not the case. not sure if this was done by someone other than any of the salmon developers, but it definitely creates headaches for groups trying to automate expression analysis workflows using snakemake/conda

**Comment by rob-p** [comment]
Depending on what environment you install in (other conda software), the default resolver in conda is messed up. You should just explicitly ask for 1.10.2 with “ conda install salmon=1.10.2”. You can also try installing it in a clean conda env which is how I install most of my conda software anyway.

Best,
Rob

**Comment by adamfreedman** [comment]
I didn't realize the resolver was so screwed up. And yeah, I get it that it's not your responsibility to fix it! In retrospect, as we're always specify versions in Snakemake profiles, the problem should be a non-issue. I was just doing some local testing when I encountered the "issue"

Thx,
Adam

**Comment by adamfreedman** [comment]
Fwiw, the conda resolver is not the only issue:

>conda create -n salmon -c bioconda -c conda-forge salmon=1.10.2

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): / Killed

Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________

**Comment by rob-p** [comment]
I'm going to cc @dpryan79 on this — does it just not finish? It seems to work within our GitHub CI, where we have to grab the prebuilt salmon to test `simpleaf`.

**Comment by adamfreedman** [comment]
conda create never seems to even get out of the gate ...

a little bit of testing strongly suggests that version of salmon can't be found :

conda create -n owlVsunicorn -c bioconda owlVsunicorn
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): / Killed


this is the first time I've encountered an issue where something that is "supposed" to be there can't be found

Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________

**Comment by rob-p** [comment]
Hi @adamfreedman,

  I think this is just conda being very very very slow (and potentially broken).  The following works fine for me (and finishes in ~1 minute):

```
mamba create -n salmon -c conda-forge -c bioconda salmon=1.10.2
```

Can you use the `mamba` resolver in your environment? Conda has become hardly usable over the years, but `mamba` works quite well as a fast replacement. I'll also note that I swapped the order of `conda-forge` and `bioconda` as the docs specify that `bioconda` should preferably come last in the list of channels.

--Rob

**Comment by adamfreedman** [comment]
I think you're right wrt conda. I was able to install 1.10.2 with mamba fairly easily. We've been moving away from conda (towards mamba) but this didn't cross my mind when I was playing in my sandbox. Might be some cluster latency issues combined with conda's snail's pace causing the problem on our end.

Thx for the quick replies!

Adam H. Freedman, PhD
Data Scientist
Faculty of Arts & Sciences Informatics Group
Harvard University
38 Oxford St
Cambridge, MA 02138
phone: +001 310 415 7145
________________________________
